// ════════════════════════════════════════════════════════════════
// LÛTKE — İngilizce Modülü A1 Kelime DB
//
// Hedef kitle: Kurmancî anadilli olup İngilizce öğrenenler.
// Açıklamalar Kurmancî, hedef dil İngilizce.
//
// Kaynak: Oxford 3000 (CEFR A1 dilim) — kamuya açık liste.
// Çeviriler: Kurmancî dilbilimci tarafından gözden geçirildi.
//
// Format: EnWord typedef (en_word.dart)
//   id, en, ku, ipa, pos, form, kat, zor, notKu, her, herKu, emoji
// ════════════════════════════════════════════════════════════════

import 'en_word.dart';

const List<EnWord> kEnA1Liste = [
  // ── Selamlama / Sosyal ──────────────────────────────────────
  (id:'en_a1_001', en:'hello', ku:'silav', ipa:'/həˈloʊ/', pos:'interjection',
   form:null, kat:'silav', zor:0.95,
   notKu:'Silav. Her demê tê bikaranîn.',
   her:['Hello, friend!', 'Hello, my name is Ali.'],
   herKu:['Silav, heval!', 'Silav, navê min Alî ye.'], emoji:'👋'),

  (id:'en_a1_002', en:'hi', ku:'silav', ipa:'/haɪ/', pos:'interjection',
   form:null, kat:'silav', zor:0.95,
   notKu:'Silav (nefermî). "Hello"yê kurttir.',
   her:['Hi! How are you?', 'Hi, mom!'],
   herKu:['Silav! Tu çawa yî?', 'Silav, dayê!'], emoji:'👋'),

  (id:'en_a1_003', en:'goodbye', ku:'xatirê te', ipa:'/ɡʊdˈbaɪ/', pos:'interjection',
   form:null, kat:'silav', zor:0.85,
   notKu:'Xatirê te. Demek ku diçî tê gotin.',
   her:['Goodbye, see you tomorrow.', 'Goodbye, my friends.'],
   herKu:['Xatirê te, sibê em hev dibînin.', 'Xatirê we, hevalên min.'], emoji:'👋'),

  (id:'en_a1_004', en:'please', ku:'ji kerema xwe', ipa:'/pliːz/', pos:'adv',
   form:null, kat:'silav', zor:0.88,
   notKu:'Ji kerema xwe (re). Daxwazê nazik dike.',
   her:['Water, please.', 'Please help me.'],
   herKu:['Ji kerema xwe re, av.', 'Ji kerema xwe re, alî min bike.'], emoji:'🙏'),

  (id:'en_a1_005', en:'thanks', ku:'spas', ipa:'/θæŋks/', pos:'interjection',
   form:'plural noun', kat:'silav', zor:0.92,
   notKu:'Spas. "Thank you"yê kurttir.',
   her:['Thanks a lot!', 'Thanks for your help.'],
   herKu:['Gelek spas!', 'Spas ji bo alîkariya te.'], emoji:'🙏'),

  (id:'en_a1_006', en:'sorry', ku:'bibore', ipa:'/ˈsɔːri/', pos:'adj',
   form:null, kat:'silav', zor:0.85,
   notKu:'Bibore. Lêborînê dixwaze.',
   her:['I am sorry.', 'Sorry, I am late.'],
   herKu:['Ez bibore me.', 'Bibore, ez dereng mam.'], emoji:'😔'),

  (id:'en_a1_007', en:'yes', ku:'erê', ipa:'/jes/', pos:'adv',
   form:null, kat:'silav', zor:0.95,
   notKu:'Erê. Pejirandin.',
   her:['Yes, I can.', 'Yes, please.'],
   herKu:['Erê, ez dikarim.', 'Erê, ji kerema xwe re.'], emoji:'✅'),

  (id:'en_a1_008', en:'no', ku:'na', ipa:'/noʊ/', pos:'adv',
   form:null, kat:'silav', zor:0.95,
   notKu:'Na. Redkirin.',
   her:['No, thanks.', 'No, I do not want.'],
   herKu:['Na, spas.', 'Na, ez naxwazim.'], emoji:'❌'),

  (id:'en_a1_009', en:'ok', ku:'baş e', ipa:'/oʊˈkeɪ/', pos:'adj',
   form:null, kat:'silav', zor:0.90,
   notKu:'Baş e. Pejirandin/têgihiştin.',
   her:['Ok, let us go.', 'Are you ok?'],
   herKu:['Baş e, em biçin.', 'Tu baş î?'], emoji:'👌'),

  // ── Sayılar ────────────────────────────────────────────────
  (id:'en_a1_010', en:'zero', ku:'sifir', ipa:'/ˈzɪroʊ/', pos:'num',
   form:null, kat:'jimar', zor:0.85,
   notKu:'Sifir. Hejmara 0.',
   her:['Zero degrees today.', 'Score is zero.'],
   herKu:['Îro sifir derece ye.', 'Encam sifir e.'], emoji:'0️⃣'),

  (id:'en_a1_011', en:'one', ku:'yek', ipa:'/wʌn/', pos:'num',
   form:null, kat:'jimar', zor:0.92,
   notKu:'Yek. Hejmara 1.',
   her:['I have one apple.', 'One book, please.'],
   herKu:['Yek sêva min heye.', 'Ji kerema xwe re yek pirtûk.'], emoji:'1️⃣'),

  (id:'en_a1_012', en:'two', ku:'du', ipa:'/tuː/', pos:'num',
   form:null, kat:'jimar', zor:0.92,
   notKu:'Du. Hejmara 2.',
   her:['Two cats are here.', 'I have two brothers.'],
   herKu:['Du pisîk li vir in.', 'Du birayên min hene.'], emoji:'2️⃣'),

  (id:'en_a1_013', en:'three', ku:'sê', ipa:'/θriː/', pos:'num',
   form:null, kat:'jimar', zor:0.90,
   notKu:'Sê. Hejmara 3. (th = ث / s nerm)',
   her:['Three children play.', 'Three days a week.'],
   herKu:['Sê zarok dilîzin.', 'Sê rojên hefteyê.'], emoji:'3️⃣'),

  (id:'en_a1_014', en:'four', ku:'çar', ipa:'/fɔːr/', pos:'num',
   form:null, kat:'jimar', zor:0.90,
   notKu:'Çar. Hejmara 4.',
   her:['Four windows in the room.', 'It is four o\'clock.'],
   herKu:['Çar pencereyên odeyê.', 'Saet çar e.'], emoji:'4️⃣'),

  (id:'en_a1_015', en:'five', ku:'pênc', ipa:'/faɪv/', pos:'num',
   form:null, kat:'jimar', zor:0.90,
   notKu:'Pênc. Hejmara 5.',
   her:['Five fingers on a hand.', 'I am five years old.'],
   herKu:['Pênc tilî li destekî.', 'Ez pênc salî me.'], emoji:'5️⃣'),

  (id:'en_a1_016', en:'six', ku:'şeş', ipa:'/sɪks/', pos:'num',
   form:null, kat:'jimar', zor:0.88,
   notKu:'Şeş. Hejmara 6.',
   her:['Six eggs in the box.', 'Class starts at six.'],
   herKu:['Şeş hêk di qutiyê de.', 'Dersa di saet şeşan de dest pê dike.'], emoji:'6️⃣'),

  (id:'en_a1_017', en:'seven', ku:'heft', ipa:'/ˈsevən/', pos:'num',
   form:null, kat:'jimar', zor:0.88,
   notKu:'Heft. Hejmara 7.',
   her:['Seven days in a week.', 'I sleep seven hours.'],
   herKu:['Heft rojên di hefteyê de.', 'Ez heft saetan radizêm.'], emoji:'7️⃣'),

  (id:'en_a1_018', en:'eight', ku:'heşt', ipa:'/eɪt/', pos:'num',
   form:null, kat:'jimar', zor:0.88,
   notKu:'Heşt. Hejmara 8. ("gh" deng nake)',
   her:['Eight cars in the street.', 'It is eight in the morning.'],
   herKu:['Heşt erebe li kuçeyê.', 'Sibehê saet heşt e.'], emoji:'8️⃣'),

  (id:'en_a1_019', en:'nine', ku:'neh', ipa:'/naɪn/', pos:'num',
   form:null, kat:'jimar', zor:0.88,
   notKu:'Neh. Hejmara 9.',
   her:['Nine birds in the sky.', 'My sister is nine.'],
   herKu:['Neh çûk li ezmên.', 'Xwişka min neh salî ye.'], emoji:'9️⃣'),

  (id:'en_a1_020', en:'ten', ku:'deh', ipa:'/ten/', pos:'num',
   form:null, kat:'jimar', zor:0.90,
   notKu:'Deh. Hejmara 10.',
   her:['Ten students in class.', 'Ten minutes left.'],
   herKu:['Deh xwendekar di polê de.', 'Deh deqîqe maye.'], emoji:'🔟'),

  (id:'en_a1_021', en:'hundred', ku:'sed', ipa:'/ˈhʌndrəd/', pos:'num',
   form:null, kat:'jimar', zor:0.78,
   notKu:'Sed. Hejmara 100.',
   her:['One hundred dollars.', 'A hundred years ago.'],
   herKu:['Sed dolar.', 'Sed sal berê.'], emoji:'💯'),

  // ── Renkler ────────────────────────────────────────────────
  (id:'en_a1_022', en:'red', ku:'sor', ipa:'/red/', pos:'adj',
   form:null, kat:'reng', zor:0.90,
   notKu:'Sor. Renga xwînê.',
   her:['A red apple.', 'My car is red.'],
   herKu:['Sêveke sor.', 'Ereba min sor e.'], emoji:'🔴'),

  (id:'en_a1_023', en:'blue', ku:'şîn', ipa:'/bluː/', pos:'adj',
   form:null, kat:'reng', zor:0.90,
   notKu:'Şîn. Renga ezmên.',
   her:['The sky is blue.', 'A blue pen.'],
   herKu:['Ezman şîn e.', 'Pênûseke şîn.'], emoji:'🔵'),

  (id:'en_a1_024', en:'green', ku:'kesk', ipa:'/ɡriːn/', pos:'adj',
   form:null, kat:'reng', zor:0.88,
   notKu:'Kesk. Renga giya/daran.',
   her:['Green leaves on tree.', 'A green door.'],
   herKu:['Pelên kesk li ser darê.', 'Deriyekî kesk.'], emoji:'🟢'),

  (id:'en_a1_025', en:'yellow', ku:'zer', ipa:'/ˈjeloʊ/', pos:'adj',
   form:null, kat:'reng', zor:0.88,
   notKu:'Zer. Renga rojê/limonê.',
   her:['A yellow flower.', 'The sun is yellow.'],
   herKu:['Kulîlkeke zer.', 'Roj zer e.'], emoji:'🟡'),

  (id:'en_a1_026', en:'black', ku:'reş', ipa:'/blæk/', pos:'adj',
   form:null, kat:'reng', zor:0.88,
   notKu:'Reş. Renga şevê.',
   her:['Black shoes.', 'A black cat.'],
   herKu:['Solên reş.', 'Pisîkeke reş.'], emoji:'⚫'),

  (id:'en_a1_027', en:'white', ku:'spî', ipa:'/waɪt/', pos:'adj',
   form:null, kat:'reng', zor:0.88,
   notKu:'Spî. Renga berfê/şîr.',
   her:['White snow falls.', 'A white house.'],
   herKu:['Berfa spî dibare.', 'Mala spî.'], emoji:'⚪'),

  (id:'en_a1_028', en:'orange', ku:'narincî', ipa:'/ˈɔːrɪndʒ/', pos:'adj',
   form:null, kat:'reng', zor:0.78,
   notKu:'Narincî. Reng + fêkî.',
   her:['Orange juice.', 'An orange shirt.'],
   herKu:['Şîreya porteqalê.', 'Kirasekî narincî.'], emoji:'🟠'),

  (id:'en_a1_029', en:'pink', ku:'pembe', ipa:'/pɪŋk/', pos:'adj',
   form:null, kat:'reng', zor:0.80,
   notKu:'Pembe. Renga gulê.',
   her:['A pink flower.', 'Her dress is pink.'],
   herKu:['Kulîlkeke pembe.', 'Cilê wê pembe ye.'], emoji:'🩷'),

  (id:'en_a1_030', en:'purple', ku:'mor', ipa:'/ˈpɜːrpəl/', pos:'adj',
   form:null, kat:'reng', zor:0.78,
   notKu:'Mor. Renga binefşê.',
   her:['Purple flowers.', 'A purple book.'],
   herKu:['Kulîlkên mor.', 'Pirtûkeke mor.'], emoji:'🟣'),

  (id:'en_a1_031', en:'brown', ku:'qehweyî', ipa:'/braʊn/', pos:'adj',
   form:null, kat:'reng', zor:0.78,
   notKu:'Qehweyî. Renga qehweyê.',
   her:['Brown bread.', 'A brown horse.'],
   herKu:['Nanê qehweyî.', 'Hespekî qehweyî.'], emoji:'🟤'),

  // ── Aile ────────────────────────────────────────────────────
  (id:'en_a1_032', en:'father', ku:'bav', ipa:'/ˈfɑːðər/', pos:'noun',
   form:null, kat:'malbat', zor:0.92,
   notKu:'Bav. (th = θ deng dike)',
   her:['My father is at home.', 'Father, where are you?'],
   herKu:['Bavê min li malê ye.', 'Bavo, tu li ku derê yî?'], emoji:'👨'),

  (id:'en_a1_033', en:'mother', ku:'dayik', ipa:'/ˈmʌðər/', pos:'noun',
   form:null, kat:'malbat', zor:0.92,
   notKu:'Dayik / Dê.',
   her:['My mother cooks well.', 'Mother loves us.'],
   herKu:['Dayika min baş çêdike.', 'Dayik me hez dike.'], emoji:'👩'),

  (id:'en_a1_034', en:'son', ku:'kur', ipa:'/sʌn/', pos:'noun',
   form:null, kat:'malbat', zor:0.85,
   notKu:'Kur. Zarokê nêr.',
   her:['Their son is young.', 'I have one son.'],
   herKu:['Kurê wan ciwan e.', 'Yek kurê min heye.'], emoji:'👦'),

  (id:'en_a1_035', en:'daughter', ku:'keç', ipa:'/ˈdɔːtər/', pos:'noun',
   form:null, kat:'malbat', zor:0.85,
   notKu:'Keç. Zaroka mê.',
   her:['Their daughter is smart.', 'My daughter is six.'],
   herKu:['Keça wan jîr e.', 'Keça min şeş salî ye.'], emoji:'👧'),

  (id:'en_a1_036', en:'brother', ku:'bira', ipa:'/ˈbrʌðər/', pos:'noun',
   form:null, kat:'malbat', zor:0.92,
   notKu:'Bira. Birayê min/te.',
   her:['My brother plays football.', 'Brother and sister.'],
   herKu:['Birayê min futbolê dilîze.', 'Bira û xwişk.'], emoji:'👨'),

  (id:'en_a1_037', en:'sister', ku:'xwişk', ipa:'/ˈsɪstər/', pos:'noun',
   form:null, kat:'malbat', zor:0.92,
   notKu:'Xwişk. Xwişka min/te.',
   her:['My sister is a teacher.', 'She has two sisters.'],
   herKu:['Xwişka min mamoste ye.', 'Du xwişkên wê hene.'], emoji:'👩'),

  (id:'en_a1_038', en:'grandfather', ku:'kalik', ipa:'/ˈɡrænfɑːðər/', pos:'noun',
   form:null, kat:'malbat', zor:0.78,
   notKu:'Kalik / Bapîr.',
   her:['My grandfather is old.', 'Grandfather tells stories.'],
   herKu:['Kalê min pîr e.', 'Kalik çîrokan dibêje.'], emoji:'👴'),

  (id:'en_a1_039', en:'grandmother', ku:'pîrê', ipa:'/ˈɡrænmʌðər/', pos:'noun',
   form:null, kat:'malbat', zor:0.78,
   notKu:'Pîrê / Dapîr.',
   her:['Grandmother makes bread.', 'My grandmother loves me.'],
   herKu:['Pîrê nan çêdike.', 'Pîra min hez ji min dike.'], emoji:'👵'),

  (id:'en_a1_040', en:'uncle', ku:'ap', ipa:'/ˈʌŋkəl/', pos:'noun',
   form:null, kat:'malbat', zor:0.75,
   notKu:'Ap (bavê bav) / Xal (birayê dê).',
   her:['My uncle lives far.', 'Uncle, hello!'],
   herKu:['Apê min li dûr dijî.', 'Apo, silav!'], emoji:'👨'),

  (id:'en_a1_041', en:'aunt', ku:'met', ipa:'/ænt/', pos:'noun',
   form:null, kat:'malbat', zor:0.75,
   notKu:'Met (xwişka bav) / Xaltî (xwişka dê).',
   her:['My aunt is here.', 'Aunt brings cake.'],
   herKu:['Meta min li vir e.', 'Met kek tîne.'], emoji:'👩'),

  (id:'en_a1_042', en:'child', ku:'zarok', ipa:'/tʃaɪld/', pos:'noun',
   form:'pl: children', kat:'malbat', zor:0.88,
   notKu:'Zarok. Pirjimar: children.',
   her:['The child plays.', 'Two children sleep.'],
   herKu:['Zarok dilîze.', 'Du zarok radizên.'], emoji:'🧒'),

  (id:'en_a1_043', en:'baby', ku:'pitik', ipa:'/ˈbeɪbi/', pos:'noun',
   form:null, kat:'malbat', zor:0.85,
   notKu:'Pitik / Zarokê biçûk.',
   her:['The baby cries.', 'My baby sister.'],
   herKu:['Pitik digirî.', 'Xwişka min ya pitik.'], emoji:'👶'),

  (id:'en_a1_044', en:'family', ku:'malbat', ipa:'/ˈfæməli/', pos:'noun',
   form:null, kat:'malbat', zor:0.92,
   notKu:'Malbat. Mal + bav, dê, zarok.',
   her:['I love my family.', 'A big family.'],
   herKu:['Ez ji malbata xwe hez dikim.', 'Malbateke mezin.'], emoji:'👨‍👩‍👧‍👦'),

  (id:'en_a1_045', en:'man', ku:'mêr', ipa:'/mæn/', pos:'noun',
   form:'pl: men', kat:'mirov', zor:0.92,
   notKu:'Mêr. Pirjimar: men.',
   her:['A tall man.', 'The man works.'],
   herKu:['Mêrekî dirêj.', 'Mêr dixebite.'], emoji:'👨'),

  (id:'en_a1_046', en:'woman', ku:'jin', ipa:'/ˈwʊmən/', pos:'noun',
   form:'pl: women', kat:'mirov', zor:0.92,
   notKu:'Jin. Pirjimar: women.',
   her:['A young woman.', 'The woman reads.'],
   herKu:['Jineke ciwan.', 'Jin dixwîne.'], emoji:'👩'),

  (id:'en_a1_047', en:'boy', ku:'lawik', ipa:'/bɔɪ/', pos:'noun',
   form:null, kat:'mirov', zor:0.90,
   notKu:'Lawik / Kur.',
   her:['The boy runs fast.', 'A good boy.'],
   herKu:['Lawik bi lez direve.', 'Lawikekî baş.'], emoji:'👦'),

  (id:'en_a1_048', en:'girl', ku:'keçik', ipa:'/ɡɜːrl/', pos:'noun',
   form:null, kat:'mirov', zor:0.90,
   notKu:'Keçik. Zaroka mê.',
   her:['The girl smiles.', 'A clever girl.'],
   herKu:['Keçik dikene.', 'Keçikeke jîr.'], emoji:'👧'),

  (id:'en_a1_049', en:'friend', ku:'heval', ipa:'/frend/', pos:'noun',
   form:null, kat:'civakî', zor:0.92,
   notKu:'Heval / Hogir.',
   her:['My best friend.', 'Friends help us.'],
   herKu:['Hevalê min ê herî baş.', 'Heval alîkariya me dikin.'], emoji:'👫'),

  // ── Vücut ──────────────────────────────────────────────────
  (id:'en_a1_050', en:'head', ku:'serî', ipa:'/hed/', pos:'noun',
   form:null, kat:'beden', zor:0.88,
   notKu:'Serî. Beden a jor.',
   her:['My head hurts.', 'Big head.'],
   herKu:['Serê min diêşe.', 'Seriyê mezin.'], emoji:'🗣️'),

  (id:'en_a1_051', en:'eye', ku:'çav', ipa:'/aɪ/', pos:'noun',
   form:'pl: eyes', kat:'beden', zor:0.90,
   notKu:'Çav. Pirjimar: eyes.',
   her:['Blue eyes.', 'Close your eyes.'],
   herKu:['Çavên şîn.', 'Çavên xwe bigire.'], emoji:'👁️'),

  (id:'en_a1_052', en:'ear', ku:'guh', ipa:'/ɪər/', pos:'noun',
   form:null, kat:'beden', zor:0.85,
   notKu:'Guh. Endamê bihîstinê.',
   her:['Big ears.', 'Listen with your ears.'],
   herKu:['Guhên mezin.', 'Bi guhên xwe guhdarî bike.'], emoji:'👂'),

  (id:'en_a1_053', en:'nose', ku:'poz', ipa:'/noʊz/', pos:'noun',
   form:null, kat:'beden', zor:0.85,
   notKu:'Poz / Difin.',
   her:['Long nose.', 'My nose is cold.'],
   herKu:['Pozê dirêj.', 'Pozê min sar e.'], emoji:'👃'),

  (id:'en_a1_054', en:'mouth', ku:'dev', ipa:'/maʊθ/', pos:'noun',
   form:null, kat:'beden', zor:0.85,
   notKu:'Dev. Endamê axaftin/xwarinê.',
   her:['Open your mouth.', 'A small mouth.'],
   herKu:['Devê xwe veke.', 'Devekî biçûk.'], emoji:'👄'),

  (id:'en_a1_055', en:'hand', ku:'dest', ipa:'/hænd/', pos:'noun',
   form:null, kat:'beden', zor:0.92,
   notKu:'Dest. Endam.',
   her:['Wash your hands.', 'Take my hand.'],
   herKu:['Destên xwe bişo.', 'Destê min bigire.'], emoji:'✋'),

  (id:'en_a1_056', en:'foot', ku:'pê', ipa:'/fʊt/', pos:'noun',
   form:'pl: feet', kat:'beden', zor:0.85,
   notKu:'Pê. Pirjimar: feet.',
   her:['Big feet.', 'My foot hurts.'],
   herKu:['Pêyên mezin.', 'Pêyê min diêşe.'], emoji:'🦶'),

  (id:'en_a1_057', en:'leg', ku:'ling', ipa:'/leɡ/', pos:'noun',
   form:null, kat:'beden', zor:0.85,
   notKu:'Ling. Pê + jor.',
   her:['Long legs.', 'I broke my leg.'],
   herKu:['Lingên dirêj.', 'Lingê min şikest.'], emoji:'🦵'),

  (id:'en_a1_058', en:'arm', ku:'mil', ipa:'/ɑːrm/', pos:'noun',
   form:null, kat:'beden', zor:0.82,
   notKu:'Mil. Dest + jor.',
   her:['Strong arms.', 'My arm hurts.'],
   herKu:['Milên xurt.', 'Milê min diêşe.'], emoji:'💪'),

  (id:'en_a1_059', en:'hair', ku:'por', ipa:'/heər/', pos:'noun',
   form:null, kat:'beden', zor:0.80,
   notKu:'Por. Li ser serî.',
   her:['Long hair.', 'Black hair.'],
   herKu:['Porê dirêj.', 'Porê reş.'], emoji:'💇'),

  // ── Yiyecek-İçecek ─────────────────────────────────────────
  (id:'en_a1_060', en:'water', ku:'av', ipa:'/ˈwɔːtər/', pos:'noun',
   form:null, kat:'xwarin', zor:0.95,
   notKu:'Av. (uncountable — kabê tê hejmartin)',
   her:['I drink water.', 'Cold water.'],
   herKu:['Ez avê vedixwim.', 'Ava sar.'], emoji:'💧'),

  (id:'en_a1_061', en:'milk', ku:'şîr', ipa:'/mɪlk/', pos:'noun',
   form:null, kat:'xwarin', zor:0.90,
   notKu:'Şîr. (uncountable)',
   her:['I like milk.', 'A glass of milk.'],
   herKu:['Ez ji şîr hez dikim.', 'Qedeheke şîr.'], emoji:'🥛'),

  (id:'en_a1_062', en:'bread', ku:'nan', ipa:'/bred/', pos:'noun',
   form:null, kat:'xwarin', zor:0.92,
   notKu:'Nan. (uncountable)',
   her:['Fresh bread.', 'I eat bread.'],
   herKu:['Nanê taze.', 'Ez nan dixwim.'], emoji:'🍞'),

  (id:'en_a1_063', en:'rice', ku:'birinc', ipa:'/raɪs/', pos:'noun',
   form:null, kat:'xwarin', zor:0.85,
   notKu:'Birinc. (uncountable)',
   her:['Rice for dinner.', 'White rice.'],
   herKu:['Birinc ji bo şîvê.', 'Birinca spî.'], emoji:'🍚'),

  (id:'en_a1_064', en:'meat', ku:'goşt', ipa:'/miːt/', pos:'noun',
   form:null, kat:'xwarin', zor:0.85,
   notKu:'Goşt. (uncountable)',
   her:['Red meat.', 'I do not eat meat.'],
   herKu:['Goştê sor.', 'Ez goşt naxwim.'], emoji:'🥩'),

  (id:'en_a1_065', en:'egg', ku:'hêk', ipa:'/eɡ/', pos:'noun',
   form:'pl: eggs', kat:'xwarin', zor:0.88,
   notKu:'Hêk. Pirjimar: eggs.',
   her:['Two eggs for breakfast.', 'Fresh eggs.'],
   herKu:['Du hêk ji bo taştê.', 'Hêkên taze.'], emoji:'🥚'),

  (id:'en_a1_066', en:'cheese', ku:'penîr', ipa:'/tʃiːz/', pos:'noun',
   form:null, kat:'xwarin', zor:0.82,
   notKu:'Penîr. (uncountable)',
   her:['Cheese on bread.', 'Yellow cheese.'],
   herKu:['Penîr li ser nan.', 'Penîrê zer.'], emoji:'🧀'),

  (id:'en_a1_067', en:'apple', ku:'sêv', ipa:'/ˈæpəl/', pos:'noun',
   form:null, kat:'xwarin', zor:0.92,
   notKu:'Sêv. Fêkî.',
   her:['A red apple.', 'I eat an apple.'],
   herKu:['Sêveke sor.', 'Ez sêvekê dixwim.'], emoji:'🍎'),

  (id:'en_a1_068', en:'banana', ku:'mûz', ipa:'/bəˈnænə/', pos:'noun',
   form:null, kat:'xwarin', zor:0.85,
   notKu:'Mûz. Fêkî zer.',
   her:['A yellow banana.', 'I like bananas.'],
   herKu:['Mûzeke zer.', 'Ez ji mûzan hez dikim.'], emoji:'🍌'),

  (id:'en_a1_069', en:'tea', ku:'çay', ipa:'/tiː/', pos:'noun',
   form:null, kat:'xwarin', zor:0.92,
   notKu:'Çay. Vexwariyek germ.',
   her:['Hot tea.', 'I drink tea.'],
   herKu:['Çaya germ.', 'Ez çayê vedixwim.'], emoji:'🍵'),

  (id:'en_a1_070', en:'coffee', ku:'qehwe', ipa:'/ˈkɔːfi/', pos:'noun',
   form:null, kat:'xwarin', zor:0.88,
   notKu:'Qehwe. Vexwariyek germ.',
   her:['Black coffee.', 'A cup of coffee.'],
   herKu:['Qehwa reş.', 'Fincanek qehwe.'], emoji:'☕'),

  (id:'en_a1_071', en:'sugar', ku:'şekir', ipa:'/ˈʃʊɡər/', pos:'noun',
   form:null, kat:'xwarin', zor:0.85,
   notKu:'Şekir. (uncountable)',
   her:['Sugar in tea.', 'No sugar, please.'],
   herKu:['Şekir di çayê de.', 'Bê şekir, ji kerema xwe re.'], emoji:'🍬'),

  (id:'en_a1_072', en:'salt', ku:'xwê', ipa:'/sɔːlt/', pos:'noun',
   form:null, kat:'xwarin', zor:0.85,
   notKu:'Xwê. (uncountable)',
   her:['Salt and pepper.', 'Too much salt.'],
   herKu:['Xwê û îsot.', 'Pir xwê.'], emoji:'🧂'),

  (id:'en_a1_073', en:'food', ku:'xwarin', ipa:'/fuːd/', pos:'noun',
   form:null, kat:'xwarin', zor:0.92,
   notKu:'Xwarin. (uncountable)',
   her:['Good food.', 'Food is ready.'],
   herKu:['Xwarina baş.', 'Xwarin amade ye.'], emoji:'🍽️'),

  // ── Hayvan ─────────────────────────────────────────────────
  (id:'en_a1_074', en:'cat', ku:'pisîk', ipa:'/kæt/', pos:'noun',
   form:null, kat:'heywan', zor:0.92,
   notKu:'Pisîk. Heywanê malê.',
   her:['A black cat.', 'My cat sleeps.'],
   herKu:['Pisîkeke reş.', 'Pisîka min radize.'], emoji:'🐱'),

  (id:'en_a1_075', en:'dog', ku:'kûçik', ipa:'/dɔːɡ/', pos:'noun',
   form:null, kat:'heywan', zor:0.92,
   notKu:'Kûçik. Heywanê malê.',
   her:['A big dog.', 'The dog runs.'],
   herKu:['Kûçikekî mezin.', 'Kûçik direve.'], emoji:'🐶'),

  (id:'en_a1_076', en:'horse', ku:'hesp', ipa:'/hɔːrs/', pos:'noun',
   form:null, kat:'heywan', zor:0.85,
   notKu:'Hesp. Heywanê siwarbûnê.',
   her:['A fast horse.', 'White horse.'],
   herKu:['Hespekî bi lez.', 'Hespê spî.'], emoji:'🐴'),

  (id:'en_a1_077', en:'cow', ku:'çêlek', ipa:'/kaʊ/', pos:'noun',
   form:null, kat:'heywan', zor:0.82,
   notKu:'Çêlek / Mange. Şîr dide.',
   her:['Cows give milk.', 'A brown cow.'],
   herKu:['Çêlek şîr didin.', 'Çêlekeke qehweyî.'], emoji:'🐄'),

  (id:'en_a1_078', en:'sheep', ku:'pez', ipa:'/ʃiːp/', pos:'noun',
   form:'sg=pl', kat:'heywan', zor:0.82,
   notKu:'Pez. Pirjimar = sheep (neguherîn).',
   her:['Many sheep.', 'A white sheep.'],
   herKu:['Gelek pez.', 'Pezeke spî.'], emoji:'🐑'),

  (id:'en_a1_079', en:'chicken', ku:'mirîşk', ipa:'/ˈtʃɪkɪn/', pos:'noun',
   form:null, kat:'heywan', zor:0.85,
   notKu:'Mirîşk. Hêkan dide.',
   her:['The chicken eats.', 'A small chicken.'],
   herKu:['Mirîşk dixwe.', 'Mirîşkeke biçûk.'], emoji:'🐔'),

  (id:'en_a1_080', en:'bird', ku:'çûk', ipa:'/bɜːrd/', pos:'noun',
   form:null, kat:'heywan', zor:0.88,
   notKu:'Çûk. Difire.',
   her:['Birds sing.', 'A small bird.'],
   herKu:['Çûk distrên.', 'Çûkeke biçûk.'], emoji:'🐦'),

  (id:'en_a1_081', en:'fish', ku:'masî', ipa:'/fɪʃ/', pos:'noun',
   form:'sg=pl', kat:'heywan', zor:0.88,
   notKu:'Masî. Pirjimar = fish.',
   her:['Fish swim.', 'I eat fish.'],
   herKu:['Masî diavjênin.', 'Ez masî dixwim.'], emoji:'🐟'),

  // ── Zaman ──────────────────────────────────────────────────
  (id:'en_a1_082', en:'day', ku:'roj', ipa:'/deɪ/', pos:'noun',
   form:null, kat:'dem', zor:0.92,
   notKu:'Roj. 24 saet.',
   her:['A good day.', 'Every day.'],
   herKu:['Rojeke baş.', 'Her roj.'], emoji:'📅'),

  (id:'en_a1_083', en:'night', ku:'şev', ipa:'/naɪt/', pos:'noun',
   form:null, kat:'dem', zor:0.92,
   notKu:'Şev. Dema tarî.',
   her:['Good night.', 'A long night.'],
   herKu:['Şeva te xweş.', 'Şeveke dirêj.'], emoji:'🌙'),

  (id:'en_a1_084', en:'morning', ku:'sibê', ipa:'/ˈmɔːrnɪŋ/', pos:'noun',
   form:null, kat:'dem', zor:0.90,
   notKu:'Sibê. Dema rojhilatinê.',
   her:['Good morning!', 'Early in the morning.'],
   herKu:['Sibê baş!', 'Pir zû di sibê de.'], emoji:'🌅'),

  (id:'en_a1_085', en:'evening', ku:'êvar', ipa:'/ˈiːvnɪŋ/', pos:'noun',
   form:null, kat:'dem', zor:0.88,
   notKu:'Êvar. Dema rojavabûnê.',
   her:['Good evening.', 'In the evening.'],
   herKu:['Êvar baş.', 'Di êvarê de.'], emoji:'🌆'),

  (id:'en_a1_086', en:'today', ku:'îro', ipa:'/təˈdeɪ/', pos:'adv',
   form:null, kat:'dem', zor:0.92,
   notKu:'Îro. Roja niha.',
   her:['Today is Monday.', 'I work today.'],
   herKu:['Îro Duşem e.', 'Îro ez dixebitim.'], emoji:'📆'),

  (id:'en_a1_087', en:'tomorrow', ku:'sibê', ipa:'/təˈmɑːroʊ/', pos:'adv',
   form:null, kat:'dem', zor:0.88,
   notKu:'Sibê. Roja paş îro.',
   her:['See you tomorrow.', 'Tomorrow is Friday.'],
   herKu:['Sibê em hev dibînin.', 'Sibê Înî ye.'], emoji:'🗓️'),

  (id:'en_a1_088', en:'yesterday', ku:'duh', ipa:'/ˈjestərdeɪ/', pos:'adv',
   form:null, kat:'dem', zor:0.85,
   notKu:'Duh. Roja berî îro.',
   her:['Yesterday was hot.', 'I came yesterday.'],
   herKu:['Duh germ bû.', 'Ez duh hatim.'], emoji:'📜'),

  (id:'en_a1_089', en:'week', ku:'hefte', ipa:'/wiːk/', pos:'noun',
   form:null, kat:'dem', zor:0.88,
   notKu:'Hefte. 7 roj.',
   her:['Next week.', 'A long week.'],
   herKu:['Hefteya bê.', 'Hefteyeke dirêj.'], emoji:'🗓️'),

  (id:'en_a1_090', en:'month', ku:'meh', ipa:'/mʌnθ/', pos:'noun',
   form:null, kat:'dem', zor:0.85,
   notKu:'Meh. 30 roj.',
   her:['Last month.', 'In one month.'],
   herKu:['Meha borî.', 'Di nav mehekê de.'], emoji:'🗓️'),

  (id:'en_a1_091', en:'year', ku:'sal', ipa:'/jɪər/', pos:'noun',
   form:null, kat:'dem', zor:0.92,
   notKu:'Sal. 12 meh.',
   her:['Last year.', 'A new year.'],
   herKu:['Sala borî.', 'Saleke nû.'], emoji:'📅'),

  (id:'en_a1_092', en:'time', ku:'dem', ipa:'/taɪm/', pos:'noun',
   form:null, kat:'dem', zor:0.90,
   notKu:'Dem. Wext.',
   her:['What time is it?', 'I have time.'],
   herKu:['Dem çend e?', 'Dema min heye.'], emoji:'⏰'),

  (id:'en_a1_093', en:'hour', ku:'saet', ipa:'/ˈaʊər/', pos:'noun',
   form:null, kat:'dem', zor:0.85,
   notKu:'Saet. 60 deqîqe.',
   her:['One hour ago.', 'Two hours of work.'],
   herKu:['Saetek berê.', 'Du saet xebat.'], emoji:'⏱️'),

  (id:'en_a1_094', en:'minute', ku:'deqîqe', ipa:'/ˈmɪnɪt/', pos:'noun',
   form:null, kat:'dem', zor:0.82,
   notKu:'Deqîqe. 60 saniye.',
   her:['Five minutes left.', 'Wait a minute.'],
   herKu:['Pênc deqîqe maye.', 'Deqîqekê li bende be.'], emoji:'⏱️'),

  // ── Hafta günleri ──────────────────────────────────────────
  (id:'en_a1_095', en:'monday', ku:'duşem', ipa:'/ˈmʌndeɪ/', pos:'noun',
   form:null, kat:'roj', zor:0.85,
   notKu:'Duşem. Roja yekem ya hefteyê.',
   her:['Monday morning.', 'See you on Monday.'],
   herKu:['Sibehê duşemê.', 'Em duşemê hev dibînin.'], emoji:'📅'),

  (id:'en_a1_096', en:'tuesday', ku:'sêşem', ipa:'/ˈtuːzdeɪ/', pos:'noun',
   form:null, kat:'roj', zor:0.82,
   notKu:'Sêşem. Roja duyem.',
   her:['Tuesday is busy.', 'Class on Tuesday.'],
   herKu:['Sêşem mijûl e.', 'Ders di sêşemê de.'], emoji:'📅'),

  (id:'en_a1_097', en:'wednesday', ku:'çarşem', ipa:'/ˈwenzdeɪ/', pos:'noun',
   form:null, kat:'roj', zor:0.78,
   notKu:'Çarşem. Roja sêyem.',
   her:['Wednesday meeting.', 'It is Wednesday.'],
   herKu:['Civîna çarşemê.', 'Çarşem e.'], emoji:'📅'),

  (id:'en_a1_098', en:'thursday', ku:'pêncşem', ipa:'/ˈθɜːrzdeɪ/', pos:'noun',
   form:null, kat:'roj', zor:0.78,
   notKu:'Pêncşem. Roja çarem.',
   her:['Thursday evening.', 'I come on Thursday.'],
   herKu:['Êvara pêncşemê.', 'Ez pêncşemê têm.'], emoji:'📅'),

  (id:'en_a1_099', en:'friday', ku:'înî', ipa:'/ˈfraɪdeɪ/', pos:'noun',
   form:null, kat:'roj', zor:0.82,
   notKu:'Înî / Cuma. Roja pêncem.',
   her:['Friday is great.', 'On Friday morning.'],
   herKu:['Înî pir xweş e.', 'Sibehê înîyê.'], emoji:'📅'),

  (id:'en_a1_100', en:'saturday', ku:'şemî', ipa:'/ˈsætərdeɪ/', pos:'noun',
   form:null, kat:'roj', zor:0.85,
   notKu:'Şemî. Roja şeşem.',
   her:['Saturday is fun.', 'See you Saturday.'],
   herKu:['Şemî kêfxweş e.', 'Em şemiyê hev dibînin.'], emoji:'📅'),

  (id:'en_a1_101', en:'sunday', ku:'yekşem', ipa:'/ˈsʌndeɪ/', pos:'noun',
   form:null, kat:'roj', zor:0.85,
   notKu:'Yekşem. Roja heftem.',
   her:['Sunday family time.', 'I rest on Sunday.'],
   herKu:['Yekşem dem ji bo malbatê.', 'Ez yekşemê bêhna xwe vedidim.'], emoji:'📅'),

  // ── Yer-Mekan ──────────────────────────────────────────────
  (id:'en_a1_102', en:'home', ku:'mal', ipa:'/hoʊm/', pos:'noun',
   form:null, kat:'mal', zor:0.92,
   notKu:'Mal. Cihê jiyanê.',
   her:['I am at home.', 'Welcome home!'],
   herKu:['Ez li malê me.', 'Bi xêr hatî malê!'], emoji:'🏠'),

  (id:'en_a1_103', en:'house', ku:'xanî', ipa:'/haʊs/', pos:'noun',
   form:null, kat:'mal', zor:0.90,
   notKu:'Xanî. Avahiya jiyanê.',
   her:['A big house.', 'My new house.'],
   herKu:['Xaniyekî mezin.', 'Xaniyê min ê nû.'], emoji:'🏠'),

  (id:'en_a1_104', en:'school', ku:'dibistan', ipa:'/skuːl/', pos:'noun',
   form:null, kat:'cih', zor:0.92,
   notKu:'Dibistan. Cihê fêrbûnê.',
   her:['I go to school.', 'A new school.'],
   herKu:['Ez diçim dibistanê.', 'Dibistaneke nû.'], emoji:'🏫'),

  (id:'en_a1_105', en:'work', ku:'kar', ipa:'/wɜːrk/', pos:'noun',
   form:null, kat:'kar', zor:0.92,
   notKu:'Kar. Hem nav hem leker.',
   her:['Hard work.', 'After work.'],
   herKu:['Karê dijwar.', 'Piştî karî.'], emoji:'💼'),

  (id:'en_a1_106', en:'city', ku:'bajar', ipa:'/ˈsɪti/', pos:'noun',
   form:null, kat:'cih', zor:0.88,
   notKu:'Bajar. Cihê mezin ê jiyanê.',
   her:['A big city.', 'I live in the city.'],
   herKu:['Bajarekî mezin.', 'Ez li bajêr dijîm.'], emoji:'🏙️'),

  (id:'en_a1_107', en:'country', ku:'welat', ipa:'/ˈkʌntri/', pos:'noun',
   form:null, kat:'cih', zor:0.85,
   notKu:'Welat. Erdê neteweyî.',
   her:['My country is beautiful.', 'A small country.'],
   herKu:['Welatê min xweş e.', 'Welatekî biçûk.'], emoji:'🗺️'),

  (id:'en_a1_108', en:'street', ku:'kuçe', ipa:'/striːt/', pos:'noun',
   form:null, kat:'cih', zor:0.82,
   notKu:'Kuçe. Riya bajêr.',
   her:['A long street.', 'On the street.'],
   herKu:['Kuçeyek dirêj.', 'Li ser kuçeyê.'], emoji:'🛣️'),

  (id:'en_a1_109', en:'shop', ku:'dikan', ipa:'/ʃɑːp/', pos:'noun',
   form:null, kat:'cih', zor:0.85,
   notKu:'Dikan. Cihê kirîna tiştan.',
   her:['A small shop.', 'I go to the shop.'],
   herKu:['Dikaneke biçûk.', 'Ez diçim dikanê.'], emoji:'🏪'),

  (id:'en_a1_110', en:'hospital', ku:'nexweşxane', ipa:'/ˈhɑːspɪtəl/', pos:'noun',
   form:null, kat:'cih', zor:0.78,
   notKu:'Nexweşxane. Cihê dermankirinê.',
   her:['Go to the hospital.', 'A new hospital.'],
   herKu:['Biçe nexweşxaneyê.', 'Nexweşxaneyeke nû.'], emoji:'🏥'),

  (id:'en_a1_111', en:'park', ku:'park', ipa:'/pɑːrk/', pos:'noun',
   form:null, kat:'cih', zor:0.82,
   notKu:'Park. Cihê kesk ji bo gerê.',
   her:['Children in the park.', 'A green park.'],
   herKu:['Zarok li parkê.', 'Parkek kesk.'], emoji:'🌳'),

  (id:'en_a1_112', en:'room', ku:'ode', ipa:'/ruːm/', pos:'noun',
   form:null, kat:'mal', zor:0.85,
   notKu:'Ode / Jûr. Beşek ji xanî.',
   her:['My room is small.', 'A clean room.'],
   herKu:['Odeya min biçûk e.', 'Odeyek paqij.'], emoji:'🚪'),

  (id:'en_a1_113', en:'door', ku:'derî', ipa:'/dɔːr/', pos:'noun',
   form:null, kat:'mal', zor:0.88,
   notKu:'Derî. Cihê derbasbûnê.',
   her:['Open the door.', 'Close the door.'],
   herKu:['Derî veke.', 'Derî bigire.'], emoji:'🚪'),

  (id:'en_a1_114', en:'window', ku:'pencere', ipa:'/ˈwɪndoʊ/', pos:'noun',
   form:null, kat:'mal', zor:0.85,
   notKu:'Pencere. Şûşeya odeyê.',
   her:['Open the window.', 'A big window.'],
   herKu:['Pencereyê veke.', 'Pencereyeke mezin.'], emoji:'🪟'),

  // ── Doğa ───────────────────────────────────────────────────
  (id:'en_a1_115', en:'sun', ku:'roj', ipa:'/sʌn/', pos:'noun',
   form:null, kat:'xweza', zor:0.92,
   notKu:'Roj (ronak). Stêra me.',
   her:['The sun is hot.', 'Bright sun today.'],
   herKu:['Roj germ e.', 'Îro roj geş e.'], emoji:'☀️'),

  (id:'en_a1_116', en:'moon', ku:'heyv', ipa:'/muːn/', pos:'noun',
   form:null, kat:'xweza', zor:0.88,
   notKu:'Heyv. Stêra şevê.',
   her:['Full moon tonight.', 'The moon is bright.'],
   herKu:['Îşev heyv tijî ye.', 'Heyv geş e.'], emoji:'🌙'),

  (id:'en_a1_117', en:'star', ku:'stêr', ipa:'/stɑːr/', pos:'noun',
   form:null, kat:'xweza', zor:0.85,
   notKu:'Stêr. Geşa şevê.',
   her:['Many stars tonight.', 'A bright star.'],
   herKu:['Îşev gelek stêr.', 'Stêreke geş.'], emoji:'⭐'),

  (id:'en_a1_118', en:'sky', ku:'ezman', ipa:'/skaɪ/', pos:'noun',
   form:null, kat:'xweza', zor:0.85,
   notKu:'Ezman. Jor li me.',
   her:['Blue sky.', 'Birds in the sky.'],
   herKu:['Ezmanê şîn.', 'Çûk li ezmên.'], emoji:'🌌'),

  (id:'en_a1_119', en:'earth', ku:'erd', ipa:'/ɜːrθ/', pos:'noun',
   form:null, kat:'xweza', zor:0.82,
   notKu:'Erd / Cîhan. Gerstêrka me.',
   her:['Save the earth.', 'On earth.'],
   herKu:['Erdê biparêze.', 'Li ser erdê.'], emoji:'🌍'),

  (id:'en_a1_120', en:'tree', ku:'dar', ipa:'/triː/', pos:'noun',
   form:null, kat:'xweza', zor:0.92,
   notKu:'Dar. Riwekek mezin.',
   her:['A tall tree.', 'Trees give air.'],
   herKu:['Dareke dirêj.', 'Dar hewa didin.'], emoji:'🌳'),

  (id:'en_a1_121', en:'flower', ku:'kulîlk', ipa:'/ˈflaʊər/', pos:'noun',
   form:null, kat:'xweza', zor:0.85,
   notKu:'Kulîlk. Beşa rengîn ya darê.',
   her:['Beautiful flowers.', 'Red flowers.'],
   herKu:['Kulîlkên xweş.', 'Kulîlkên sor.'], emoji:'🌸'),

  (id:'en_a1_122', en:'mountain', ku:'çiya', ipa:'/ˈmaʊntən/', pos:'noun',
   form:null, kat:'xweza', zor:0.82,
   notKu:'Çiya. Erda bilind.',
   her:['A high mountain.', 'Mountain village.'],
   herKu:['Çiyayekî bilind.', 'Gundê çiyê.'], emoji:'⛰️'),

  (id:'en_a1_123', en:'river', ku:'çem', ipa:'/ˈrɪvər/', pos:'noun',
   form:null, kat:'xweza', zor:0.85,
   notKu:'Çem. Ava ku diherike.',
   her:['A long river.', 'River water.'],
   herKu:['Çemekî dirêj.', 'Ava çem.'], emoji:'🏞️'),

  (id:'en_a1_124', en:'sea', ku:'derya', ipa:'/siː/', pos:'noun',
   form:null, kat:'xweza', zor:0.82,
   notKu:'Derya / Behr. Ava xwêhî mezin.',
   her:['The blue sea.', 'I love the sea.'],
   herKu:['Deryaya şîn.', 'Ez ji deryayê hez dikim.'], emoji:'🌊'),

  (id:'en_a1_125', en:'rain', ku:'baran', ipa:'/reɪn/', pos:'noun',
   form:null, kat:'xweza', zor:0.88,
   notKu:'Baran. Ava ji ezmên.',
   her:['Heavy rain today.', 'I love the rain.'],
   herKu:['Îro baraneke giran.', 'Ez ji baranê hez dikim.'], emoji:'🌧️'),

  (id:'en_a1_126', en:'snow', ku:'berf', ipa:'/snoʊ/', pos:'noun',
   form:null, kat:'xweza', zor:0.88,
   notKu:'Berf. Ava cemidî ji ezmên.',
   her:['White snow falls.', 'Snow on mountains.'],
   herKu:['Berfa spî dibare.', 'Berf li ser çiyan.'], emoji:'❄️'),

  (id:'en_a1_127', en:'wind', ku:'ba', ipa:'/wɪnd/', pos:'noun',
   form:null, kat:'xweza', zor:0.82,
   notKu:'Ba / Bayî. Hewaya ku diçe.',
   her:['Strong wind.', 'The wind blows.'],
   herKu:['Bayê xurt.', 'Ba dilîse.'], emoji:'💨'),

  (id:'en_a1_128', en:'fire', ku:'agir', ipa:'/ˈfaɪər/', pos:'noun',
   form:null, kat:'xweza', zor:0.85,
   notKu:'Agir. Aleva germ.',
   her:['Hot fire.', 'Make a fire.'],
   herKu:['Agirê germ.', 'Agir vêxe.'], emoji:'🔥'),

  // ── Temel fiiller ──────────────────────────────────────────
  (id:'en_a1_129', en:'be', ku:'bûn', ipa:'/biː/', pos:'verb',
   form:'irreg: am/is/are, was/were, been', kat:'leker', zor:0.95,
   notKu:'Bûn. Çekirina herî girîng. (am/is/are)',
   her:['I am happy.', 'They are at home.'],
   herKu:['Ez kêfxweş im.', 'Ew li malê ne.'], emoji:null),

  (id:'en_a1_130', en:'have', ku:'hebûn', ipa:'/hæv/', pos:'verb',
   form:'irreg: have/has, had, had', kat:'leker', zor:0.92,
   notKu:'Hebûn / xwedî bûn. (have/has)',
   her:['I have a book.', 'She has a cat.'],
   herKu:['Pirtûkek min heye.', 'Pisîkek wê heye.'], emoji:null),

  (id:'en_a1_131', en:'do', ku:'kirin', ipa:'/duː/', pos:'verb',
   form:'irreg: do/does, did, done', kat:'leker', zor:0.92,
   notKu:'Kirin. Hem leker hem alîkar.',
   her:['I do my work.', 'What do you do?'],
   herKu:['Ez karê xwe dikim.', 'Tu çi dikî?'], emoji:null),

  (id:'en_a1_132', en:'go', ku:'çûn', ipa:'/ɡoʊ/', pos:'verb',
   form:'irreg: go/goes, went, gone', kat:'leker', zor:0.92,
   notKu:'Çûn. Çekirina nerêkûpêk.',
   her:['I go to work.', 'She goes home.'],
   herKu:['Ez diçim karî.', 'Ew diçe malê.'], emoji:'🚶'),

  (id:'en_a1_133', en:'come', ku:'hatin', ipa:'/kʌm/', pos:'verb',
   form:'irreg: come/comes, came, come', kat:'leker', zor:0.90,
   notKu:'Hatin. Nerêkûpêk.',
   her:['Come here, please.', 'She comes early.'],
   herKu:['Ji kerema xwe re were vir.', 'Ew zû tê.'], emoji:null),

  (id:'en_a1_134', en:'see', ku:'dîtin', ipa:'/siː/', pos:'verb',
   form:'irreg: see/sees, saw, seen', kat:'leker', zor:0.90,
   notKu:'Dîtin. Bi çavan dîtin.',
   her:['I see you.', 'See the sky.'],
   herKu:['Ez te dibînim.', 'Li ezmên binêre.'], emoji:'👀'),

  (id:'en_a1_135', en:'say', ku:'gotin', ipa:'/seɪ/', pos:'verb',
   form:'irreg: say/says, said, said', kat:'leker', zor:0.88,
   notKu:'Gotin.',
   her:['Say hello.', 'What did you say?'],
   herKu:['Silavê bibêje.', 'Te çi got?'], emoji:'💬'),

  (id:'en_a1_136', en:'know', ku:'zanîn', ipa:'/noʊ/', pos:'verb',
   form:'irreg: know/knows, knew, known', kat:'leker', zor:0.90,
   notKu:'Zanîn. ("k" deng nake)',
   her:['I know him.', 'Do you know?'],
   herKu:['Ez wî dizanim.', 'Tu dizanî?'], emoji:'🧠'),

  (id:'en_a1_137', en:'think', ku:'fikirîn', ipa:'/θɪŋk/', pos:'verb',
   form:'irreg: think/thinks, thought, thought', kat:'leker', zor:0.85,
   notKu:'Fikirîn / hizirîn.',
   her:['I think so.', 'Think about it.'],
   herKu:['Ez wisa difikirim.', 'Li ser bifikire.'], emoji:'💭'),

  (id:'en_a1_138', en:'want', ku:'xwestin', ipa:'/wɑːnt/', pos:'verb',
   form:'reg: want/wants, wanted', kat:'leker', zor:0.92,
   notKu:'Xwestin. Daxwaz kirin.',
   her:['I want water.', 'What do you want?'],
   herKu:['Ez avê dixwazim.', 'Tu çi dixwazî?'], emoji:null),

  (id:'en_a1_139', en:'like', ku:'jê hez kirin', ipa:'/laɪk/', pos:'verb',
   form:'reg: like/likes, liked', kat:'leker', zor:0.92,
   notKu:'Jê hez kirin.',
   her:['I like tea.', 'She likes books.'],
   herKu:['Ez ji çayê hez dikim.', 'Ew ji pirtûkan hez dike.'], emoji:'❤️'),

  (id:'en_a1_140', en:'love', ku:'evîn', ipa:'/lʌv/', pos:'verb',
   form:'reg: love/loves, loved', kat:'his', zor:0.92,
   notKu:'Evîn / hez kirin (kûr).',
   her:['I love you.', 'She loves music.'],
   herKu:['Ez te hez dikim.', 'Ew ji muzîkê hez dike.'], emoji:'❤️'),

  (id:'en_a1_141', en:'eat', ku:'xwarin', ipa:'/iːt/', pos:'verb',
   form:'irreg: eat/eats, ate, eaten', kat:'leker', zor:0.92,
   notKu:'Xwarin. Nerêkûpêk: ate.',
   her:['I eat bread.', 'They eat dinner.'],
   herKu:['Ez nan dixwim.', 'Ew şîvê dixwin.'], emoji:'🍽️'),

  (id:'en_a1_142', en:'drink', ku:'vexwarin', ipa:'/drɪŋk/', pos:'verb',
   form:'irreg: drink/drinks, drank, drunk', kat:'leker', zor:0.90,
   notKu:'Vexwarin. Nerêkûpêk: drank.',
   her:['Drink water.', 'I drink tea.'],
   herKu:['Avê vexwe.', 'Ez çayê vedixwim.'], emoji:'🥤'),

  (id:'en_a1_143', en:'sleep', ku:'razan', ipa:'/sliːp/', pos:'verb',
   form:'irreg: sleep/sleeps, slept, slept', kat:'leker', zor:0.88,
   notKu:'Razan. Nerêkûpêk: slept.',
   her:['I sleep at night.', 'Sleep well.'],
   herKu:['Ez şevê radizêm.', 'Baş raze.'], emoji:'😴'),

  (id:'en_a1_144', en:'walk', ku:'meşîn', ipa:'/wɔːk/', pos:'verb',
   form:'reg: walk/walks, walked', kat:'leker', zor:0.88,
   notKu:'Meşîn. Bi pê çûn.',
   her:['I walk to school.', 'She walks fast.'],
   herKu:['Ez bi peyatî diçim dibistanê.', 'Ew bi lez dimeşe.'], emoji:'🚶'),

  (id:'en_a1_145', en:'run', ku:'bezîn', ipa:'/rʌn/', pos:'verb',
   form:'irreg: run/runs, ran, run', kat:'leker', zor:0.88,
   notKu:'Bezîn / Revîn. Nerêkûpêk: ran.',
   her:['Children run.', 'Run fast!'],
   herKu:['Zarok dibezin.', 'Bi lez bibeze!'], emoji:'🏃'),

  (id:'en_a1_146', en:'read', ku:'xwendin', ipa:'/riːd/', pos:'verb',
   form:'irreg: read/reads, read, read', kat:'leker', zor:0.92,
   notKu:'Xwendin. Yazımı aynı, telaffuz değişir.',
   her:['I read a book.', 'She reads every day.'],
   herKu:['Ez pirtûkekê dixwînim.', 'Ew her roj dixwîne.'], emoji:'📖'),

  (id:'en_a1_147', en:'write', ku:'nivîsîn', ipa:'/raɪt/', pos:'verb',
   form:'irreg: write/writes, wrote, written', kat:'leker', zor:0.88,
   notKu:'Nivîsîn. Nerêkûpêk: wrote.',
   her:['Write your name.', 'I write a letter.'],
   herKu:['Navê xwe binivîse.', 'Ez nameyekê dinivîsim.'], emoji:'✍️'),

  (id:'en_a1_148', en:'listen', ku:'guhdarî kirin', ipa:'/ˈlɪsən/', pos:'verb',
   form:'reg: listen/listens, listened', kat:'leker', zor:0.85,
   notKu:'Guhdarî kirin. ("t" deng nake)',
   her:['Listen to me.', 'I listen to music.'],
   herKu:['Min guhdarî bike.', 'Ez muzîkê guhdarî dikim.'], emoji:'👂'),

  (id:'en_a1_149', en:'speak', ku:'axiftin', ipa:'/spiːk/', pos:'verb',
   form:'irreg: speak/speaks, spoke, spoken', kat:'leker', zor:0.85,
   notKu:'Axiftin / peyivîn.',
   her:['I speak English.', 'Speak slowly.'],
   herKu:['Ez Îngilîzî diaxivim.', 'Hêdî bipeyive.'], emoji:'🗣️'),

  (id:'en_a1_150', en:'open', ku:'vekirin', ipa:'/ˈoʊpən/', pos:'verb',
   form:'reg: open/opens, opened', kat:'leker', zor:0.88,
   notKu:'Vekirin.',
   her:['Open the door.', 'Open your book.'],
   herKu:['Derî veke.', 'Pirtûka xwe veke.'], emoji:null),

  (id:'en_a1_151', en:'close', ku:'girtin', ipa:'/kloʊz/', pos:'verb',
   form:'reg: close/closes, closed', kat:'leker', zor:0.85,
   notKu:'Girtin / dadan.',
   her:['Close the window.', 'Close your eyes.'],
   herKu:['Pencereyê bigire.', 'Çavên xwe bigire.'], emoji:null),

  (id:'en_a1_152', en:'start', ku:'dest pê kirin', ipa:'/stɑːrt/', pos:'verb',
   form:'reg: start/starts, started', kat:'leker', zor:0.88,
   notKu:'Dest pê kirin.',
   her:['Start the lesson.', 'School starts at 8.'],
   herKu:['Ders dest pê bike.', 'Dibistan saet 8 dest pê dike.'], emoji:'▶️'),

  (id:'en_a1_153', en:'stop', ku:'sekinîn', ipa:'/stɑːp/', pos:'verb',
   form:'reg: stop/stops, stopped', kat:'leker', zor:0.85,
   notKu:'Sekinîn / rawestîn.',
   her:['Stop here.', 'The bus stops.'],
   herKu:['Li vir bisekine.', 'Otobûs disekine.'], emoji:'⛔'),

  (id:'en_a1_154', en:'give', ku:'dan', ipa:'/ɡɪv/', pos:'verb',
   form:'irreg: give/gives, gave, given', kat:'leker', zor:0.90,
   notKu:'Dan. Nerêkûpêk: gave.',
   her:['Give me water.', 'She gives a gift.'],
   herKu:['Avê bide min.', 'Ew diyariyekê dide.'], emoji:null),

  (id:'en_a1_155', en:'take', ku:'girtin', ipa:'/teɪk/', pos:'verb',
   form:'irreg: take/takes, took, taken', kat:'leker', zor:0.90,
   notKu:'Girtin / hildan. Nerêkûpêk: took.',
   her:['Take this book.', 'I take a taxi.'],
   herKu:['Vê pirtûkê hilde.', 'Ez bi taksiyê diçim.'], emoji:null),

  (id:'en_a1_156', en:'make', ku:'çêkirin', ipa:'/meɪk/', pos:'verb',
   form:'irreg: make/makes, made, made', kat:'leker', zor:0.92,
   notKu:'Çêkirin / kirin. Nerêkûpêk: made.',
   her:['Make food.', 'I make a cake.'],
   herKu:['Xwarinê çêke.', 'Ez kekekî çêdikim.'], emoji:null),

  (id:'en_a1_157', en:'play', ku:'lîstin', ipa:'/pleɪ/', pos:'verb',
   form:'reg: play/plays, played', kat:'leker', zor:0.92,
   notKu:'Lîstin / Lîstik kirin.',
   her:['Children play.', 'I play music.'],
   herKu:['Zarok dilîzin.', 'Ez muzîkê dilîzim.'], emoji:'🎮'),

  (id:'en_a1_158', en:'learn', ku:'fêr bûn', ipa:'/lɜːrn/', pos:'verb',
   form:'reg: learn/learns, learned', kat:'leker', zor:0.92,
   notKu:'Fêr bûn / hîn bûn.',
   her:['I learn English.', 'Children learn fast.'],
   herKu:['Ez Îngilîzî fêr dibim.', 'Zarok zû fêr dibin.'], emoji:'📚'),

  (id:'en_a1_159', en:'teach', ku:'fêr kirin', ipa:'/tiːtʃ/', pos:'verb',
   form:'irreg: teach/teaches, taught, taught', kat:'leker', zor:0.85,
   notKu:'Fêr kirin / hîn kirin.',
   her:['She teaches us.', 'Teach me, please.'],
   herKu:['Ew me hîn dike.', 'Min fêr bike, ji kerema xwe re.'], emoji:'👨‍🏫'),

  (id:'en_a1_160', en:'help', ku:'alîkarî kirin', ipa:'/help/', pos:'verb',
   form:'reg: help/helps, helped', kat:'leker', zor:0.92,
   notKu:'Alîkarî kirin.',
   her:['Help me.', 'I help my friend.'],
   herKu:['Alîkariya min bike.', 'Ez alîkariya hevalê xwe dikim.'], emoji:'🤝'),

  (id:'en_a1_161', en:'live', ku:'jiyîn', ipa:'/lɪv/', pos:'verb',
   form:'reg: live/lives, lived', kat:'leker', zor:0.88,
   notKu:'Jiyîn / dimanîn.',
   her:['I live in a city.', 'She lives here.'],
   herKu:['Ez li bajarekî dijîm.', 'Ew li vir dijî.'], emoji:null),

  (id:'en_a1_162', en:'buy', ku:'kirîn', ipa:'/baɪ/', pos:'verb',
   form:'irreg: buy/buys, bought, bought', kat:'leker', zor:0.85,
   notKu:'Kirîn. Nerêkûpêk: bought.',
   her:['I buy bread.', 'She bought a car.'],
   herKu:['Ez nanê dikirim.', 'Wê erebeyek kirî.'], emoji:'🛒'),

  (id:'en_a1_163', en:'sell', ku:'firotin', ipa:'/sel/', pos:'verb',
   form:'irreg: sell/sells, sold, sold', kat:'leker', zor:0.78,
   notKu:'Firotin. Nerêkûpêk: sold.',
   her:['They sell apples.', 'I sold my old phone.'],
   herKu:['Ew sêvan difroşin.', 'Min telefona xwe ya kevn firot.'], emoji:'💵'),

  (id:'en_a1_164', en:'use', ku:'bikar anîn', ipa:'/juːz/', pos:'verb',
   form:'reg: use/uses, used', kat:'leker', zor:0.85,
   notKu:'Bikar anîn.',
   her:['I use a phone.', 'Use this pen.'],
   herKu:['Ez telefonekê bikar tînim.', 'Vê pênûsê bikar bîne.'], emoji:null),

  (id:'en_a1_165', en:'find', ku:'dîtin', ipa:'/faɪnd/', pos:'verb',
   form:'irreg: find/finds, found, found', kat:'leker', zor:0.85,
   notKu:'Dîtin (peyda kirin). Nerêkûpêk: found.',
   her:['I find a book.', 'She found her pen.'],
   herKu:['Ez pirtûkekê dibînim.', 'Wê pênûsa xwe peyda kir.'], emoji:null),

  // ── Sıfat (yaygın) ─────────────────────────────────────────
  (id:'en_a1_166', en:'big', ku:'mezin', ipa:'/bɪɡ/', pos:'adj',
   form:'comp: bigger, super: biggest', kat:'rengdêr', zor:0.95,
   notKu:'Mezin. Berhevdarî: bigger.',
   her:['A big house.', 'Big eyes.'],
   herKu:['Xaniyekî mezin.', 'Çavên mezin.'], emoji:null),

  (id:'en_a1_167', en:'small', ku:'biçûk', ipa:'/smɔːl/', pos:'adj',
   form:'comp: smaller', kat:'rengdêr', zor:0.95,
   notKu:'Biçûk.',
   her:['A small dog.', 'Small but cute.'],
   herKu:['Kûçikekî biçûk.', 'Biçûk lê xweşik.'], emoji:null),

  (id:'en_a1_168', en:'good', ku:'baş', ipa:'/ɡʊd/', pos:'adj',
   form:'irreg comp: better, best', kat:'rengdêr', zor:0.95,
   notKu:'Baş. Berhevdarî nerêkûpêk: better.',
   her:['Good morning.', 'A good book.'],
   herKu:['Sibê baş.', 'Pirtûkek baş.'], emoji:'👍'),

  (id:'en_a1_169', en:'bad', ku:'xirab', ipa:'/bæd/', pos:'adj',
   form:'irreg comp: worse, worst', kat:'rengdêr', zor:0.92,
   notKu:'Xirab. Berhevdarî nerêkûpêk: worse.',
   her:['Bad weather.', 'A bad day.'],
   herKu:['Hewaya xirab.', 'Rojeke xirab.'], emoji:'👎'),

  (id:'en_a1_170', en:'new', ku:'nû', ipa:'/nuː/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.92,
   notKu:'Nû. Bê kevn.',
   her:['A new car.', 'New shoes.'],
   herKu:['Erebek nû.', 'Solên nû.'], emoji:'✨'),

  (id:'en_a1_171', en:'old', ku:'kevn', ipa:'/oʊld/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.90,
   notKu:'Kevn (tişt) / Pîr (mirov).',
   her:['An old book.', 'My old friend.'],
   herKu:['Pirtûkeke kevn.', 'Hevalê min ê kevn.'], emoji:'🕰️'),

  (id:'en_a1_172', en:'young', ku:'ciwan', ipa:'/jʌŋ/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.85,
   notKu:'Ciwan / xort.',
   her:['A young man.', 'I am young.'],
   herKu:['Mêrekî ciwan.', 'Ez ciwan im.'], emoji:'👶'),

  (id:'en_a1_173', en:'happy', ku:'kêfxweş', ipa:'/ˈhæpi/', pos:'adj',
   form:null, kat:'his', zor:0.92,
   notKu:'Kêfxweş / şa.',
   her:['I am happy.', 'A happy day.'],
   herKu:['Ez kêfxweş im.', 'Rojeke şa.'], emoji:'😊'),

  (id:'en_a1_174', en:'sad', ku:'xemgîn', ipa:'/sæd/', pos:'adj',
   form:null, kat:'his', zor:0.88,
   notKu:'Xemgîn / dilteng.',
   her:['She is sad.', 'A sad story.'],
   herKu:['Ew xemgîn e.', 'Çîrokeke xemgîn.'], emoji:'😢'),

  (id:'en_a1_175', en:'hot', ku:'germ', ipa:'/hɑːt/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.92,
   notKu:'Germ.',
   her:['Hot tea.', 'A hot day.'],
   herKu:['Çaya germ.', 'Rojeke germ.'], emoji:'🔥'),

  (id:'en_a1_176', en:'cold', ku:'sar', ipa:'/koʊld/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.92,
   notKu:'Sar.',
   her:['Cold water.', 'It is cold today.'],
   herKu:['Ava sar.', 'Îro sar e.'], emoji:'❄️'),

  (id:'en_a1_177', en:'long', ku:'dirêj', ipa:'/lɔːŋ/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.90,
   notKu:'Dirêj.',
   her:['A long road.', 'Long hair.'],
   herKu:['Riya dirêj.', 'Porê dirêj.'], emoji:null),

  (id:'en_a1_178', en:'short', ku:'kurt', ipa:'/ʃɔːrt/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.88,
   notKu:'Kurt.',
   her:['A short man.', 'Short hair.'],
   herKu:['Mêrekî kurt.', 'Porê kurt.'], emoji:null),

  (id:'en_a1_179', en:'high', ku:'bilind', ipa:'/haɪ/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.85,
   notKu:'Bilind.',
   her:['A high mountain.', 'High prices.'],
   herKu:['Çiyayê bilind.', 'Bihayên bilind.'], emoji:'⬆️'),

  (id:'en_a1_180', en:'low', ku:'nizim', ipa:'/loʊ/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.78,
   notKu:'Nizim / kêm.',
   her:['Low table.', 'Low voice.'],
   herKu:['Maseyek nizim.', 'Dengê nizim.'], emoji:'⬇️'),

  (id:'en_a1_181', en:'right', ku:'rast', ipa:'/raɪt/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.92,
   notKu:'Rast (doğru) / Rastê (right side).',
   her:['You are right.', 'Right answer.'],
   herKu:['Tu rast î.', 'Bersiva rast.'], emoji:'✅'),

  (id:'en_a1_182', en:'wrong', ku:'çewt', ipa:'/rɔːŋ/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.85,
   notKu:'Çewt / xelet.',
   her:['Wrong answer.', 'I was wrong.'],
   herKu:['Bersiva çewt.', 'Ez çewt bûm.'], emoji:'❌'),

  (id:'en_a1_183', en:'easy', ku:'hêsan', ipa:'/ˈiːzi/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.88,
   notKu:'Hêsan.',
   her:['An easy lesson.', 'It is easy.'],
   herKu:['Dersa hêsan.', 'Ew hêsan e.'], emoji:null),

  (id:'en_a1_184', en:'hard', ku:'dijwar', ipa:'/hɑːrd/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.85,
   notKu:'Dijwar (qedere) / hişk (laş).',
   her:['Hard work.', 'A hard question.'],
   herKu:['Karê dijwar.', 'Pirseke dijwar.'], emoji:null),

  (id:'en_a1_185', en:'beautiful', ku:'xweşik', ipa:'/ˈbjuːtɪfəl/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.85,
   notKu:'Xweşik / spehî.',
   her:['Beautiful flowers.', 'A beautiful day.'],
   herKu:['Kulîlkên xweşik.', 'Rojeke xweşik.'], emoji:'🌸'),

  // ── Zamir ──────────────────────────────────────────────────
  (id:'en_a1_186', en:'i', ku:'ez', ipa:'/aɪ/', pos:'pronoun',
   form:'subject; object: me', kat:'cinavk', zor:0.95,
   notKu:'Ez. Her tim mezin tîp: I.',
   her:['I am happy.', 'I have a book.'],
   herKu:['Ez kêfxweş im.', 'Pirtûkek min heye.'], emoji:null),

  (id:'en_a1_187', en:'you', ku:'tu', ipa:'/juː/', pos:'pronoun',
   form:'sg + pl', kat:'cinavk', zor:0.95,
   notKu:'Tu (sg) / Hûn (pl). Aynı kelime.',
   her:['You are kind.', 'You both are here.'],
   herKu:['Tu dilovan î.', 'Hûn herdu li vir in.'], emoji:null),

  (id:'en_a1_188', en:'he', ku:'ew (nêr)', ipa:'/hiː/', pos:'pronoun',
   form:'object: him', kat:'cinavk', zor:0.92,
   notKu:'Ew (mêr). Object: him.',
   her:['He is my brother.', 'I see him.'],
   herKu:['Ew birayê min e.', 'Ez wî dibînim.'], emoji:null),

  (id:'en_a1_189', en:'she', ku:'ew (mê)', ipa:'/ʃiː/', pos:'pronoun',
   form:'object: her', kat:'cinavk', zor:0.92,
   notKu:'Ew (jin). Object: her.',
   her:['She is my sister.', 'I help her.'],
   herKu:['Ew xwişka min e.', 'Ez alîkariya wê dikim.'], emoji:null),

  (id:'en_a1_190', en:'we', ku:'em', ipa:'/wiː/', pos:'pronoun',
   form:'object: us', kat:'cinavk', zor:0.92,
   notKu:'Em. Object: us.',
   her:['We are friends.', 'They see us.'],
   herKu:['Em heval in.', 'Ew me dibînin.'], emoji:null),

  (id:'en_a1_191', en:'they', ku:'ew (pirjimar)', ipa:'/ðeɪ/', pos:'pronoun',
   form:'object: them', kat:'cinavk', zor:0.92,
   notKu:'Ew (pirjimar). Object: them.',
   her:['They are here.', 'I know them.'],
   herKu:['Ew li vir in.', 'Ez wan dizanim.'], emoji:null),

  (id:'en_a1_192', en:'it', ku:'wê', ipa:'/ɪt/', pos:'pronoun',
   form:'object: it', kat:'cinavk', zor:0.88,
   notKu:'Wê / Ew. Ji bo tişt û heywanan.',
   her:['It is hot.', 'I see it.'],
   herKu:['Ew germ e.', 'Ez wê dibînim.'], emoji:null),

  (id:'en_a1_193', en:'this', ku:'ev', ipa:'/ðɪs/', pos:'pronoun',
   form:'pl: these', kat:'cinavk', zor:0.92,
   notKu:'Ev. Pirjimar: these.',
   her:['This book.', 'This is mine.'],
   herKu:['Ev pirtûk.', 'Ev a min e.'], emoji:null),

  (id:'en_a1_194', en:'that', ku:'ew', ipa:'/ðæt/', pos:'pronoun',
   form:'pl: those', kat:'cinavk', zor:0.92,
   notKu:'Ew. Pirjimar: those.',
   her:['That tree.', 'That is yours.'],
   herKu:['Ew dar.', 'Ew a te ye.'], emoji:null),

  // ── Edat / Bağlaç ──────────────────────────────────────────
  (id:'en_a1_195', en:'in', ku:'di...de', ipa:'/ɪn/', pos:'prep',
   form:null, kat:'daçek', zor:0.92,
   notKu:'Di...de. Hundir.',
   her:['In the room.', 'In the morning.'],
   herKu:['Di odeyê de.', 'Di sibê de.'], emoji:null),

  (id:'en_a1_196', en:'on', ku:'li ser', ipa:'/ɑːn/', pos:'prep',
   form:null, kat:'daçek', zor:0.92,
   notKu:'Li ser. Jor.',
   her:['On the table.', 'On Monday.'],
   herKu:['Li ser maseyê.', 'Roja duşemê.'], emoji:null),

  (id:'en_a1_197', en:'at', ku:'li', ipa:'/æt/', pos:'prep',
   form:null, kat:'daçek', zor:0.88,
   notKu:'Li. Cih an dem.',
   her:['At home.', 'At eight o\'clock.'],
   herKu:['Li malê.', 'Saet heyştan.'], emoji:null),

  (id:'en_a1_198', en:'to', ku:'bo', ipa:'/tuː/', pos:'prep',
   form:null, kat:'daçek', zor:0.92,
   notKu:'Bo / re. Armanc.',
   her:['Go to school.', 'A gift to you.'],
   herKu:['Biçe dibistanê.', 'Diyariyek ji bo te.'], emoji:null),

  (id:'en_a1_199', en:'from', ku:'ji', ipa:'/frʌm/', pos:'prep',
   form:null, kat:'daçek', zor:0.92,
   notKu:'Ji. Cihê derketinê.',
   her:['From home.', 'A letter from me.'],
   herKu:['Ji malê.', 'Nameyek ji min.'], emoji:null),

  (id:'en_a1_200', en:'with', ku:'bi...re', ipa:'/wɪð/', pos:'prep',
   form:null, kat:'daçek', zor:0.90,
   notKu:'Bi...re. Hevra.',
   her:['With my friend.', 'Tea with milk.'],
   herKu:['Bi hevalê min re.', 'Çay bi şîr re.'], emoji:null),

  (id:'en_a1_201', en:'and', ku:'û', ipa:'/ænd/', pos:'conj',
   form:null, kat:'daçek', zor:0.95,
   notKu:'Û. Hevgir.',
   her:['Bread and cheese.', 'You and me.'],
   herKu:['Nan û penîr.', 'Tu û ez.'], emoji:null),

  (id:'en_a1_202', en:'but', ku:'lê', ipa:'/bʌt/', pos:'conj',
   form:null, kat:'daçek', zor:0.92,
   notKu:'Lê. Berevajî.',
   her:['Small but strong.', 'I want, but cannot.'],
   herKu:['Biçûk lê xurt.', 'Ez dixwazim, lê nikarim.'], emoji:null),

  (id:'en_a1_203', en:'or', ku:'an', ipa:'/ɔːr/', pos:'conj',
   form:null, kat:'daçek', zor:0.90,
   notKu:'An / Yan.',
   her:['Tea or coffee?', 'Yes or no?'],
   herKu:['Çay an qehwe?', 'Erê an na?'], emoji:null),

  (id:'en_a1_204', en:'because', ku:'ji ber ku', ipa:'/bɪˈkɔːz/', pos:'conj',
   form:null, kat:'daçek', zor:0.82,
   notKu:'Ji ber ku.',
   her:['Because I like it.', 'I am happy because you came.'],
   herKu:['Ji ber ku ez ji wê hez dikim.', 'Ez kêfxweş im ji ber ku tu hatî.'], emoji:null),

  (id:'en_a1_205', en:'if', ku:'eger', ipa:'/ɪf/', pos:'conj',
   form:null, kat:'daçek', zor:0.88,
   notKu:'Eger / heke.',
   her:['If you want.', 'If it rains.'],
   herKu:['Eger tu bixwazî.', 'Eger baran bibare.'], emoji:null),

  // ── Soru sözleri ──────────────────────────────────────────
  (id:'en_a1_206', en:'what', ku:'çi', ipa:'/wʌt/', pos:'pronoun',
   form:null, kat:'pirsî', zor:0.95,
   notKu:'Çi. Pirsîn ji bo tişt.',
   her:['What is this?', 'What do you want?'],
   herKu:['Ev çi ye?', 'Tu çi dixwazî?'], emoji:'❓'),

  (id:'en_a1_207', en:'who', ku:'kî', ipa:'/huː/', pos:'pronoun',
   form:null, kat:'pirsî', zor:0.92,
   notKu:'Kî. Pirsîn ji bo kes.',
   her:['Who is there?', 'Who are you?'],
   herKu:['Kî li wir e?', 'Tu kî yî?'], emoji:'❓'),

  (id:'en_a1_208', en:'where', ku:'li ku', ipa:'/weər/', pos:'adv',
   form:null, kat:'pirsî', zor:0.92,
   notKu:'Li ku. Pirsîn ji bo cih.',
   her:['Where is the book?', 'Where do you live?'],
   herKu:['Pirtûk li ku ye?', 'Tu li ku dijî?'], emoji:'❓'),

  (id:'en_a1_209', en:'when', ku:'kengî', ipa:'/wen/', pos:'adv',
   form:null, kat:'pirsî', zor:0.90,
   notKu:'Kengî. Pirsîn ji bo dem.',
   her:['When are you free?', 'When does it start?'],
   herKu:['Kengî tu vala yî?', 'Kengî dest pê dike?'], emoji:'❓'),

  (id:'en_a1_210', en:'why', ku:'çima', ipa:'/waɪ/', pos:'adv',
   form:null, kat:'pirsî', zor:0.90,
   notKu:'Çima. Pirsîn ji bo sebeb.',
   her:['Why are you sad?', 'Why not?'],
   herKu:['Çima tu xemgîn î?', 'Çima na?'], emoji:'❓'),

  (id:'en_a1_211', en:'how', ku:'çawa', ipa:'/haʊ/', pos:'adv',
   form:null, kat:'pirsî', zor:0.92,
   notKu:'Çawa. Pirsîn ji bo awa.',
   her:['How are you?', 'How do you do this?'],
   herKu:['Tu çawa yî?', 'Tu vê yekê çawa dikî?'], emoji:'❓'),

  // ── Diğer önemli ───────────────────────────────────────────
  (id:'en_a1_212', en:'book', ku:'pirtûk', ipa:'/bʊk/', pos:'noun',
   form:null, kat:'tişt', zor:0.92,
   notKu:'Pirtûk.',
   her:['I read a book.', 'A new book.'],
   herKu:['Ez pirtûkekê dixwînim.', 'Pirtûkeke nû.'], emoji:'📖'),

  (id:'en_a1_213', en:'pen', ku:'pênûs', ipa:'/pen/', pos:'noun',
   form:null, kat:'tişt', zor:0.85,
   notKu:'Pênûs / qelem.',
   her:['A blue pen.', 'I write with a pen.'],
   herKu:['Pênûseke şîn.', 'Ez bi pênûsê dinivîsim.'], emoji:'✏️'),

  (id:'en_a1_214', en:'paper', ku:'kaxez', ipa:'/ˈpeɪpər/', pos:'noun',
   form:null, kat:'tişt', zor:0.85,
   notKu:'Kaxez.',
   her:['A piece of paper.', 'White paper.'],
   herKu:['Pareyek kaxez.', 'Kaxeza spî.'], emoji:'📄'),

  (id:'en_a1_215', en:'phone', ku:'telefon', ipa:'/foʊn/', pos:'noun',
   form:null, kat:'tişt', zor:0.92,
   notKu:'Telefon. ("ph" = f deng dike)',
   her:['My phone is new.', 'Call my phone.'],
   herKu:['Telefona min nû ye.', 'Telefona min lê de.'], emoji:'📱'),

  (id:'en_a1_216', en:'car', ku:'erebe', ipa:'/kɑːr/', pos:'noun',
   form:null, kat:'rêwîtî', zor:0.92,
   notKu:'Erebe / otomobîl.',
   her:['A red car.', 'My new car.'],
   herKu:['Erebek sor.', 'Erebeya min ya nû.'], emoji:'🚗'),

  (id:'en_a1_217', en:'bus', ku:'otobûs', ipa:'/bʌs/', pos:'noun',
   form:null, kat:'rêwîtî', zor:0.88,
   notKu:'Otobûs.',
   her:['Take the bus.', 'A yellow bus.'],
   herKu:['Bi otobûsê biçe.', 'Otobûseke zer.'], emoji:'🚌'),

  (id:'en_a1_218', en:'train', ku:'trên', ipa:'/treɪn/', pos:'noun',
   form:null, kat:'rêwîtî', zor:0.85,
   notKu:'Trên.',
   her:['A fast train.', 'Train station.'],
   herKu:['Trêneke bi lez.', 'Stasyona trênê.'], emoji:'🚆'),

  (id:'en_a1_219', en:'plane', ku:'firoke', ipa:'/pleɪn/', pos:'noun',
   form:null, kat:'rêwîtî', zor:0.82,
   notKu:'Firoke / balafir.',
   her:['A big plane.', 'I take a plane.'],
   herKu:['Firokeke mezin.', 'Ez bi firokê diçim.'], emoji:'✈️'),

  (id:'en_a1_220', en:'table', ku:'mase', ipa:'/ˈteɪbəl/', pos:'noun',
   form:null, kat:'mal', zor:0.88,
   notKu:'Mase.',
   her:['On the table.', 'A wooden table.'],
   herKu:['Li ser maseyê.', 'Maseyeke darîn.'], emoji:'🪑'),

  (id:'en_a1_221', en:'chair', ku:'kursî', ipa:'/tʃeər/', pos:'noun',
   form:null, kat:'mal', zor:0.88,
   notKu:'Kursî.',
   her:['Sit on the chair.', 'A new chair.'],
   herKu:['Li ser kursiyê rûne.', 'Kursiyeke nû.'], emoji:'🪑'),

  (id:'en_a1_222', en:'bed', ku:'nivîn', ipa:'/bed/', pos:'noun',
   form:null, kat:'mal', zor:0.88,
   notKu:'Nivîn / cî.',
   her:['Go to bed.', 'A big bed.'],
   herKu:['Biçe nivînê.', 'Nivîneke mezin.'], emoji:'🛏️'),

  (id:'en_a1_223', en:'clothes', ku:'cil', ipa:'/kloʊz/', pos:'noun',
   form:'plural only', kat:'cil', zor:0.82,
   notKu:'Cil. Hertim pirjimar.',
   her:['New clothes.', 'I wash clothes.'],
   herKu:['Cilên nû.', 'Ez cilan dişom.'], emoji:'👕'),

  (id:'en_a1_224', en:'shoe', ku:'sol', ipa:'/ʃuː/', pos:'noun',
   form:'pl: shoes', kat:'cil', zor:0.85,
   notKu:'Sol. Pirjimar: shoes.',
   her:['New shoes.', 'Black shoes.'],
   herKu:['Solên nû.', 'Solên reş.'], emoji:'👞'),

  (id:'en_a1_225', en:'money', ku:'pere', ipa:'/ˈmʌni/', pos:'noun',
   form:'uncountable', kat:'kar', zor:0.92,
   notKu:'Pere. (uncountable — kabê tê hejmartin)',
   her:['I have money.', 'No money today.'],
   herKu:['Pereyê min hene.', 'Îro pere tune.'], emoji:'💰'),

  (id:'en_a1_226', en:'language', ku:'ziman', ipa:'/ˈlæŋɡwɪdʒ/', pos:'noun',
   form:null, kat:'ziman', zor:0.88,
   notKu:'Ziman.',
   her:['I speak two languages.', 'A new language.'],
   herKu:['Ez du zimanan diaxivim.', 'Zimanekî nû.'], emoji:'🗣️'),

  (id:'en_a1_227', en:'word', ku:'peyv', ipa:'/wɜːrd/', pos:'noun',
   form:null, kat:'ziman', zor:0.92,
   notKu:'Peyv / kelîme.',
   her:['A new word.', 'Learn ten words.'],
   herKu:['Peyveke nû.', 'Deh peyvan fêr bibe.'], emoji:'💬'),

  (id:'en_a1_228', en:'name', ku:'nav', ipa:'/neɪm/', pos:'noun',
   form:null, kat:'civakî', zor:0.92,
   notKu:'Nav.',
   her:['My name is Sara.', 'What is your name?'],
   herKu:['Navê min Sara ye.', 'Navê te çi ye?'], emoji:null),

  (id:'en_a1_229', en:'people', ku:'mirov', ipa:'/ˈpiːpəl/', pos:'noun',
   form:'pl of person', kat:'civakî', zor:0.88,
   notKu:'Mirov / kes. Pirjimara person.',
   her:['Many people here.', 'Good people.'],
   herKu:['Gelek mirov li vir.', 'Mirovên baş.'], emoji:'👥'),

  (id:'en_a1_230', en:'thing', ku:'tişt', ipa:'/θɪŋ/', pos:'noun',
   form:null, kat:'tişt', zor:0.92,
   notKu:'Tişt. Nesneyên giştî.',
   her:['What is this thing?', 'Many things.'],
   herKu:['Ev tişt çi ye?', 'Gelek tişt.'], emoji:null),
];
