// LÛTKE — İngilizce Çocuk A1 (Pre-A1 Starters)
// Oxford 3000/5000 + EVP CHILD_A1 referans.
// 200 kelime.

import 'en_word.dart';

const List<EnWord> kEnChildA1Liste = [
  (id:'en_child_a1_001', en:'cat', ku:'pisîk', ipa:'/kæt/', pos:'noun',
   form:null, kat:'heywan', zor:0.95,
   notKu:'Pisîk. Heywanê mal.',
   her:["I have a cat.", "The cat is small."],
   herKu:['Pisîkek min heye.', 'Pisîk biçûk e.'], emoji:'🐱'),

  (id:'en_child_a1_002', en:'dog', ku:'kûçik', ipa:'/dɒɡ/', pos:'noun',
   form:null, kat:'heywan', zor:0.95,
   notKu:'Kûçik. Hevalê mirov.',
   her:["The dog runs fast.", "My dog is big."],
   herKu:['Kûçik bi lez dibeze.', 'Kûçikê min mezin e.'], emoji:'🐶'),

  (id:'en_child_a1_003', en:'bird', ku:'çûk', ipa:'/bɜːd/', pos:'noun',
   form:null, kat:'heywan', zor:0.94,
   notKu:'Çûk. Dikare bifire.',
   her:["The bird can fly.", "I see a bird."],
   herKu:['Çûk dikare bifire.', 'Ez çûkekê dibînim.'], emoji:'🐦'),

  (id:'en_child_a1_004', en:'fish', ku:'masî', ipa:'/fɪʃ/', pos:'noun',
   form:null, kat:'heywan', zor:0.94,
   notKu:'Masî. Di avê de dijî.',
   her:["The fish swims.", "I like fish."],
   herKu:['Masî avjeniyê dike.', 'Ez ji masiyan hez dikim.'], emoji:'🐟'),

  (id:'en_child_a1_005', en:'rabbit', ku:'kêvroşk', ipa:'/ˈræbɪt/', pos:'noun',
   form:null, kat:'heywan', zor:0.92,
   notKu:'Kêvroşk. Guhên dirêj.',
   her:["The rabbit jumps.", "A white rabbit."],
   herKu:['Kêvroşk diavêje.', 'Kêvroşkeke spî.'], emoji:'🐰'),

  (id:'en_child_a1_006', en:'mouse', ku:'mişk', ipa:'/maʊs/', pos:'noun',
   form:null, kat:'heywan', zor:0.92,
   notKu:'Mişk. Heywanekî biçûk.',
   her:["The mouse is small.", "I see a mouse."],
   herKu:['Mişk biçûk e.', 'Ez mişkekî dibînim.'], emoji:'🐭'),

  (id:'en_child_a1_007', en:'duck', ku:'werdek', ipa:'/dʌk/', pos:'noun',
   form:null, kat:'heywan', zor:0.93,
   notKu:'Werdek. Di avê de.',
   her:["The duck swims.", "Ducks say quack."],
   herKu:['Werdek avjeniyê dike.', 'Werdek wek-wek dike.'], emoji:'🦆'),

  (id:'en_child_a1_008', en:'cow', ku:'çêlek', ipa:'/kaʊ/', pos:'noun',
   form:null, kat:'heywan', zor:0.94,
   notKu:'Çêlek. Şîrê dide me.',
   her:["The cow is big.", "Cows give milk."],
   herKu:['Çêlek mezin e.', 'Çêlek şîr didin.'], emoji:'🐮'),

  (id:'en_child_a1_009', en:'horse', ku:'hesp', ipa:'/hɔːs/', pos:'noun',
   form:null, kat:'heywan', zor:0.93,
   notKu:'Hesp. Dikare bibeze.',
   her:["The horse runs.", "I ride a horse."],
   herKu:['Hesp dibeze.', 'Ez li hespê siwar dibim.'], emoji:'🐴'),

  (id:'en_child_a1_010', en:'sheep', ku:'pez', ipa:'/ʃiːp/', pos:'noun',
   form:null, kat:'heywan', zor:0.92,
   notKu:'Pez. Hirî ye.',
   her:["The sheep eats grass.", "Sheep are white."],
   herKu:['Pez giyê dixwe.', 'Pez spî ne.'], emoji:'🐑'),

  (id:'en_child_a1_011', en:'frog', ku:'beq', ipa:'/frɒɡ/', pos:'noun',
   form:null, kat:'heywan', zor:0.91,
   notKu:'Beq. Heywanekî hûr.',
   her:["The frog jumps.", "A green frog."],
   herKu:['Beq diavêje.', 'Beqeke kesk.'], emoji:'🐸'),

  (id:'en_child_a1_012', en:'bee', ku:'mêş', ipa:'/biː/', pos:'noun',
   form:null, kat:'heywan', zor:0.91,
   notKu:'Mêş. Hingiv çêdike.',
   her:["The bee flies.", "Bees make honey."],
   herKu:['Mêş difire.', 'Mêş hingiv çêdikin.'], emoji:'🐝'),

  (id:'en_child_a1_013', en:'butterfly', ku:'pirpirok', ipa:'/ˈbʌtəflaɪ/', pos:'noun',
   form:null, kat:'heywan', zor:0.88,
   notKu:'Pirpirok. Baskên rengîn.',
   her:["The butterfly is pretty.", "A small butterfly."],
   herKu:['Pirpirok xweşik e.', 'Pirpirokeke biçûk.'], emoji:'🦋'),

  (id:'en_child_a1_014', en:'elephant', ku:'fîl', ipa:'/ˈelɪfənt/', pos:'noun',
   form:null, kat:'heywan', zor:0.90,
   notKu:'Fîl. Heywanekî mezin.',
   her:["The elephant is big.", "I see an elephant."],
   herKu:['Fîl mezin e.', 'Ez fîlekî dibînim.'], emoji:'🐘'),

  (id:'en_child_a1_015', en:'lion', ku:'şêr', ipa:'/ˈlaɪən/', pos:'noun',
   form:null, kat:'heywan', zor:0.91,
   notKu:'Şêr. Padîşahê heywanan.',
   her:["The lion is strong.", "I like lions."],
   herKu:['Şêr bihêz e.', 'Ez ji şêran hez dikim.'], emoji:'🦁'),

  (id:'en_child_a1_016', en:'monkey', ku:'meymûn', ipa:'/ˈmʌŋki/', pos:'noun',
   form:null, kat:'heywan', zor:0.91,
   notKu:'Meymûn. Li daran dilîze.',
   her:["The monkey climbs trees.", "Monkeys are funny."],
   herKu:['Meymûn li daran hildikişe.', 'Meymûn henek in.'], emoji:'🐵'),

  (id:'en_child_a1_017', en:'bear', ku:'hirç', ipa:'/beə(r)/', pos:'noun',
   form:null, kat:'heywan', zor:0.90,
   notKu:'Hirç. Heywanekî mezin.',
   her:["The bear is brown.", "A big bear."],
   herKu:['Hirç qehweyî ye.', 'Hirçeke mezin.'], emoji:'🐻'),

  (id:'en_child_a1_018', en:'fox', ku:'rovî', ipa:'/fɒks/', pos:'noun',
   form:null, kat:'heywan', zor:0.89,
   notKu:'Rovî. Heywanekî jîr.',
   her:["The fox is red.", "A clever fox."],
   herKu:['Rovî sor e.', 'Roviyekî jîr.'], emoji:'🦊'),

  (id:'en_child_a1_019', en:'tiger', ku:'piling', ipa:'/ˈtaɪɡə(r)/', pos:'noun',
   form:null, kat:'heywan', zor:0.90,
   notKu:'Piling. Heywanekî xurt.',
   her:["The tiger is fast.", "Tigers have stripes."],
   herKu:['Piling bilez e.', 'Pilingên xêzker hene.'], emoji:'🐯'),

  (id:'en_child_a1_020', en:'chicken', ku:'mirîşk', ipa:'/ˈtʃɪkɪn/', pos:'noun',
   form:null, kat:'heywan', zor:0.92,
   notKu:'Mirîşk. Hêkan dike.',
   her:["The chicken is small.", "Chickens lay eggs."],
   herKu:['Mirîşk biçûk e.', 'Mirîşk hêkan dikin.'], emoji:'🐔'),

  (id:'en_child_a1_021', en:'pig', ku:'beraz', ipa:'/pɪɡ/', pos:'noun',
   form:null, kat:'heywan', zor:0.91,
   notKu:'Beraz. Heywanekî mal.',
   her:["The pig is pink.", "A fat pig."],
   herKu:['Beraz pembe ye.', 'Berazekî qelew.'], emoji:'🐷'),

  (id:'en_child_a1_022', en:'goat', ku:'bizin', ipa:'/ɡəʊt/', pos:'noun',
   form:null, kat:'heywan', zor:0.90,
   notKu:'Bizin. Şîrê dide.',
   her:["The goat eats grass.", "I have a goat."],
   herKu:['Bizin giyê dixwe.', 'Bizineke min heye.'], emoji:'🐐'),

  (id:'en_child_a1_023', en:'snake', ku:'mar', ipa:'/sneɪk/', pos:'noun',
   form:null, kat:'heywan', zor:0.89,
   notKu:'Mar. Dirêj û zirav.',
   her:["The snake is long.", "Snakes crawl."],
   herKu:['Mar dirêj e.', 'Mar dikişin.'], emoji:'🐍'),

  (id:'en_child_a1_024', en:'turtle', ku:'kiso', ipa:'/ˈtɜːtl/', pos:'noun',
   form:null, kat:'heywan', zor:0.87,
   notKu:'Kiso. Hêdî dimeşe.',
   her:["The turtle is slow.", "I see a turtle."],
   herKu:['Kiso hêdî ye.', 'Ez kisokekî dibînim.'], emoji:'🐢'),

  (id:'en_child_a1_025', en:'spider', ku:'pîrhevok', ipa:'/ˈspaɪdə(r)/', pos:'noun',
   form:null, kat:'heywan', zor:0.87,
   notKu:'Pîrhevok. Tor çêdike.',
   her:["The spider is small.", "Spiders make webs."],
   herKu:['Pîrhevok biçûk e.', 'Pîrhevok tor çêdikin.'], emoji:'🕷️'),

  (id:'en_child_a1_026', en:'red', ku:'sor', ipa:'/red/', pos:'adj',
   form:null, kat:'reng', zor:0.95,
   notKu:'Rengê sor.',
   her:["The apple is red.", "I like red."],
   herKu:['Sêv sor e.', 'Ez ji sor hez dikim.'], emoji:'🟥'),

  (id:'en_child_a1_027', en:'blue', ku:'şîn', ipa:'/bluː/', pos:'adj',
   form:null, kat:'reng', zor:0.95,
   notKu:'Rengê şîn.',
   her:["The sky is blue.", "A blue car."],
   herKu:['Asîman şîn e.', 'Tirimbêleke şîn.'], emoji:'🟦'),

  (id:'en_child_a1_028', en:'green', ku:'kesk', ipa:'/ɡriːn/', pos:'adj',
   form:null, kat:'reng', zor:0.95,
   notKu:'Rengê kesk.',
   her:["The grass is green.", "A green tree."],
   herKu:['Gî kesk e.', 'Dareke kesk.'], emoji:'🟩'),

  (id:'en_child_a1_029', en:'yellow', ku:'zer', ipa:'/ˈjeləʊ/', pos:'adj',
   form:null, kat:'reng', zor:0.94,
   notKu:'Rengê zer.',
   her:["The sun is yellow.", "A yellow flower."],
   herKu:['Roj zer e.', 'Kulîlkeke zer.'], emoji:'🟨'),

  (id:'en_child_a1_030', en:'orange', ku:'pirteqalî', ipa:'/ˈɒrɪndʒ/', pos:'adj',
   form:null, kat:'reng', zor:0.91,
   notKu:'Rengê pirteqalî.',
   her:["The ball is orange.", "An orange fruit."],
   herKu:['Tope pirteqalî ye.', 'Fêkiyekî pirteqalî.'], emoji:'🟧'),

  (id:'en_child_a1_031', en:'pink', ku:'pembe', ipa:'/pɪŋk/', pos:'adj',
   form:null, kat:'reng', zor:0.92,
   notKu:'Rengê pembe.',
   her:["The flower is pink.", "I like pink."],
   herKu:['Kulîlk pembe ye.', 'Ez ji pembe hez dikim.'], emoji:'🩷'),

  (id:'en_child_a1_032', en:'purple', ku:'mor', ipa:'/ˈpɜːpl/', pos:'adj',
   form:null, kat:'reng', zor:0.90,
   notKu:'Rengê mor.',
   her:["The grape is purple.", "A purple dress."],
   herKu:['Tirî mor e.', 'Kincekî mor.'], emoji:'🟪'),

  (id:'en_child_a1_033', en:'white', ku:'spî', ipa:'/waɪt/', pos:'adj',
   form:null, kat:'reng', zor:0.94,
   notKu:'Rengê spî.',
   her:["The snow is white.", "A white cat."],
   herKu:['Berf spî ye.', 'Pisîkeke spî.'], emoji:'⬜'),

  (id:'en_child_a1_034', en:'black', ku:'reş', ipa:'/blæk/', pos:'adj',
   form:null, kat:'reng', zor:0.94,
   notKu:'Rengê reş.',
   her:["The night is black.", "A black dog."],
   herKu:['Şev reş e.', 'Kûçikekî reş.'], emoji:'⬛'),

  (id:'en_child_a1_035', en:'brown', ku:'qehweyî', ipa:'/braʊn/', pos:'adj',
   form:null, kat:'reng', zor:0.91,
   notKu:'Rengê qehweyî.',
   her:["The bear is brown.", "Brown hair."],
   herKu:['Hirç qehweyî ye.', 'Porê qehweyî.'], emoji:'🟫'),

  (id:'en_child_a1_036', en:'one', ku:'yek', ipa:'/wʌn/', pos:'num',
   form:null, kat:'jimar', zor:0.95,
   notKu:'Jimara 1.',
   her:["I have one cat.", "One apple please."],
   herKu:['Pisîkek min heye.', 'Sêvek ji kerema xwe.'], emoji:'1️⃣'),

  (id:'en_child_a1_037', en:'two', ku:'du', ipa:'/tuː/', pos:'num',
   form:null, kat:'jimar', zor:0.95,
   notKu:'Jimara 2.',
   her:["I see two birds.", "Two and two."],
   herKu:['Ez du çûkan dibînim.', 'Du û du.'], emoji:'2️⃣'),

  (id:'en_child_a1_038', en:'three', ku:'sê', ipa:'/θriː/', pos:'num',
   form:null, kat:'jimar', zor:0.94,
   notKu:'Jimara 3.',
   her:["I have three toys.", "Three dogs play."],
   herKu:['Sê leyîstikên min hene.', 'Sê kûçik dilîzin.'], emoji:'3️⃣'),

  (id:'en_child_a1_039', en:'four', ku:'çar', ipa:'/fɔː(r)/', pos:'num',
   form:null, kat:'jimar', zor:0.94,
   notKu:'Jimara 4.',
   her:["Four chairs here.", "I see four cats."],
   herKu:['Çar kursî li vir in.', 'Ez çar pisîkan dibînim.'], emoji:'4️⃣'),

  (id:'en_child_a1_040', en:'five', ku:'pênc', ipa:'/faɪv/', pos:'num',
   form:null, kat:'jimar', zor:0.94,
   notKu:'Jimara 5.',
   her:["I have five books.", "Five fingers here."],
   herKu:['Pênc pirtûkên min hene.', 'Pênc tilî li vir.'], emoji:'5️⃣'),

  (id:'en_child_a1_041', en:'six', ku:'şeş', ipa:'/sɪks/', pos:'num',
   form:null, kat:'jimar', zor:0.93,
   notKu:'Jimara 6.',
   her:["Six eggs please.", "I am six."],
   herKu:['Şeş hêk ji kerema xwe.', 'Ez şeş salî me.'], emoji:'6️⃣'),

  (id:'en_child_a1_042', en:'seven', ku:'heft', ipa:'/ˈsevn/', pos:'num',
   form:null, kat:'jimar', zor:0.93,
   notKu:'Jimara 7.',
   her:["Seven days a week.", "Seven stars."],
   herKu:['Hefta heft roj in.', 'Heft stêrk.'], emoji:'7️⃣'),

  (id:'en_child_a1_043', en:'eight', ku:'heşt', ipa:'/eɪt/', pos:'num',
   form:null, kat:'jimar', zor:0.92,
   notKu:'Jimara 8.',
   her:["Eight balloons.", "I see eight birds."],
   herKu:['Heşt balon.', 'Ez heşt çûkan dibînim.'], emoji:'8️⃣'),

  (id:'en_child_a1_044', en:'nine', ku:'neh', ipa:'/naɪn/', pos:'num',
   form:null, kat:'jimar', zor:0.92,
   notKu:'Jimara 9.',
   her:["Nine red apples.", "Count to nine."],
   herKu:['Neh sêvên sor.', 'Heta neh bijmêre.'], emoji:'9️⃣'),

  (id:'en_child_a1_045', en:'ten', ku:'deh', ipa:'/ten/', pos:'num',
   form:null, kat:'jimar', zor:0.93,
   notKu:'Jimara 10.',
   her:["Ten little fingers.", "I count ten."],
   herKu:['Deh tiliyên biçûk.', 'Ez deh dijmêrim.'], emoji:'🔟'),

  (id:'en_child_a1_046', en:'eleven', ku:'yanzdeh', ipa:'/ɪˈlevn/', pos:'num',
   form:null, kat:'jimar', zor:0.88,
   notKu:'Jimara 11.',
   her:["Eleven boys here.", "I have eleven."],
   herKu:['Yanzdeh kur li vir in.', 'Yanzdeh hene min.'], emoji:'🔢'),

  (id:'en_child_a1_047', en:'twelve', ku:'dozdeh', ipa:'/twelv/', pos:'num',
   form:null, kat:'jimar', zor:0.87,
   notKu:'Jimara 12.',
   her:["Twelve months a year.", "I see twelve."],
   herKu:['Sal dozdeh meh in.', 'Ez dozdehan dibînim.'], emoji:'🔢'),

  (id:'en_child_a1_048', en:'thirteen', ku:'sêzdeh', ipa:'/ˌθɜːˈtiːn/', pos:'num',
   form:null, kat:'jimar', zor:0.85,
   notKu:'Jimara 13.',
   her:["Thirteen stars.", "Count thirteen."],
   herKu:['Sêzdeh stêrk.', 'Sêzdehan bijmêre.'], emoji:'🔢'),

  (id:'en_child_a1_049', en:'fourteen', ku:'çardeh', ipa:'/ˌfɔːˈtiːn/', pos:'num',
   form:null, kat:'jimar', zor:0.85,
   notKu:'Jimara 14.',
   her:["Fourteen cats.", "I have fourteen."],
   herKu:['Çardeh pisîk.', 'Min çardeh hene.'], emoji:'🔢'),

  (id:'en_child_a1_050', en:'fifteen', ku:'panzdeh', ipa:'/ˌfɪfˈtiːn/', pos:'num',
   form:null, kat:'jimar', zor:0.85,
   notKu:'Jimara 15.',
   her:["Fifteen books.", "Count to fifteen."],
   herKu:['Panzdeh pirtûk.', 'Heta panzdeh bijmêre.'], emoji:'🔢'),

  (id:'en_child_a1_051', en:'sixteen', ku:'şanzdeh', ipa:'/ˌsɪksˈtiːn/', pos:'num',
   form:null, kat:'jimar', zor:0.85,
   notKu:'Jimara 16.',
   her:["Sixteen dogs.", "I see sixteen."],
   herKu:['Şanzdeh kûçik.', 'Ez şanzdehan dibînim.'], emoji:'🔢'),

  (id:'en_child_a1_052', en:'seventeen', ku:'hivdeh', ipa:'/ˌsevnˈtiːn/', pos:'num',
   form:null, kat:'jimar', zor:0.84,
   notKu:'Jimara 17.',
   her:["Seventeen stars.", "Count seventeen."],
   herKu:['Hivdeh stêrk.', 'Hivdehan bijmêre.'], emoji:'🔢'),

  (id:'en_child_a1_053', en:'eighteen', ku:'hîjdeh', ipa:'/ˌeɪˈtiːn/', pos:'num',
   form:null, kat:'jimar', zor:0.84,
   notKu:'Jimara 18.',
   her:["Eighteen apples.", "I have eighteen."],
   herKu:['Hîjdeh sêv.', 'Min hîjdeh hene.'], emoji:'🔢'),

  (id:'en_child_a1_054', en:'nineteen', ku:'nozdeh', ipa:'/ˌnaɪnˈtiːn/', pos:'num',
   form:null, kat:'jimar', zor:0.84,
   notKu:'Jimara 19.',
   her:["Nineteen balloons.", "Count nineteen."],
   herKu:['Nozdeh balon.', 'Nozdehan bijmêre.'], emoji:'🔢'),

  (id:'en_child_a1_055', en:'twenty', ku:'bîst', ipa:'/ˈtwenti/', pos:'num',
   form:null, kat:'jimar', zor:0.88,
   notKu:'Jimara 20.',
   her:["Twenty fingers and toes.", "I see twenty."],
   herKu:['Bîst tilî û pêçî.', 'Ez bîstan dibînim.'], emoji:'🔢'),

  (id:'en_child_a1_056', en:'mom', ku:'dayik', ipa:'/mɒm/', pos:'noun',
   form:null, kat:'malbat', zor:0.95,
   notKu:'Dayika min.',
   her:["I love mom.", "Mom is nice."],
   herKu:['Ez ji dayikê hez dikim.', 'Dayik xweş e.'], emoji:'👩'),

  (id:'en_child_a1_057', en:'mum', ku:'dayik', ipa:'/mʌm/', pos:'noun',
   form:null, kat:'malbat', zor:0.94,
   notKu:'Dayik (Brîtanî).',
   her:["My mum is kind.", "I hug mum."],
   herKu:['Dayika min dilovan e.', 'Ez dayikê himêz dikim.'], emoji:'👩'),

  (id:'en_child_a1_058', en:'dad', ku:'bav', ipa:'/dæd/', pos:'noun',
   form:null, kat:'malbat', zor:0.95,
   notKu:'Bavê min.',
   her:["My dad is tall.", "I love dad."],
   herKu:['Bavê min dirêj e.', 'Ez ji bav hez dikim.'], emoji:'👨'),

  (id:'en_child_a1_059', en:'daddy', ku:'babo', ipa:'/ˈdædi/', pos:'noun',
   form:null, kat:'malbat', zor:0.93,
   notKu:'Bav (xweşnav).',
   her:["Daddy plays with me.", "I love daddy."],
   herKu:['Babo bi min re dilîze.', 'Ez ji babo hez dikim.'], emoji:'👨'),

  (id:'en_child_a1_060', en:'brother', ku:'bira', ipa:'/ˈbrʌðə(r)/', pos:'noun',
   form:null, kat:'malbat', zor:0.93,
   notKu:'Birayê min.',
   her:["My brother is big.", "I have a brother."],
   herKu:['Birayê min mezin e.', 'Birayekî min heye.'], emoji:'👦'),

  (id:'en_child_a1_061', en:'sister', ku:'xwişk', ipa:'/ˈsɪstə(r)/', pos:'noun',
   form:null, kat:'malbat', zor:0.93,
   notKu:'Xwişka min.',
   her:["My sister is kind.", "I love my sister."],
   herKu:['Xwişka min dilovan e.', 'Ez ji xwişkê hez dikim.'], emoji:'👧'),

  (id:'en_child_a1_062', en:'baby', ku:'pitik', ipa:'/ˈbeɪbi/', pos:'noun',
   form:null, kat:'malbat', zor:0.93,
   notKu:'Pitika biçûk.',
   her:["The baby is small.", "Baby is sleeping."],
   herKu:['Pitik biçûk e.', 'Pitik radizê.'], emoji:'👶'),

  (id:'en_child_a1_063', en:'grandma', ku:'dapîr', ipa:'/ˈɡrænmɑː/', pos:'noun',
   form:null, kat:'malbat', zor:0.91,
   notKu:'Dapîra min.',
   her:["Grandma is kind.", "I love grandma."],
   herKu:['Dapîr dilovan e.', 'Ez ji dapîrê hez dikim.'], emoji:'👵'),

  (id:'en_child_a1_064', en:'grandpa', ku:'bapîr', ipa:'/ˈɡrænpɑː/', pos:'noun',
   form:null, kat:'malbat', zor:0.91,
   notKu:'Bapîrê min.',
   her:["Grandpa is old.", "I love grandpa."],
   herKu:['Bapîr pîr e.', 'Ez ji bapîr hez dikim.'], emoji:'👴'),

  (id:'en_child_a1_065', en:'family', ku:'malbat', ipa:'/ˈfæməli/', pos:'noun',
   form:null, kat:'malbat', zor:0.90,
   notKu:'Malbata min.',
   her:["I love my family.", "My family is big."],
   herKu:['Ez ji malbata xwe hez dikim.', 'Malbata min mezin e.'], emoji:'👨‍👩‍👧‍👦'),

  (id:'en_child_a1_066', en:'head', ku:'serî', ipa:'/hed/', pos:'noun',
   form:null, kat:'beden', zor:0.93,
   notKu:'Serê min.',
   her:["My head is round.", "Touch your head."],
   herKu:['Serê min gilor e.', 'Serê xwe destek bike.'], emoji:'👤'),

  (id:'en_child_a1_067', en:'eye', ku:'çav', ipa:'/aɪ/', pos:'noun',
   form:null, kat:'beden', zor:0.94,
   notKu:'Çavê min.',
   her:["I have two eyes.", "My eyes are blue."],
   herKu:['Du çavên min hene.', 'Çavên min şîn in.'], emoji:'👁️'),

  (id:'en_child_a1_068', en:'ear', ku:'guh', ipa:'/ɪə(r)/', pos:'noun',
   form:null, kat:'beden', zor:0.93,
   notKu:'Guhê min.',
   her:["I have two ears.", "My ears hear."],
   herKu:['Du guhên min hene.', 'Guhên min dibihîzin.'], emoji:'👂'),

  (id:'en_child_a1_069', en:'nose', ku:'poz', ipa:'/nəʊz/', pos:'noun',
   form:null, kat:'beden', zor:0.93,
   notKu:'Pozê min.',
   her:["My nose is small.", "Touch your nose."],
   herKu:['Pozê min biçûk e.', 'Pozê xwe destek bike.'], emoji:'👃'),

  (id:'en_child_a1_070', en:'mouth', ku:'dev', ipa:'/maʊθ/', pos:'noun',
   form:null, kat:'beden', zor:0.92,
   notKu:'Devê min.',
   her:["My mouth is open.", "Close your mouth."],
   herKu:['Devê min vekirî ye.', 'Devê xwe bigre.'], emoji:'👄'),

  (id:'en_child_a1_071', en:'hand', ku:'dest', ipa:'/hænd/', pos:'noun',
   form:null, kat:'beden', zor:0.94,
   notKu:'Destê min.',
   her:["I have two hands.", "Wash your hands."],
   herKu:['Du destên min hene.', 'Destên xwe bişo.'], emoji:'✋'),

  (id:'en_child_a1_072', en:'foot', ku:'pê', ipa:'/fʊt/', pos:'noun',
   form:null, kat:'beden', zor:0.93,
   notKu:'Pêyê min.',
   her:["My foot is big.", "I have two feet."],
   herKu:['Pêyê min mezin e.', 'Du pêyên min hene.'], emoji:'🦶'),

  (id:'en_child_a1_073', en:'hair', ku:'por', ipa:'/heə(r)/', pos:'noun',
   form:null, kat:'beden', zor:0.92,
   notKu:'Porê min.',
   her:["My hair is long.", "Brown hair."],
   herKu:['Porê min dirêj e.', 'Porê qehweyî.'], emoji:'💇'),

  (id:'en_child_a1_074', en:'finger', ku:'tilî', ipa:'/ˈfɪŋɡə(r)/', pos:'noun',
   form:null, kat:'beden', zor:0.91,
   notKu:'Tiliya min.',
   her:["I have ten fingers.", "Small finger."],
   herKu:['Deh tiliyên min hene.', 'Tiliya biçûk.'], emoji:'☝️'),

  (id:'en_child_a1_075', en:'tooth', ku:'diran', ipa:'/tuːθ/', pos:'noun',
   form:null, kat:'beden', zor:0.90,
   notKu:'Diranê min.',
   her:["Brush your tooth.", "My tooth is white."],
   herKu:['Diranên xwe bişo.', 'Diranê min spî ye.'], emoji:'🦷'),

  (id:'en_child_a1_076', en:'apple', ku:'sêv', ipa:'/ˈæpl/', pos:'noun',
   form:null, kat:'xwarin', zor:0.95,
   notKu:'Sêv. Fêkiyekî sor.',
   her:["The apple is red.", "I eat an apple."],
   herKu:['Sêv sor e.', 'Ez sêvekê dixwim.'], emoji:'🍎'),

  (id:'en_child_a1_077', en:'banana', ku:'mûz', ipa:'/bəˈnɑːnə/', pos:'noun',
   form:null, kat:'xwarin', zor:0.94,
   notKu:'Mûz. Fêkiyekî zer.',
   her:["The banana is yellow.", "I like bananas."],
   herKu:['Mûz zer e.', 'Ez ji mûzan hez dikim.'], emoji:'🍌'),

  (id:'en_child_a1_078', en:'cake', ku:'kek', ipa:'/keɪk/', pos:'noun',
   form:null, kat:'xwarin', zor:0.93,
   notKu:'Kek. Şirîn e.',
   her:["The cake is sweet.", "Birthday cake."],
   herKu:['Kek şirîn e.', 'Kekê rojbûnê.'], emoji:'🍰'),

  (id:'en_child_a1_079', en:'ice cream', ku:'qeşaîd', ipa:'/ˈaɪs kriːm/', pos:'noun',
   form:null, kat:'xwarin', zor:0.92,
   notKu:'Qeşaîd. Sar û şirîn.',
   her:["I like ice cream.", "Ice cream is cold."],
   herKu:['Ez ji qeşaîdê hez dikim.', 'Qeşaîd sar e.'], emoji:'🍦'),

  (id:'en_child_a1_080', en:'milk', ku:'şîr', ipa:'/mɪlk/', pos:'noun',
   form:null, kat:'xwarin', zor:0.94,
   notKu:'Şîr. Ji çêlekê.',
   her:["I drink milk.", "Milk is white."],
   herKu:['Ez şîr vedixwim.', 'Şîr spî ye.'], emoji:'🥛'),

  (id:'en_child_a1_081', en:'water', ku:'av', ipa:'/ˈwɔːtə(r)/', pos:'noun',
   form:null, kat:'xwarin', zor:0.95,
   notKu:'Av. Em vedixwin.',
   her:["I drink water.", "Water is cold."],
   herKu:['Ez av vedixwim.', 'Av sar e.'], emoji:'💧'),

  (id:'en_child_a1_082', en:'juice', ku:'afirk', ipa:'/dʒuːs/', pos:'noun',
   form:null, kat:'xwarin', zor:0.92,
   notKu:'Afirk. Ji fêkiyan.',
   her:["I like apple juice.", "Juice is sweet."],
   herKu:['Ez ji afirka sêvan hez dikim.', 'Afirk şirîn e.'], emoji:'🧃'),

  (id:'en_child_a1_083', en:'cookie', ku:'kurabiye', ipa:'/ˈkʊki/', pos:'noun',
   form:null, kat:'xwarin', zor:0.91,
   notKu:'Kurabiye. Şirîn.',
   her:["I eat a cookie.", "Cookies are sweet."],
   herKu:['Ez kurabiyekê dixwim.', 'Kurabiye şirîn in.'], emoji:'🍪'),

  (id:'en_child_a1_084', en:'bread', ku:'nan', ipa:'/bred/', pos:'noun',
   form:null, kat:'xwarin', zor:0.94,
   notKu:'Nan. Rojane.',
   her:["I eat bread.", "Fresh bread."],
   herKu:['Ez nan dixwim.', 'Nanê teze.'], emoji:'🍞'),

  (id:'en_child_a1_085', en:'candy', ku:'şekir', ipa:'/ˈkændi/', pos:'noun',
   form:null, kat:'xwarin', zor:0.91,
   notKu:'Şekir. Gelek şirîn.',
   her:["I like candy.", "Candy is sweet."],
   herKu:['Ez ji şekir hez dikim.', 'Şekir şirîn e.'], emoji:'🍬'),

  (id:'en_child_a1_086', en:'chocolate', ku:'çîkolata', ipa:'/ˈtʃɒklət/', pos:'noun',
   form:null, kat:'xwarin', zor:0.92,
   notKu:'Çîkolata. Qehweyî.',
   her:["I love chocolate.", "Chocolate cake."],
   herKu:['Ez ji çîkolatayê hez dikim.', 'Keke çîkolatayê.'], emoji:'🍫'),

  (id:'en_child_a1_087', en:'pizza', ku:'pîza', ipa:'/ˈpiːtsə/', pos:'noun',
   form:null, kat:'xwarin', zor:0.93,
   notKu:'Pîza. Ji Îtalya.',
   her:["I like pizza.", "Hot pizza."],
   herKu:['Ez ji pîzayê hez dikim.', 'Pîzaya germ.'], emoji:'🍕'),

  (id:'en_child_a1_088', en:'cheese', ku:'penîr', ipa:'/tʃiːz/', pos:'noun',
   form:null, kat:'xwarin', zor:0.91,
   notKu:'Penîr. Ji şîr.',
   her:["I eat cheese.", "Yellow cheese."],
   herKu:['Ez penîr dixwim.', 'Penîrê zer.'], emoji:'🧀'),

  (id:'en_child_a1_089', en:'egg', ku:'hêk', ipa:'/eɡ/', pos:'noun',
   form:null, kat:'xwarin', zor:0.93,
   notKu:'Hêk. Ji mirîşkan.',
   her:["I eat an egg.", "The egg is white."],
   herKu:['Ez hêkekê dixwim.', 'Hêk spî ye.'], emoji:'🥚'),

  (id:'en_child_a1_090', en:'orange', ku:'pirteqal', ipa:'/ˈɒrɪndʒ/', pos:'noun',
   form:null, kat:'xwarin', zor:0.91,
   notKu:'Pirteqal. Fêkî.',
   her:["I eat an orange.", "Orange is sweet."],
   herKu:['Ez pirteqalê dixwim.', 'Pirteqal şirîn e.'], emoji:'🍊'),

  (id:'en_child_a1_091', en:'ball', ku:'top', ipa:'/bɔːl/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.95,
   notKu:'Top. Em dilîzin.',
   her:["I play with a ball.", "The ball is red."],
   herKu:['Ez bi topê dilîzim.', 'Top sor e.'], emoji:'⚽'),

  (id:'en_child_a1_092', en:'doll', ku:'bûka leyîstikê', ipa:'/dɒl/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.92,
   notKu:'Bûka leyîstikê.',
   her:["I have a doll.", "My doll is pretty."],
   herKu:['Bûkeka min heye.', 'Bûka min xweşik e.'], emoji:'🪆'),

  (id:'en_child_a1_093', en:'kite', ku:'lepik', ipa:'/kaɪt/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.89,
   notKu:'Lepik. Li ezmên.',
   her:["The kite flies high.", "I fly a kite."],
   herKu:['Lepik bilind difire.', 'Ez lepikan difirînim.'], emoji:'🪁'),

  (id:'en_child_a1_094', en:'toy', ku:'leyîstik', ipa:'/tɔɪ/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.93,
   notKu:'Leyîstik. Em dilîzin.',
   her:["I have many toys.", "My favorite toy."],
   herKu:['Gelek leyîstikên min hene.', 'Leyîstika hezkirî.'], emoji:'🧸'),

  (id:'en_child_a1_095', en:'balloon', ku:'balon', ipa:'/bəˈluːn/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.91,
   notKu:'Balon. Pifdayî.',
   her:["The balloon is red.", "I have a balloon."],
   herKu:['Balon sor e.', 'Baloneke min heye.'], emoji:'🎈'),

  (id:'en_child_a1_096', en:'teddy bear', ku:'hirça leyîstikê', ipa:'/ˈtedi beə(r)/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.90,
   notKu:'Hirça leyîstikê.',
   her:["I love my teddy bear.", "Soft teddy bear."],
   herKu:['Ez ji hirça xwe hez dikim.', 'Hirça nerm.'], emoji:'🧸'),

  (id:'en_child_a1_097', en:'train', ku:'trên', ipa:'/treɪn/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.90,
   notKu:'Trên. Dilîze.',
   her:["The train is fast.", "I like trains."],
   herKu:['Trên bi lez e.', 'Ez ji trênan hez dikim.'], emoji:'🚂'),

  (id:'en_child_a1_098', en:'car', ku:'tirimbêl', ipa:'/kɑː(r)/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.93,
   notKu:'Tirimbêl. Dilîzim.',
   her:["The car is red.", "I have a car."],
   herKu:['Tirimbêl sor e.', 'Tirimbêlek min heye.'], emoji:'🚗'),

  (id:'en_child_a1_099', en:'bike', ku:'duçerxe', ipa:'/baɪk/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.91,
   notKu:'Duçerxe. Ez siwar dibim.',
   her:["I ride a bike.", "The bike is blue."],
   herKu:['Ez li duçerxê siwar dibim.', 'Duçerxe şîn e.'], emoji:'🚲'),

  (id:'en_child_a1_100', en:'robot', ku:'robot', ipa:'/ˈrəʊbɒt/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.89,
   notKu:'Robot. Leyîstik.',
   her:["The robot is fun.", "My robot moves."],
   herKu:['Robot xweş e.', 'Robotê min dimeşe.'], emoji:'🤖'),

  (id:'en_child_a1_101', en:'book', ku:'pirtûk', ipa:'/bʊk/', pos:'noun',
   form:null, kat:'dibistan', zor:0.95,
   notKu:'Pirtûk. Em dixwînin.',
   her:["I read a book.", "The book is new."],
   herKu:['Ez pirtûkekê dixwînim.', 'Pirtûk nû ye.'], emoji:'📖'),

  (id:'en_child_a1_102', en:'pen', ku:'pênûs', ipa:'/pen/', pos:'noun',
   form:null, kat:'dibistan', zor:0.94,
   notKu:'Pênûs. Em dinivîsin.',
   her:["I have a pen.", "The pen is blue."],
   herKu:['Pênûseke min heye.', 'Pênûs şîn e.'], emoji:'🖊️'),

  (id:'en_child_a1_103', en:'pencil', ku:'qelem', ipa:'/ˈpensl/', pos:'noun',
   form:null, kat:'dibistan', zor:0.93,
   notKu:'Qelem. Em dinivîsin.',
   her:["I write with a pencil.", "A red pencil."],
   herKu:['Ez bi qelemê dinivîsim.', 'Qelemeke sor.'], emoji:'✏️'),

  (id:'en_child_a1_104', en:'bag', ku:'çant', ipa:'/bæɡ/', pos:'noun',
   form:null, kat:'dibistan', zor:0.93,
   notKu:'Çant. Ji bo dibistanê.',
   her:["My bag is big.", "I carry a bag."],
   herKu:['Çanta min mezin e.', 'Ez çantê hildigirim.'], emoji:'🎒'),

  (id:'en_child_a1_105', en:'desk', ku:'sehpe', ipa:'/desk/', pos:'noun',
   form:null, kat:'dibistan', zor:0.91,
   notKu:'Sehpe. Li dibistanê.',
   her:["My desk is clean.", "Sit at the desk."],
   herKu:['Sehpeya min paqij e.', 'Li sehpê rûnê.'], emoji:'🪑'),

  (id:'en_child_a1_106', en:'chair', ku:'kursî', ipa:'/tʃeə(r)/', pos:'noun',
   form:null, kat:'dibistan', zor:0.93,
   notKu:'Kursî. Em lê rûdinin.',
   her:["The chair is small.", "Sit on the chair."],
   herKu:['Kursî biçûk e.', 'Li kursî rûnê.'], emoji:'🪑'),

  (id:'en_child_a1_107', en:'classroom', ku:'çîn', ipa:'/ˈklɑːsruːm/', pos:'noun',
   form:null, kat:'dibistan', zor:0.89,
   notKu:'Çîna dersê.',
   her:["My classroom is nice.", "In the classroom."],
   herKu:['Çîna min xweş e.', 'Di çînê de.'], emoji:'🏫'),

  (id:'en_child_a1_108', en:'teacher', ku:'mamoste', ipa:'/ˈtiːtʃə(r)/', pos:'noun',
   form:null, kat:'dibistan', zor:0.92,
   notKu:'Mamoste. Dibistanê.',
   her:["My teacher is nice.", "The teacher helps."],
   herKu:['Mamosteyê min xweş e.', 'Mamoste dibe alîkar.'], emoji:'👩‍🏫'),

  (id:'en_child_a1_109', en:'friend', ku:'heval', ipa:'/frend/', pos:'noun',
   form:null, kat:'dibistan', zor:0.94,
   notKu:'Heval. Em dilîzin.',
   her:["I have a friend.", "My friend is nice."],
   herKu:['Hevalek min heye.', 'Hevalê min xweş e.'], emoji:'👫'),

  (id:'en_child_a1_110', en:'school', ku:'dibistan', ipa:'/skuːl/', pos:'noun',
   form:null, kat:'dibistan', zor:0.93,
   notKu:'Dibistan. Em dixwînin.',
   her:["I go to school.", "School is fun."],
   herKu:['Ez diçim dibistanê.', 'Dibistan xweş e.'], emoji:'🏫'),

  (id:'en_child_a1_111', en:'house', ku:'mal', ipa:'/haʊs/', pos:'noun',
   form:null, kat:'mal', zor:0.94,
   notKu:'Mal. Em lê dijîn.',
   her:["My house is big.", "I love my house."],
   herKu:['Mala min mezin e.', 'Ez ji mala xwe hez dikim.'], emoji:'🏠'),

  (id:'en_child_a1_112', en:'room', ku:'ode', ipa:'/ruːm/', pos:'noun',
   form:null, kat:'mal', zor:0.92,
   notKu:'Ode. Li malê.',
   her:["My room is clean.", "A big room."],
   herKu:['Odeya min paqij e.', 'Odeyeke mezin.'], emoji:'🚪'),

  (id:'en_child_a1_113', en:'door', ku:'derî', ipa:'/dɔː(r)/', pos:'noun',
   form:null, kat:'mal', zor:0.92,
   notKu:'Derî. Em vedikin.',
   her:["Open the door.", "The door is red."],
   herKu:['Derî veke.', 'Derî sor e.'], emoji:'🚪'),

  (id:'en_child_a1_114', en:'window', ku:'pencere', ipa:'/ˈwɪndəʊ/', pos:'noun',
   form:null, kat:'mal', zor:0.91,
   notKu:'Pencere. Em dibînin.',
   her:["Open the window.", "A big window."],
   herKu:['Pencereyê veke.', 'Pencereyeke mezin.'], emoji:'🪟'),

  (id:'en_child_a1_115', en:'bed', ku:'nivîn', ipa:'/bed/', pos:'noun',
   form:null, kat:'mal', zor:0.93,
   notKu:'Nivîn. Em radizin.',
   her:["I sleep in bed.", "My bed is soft."],
   herKu:['Ez di nivînê de radizim.', 'Nivîna min nerm e.'], emoji:'🛏️'),

  (id:'en_child_a1_116', en:'table', ku:'mase', ipa:'/ˈteɪbl/', pos:'noun',
   form:null, kat:'mal', zor:0.93,
   notKu:'Mase. Em lê dixwin.',
   her:["The table is big.", "Sit at the table."],
   herKu:['Mase mezin e.', 'Li maseyê rûnê.'], emoji:'🪑'),

  (id:'en_child_a1_117', en:'kitchen', ku:'metbex', ipa:'/ˈkɪtʃɪn/', pos:'noun',
   form:null, kat:'mal', zor:0.90,
   notKu:'Metbex. Em lê dipêjin.',
   her:["Mom is in the kitchen.", "A clean kitchen."],
   herKu:['Dayik di metbexê de ye.', 'Metbexeke paqij.'], emoji:'🍳'),

  (id:'en_child_a1_118', en:'garden', ku:'bexçe', ipa:'/ˈɡɑːdn/', pos:'noun',
   form:null, kat:'mal', zor:0.90,
   notKu:'Bexçe. Kulîlk lê ne.',
   her:["My garden is pretty.", "Play in the garden."],
   herKu:['Bexçeyê min xweşik e.', 'Di bexçê de bilîze.'], emoji:'🌷'),

  (id:'en_child_a1_119', en:'bathroom', ku:'serşûştî', ipa:'/ˈbɑːθruːm/', pos:'noun',
   form:null, kat:'mal', zor:0.88,
   notKu:'Serşûştî. Em xwe dişon.',
   her:["The bathroom is here.", "Clean bathroom."],
   herKu:['Serşûştî li vir e.', 'Serşûştiya paqij.'], emoji:'🛁'),

  (id:'en_child_a1_120', en:'bedroom', ku:'oda raketinê', ipa:'/ˈbedruːm/', pos:'noun',
   form:null, kat:'mal', zor:0.88,
   notKu:'Oda raketinê.',
   her:["My bedroom is pink.", "A small bedroom."],
   herKu:['Oda min pembe ye.', 'Odeyeke biçûk.'], emoji:'🛏️'),

  (id:'en_child_a1_121', en:'sun', ku:'roj', ipa:'/sʌn/', pos:'noun',
   form:null, kat:'xweza', zor:0.95,
   notKu:'Roj. Li ezmên.',
   her:["The sun is yellow.", "I see the sun."],
   herKu:['Roj zer e.', 'Ez rojê dibînim.'], emoji:'☀️'),

  (id:'en_child_a1_122', en:'moon', ku:'heyv', ipa:'/muːn/', pos:'noun',
   form:null, kat:'xweza', zor:0.93,
   notKu:'Heyv. Bi şev.',
   her:["The moon is bright.", "A full moon."],
   herKu:['Heyv ron e.', 'Heyvek tije.'], emoji:'🌙'),

  (id:'en_child_a1_123', en:'star', ku:'stêrk', ipa:'/stɑː(r)/', pos:'noun',
   form:null, kat:'xweza', zor:0.93,
   notKu:'Stêrk. Bi şev.',
   her:["I see a star.", "Stars are bright."],
   herKu:['Ez stêrkê dibînim.', 'Stêrk ron in.'], emoji:'⭐'),

  (id:'en_child_a1_124', en:'sky', ku:'asîman', ipa:'/skaɪ/', pos:'noun',
   form:null, kat:'xweza', zor:0.92,
   notKu:'Asîman. Li jor.',
   her:["The sky is blue.", "I look at the sky."],
   herKu:['Asîman şîn e.', 'Ez li asîmanî dinêrim.'], emoji:'🌌'),

  (id:'en_child_a1_125', en:'tree', ku:'dar', ipa:'/triː/', pos:'noun',
   form:null, kat:'xweza', zor:0.94,
   notKu:'Dar. Li bexçe.',
   her:["The tree is tall.", "A big tree."],
   herKu:['Dar dirêj e.', 'Dareke mezin.'], emoji:'🌳'),

  (id:'en_child_a1_126', en:'flower', ku:'kulîlk', ipa:'/ˈflaʊə(r)/', pos:'noun',
   form:null, kat:'xweza', zor:0.93,
   notKu:'Kulîlk. Rengîn.',
   her:["The flower is pretty.", "A red flower."],
   herKu:['Kulîlk xweşik e.', 'Kulîlkeke sor.'], emoji:'🌸'),

  (id:'en_child_a1_127', en:'grass', ku:'gî', ipa:'/ɡrɑːs/', pos:'noun',
   form:null, kat:'xweza', zor:0.90,
   notKu:'Gî. Li bexçê.',
   her:["The grass is green.", "Soft grass."],
   herKu:['Gî kesk e.', 'Giyê nerm.'], emoji:'🌱'),

  (id:'en_child_a1_128', en:'river', ku:'rûbar', ipa:'/ˈrɪvə(r)/', pos:'noun',
   form:null, kat:'xweza', zor:0.89,
   notKu:'Rûbar. Av diçe.',
   her:["The river is long.", "I see a river."],
   herKu:['Rûbar dirêj e.', 'Ez rûbarekî dibînim.'], emoji:'🏞️'),

  (id:'en_child_a1_129', en:'sea', ku:'derya', ipa:'/siː/', pos:'noun',
   form:null, kat:'xweza', zor:0.91,
   notKu:'Derya. Ava mezin.',
   her:["The sea is blue.", "I like the sea."],
   herKu:['Derya şîn e.', 'Ez ji deryayê hez dikim.'], emoji:'🌊'),

  (id:'en_child_a1_130', en:'mountain', ku:'çiya', ipa:'/ˈmaʊntən/', pos:'noun',
   form:null, kat:'xweza', zor:0.88,
   notKu:'Çiya. Gelek bilind.',
   her:["The mountain is high.", "I see mountains."],
   herKu:['Çiya bilind e.', 'Ez çiyayan dibînim.'], emoji:'⛰️'),

  (id:'en_child_a1_131', en:'rain', ku:'baran', ipa:'/reɪn/', pos:'noun',
   form:null, kat:'xweza', zor:0.92,
   notKu:'Baran. Av ji ezmên.',
   her:["The rain is cold.", "I like rain."],
   herKu:['Baran sar e.', 'Ez ji baranê hez dikim.'], emoji:'🌧️'),

  (id:'en_child_a1_132', en:'snow', ku:'berf', ipa:'/snəʊ/', pos:'noun',
   form:null, kat:'xweza', zor:0.92,
   notKu:'Berf. Spî û sar.',
   her:["The snow is white.", "I play in snow."],
   herKu:['Berf spî ye.', 'Ez di berfê de dilîzim.'], emoji:'❄️'),

  (id:'en_child_a1_133', en:'cloud', ku:'ewr', ipa:'/klaʊd/', pos:'noun',
   form:null, kat:'xweza', zor:0.90,
   notKu:'Ewr. Li ezmên.',
   her:["The cloud is white.", "I see clouds."],
   herKu:['Ewr spî ye.', 'Ez ewran dibînim.'], emoji:'☁️'),

  (id:'en_child_a1_134', en:'wind', ku:'ba', ipa:'/wɪnd/', pos:'noun',
   form:null, kat:'xweza', zor:0.89,
   notKu:'Ba. Ba tê.',
   her:["The wind is cold.", "I feel the wind."],
   herKu:['Ba sar e.', 'Ez bayê hîs dikim.'], emoji:'💨'),

  (id:'en_child_a1_135', en:'rainbow', ku:'keskesor', ipa:'/ˈreɪnbəʊ/', pos:'noun',
   form:null, kat:'xweza', zor:0.87,
   notKu:'Keskesor. Rengîn.',
   her:["I see a rainbow.", "Rainbows are pretty."],
   herKu:['Ez keskesorekê dibînim.', 'Keskesor xweşik in.'], emoji:'🌈'),

  (id:'en_child_a1_136', en:'hot', ku:'germ', ipa:'/hɒt/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.93,
   notKu:'Germ. Ne sar.',
   her:["The sun is hot.", "Hot tea."],
   herKu:['Roj germ e.', 'Çaya germ.'], emoji:'🔥'),

  (id:'en_child_a1_137', en:'cold', ku:'sar', ipa:'/kəʊld/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.93,
   notKu:'Sar. Ne germ.',
   her:["The water is cold.", "Cold weather."],
   herKu:['Av sar e.', 'Hewa sar.'], emoji:'🥶'),

  (id:'en_child_a1_138', en:'warm', ku:'nerm', ipa:'/wɔːm/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.89,
   notKu:'Nerm. Germ-xweş.',
   her:["The room is warm.", "A warm day."],
   herKu:['Ode nerm e.', 'Rojeke nerm.'], emoji:'🌡️'),

  (id:'en_child_a1_139', en:'walk', ku:'meşîn', ipa:'/wɔːk/', pos:'verb',
   form:null, kat:'leker', zor:0.94,
   notKu:'Meşîn. Em dimeşin.',
   her:["I walk to school.", "We walk fast."],
   herKu:['Ez berbi dibistanê dimeşim.', 'Em bi lez dimeşin.'], emoji:'🚶'),

  (id:'en_child_a1_140', en:'run', ku:'bezîn', ipa:'/rʌn/', pos:'verb',
   form:null, kat:'leker', zor:0.94,
   notKu:'Bezîn. Bi lez diçe.',
   her:["I run fast.", "The dog runs."],
   herKu:['Ez bi lez dibezim.', 'Kûçik dibeze.'], emoji:'🏃'),

  (id:'en_child_a1_141', en:'jump', ku:'avêtin', ipa:'/dʒʌmp/', pos:'verb',
   form:null, kat:'leker', zor:0.92,
   notKu:'Avêtin. Em diavêjin.',
   her:["I jump high.", "Frogs jump."],
   herKu:['Ez bilind diavêjim.', 'Beq diavêjin.'], emoji:'🤸'),

  (id:'en_child_a1_142', en:'sit', ku:'rûniştin', ipa:'/sɪt/', pos:'verb',
   form:null, kat:'leker', zor:0.93,
   notKu:'Rûniştin.',
   her:["I sit on a chair.", "Sit down please."],
   herKu:['Ez li kursî rûdinim.', 'Ji kerema xwe rûnê.'], emoji:'🪑'),

  (id:'en_child_a1_143', en:'stand', ku:'rawestîn', ipa:'/stænd/', pos:'verb',
   form:null, kat:'leker', zor:0.90,
   notKu:'Rawestîn. Li ser pêyan.',
   her:["I stand up.", "Stand here please."],
   herKu:['Ez rabûm.', 'Ji kerema xwe li vir raweste.'], emoji:'🧍'),

  (id:'en_child_a1_144', en:'sleep', ku:'raketin', ipa:'/sliːp/', pos:'verb',
   form:null, kat:'leker', zor:0.93,
   notKu:'Raketin. Di nivînê de.',
   her:["I sleep at night.", "The baby sleeps."],
   herKu:['Ez bi şev radikevim.', 'Pitik radizê.'], emoji:'😴'),

  (id:'en_child_a1_145', en:'eat', ku:'xwarin', ipa:'/iːt/', pos:'verb',
   form:null, kat:'leker', zor:0.95,
   notKu:'Xwarin. Xwarinê.',
   her:["I eat an apple.", "We eat bread."],
   herKu:['Ez sêvekê dixwim.', 'Em nan dixwin.'], emoji:'🍽️'),

  (id:'en_child_a1_146', en:'drink', ku:'vexwarin', ipa:'/drɪŋk/', pos:'verb',
   form:null, kat:'leker', zor:0.94,
   notKu:'Vexwarin. Av vedixwim.',
   her:["I drink water.", "Drink your milk."],
   herKu:['Ez av vedixwim.', 'Şîrê xwe vexwe.'], emoji:'🥤'),

  (id:'en_child_a1_147', en:'play', ku:'lîstin', ipa:'/pleɪ/', pos:'verb',
   form:null, kat:'leker', zor:0.95,
   notKu:'Lîstin. Em dilîzin.',
   her:["I play with my friend.", "Play with me."],
   herKu:['Ez bi heval re dilîzim.', 'Bi min re bilîze.'], emoji:'🎮'),

  (id:'en_child_a1_148', en:'sing', ku:'stran gotin', ipa:'/sɪŋ/', pos:'verb',
   form:null, kat:'leker', zor:0.91,
   notKu:'Stran gotin.',
   her:["I sing a song.", "We sing together."],
   herKu:['Ez stranekê dibêjim.', 'Em bi hev re stran dibêjin.'], emoji:'🎤'),

  (id:'en_child_a1_149', en:'dance', ku:'dîlan', ipa:'/dɑːns/', pos:'verb',
   form:null, kat:'leker', zor:0.91,
   notKu:'Dîlan. Em dikin.',
   her:["I dance with mom.", "I like to dance."],
   herKu:['Ez bi dayikê re dîlan dikim.', 'Ez ji dîlanê hez dikim.'], emoji:'💃'),

  (id:'en_child_a1_150', en:'swim', ku:'avjenî', ipa:'/swɪm/', pos:'verb',
   form:null, kat:'leker', zor:0.90,
   notKu:'Avjenî. Di avê de.',
   her:["I swim fast.", "Fish swim."],
   herKu:['Ez bi lez avjeniyê dikim.', 'Masî avjeniyê dikin.'], emoji:'🏊'),

  (id:'en_child_a1_151', en:'climb', ku:'hilkişîn', ipa:'/klaɪm/', pos:'verb',
   form:null, kat:'leker', zor:0.89,
   notKu:'Hilkişîn. Li daran.',
   her:["I climb a tree.", "Monkeys climb."],
   herKu:['Ez li darê hildikişim.', 'Meymûn hildikişin.'], emoji:'🧗'),

  (id:'en_child_a1_152', en:'read', ku:'xwendin', ipa:'/riːd/', pos:'verb',
   form:null, kat:'leker', zor:0.92,
   notKu:'Xwendin. Pirtûkan.',
   her:["I read a book.", "Read with me."],
   herKu:['Ez pirtûkekê dixwînim.', 'Bi min re bixwîne.'], emoji:'📚'),

  (id:'en_child_a1_153', en:'write', ku:'nivîsîn', ipa:'/raɪt/', pos:'verb',
   form:null, kat:'leker', zor:0.91,
   notKu:'Nivîsîn. Bi qelemê.',
   her:["I write my name.", "Write on paper."],
   herKu:['Ez navê xwe dinivîsim.', 'Li ser kaxezê binivîse.'], emoji:'✍️'),

  (id:'en_child_a1_154', en:'see', ku:'dîtin', ipa:'/siː/', pos:'verb',
   form:null, kat:'leker', zor:0.93,
   notKu:'Dîtin. Bi çavan.',
   her:["I see a cat.", "I can see you."],
   herKu:['Ez pisîkekê dibînim.', 'Ez te dibînim.'], emoji:'👀'),

  (id:'en_child_a1_155', en:'hear', ku:'bihîstin', ipa:'/hɪə(r)/', pos:'verb',
   form:null, kat:'leker', zor:0.90,
   notKu:'Bihîstin. Bi guhan.',
   her:["I hear music.", "Can you hear me?"],
   herKu:['Ez muzîkê dibihîzim.', 'Tu min dibihîzî?'], emoji:'👂'),

  (id:'en_child_a1_156', en:'big', ku:'mezin', ipa:'/bɪɡ/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.95,
   notKu:'Mezin. Ne biçûk.',
   her:["The bear is big.", "A big house."],
   herKu:['Hirç mezin e.', 'Maleke mezin.'], emoji:'🔼'),

  (id:'en_child_a1_157', en:'small', ku:'biçûk', ipa:'/smɔːl/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.95,
   notKu:'Biçûk. Ne mezin.',
   her:["The mouse is small.", "A small baby."],
   herKu:['Mişk biçûk e.', 'Pitikek biçûk.'], emoji:'🔽'),

  (id:'en_child_a1_158', en:'happy', ku:'kêfxweş', ipa:'/ˈhæpi/', pos:'adj',
   form:null, kat:'his', zor:0.94,
   notKu:'Kêfxweş. Bi şabûn.',
   her:["I am happy.", "A happy day."],
   herKu:['Ez kêfxweş im.', 'Rojeke kêfxweş.'], emoji:'😊'),

  (id:'en_child_a1_159', en:'sad', ku:'xemgîn', ipa:'/sæd/', pos:'adj',
   form:null, kat:'his', zor:0.92,
   notKu:'Xemgîn. Ne kêfxweş.',
   her:["I am sad.", "Do not be sad."],
   herKu:['Ez xemgîn im.', 'Xemgîn nebe.'], emoji:'😢'),

  (id:'en_child_a1_160', en:'good', ku:'baş', ipa:'/ɡʊd/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.95,
   notKu:'Baş. Ne xirab.',
   her:["I am a good boy.", "Good job!"],
   herKu:['Ez kurekî baş im.', 'Karê baş!'], emoji:'👍'),

  (id:'en_child_a1_161', en:'bad', ku:'xirab', ipa:'/bæd/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.92,
   notKu:'Xirab. Ne baş.',
   her:["This is bad.", "A bad day."],
   herKu:['Ev xirab e.', 'Rojeke xirab.'], emoji:'👎'),

  (id:'en_child_a1_162', en:'fast', ku:'bilez', ipa:'/fɑːst/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.92,
   notKu:'Bilez. Ne hêdî.',
   her:["The car is fast.", "I run fast."],
   herKu:['Tirimbêl bilez e.', 'Ez bi lez dibezim.'], emoji:'⚡'),

  (id:'en_child_a1_163', en:'slow', ku:'hêdî', ipa:'/sləʊ/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.90,
   notKu:'Hêdî. Ne bilez.',
   her:["The turtle is slow.", "Walk slow please."],
   herKu:['Kiso hêdî ye.', 'Ji kerema xwe hêdî bimeşe.'], emoji:'🐢'),

  (id:'en_child_a1_164', en:'new', ku:'nû', ipa:'/njuː/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.93,
   notKu:'Nû. Ne kevin.',
   her:["I have a new book.", "A new toy."],
   herKu:['Pirtûka min a nû heye.', 'Leyîstikek nû.'], emoji:'✨'),

  (id:'en_child_a1_165', en:'old', ku:'kevin', ipa:'/əʊld/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.91,
   notKu:'Kevin. Ne nû.',
   her:["An old book.", "My shoe is old."],
   herKu:['Pirtûkeke kevin.', 'Sola min kevin e.'], emoji:'📜'),

  (id:'en_child_a1_166', en:'nice', ku:'xweş', ipa:'/naɪs/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.92,
   notKu:'Xweş. Baş û spehî.',
   her:["You are nice.", "A nice day."],
   herKu:['Tu xweş î.', 'Rojeke xweş.'], emoji:'🙂'),

  (id:'en_child_a1_167', en:'pretty', ku:'xweşik', ipa:'/ˈprɪti/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.90,
   notKu:'Xweşik. Rengîn.',
   her:["The flower is pretty.", "A pretty girl."],
   herKu:['Kulîlk xweşik e.', 'Keçikeke xweşik.'], emoji:'🌸'),

  (id:'en_child_a1_168', en:'long', ku:'dirêj', ipa:'/lɒŋ/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.91,
   notKu:'Dirêj. Ne kurt.',
   her:["My hair is long.", "A long road."],
   herKu:['Porê min dirêj e.', 'Rêyeke dirêj.'], emoji:'📏'),

  (id:'en_child_a1_169', en:'short', ku:'kurt', ipa:'/ʃɔːt/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.90,
   notKu:'Kurt. Ne dirêj.',
   her:["My hair is short.", "A short story."],
   herKu:['Porê min kurt e.', 'Çîrokeke kurt.'], emoji:'📐'),

  (id:'en_child_a1_170', en:'tall', ku:'bilind', ipa:'/tɔːl/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.90,
   notKu:'Bilind. Ne kurt.',
   her:["The tree is tall.", "A tall boy."],
   herKu:['Dar bilind e.', 'Kurekî bilind.'], emoji:'📏'),

  (id:'en_child_a1_171', en:'hello', ku:'silav', ipa:'/həˈləʊ/', pos:'interj',
   form:null, kat:'silav', zor:0.95,
   notKu:'Silav. Destpêk.',
   her:["Hello friend.", "Hello teacher."],
   herKu:['Silav heval.', 'Silav mamoste.'], emoji:'👋'),

  (id:'en_child_a1_172', en:'hi', ku:'silav', ipa:'/haɪ/', pos:'interj',
   form:null, kat:'silav', zor:0.95,
   notKu:'Silav (nerm).',
   her:["Hi mom.", "Hi everyone."],
   herKu:['Silav dayê.', 'Silav hemî.'], emoji:'👋'),

  (id:'en_child_a1_173', en:'bye', ku:'bi xatirê te', ipa:'/baɪ/', pos:'interj',
   form:null, kat:'silav', zor:0.93,
   notKu:'Bi xatirê te.',
   her:["Bye mom.", "Bye friend."],
   herKu:['Bi xatirê te dayê.', 'Bi xatirê te heval.'], emoji:'👋'),

  (id:'en_child_a1_174', en:'goodbye', ku:'bi xatirê te', ipa:'/ˌɡʊdˈbaɪ/', pos:'interj',
   form:null, kat:'silav', zor:0.91,
   notKu:'Bi xatirê te (fermî).',
   her:["Goodbye teacher.", "Goodbye grandma."],
   herKu:['Bi xatirê te mamoste.', 'Bi xatirê te dapîr.'], emoji:'👋'),

  (id:'en_child_a1_175', en:'please', ku:'ji kerema xwe', ipa:'/pliːz/', pos:'interj',
   form:null, kat:'silav', zor:0.92,
   notKu:'Ji kerema xwe.',
   her:["Water please.", "Help me please."],
   herKu:['Ji kerema xwe av.', 'Ji kerema xwe alîkariya min bike.'], emoji:'🙏'),

  (id:'en_child_a1_176', en:'thanks', ku:'spas', ipa:'/θæŋks/', pos:'interj',
   form:null, kat:'silav', zor:0.93,
   notKu:'Spas. Em dibêjin.',
   her:["Thanks mom.", "Thanks a lot."],
   herKu:['Spas dayê.', 'Gelek spas.'], emoji:'🙏'),

  (id:'en_child_a1_177', en:'sorry', ku:'bibore', ipa:'/ˈsɒri/', pos:'interj',
   form:null, kat:'silav', zor:0.91,
   notKu:'Bibore. Lêborîn.',
   her:["Sorry mom.", "I am sorry."],
   herKu:['Bibore dayê.', 'Ez bibore.'], emoji:'🙇'),

  (id:'en_child_a1_178', en:'yes', ku:'erê', ipa:'/jes/', pos:'interj',
   form:null, kat:'silav', zor:0.95,
   notKu:'Erê. Pejirandin.',
   her:["Yes please.", "Yes mom."],
   herKu:['Erê ji kerema xwe.', 'Erê dayê.'], emoji:'✅'),

  (id:'en_child_a1_179', en:'no', ku:'na', ipa:'/nəʊ/', pos:'interj',
   form:null, kat:'silav', zor:0.95,
   notKu:'Na. Nepejirandin.',
   her:["No thanks.", "No please."],
   herKu:['Na spas.', 'Na ji kerema xwe.'], emoji:'❌'),

  (id:'en_child_a1_180', en:'welcome', ku:'bi xêr hatî', ipa:'/ˈwelkəm/', pos:'interj',
   form:null, kat:'silav', zor:0.89,
   notKu:'Bi xêr hatî.',
   her:["Welcome home.", "You are welcome."],
   herKu:['Bi xêr hatî malê.', 'Tu bi xêr hatî.'], emoji:'🤗'),

  (id:'en_child_a1_181', en:'scared', ku:'tirsiyayî', ipa:'/skeəd/', pos:'adj',
   form:null, kat:'his', zor:0.88,
   notKu:'Tirsiyayî. Ji tiştekî.',
   her:["I am scared.", "Do not be scared."],
   herKu:['Ez tirsiyayî me.', 'Netirse.'], emoji:'😨'),

  (id:'en_child_a1_182', en:'tired', ku:'westiyayî', ipa:'/ˈtaɪəd/', pos:'adj',
   form:null, kat:'his', zor:0.89,
   notKu:'Westiyayî. Biryar radize.',
   her:["I am tired.", "She is tired."],
   herKu:['Ez westiyayî me.', 'Ew westiyayî ye.'], emoji:'😴'),

  (id:'en_child_a1_183', en:'hungry', ku:'birçî', ipa:'/ˈhʌŋɡri/', pos:'adj',
   form:null, kat:'his', zor:0.91,
   notKu:'Birçî. Xwarin dixwaze.',
   her:["I am hungry.", "The cat is hungry."],
   herKu:['Ez birçî me.', 'Pisîk birçî ye.'], emoji:'🍽️'),

  (id:'en_child_a1_184', en:'thirsty', ku:'tîhnî', ipa:'/ˈθɜːsti/', pos:'adj',
   form:null, kat:'his', zor:0.87,
   notKu:'Tîhnî. Av dixwaze.',
   her:["I am thirsty.", "I need water."],
   herKu:['Ez tîhnî me.', 'Ez avê dixwazim.'], emoji:'💧'),

  (id:'en_child_a1_185', en:'party', ku:'şahî', ipa:'/ˈpɑːti/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.90,
   notKu:'Şahî. Em dilîzin.',
   her:["I go to a party.", "A birthday party."],
   herKu:['Ez diçim şahiyê.', 'Şahiya rojbûnê.'], emoji:'🎉'),

  (id:'en_child_a1_186', en:'gift', ku:'diyarî', ipa:'/ɡɪft/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.89,
   notKu:'Diyarî. Ji hevalan.',
   her:["I have a gift.", "A nice gift."],
   herKu:['Diyariyek min heye.', 'Diyariyeke xweş.'], emoji:'🎁'),

  (id:'en_child_a1_187', en:'story', ku:'çîrok', ipa:'/ˈstɔːri/', pos:'noun',
   form:null, kat:'dibistan', zor:0.90,
   notKu:'Çîrok. Em dibihîzin.',
   her:["Read me a story.", "A short story."],
   herKu:['Çîrokekê ji min re bixwîne.', 'Çîrokeke kurt.'], emoji:'📖'),

  (id:'en_child_a1_188', en:'song', ku:'stran', ipa:'/sɒŋ/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.90,
   notKu:'Stran. Em dibêjin.',
   her:["I sing a song.", "A nice song."],
   herKu:['Ez stranekê dibêjim.', 'Straneke xweş.'], emoji:'🎵'),

  (id:'en_child_a1_189', en:'game', ku:'leyîstin', ipa:'/ɡeɪm/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.91,
   notKu:'Leyîstin. Em dilîzin.',
   her:["I play a game.", "A fun game."],
   herKu:['Ez lîstikekê dilîzim.', 'Lîstikeke xweş.'], emoji:'🎲'),

  (id:'en_child_a1_190', en:'birthday', ku:'rojbûn', ipa:'/ˈbɜːθdeɪ/', pos:'noun',
   form:null, kat:'malbat', zor:0.89,
   notKu:'Rojbûn. Em şa dibin.',
   her:["Happy birthday!", "My birthday is today."],
   herKu:['Rojbûna te pîroz be!', 'Îro rojbûna min e.'], emoji:'🎂'),

  (id:'en_child_a1_191', en:'boy', ku:'kur', ipa:'/bɔɪ/', pos:'noun',
   form:null, kat:'malbat', zor:0.93,
   notKu:'Kur. Zarokê mêr.',
   her:["The boy is happy.", "A small boy."],
   herKu:['Kur kêfxweş e.', 'Kurekî biçûk.'], emoji:'👦'),

  (id:'en_child_a1_192', en:'girl', ku:'keç', ipa:'/ɡɜːl/', pos:'noun',
   form:null, kat:'malbat', zor:0.93,
   notKu:'Keç. Zaroka jin.',
   her:["The girl is nice.", "A pretty girl."],
   herKu:['Keç xweş e.', 'Keçikeke xweşik.'], emoji:'👧'),

  (id:'en_child_a1_193', en:'man', ku:'mêr', ipa:'/mæn/', pos:'noun',
   form:null, kat:'malbat', zor:0.91,
   notKu:'Mêr. Ne zarok.',
   her:["The man is tall.", "A good man."],
   herKu:['Mêr dirêj e.', 'Mêrekî baş.'], emoji:'👨'),

  (id:'en_child_a1_194', en:'woman', ku:'jin', ipa:'/ˈwʊmən/', pos:'noun',
   form:null, kat:'malbat', zor:0.90,
   notKu:'Jin. Ne zarok.',
   her:["The woman is kind.", "A nice woman."],
   herKu:['Jin dilovan e.', 'Jineke xweş.'], emoji:'👩'),

  (id:'en_child_a1_195', en:'open', ku:'vekirin', ipa:'/ˈəʊpən/', pos:'verb',
   form:null, kat:'leker', zor:0.90,
   notKu:'Vekirin. Derî veke.',
   her:["Open the door.", "Open your book."],
   herKu:['Derî veke.', 'Pirtûka xwe veke.'], emoji:'🔓'),

  (id:'en_child_a1_196', en:'close', ku:'girtin', ipa:'/kləʊz/', pos:'verb',
   form:null, kat:'leker', zor:0.89,
   notKu:'Girtin. Derî bigre.',
   her:["Close the door.", "Close your eyes."],
   herKu:['Derî bigre.', 'Çavên xwe bigre.'], emoji:'🔒'),

  (id:'en_child_a1_197', en:'give', ku:'dayîn', ipa:'/ɡɪv/', pos:'verb',
   form:null, kat:'leker', zor:0.91,
   notKu:'Dayîn. Tiştekî.',
   her:["Give me the ball.", "I give a gift."],
   herKu:['Topê bide min.', 'Ez diyariyekê didim.'], emoji:'🤝'),

  (id:'en_child_a1_198', en:'take', ku:'girtin', ipa:'/teɪk/', pos:'verb',
   form:null, kat:'leker', zor:0.90,
   notKu:'Girtin. Tiştekî hildidim.',
   her:["Take this book.", "I take a pen."],
   herKu:['Vê pirtûkê hilde.', 'Ez qelemekê hildidim.'], emoji:'🫳'),

  (id:'en_child_a1_199', en:'love', ku:'hezkirin', ipa:'/lʌv/', pos:'verb',
   form:null, kat:'his', zor:0.93,
   notKu:'Hezkirin. Ji dil.',
   her:["I love mom.", "I love my cat."],
   herKu:['Ez ji dayikê hez dikim.', 'Ez ji pisîka xwe hez dikim.'], emoji:'❤️'),

  (id:'en_child_a1_200', en:'like', ku:'hez kirin', ipa:'/laɪk/', pos:'verb',
   form:null, kat:'his', zor:0.94,
   notKu:'Hez kirin. Tiştek xweş.',
   her:["I like apples.", "I like my friend."],
   herKu:['Ez ji sêvan hez dikim.', 'Ez ji hevalê xwe hez dikim.'], emoji:'👍')
];
