// LÛTKE — İngilizce Çocuk A2 (YLE Movers/Flyers)
// Oxford 3000/5000 + EVP CHILD_A2 referans.
// 300 kelime.

import 'en_word.dart';

const List<EnWord> kEnChildA2Liste = [
  (id:'en_child_a2_001', en:'zebra', ku:'zebra', ipa:'/ˈziːbrə/', pos:'noun',
   form:null, kat:'heywan', zor:0.85,
   notKu:'Zebra. Heywana spî-reş ya Afrîka.',
   her:["A zebra has stripes.", "The zebra runs fast."],
   herKu:['Zebrayê xêz hene.', 'Zebra zû dibeze.'], emoji:'🦓'),

  (id:'en_child_a2_002', en:'giraffe', ku:'zerafe', ipa:'/dʒəˈrɑːf/', pos:'noun',
   form:null, kat:'heywan', zor:0.86,
   notKu:'Zerafe. Heywana stûdirêj.',
   her:["A giraffe is tall.", "Giraffes eat leaves."],
   herKu:['Zerafe dirêj e.', 'Zerafe pelan dixwin.'], emoji:'🦒'),

  (id:'en_child_a2_003', en:'dolphin', ku:'delfîn', ipa:'/ˈdɒlfɪn/', pos:'noun',
   form:null, kat:'heywan', zor:0.85,
   notKu:'Delfîn. Heywana behrê ya jîr.',
   her:["A dolphin swims fast.", "Dolphins are clever."],
   herKu:['Delfîn zû avjeniyê dike.', 'Delfîn jîr in.'], emoji:'🐬'),

  (id:'en_child_a2_004', en:'whale', ku:'balîne', ipa:'/weɪl/', pos:'noun',
   form:null, kat:'heywan', zor:0.85,
   notKu:'Balîne. Heywana herî mezin a behrê.',
   her:["A whale is big.", "Whales live in the sea."],
   herKu:['Balîne mezin e.', 'Balîne di behrê de dijîn.'], emoji:'🐋'),

  (id:'en_child_a2_005', en:'shark', ku:'köpekmasî', ipa:'/ʃɑːk/', pos:'noun',
   form:null, kat:'heywan', zor:0.86,
   notKu:'Köpekmasî. Masîyê mezin ê diranî.',
   her:["A shark has teeth.", "Sharks swim in the ocean."],
   herKu:['Köpekmasî diranên wê hene.', 'Köpekmasî di okyanûsê de avjeniyê dikin.'], emoji:'🦈'),

  (id:'en_child_a2_006', en:'snake', ku:'mar', ipa:'/sneɪk/', pos:'noun',
   form:null, kat:'heywan', zor:0.82,
   notKu:'Mar. Heywana bê ling ku diherike.',
   her:["A snake is long.", "The snake slides slowly."],
   herKu:['Mar dirêj e.', 'Mar hêdî diherike.'], emoji:'🐍'),

  (id:'en_child_a2_007', en:'kangaroo', ku:'kangûru', ipa:'/ˌkæŋɡəˈruː/', pos:'noun',
   form:null, kat:'heywan', zor:0.87,
   notKu:'Kangûru. Heywana Avustralyayê ya bazde.',
   her:["A kangaroo jumps high.", "Kangaroos live in Australia."],
   herKu:['Kangûru bilind bazdide.', 'Kangûru li Avustralyayê dijîn.'], emoji:'🦘'),

  (id:'en_child_a2_008', en:'panda', ku:'panda', ipa:'/ˈpændə/', pos:'noun',
   form:null, kat:'heywan', zor:0.82,
   notKu:'Panda. Hirçê spî-reş.',
   her:["A panda eats bamboo.", "Pandas are cute."],
   herKu:['Panda bambûyê dixwe.', 'Panda xweşik in.'], emoji:'🐼'),

  (id:'en_child_a2_009', en:'hippo', ku:'hîpopotam', ipa:'/ˈhɪpəʊ/', pos:'noun',
   form:null, kat:'heywan', zor:0.86,
   notKu:'Hîpopotam. Heywana mezin a avê.',
   her:["A hippo is heavy.", "Hippos love water."],
   herKu:['Hîpopotam giran e.', 'Hîpopotam ji avê hez dikin.'], emoji:'🦛'),

  (id:'en_child_a2_010', en:'crocodile', ku:'tîmsah', ipa:'/ˈkrɒkədaɪl/', pos:'noun',
   form:null, kat:'heywan', zor:0.87,
   notKu:'Tîmsah. Heywana diranî ya çem.',
   her:["A crocodile has sharp teeth.", "Crocodiles live in rivers."],
   herKu:['Tîmsahê diranên tûj hene.', 'Tîmsah di çeman de dijîn.'], emoji:'🐊'),

  (id:'en_child_a2_011', en:'turtle', ku:'kûsî', ipa:'/ˈtɜːtl/', pos:'noun',
   form:null, kat:'heywan', zor:0.83,
   notKu:'Kûsî. Heywana hêdî ya qalikî.',
   her:["A turtle moves slowly.", "The turtle has a shell."],
   herKu:['Kûsî hêdî diçe.', 'Qaliyê kûsîyê heye.'], emoji:'🐢'),

  (id:'en_child_a2_012', en:'octopus', ku:'heştling', ipa:'/ˈɒktəpəs/', pos:'noun',
   form:null, kat:'heywan', zor:0.88,
   notKu:'Heştling. Heywana behrê ya heşt lingî.',
   her:["An octopus has eight arms.", "Octopuses live in the sea."],
   herKu:['Heştling heşt destên wê hene.', 'Heştling di behrê de dijîn.'], emoji:'🐙'),

  (id:'en_child_a2_013', en:'eagle', ku:'teyr', ipa:'/ˈiːɡl/', pos:'noun',
   form:null, kat:'heywan', zor:0.84,
   notKu:'Teyr. Çûkê mezin ê nêçîrvan.',
   her:["An eagle flies high.", "Eagles have strong eyes."],
   herKu:['Teyr bilind difire.', 'Çavên teyr bihêz in.'], emoji:'🦅'),

  (id:'en_child_a2_014', en:'owl', ku:'bû', ipa:'/aʊl/', pos:'noun',
   form:null, kat:'heywan', zor:0.83,
   notKu:'Bû. Çûkê şevê yê çavmezin.',
   her:["An owl flies at night.", "Owls have big eyes."],
   herKu:['Bû bi şev difire.', 'Çavên bû mezin in.'], emoji:'🦉'),

  (id:'en_child_a2_015', en:'parrot', ku:'papaẍan', ipa:'/ˈpærət/', pos:'noun',
   form:null, kat:'heywan', zor:0.85,
   notKu:'Papaẍan. Çûkê rengîn ê axaftinê.',
   her:["A parrot can talk.", "Parrots have bright colors."],
   herKu:['Papaẍan dikare biaxive.', 'Rengên papaẍan geş in.'], emoji:'🦜'),

  (id:'en_child_a2_016', en:'peacock', ku:'tawis', ipa:'/ˈpiːkɒk/', pos:'noun',
   form:null, kat:'heywan', zor:0.87,
   notKu:'Tawis. Çûkê perê rengîn.',
   her:["A peacock is beautiful.", "The peacock has big feathers."],
   herKu:['Tawis xweşik e.', 'Perên tawisê mezin in.'], emoji:'🦚'),

  (id:'en_child_a2_017', en:'swan', ku:'qu', ipa:'/swɒn/', pos:'noun',
   form:null, kat:'heywan', zor:0.84,
   notKu:'Qu. Çûkê spî yê gola.',
   her:["A swan is white.", "Swans swim on the lake."],
   herKu:['Qu spî ye.', 'Qu li ser golê avjeniyê dikin.'], emoji:'🦢'),

  (id:'en_child_a2_018', en:'hamster', ku:'hamster', ipa:'/ˈhæmstə/', pos:'noun',
   form:null, kat:'heywan', zor:0.85,
   notKu:'Hamster. Heywanê piçûk ê malê.',
   her:["A hamster is small.", "Hamsters run in a wheel."],
   herKu:['Hamster piçûk e.', 'Hamster di çerxê de dibezin.'], emoji:'🐹'),

  (id:'en_child_a2_019', en:'guinea pig', ku:'berazê Hindistanê', ipa:'/ˈɡɪni pɪɡ/', pos:'noun',
   form:null, kat:'heywan', zor:0.88,
   notKu:'Berazê Hindistanê. Heywanê piçûk ê malê.',
   her:["A guinea pig eats grass.", "Guinea pigs are friendly."],
   herKu:['Berazê Hindistanê giya dixwe.', 'Berazê Hindistanê dost in.'], emoji:'🐹'),

  (id:'en_child_a2_020', en:'frog', ku:'beq', ipa:'/frɒɡ/', pos:'noun',
   form:null, kat:'heywan', zor:0.80,
   notKu:'Beq. Heywana kesk a avê.',
   her:["A frog jumps high.", "Frogs live near water."],
   herKu:['Beq bilind bazdide.', 'Beq nêzî avê dijîn.'], emoji:'🐸'),

  (id:'en_child_a2_021', en:'mouse', ku:'mişk', ipa:'/maʊs/', pos:'noun',
   form:null, kat:'heywan', zor:0.80,
   notKu:'Mişk. Heywana piçûk a malê.',
   her:["A mouse is tiny.", "The mouse eats cheese."],
   herKu:['Mişk pir piçûk e.', 'Mişk penîr dixwe.'], emoji:'🐭'),

  (id:'en_child_a2_022', en:'squirrel', ku:'sîncab', ipa:'/ˈskwɪrəl/', pos:'noun',
   form:null, kat:'heywan', zor:0.87,
   notKu:'Sîncab. Heywana darê ya biboç.',
   her:["A squirrel climbs trees.", "Squirrels eat nuts."],
   herKu:['Sîncab hilkişe daran.', 'Sîncab guz dixwin.'], emoji:'🐿️'),

  (id:'en_child_a2_023', en:'butterfly', ku:'perwane', ipa:'/ˈbʌtəflaɪ/', pos:'noun',
   form:null, kat:'heywan', zor:0.86,
   notKu:'Perwane. Kêzika perên rengîn.',
   her:["A butterfly is pretty.", "Butterflies fly in summer."],
   herKu:['Perwane xweşik e.', 'Perwane havînê difirin.'], emoji:'🦋'),

  (id:'en_child_a2_024', en:'bee', ku:'mêş', ipa:'/biː/', pos:'noun',
   form:null, kat:'heywan', zor:0.81,
   notKu:'Mêş. Kêzika ku hingiv çêdike.',
   her:["A bee makes honey.", "Bees fly in the garden."],
   herKu:['Mêş hingiv çêdike.', 'Mêş di baxçe de difirin.'], emoji:'🐝'),

  (id:'en_child_a2_025', en:'ant', ku:'gêrmor', ipa:'/ænt/', pos:'noun',
   form:null, kat:'heywan', zor:0.81,
   notKu:'Gêrmor. Kêzika piçûk a bihêz.',
   her:["An ant is small.", "Ants work together."],
   herKu:['Gêrmor piçûk e.', 'Gêrmor bi hev re dixebitin.'], emoji:'🐜'),

  (id:'en_child_a2_026', en:'sandwich', ku:'sandwîç', ipa:'/ˈsænwɪdʒ/', pos:'noun',
   form:null, kat:'xwarin', zor:0.84,
   notKu:'Sandwîç. Nan û tiştên navê.',
   her:["I eat a sandwich.", "The sandwich is tasty."],
   herKu:['Ez sandwîçekê dixwim.', 'Sandwîç bi tam e.'], emoji:'🥪'),

  (id:'en_child_a2_027', en:'hamburger', ku:'hamburger', ipa:'/ˈhæmbɜːɡə/', pos:'noun',
   form:null, kat:'xwarin', zor:0.85,
   notKu:'Hamburger. Nan û goşt bi hev re.',
   her:["I love hamburgers.", "The hamburger is hot."],
   herKu:['Ez ji hamburger hez dikim.', 'Hamburger germ e.'], emoji:'🍔'),

  (id:'en_child_a2_028', en:'pizza', ku:'pîtza', ipa:'/ˈpiːtsə/', pos:'noun',
   form:null, kat:'xwarin', zor:0.80,
   notKu:'Pîtza. Xwarina Îtalî ya gilover.',
   her:["Pizza is delicious.", "We eat pizza today."],
   herKu:['Pîtza pir bi tam e.', 'Em îro pîtzayê dixwin.'], emoji:'🍕'),

  (id:'en_child_a2_029', en:'salad', ku:'salata', ipa:'/ˈsæləd/', pos:'noun',
   form:null, kat:'xwarin', zor:0.82,
   notKu:'Salata. Xwarina sebzeyan.',
   her:["I eat salad.", "The salad is fresh."],
   herKu:['Ez salatê dixwim.', 'Salata teze ye.'], emoji:'🥗'),

  (id:'en_child_a2_030', en:'soup', ku:'şorbe', ipa:'/suːp/', pos:'noun',
   form:null, kat:'xwarin', zor:0.81,
   notKu:'Şorbe. Xwarina germ a şil.',
   her:["The soup is hot.", "I drink soup."],
   herKu:['Şorbe germ e.', 'Ez şorbeyê vedixwim.'], emoji:'🍲'),

  (id:'en_child_a2_031', en:'vegetables', ku:'sebze', ipa:'/ˈvedʒtəbəlz/', pos:'noun',
   form:null, kat:'xwarin', zor:0.88,
   notKu:'Sebze. Xwarinên kesk.',
   her:["Vegetables are healthy.", "I eat vegetables daily."],
   herKu:['Sebze saẍlem in.', 'Ez her roj sebze dixwim.'], emoji:'🥬'),

  (id:'en_child_a2_032', en:'fruit', ku:'fêkî', ipa:'/fruːt/', pos:'noun',
   form:null, kat:'xwarin', zor:0.82,
   notKu:'Fêkî. Xwarinên şîrîn ên darê.',
   her:["Fruit is sweet.", "I like fresh fruit."],
   herKu:['Fêkî şîrîn e.', 'Ez ji fêkiyên teze hez dikim.'], emoji:'🍎'),

  (id:'en_child_a2_033', en:'strawberry', ku:'tûfêkî', ipa:'/ˈstrɔːbəri/', pos:'noun',
   form:null, kat:'xwarin', zor:0.87,
   notKu:'Tûfêkî. Fêkiya sor a biçûk.',
   her:["A strawberry is red.", "I love strawberries."],
   herKu:['Tûfêkî sor e.', 'Ez ji tûfêkiyan hez dikim.'], emoji:'🍓'),

  (id:'en_child_a2_034', en:'grape', ku:'tirî', ipa:'/ɡreɪp/', pos:'noun',
   form:null, kat:'xwarin', zor:0.82,
   notKu:'Tirî. Fêkiya rezê.',
   her:["Grapes are sweet.", "I eat grapes."],
   herKu:['Tirî şîrîn e.', 'Ez tirî dixwim.'], emoji:'🍇'),

  (id:'en_child_a2_035', en:'watermelon', ku:'zebeş', ipa:'/ˈwɔːtəmelən/', pos:'noun',
   form:null, kat:'xwarin', zor:0.88,
   notKu:'Zebeş. Fêkiya mezin a havînê.',
   her:["Watermelon is cold.", "We eat watermelon."],
   herKu:['Zebeş sar e.', 'Em zebeş dixwin.'], emoji:'🍉'),

  (id:'en_child_a2_036', en:'pineapple', ku:'ananas', ipa:'/ˈpaɪnæpəl/', pos:'noun',
   form:null, kat:'xwarin', zor:0.87,
   notKu:'Ananas. Fêkiya zer a dirr.',
   her:["A pineapple is yellow.", "I like pineapple."],
   herKu:['Ananas zer e.', 'Ez ji ananasê hez dikim.'], emoji:'🍍'),

  (id:'en_child_a2_037', en:'mango', ku:'mango', ipa:'/ˈmæŋɡəʊ/', pos:'noun',
   form:null, kat:'xwarin', zor:0.83,
   notKu:'Mango. Fêkiya şîrîn a germ.',
   her:["Mango is sweet.", "I eat a mango."],
   herKu:['Mango şîrîn e.', 'Ez mangoyekê dixwim.'], emoji:'🥭'),

  (id:'en_child_a2_038', en:'lemon', ku:'lîmon', ipa:'/ˈlemən/', pos:'noun',
   form:null, kat:'xwarin', zor:0.82,
   notKu:'Lîmon. Fêkiya zer a tirş.',
   her:["A lemon is sour.", "Lemons are yellow."],
   herKu:['Lîmon tirş e.', 'Lîmon zer in.'], emoji:'🍋'),

  (id:'en_child_a2_039', en:'peach', ku:'xox', ipa:'/piːtʃ/', pos:'noun',
   form:null, kat:'xwarin', zor:0.83,
   notKu:'Xox. Fêkiya nerm a zer-sor.',
   her:["A peach is soft.", "I eat a peach."],
   herKu:['Xox nerm e.', 'Ez xoxekê dixwim.'], emoji:'🍑'),

  (id:'en_child_a2_040', en:'carrot', ku:'gêzer', ipa:'/ˈkærət/', pos:'noun',
   form:null, kat:'xwarin', zor:0.82,
   notKu:'Gêzer. Sebzeya porteqalî ya dirêj.',
   her:["A carrot is orange.", "Rabbits eat carrots."],
   herKu:['Gêzer porteqalî ye.', 'Kêvroşk gêzeran dixwin.'], emoji:'🥕'),

  (id:'en_child_a2_041', en:'potato', ku:'petate', ipa:'/pəˈteɪtəʊ/', pos:'noun',
   form:null, kat:'xwarin', zor:0.84,
   notKu:'Petate. Sebzeya binerdê.',
   her:["A potato is round.", "I cook potatoes."],
   herKu:['Petate gilover e.', 'Ez petatan dikelînim.'], emoji:'🥔'),

  (id:'en_child_a2_042', en:'tomato', ku:'firingî', ipa:'/təˈmɑːtəʊ/', pos:'noun',
   form:null, kat:'xwarin', zor:0.83,
   notKu:'Firingî. Sebzeya sor a gilover.',
   her:["A tomato is red.", "Tomatoes are juicy."],
   herKu:['Firingî sor e.', 'Firingî avilî ne.'], emoji:'🍅'),

  (id:'en_child_a2_043', en:'onion', ku:'pîvaz', ipa:'/ˈʌnjən/', pos:'noun',
   form:null, kat:'xwarin', zor:0.83,
   notKu:'Pîvaz. Sebzeya tûj a gilover.',
   her:["An onion is strong.", "I cut the onion."],
   herKu:['Pîvaz tûj e.', 'Ez pîvazê jê dikim.'], emoji:'🧅'),

  (id:'en_child_a2_044', en:'corn', ku:'garis', ipa:'/kɔːn/', pos:'noun',
   form:null, kat:'xwarin', zor:0.81,
   notKu:'Garis. Tovê zer ê çandiniyê.',
   her:["Corn is yellow.", "I eat corn."],
   herKu:['Garis zer e.', 'Ez garis dixwim.'], emoji:'🌽'),

  (id:'en_child_a2_045', en:'pasta', ku:'makarna', ipa:'/ˈpæstə/', pos:'noun',
   form:null, kat:'xwarin', zor:0.82,
   notKu:'Makarna. Xwarina hevîrî ya Îtalî.',
   her:["Pasta is tasty.", "I cook pasta."],
   herKu:['Makarna bi tam e.', 'Ez makarnayê dikelînim.'], emoji:'🍝'),

  (id:'en_child_a2_046', en:'noodles', ku:'erîşte', ipa:'/ˈnuːdlz/', pos:'noun',
   form:null, kat:'xwarin', zor:0.84,
   notKu:'Erîşte. Hevîrê zirav ê dirêj.',
   her:["I like noodles.", "Noodles are long."],
   herKu:['Ez ji erîşteyê hez dikim.', 'Erîşte dirêj e.'], emoji:'🍜'),

  (id:'en_child_a2_047', en:'rice', ku:'birinc', ipa:'/raɪs/', pos:'noun',
   form:null, kat:'xwarin', zor:0.80,
   notKu:'Birinc. Xwarina spî ya piçûk.',
   her:["Rice is white.", "We eat rice."],
   herKu:['Birinc spî ye.', 'Em birincê dixwin.'], emoji:'🍚'),

  (id:'en_child_a2_048', en:'fish', ku:'masî', ipa:'/fɪʃ/', pos:'noun',
   form:null, kat:'xwarin', zor:0.78,
   notKu:'Masî. Xwarina ji behrê.',
   her:["Fish is healthy.", "I eat fish."],
   herKu:['Masî saẍlem e.', 'Ez masiyan dixwim.'], emoji:'🐟'),

  (id:'en_child_a2_049', en:'chicken', ku:'mirîşk', ipa:'/ˈtʃɪkɪn/', pos:'noun',
   form:null, kat:'xwarin', zor:0.82,
   notKu:'Mirîşk. Goştê çûka malê.',
   her:["Chicken is tasty.", "We cook chicken."],
   herKu:['Mirîşk bi tam e.', 'Em mirîşkê dikelînin.'], emoji:'🍗'),

  (id:'en_child_a2_050', en:'sausage', ku:'sucuq', ipa:'/ˈsɒsɪdʒ/', pos:'noun',
   form:null, kat:'xwarin', zor:0.85,
   notKu:'Sucuq. Goştê di nav perdê de.',
   her:["I eat sausage.", "Sausages are hot."],
   herKu:['Ez sucuqê dixwim.', 'Sucuq germ e.'], emoji:'🌭'),

  (id:'en_child_a2_051', en:'hotdog', ku:'sucuq-nan', ipa:'/ˈhɒtdɒɡ/', pos:'noun',
   form:null, kat:'xwarin', zor:0.84,
   notKu:'Sucuq-nan. Sucuq di navê nanî de.',
   her:["A hotdog is tasty.", "I want a hotdog."],
   herKu:['Sucuq-nan bi tam e.', 'Ez sucuq-nanekê dixwazim.'], emoji:'🌭'),

  (id:'en_child_a2_052', en:'cheese', ku:'penîr', ipa:'/tʃiːz/', pos:'noun',
   form:null, kat:'xwarin', zor:0.80,
   notKu:'Penîr. Xwarina ji şîr.',
   her:["Cheese is yellow.", "I like cheese."],
   herKu:['Penîr zer e.', 'Ez ji penîr hez dikim.'], emoji:'🧀'),

  (id:'en_child_a2_053', en:'yogurt', ku:'mast', ipa:'/ˈjɒɡət/', pos:'noun',
   form:null, kat:'xwarin', zor:0.82,
   notKu:'Mast. Xwarina şîrî ya terş.',
   her:["Yogurt is white.", "I eat yogurt."],
   herKu:['Mast spî ye.', 'Ez mastê dixwim.'], emoji:'🥛'),

  (id:'en_child_a2_054', en:'butter', ku:'nîvişk', ipa:'/ˈbʌtə/', pos:'noun',
   form:null, kat:'xwarin', zor:0.82,
   notKu:'Nîvişk. Çewriya ji şîr.',
   her:["Butter is yellow.", "I put butter on bread."],
   herKu:['Nîvişk zer e.', 'Ez nîvişkê datînim ser nan.'], emoji:'🧈'),

  (id:'en_child_a2_055', en:'honey', ku:'hingiv', ipa:'/ˈhʌni/', pos:'noun',
   form:null, kat:'xwarin', zor:0.81,
   notKu:'Hingiv. Şîraniya ji mêşan.',
   her:["Honey is sweet.", "Bees make honey."],
   herKu:['Hingiv şîrîn e.', 'Mêş hingiv çêdikin.'], emoji:'🍯'),

  (id:'en_child_a2_056', en:'lesson', ku:'ders', ipa:'/ˈlesn/', pos:'noun',
   form:null, kat:'dibistan', zor:0.82,
   notKu:'Ders. Tiştê ku di dibistanê de hîn dibî.',
   her:["The lesson is fun.", "I have a math lesson."],
   herKu:['Ders xweş e.', 'Dersa min a matematîkê heye.'], emoji:'📚'),

  (id:'en_child_a2_057', en:'homework', ku:'karê malê', ipa:'/ˈhəʊmwɜːk/', pos:'noun',
   form:null, kat:'dibistan', zor:0.85,
   notKu:'Karê malê. Karê dibistanê li malê.',
   her:["I do my homework.", "Homework is important."],
   herKu:['Ez karê xwe yê malê dikim.', 'Karê malê girîng e.'], emoji:'📝'),

  (id:'en_child_a2_058', en:'test', ku:'tawan', ipa:'/test/', pos:'noun',
   form:null, kat:'dibistan', zor:0.80,
   notKu:'Tawan. Dema ku pirsên dersê tên pirsîn.',
   her:["The test is hard.", "I pass the test."],
   herKu:['Tawan zehmet e.', 'Ez tawanê derbas dikim.'], emoji:'📝'),

  (id:'en_child_a2_059', en:'ruler', ku:'metre', ipa:'/ˈruːlə/', pos:'noun',
   form:null, kat:'dibistan', zor:0.82,
   notKu:'Metre. Dirûvê rast ê pîvanê.',
   her:["I use a ruler.", "The ruler is long."],
   herKu:['Ez metreyekê bi kar tînim.', 'Metre dirêj e.'], emoji:'📏'),

  (id:'en_child_a2_060', en:'eraser', ku:'jêbir', ipa:'/ɪˈreɪzə/', pos:'noun',
   form:null, kat:'dibistan', zor:0.85,
   notKu:'Jêbir. Ji bo jêkirina nivîsê.',
   her:["I need an eraser.", "The eraser is pink."],
   herKu:['Ez jêbirekê dixwazim.', 'Jêbir pembe ye.'], emoji:'🧽'),

  (id:'en_child_a2_061', en:'scissors', ku:'meqes', ipa:'/ˈsɪzəz/', pos:'noun',
   form:null, kat:'dibistan', zor:0.85,
   notKu:'Meqes. Ji bo jêkirina kaẍiz.',
   her:["I use scissors.", "The scissors are sharp."],
   herKu:['Ez meqesê bi kar tînim.', 'Meqes tûj e.'], emoji:'✂️'),

  (id:'en_child_a2_062', en:'glue', ku:'çesp', ipa:'/ɡluː/', pos:'noun',
   form:null, kat:'dibistan', zor:0.82,
   notKu:'Çesp. Ji bo girêdana kaẍiz.',
   her:["I use glue.", "The glue is sticky."],
   herKu:['Ez çespê bi kar tînim.', 'Çesp zeliqok e.'], emoji:'🧴'),

  (id:'en_child_a2_063', en:'paint', ku:'boyax', ipa:'/peɪnt/', pos:'noun',
   form:null, kat:'dibistan', zor:0.83,
   notKu:'Boyax. Rengê şil ji bo resimkirinê.',
   her:["The paint is wet.", "I like red paint."],
   herKu:['Boyax şil e.', 'Ez ji boyaxa sor hez dikim.'], emoji:'🎨'),

  (id:'en_child_a2_064', en:'crayon', ku:'pasteqlem', ipa:'/ˈkreɪɒn/', pos:'noun',
   form:null, kat:'dibistan', zor:0.85,
   notKu:'Pasteqlem. Qelema rengîn a mom.',
   her:["I have crayons.", "Crayons are colorful."],
   herKu:['Pasteqlemên min hene.', 'Pasteqlem rengîn in.'], emoji:'🖍️'),

  (id:'en_child_a2_065', en:'paper', ku:'kaẍiz', ipa:'/ˈpeɪpə/', pos:'noun',
   form:null, kat:'dibistan', zor:0.80,
   notKu:'Kaẍiz. Ji bo nivîsê û resimkirinê.',
   her:["I need paper.", "The paper is white."],
   herKu:['Ez kaẍizê dixwazim.', 'Kaẍiz spî ye.'], emoji:'📄'),

  (id:'en_child_a2_066', en:'notebook', ku:'defter', ipa:'/ˈnəʊtbʊk/', pos:'noun',
   form:null, kat:'dibistan', zor:0.85,
   notKu:'Defter. Pirtûkê ji bo nivîsê.',
   her:["My notebook is blue.", "I write in my notebook."],
   herKu:['Deftera min şîn e.', 'Ez di deftera xwe de dinivîsim.'], emoji:'📓'),

  (id:'en_child_a2_067', en:'computer', ku:'komputer', ipa:'/kəmˈpjuːtə/', pos:'noun',
   form:null, kat:'dibistan', zor:0.86,
   notKu:'Komputer. Amûra teknolojîk a hesabkirinê.',
   her:["I use a computer.", "The computer is new."],
   herKu:['Ez komputerê bi kar tînim.', 'Komputer nû ye.'], emoji:'💻'),

  (id:'en_child_a2_068', en:'tablet', ku:'tablet', ipa:'/ˈtæblət/', pos:'noun',
   form:null, kat:'dibistan', zor:0.85,
   notKu:'Tablet. Ekraneka destan a dîjîtal.',
   her:["I have a tablet.", "The tablet is small."],
   herKu:['Tableteka min heye.', 'Tablet piçûk e.'], emoji:'📱'),

  (id:'en_child_a2_069', en:'screen', ku:'ekran', ipa:'/skriːn/', pos:'noun',
   form:null, kat:'dibistan', zor:0.83,
   notKu:'Ekran. Rûyê televizyon an komputerê.',
   her:["The screen is big.", "I watch the screen."],
   herKu:['Ekran mezin e.', 'Ez li ekranê temaşe dikim.'], emoji:'🖥️'),

  (id:'en_child_a2_070', en:'library', ku:'pirtûkxane', ipa:'/ˈlaɪbrəri/', pos:'noun',
   form:null, kat:'dibistan', zor:0.87,
   notKu:'Pirtûkxane. Cihê ku pirtûk lê ne.',
   her:["I go to the library.", "The library has books."],
   herKu:['Ez diçim pirtûkxaneyê.', 'Pirtûkxane pirtûk hene.'], emoji:'📚'),

  (id:'en_child_a2_071', en:'science', ku:'zanist', ipa:'/ˈsaɪəns/', pos:'noun',
   form:null, kat:'dibistan', zor:0.85,
   notKu:'Zanist. Dersa lêkolîna cîhanê.',
   her:["I like science.", "Science is fun."],
   herKu:['Ez ji zanistê hez dikim.', 'Zanist xweş e.'], emoji:'🔬'),

  (id:'en_child_a2_072', en:'math', ku:'matematîk', ipa:'/mæθ/', pos:'noun',
   form:null, kat:'dibistan', zor:0.82,
   notKu:'Matematîk. Zanista hejmaran.',
   her:["Math is easy.", "I study math."],
   herKu:['Matematîk hêsan e.', 'Ez matematîkê dixwînim.'], emoji:'🔢'),

  (id:'en_child_a2_073', en:'history', ku:'dîrok', ipa:'/ˈhɪstəri/', pos:'noun',
   form:null, kat:'dibistan', zor:0.83,
   notKu:'Dîrok. Dersa kevnareyê.',
   her:["History is interesting.", "I learn history."],
   herKu:['Dîrok balkêş e.', 'Ez dîrokê hîn dibim.'], emoji:'📖'),

  (id:'en_child_a2_074', en:'English', ku:'Îngilîzî', ipa:'/ˈɪŋɡlɪʃ/', pos:'noun',
   form:null, kat:'dibistan', zor:0.83,
   notKu:'Îngilîzî. Zimanê Îngilîstanê.',
   her:["I learn English.", "English is useful."],
   herKu:['Ez Îngilîzî hîn dibim.', 'Îngilîzî bi kêr tê.'], emoji:'🇬🇧'),

  (id:'en_child_a2_075', en:'music', ku:'muzîk', ipa:'/ˈmjuːzɪk/', pos:'noun',
   form:null, kat:'dibistan', zor:0.80,
   notKu:'Muzîk. Dengên xweş ên stranê.',
   her:["I love music.", "Music makes me happy."],
   herKu:['Ez ji muzîkê hez dikim.', 'Muzîk min kêfxweş dike.'], emoji:'🎵'),

  (id:'en_child_a2_076', en:'art', ku:'huner', ipa:'/ɑːt/', pos:'noun',
   form:null, kat:'dibistan', zor:0.82,
   notKu:'Huner. Resimkirina û afirandinê.',
   her:["I like art.", "Art class is fun."],
   herKu:['Ez ji hunerê hez dikim.', 'Dersa hunerê xweş e.'], emoji:'🎨'),

  (id:'en_child_a2_077', en:'gym', ku:'salona werzîşê', ipa:'/dʒɪm/', pos:'noun',
   form:null, kat:'dibistan', zor:0.84,
   notKu:'Salona werzîşê. Cihê werzîşê.',
   her:["I go to gym.", "The gym is big."],
   herKu:['Ez diçim salona werzîşê.', 'Salona werzîşê mezin e.'], emoji:'🏋️'),

  (id:'en_child_a2_078', en:'sports', ku:'werzîş', ipa:'/spɔːts/', pos:'noun',
   form:null, kat:'dibistan', zor:0.83,
   notKu:'Werzîş. Lîstikên laşî.',
   her:["I like sports.", "Sports are healthy."],
   herKu:['Ez ji werzîşê hez dikim.', 'Werzîş saẍlem in.'], emoji:'⚽'),

  (id:'en_child_a2_079', en:'playground', ku:'meydana lîstikê', ipa:'/ˈpleɪɡraʊnd/', pos:'noun',
   form:null, kat:'dibistan', zor:0.87,
   notKu:'Meydana lîstikê. Cihê lîstina zarokan.',
   her:["I play at the playground.", "The playground is fun."],
   herKu:['Ez li meydana lîstikê dilîzim.', 'Meydana lîstikê xweş e.'], emoji:'🛝'),

  (id:'en_child_a2_080', en:'recess', ku:'bêhnvedan', ipa:'/ˈriːses/', pos:'noun',
   form:null, kat:'dibistan', zor:0.86,
   notKu:'Bêhnvedan. Demê navbera dersan.',
   her:["Recess is short.", "I play at recess."],
   herKu:['Bêhnvedan kurt e.', 'Ez di bêhnvedanê de dilîzim.'], emoji:'🎒'),

  (id:'en_child_a2_081', en:'cousin', ku:'pismam', ipa:'/ˈkʌzn/', pos:'noun',
   form:null, kat:'malbat', zor:0.83,
   notKu:'Pismam. Zarokê xaltî an mamê.',
   her:["My cousin is nice.", "I have two cousins."],
   herKu:['Pismamê min xweş e.', 'Du pismamên min hene.'], emoji:'👨‍👩‍👧'),

  (id:'en_child_a2_082', en:'uncle', ku:'mam', ipa:'/ˈʌŋkl/', pos:'noun',
   form:null, kat:'malbat', zor:0.80,
   notKu:'Mam. Birayê bav an dayikê.',
   her:["My uncle is kind.", "Uncle lives near us."],
   herKu:['Mamê min dilovan e.', 'Mam nêzî me dijî.'], emoji:'👨'),

  (id:'en_child_a2_083', en:'aunt', ku:'xaltî', ipa:'/ɑːnt/', pos:'noun',
   form:null, kat:'malbat', zor:0.80,
   notKu:'Xaltî. Xwişka dayikê an bavê.',
   her:["My aunt is fun.", "Aunt visits us."],
   herKu:['Xaltiya min xweş e.', 'Xaltî tê seredana me.'], emoji:'👩'),

  (id:'en_child_a2_084', en:'niece', ku:'birazîya keç', ipa:'/niːs/', pos:'noun',
   form:null, kat:'malbat', zor:0.86,
   notKu:'Birazîya keç. Keça bira an xwişkê.',
   her:["My niece is little.", "I love my niece."],
   herKu:['Birazîya min ya keç piçûk e.', 'Ez ji birazîya xwe ya keç hez dikim.'], emoji:'👧'),

  (id:'en_child_a2_085', en:'nephew', ku:'birazîya kur', ipa:'/ˈnefjuː/', pos:'noun',
   form:null, kat:'malbat', zor:0.86,
   notKu:'Birazîya kur. Kurê bira an xwişkê.',
   her:["My nephew is cute.", "Nephew is five."],
   herKu:['Birazîya min ya kur xweşik e.', 'Birazî pênc salî ye.'], emoji:'👦'),

  (id:'en_child_a2_086', en:'neighbor', ku:'cîran', ipa:'/ˈneɪbə/', pos:'noun',
   form:null, kat:'malbat', zor:0.85,
   notKu:'Cîran. Kesê ku li tenişta me dijî.',
   her:["My neighbor is friendly.", "We greet our neighbor."],
   herKu:['Cîranê min dost e.', 'Em silavê li cîrên xwe dikin.'], emoji:'🏘️'),

  (id:'en_child_a2_087', en:'classmate', ku:'hevpol', ipa:'/ˈklɑːsmeɪt/', pos:'noun',
   form:null, kat:'malbat', zor:0.86,
   notKu:'Hevpol. Hevalê li heman polê.',
   her:["My classmate is smart.", "We help each classmate."],
   herKu:['Hevpolê min jîr e.', 'Em alîkariya her hevpolê xwe dikin.'], emoji:'👫'),

  (id:'en_child_a2_088', en:'teacher', ku:'mamoste', ipa:'/ˈtiːtʃə/', pos:'noun',
   form:null, kat:'malbat', zor:0.82,
   notKu:'Mamoste. Kesê ku hînî zarokan dike.',
   her:["The teacher is kind.", "My teacher teaches English."],
   herKu:['Mamoste dilovan e.', 'Mamosteyê min Îngilîzî hîn dike.'], emoji:'👩‍🏫'),

  (id:'en_child_a2_089', en:'doctor', ku:'bijîşk', ipa:'/ˈdɒktə/', pos:'noun',
   form:null, kat:'malbat', zor:0.82,
   notKu:'Bijîşk. Kesê ku nexweşan derman dike.',
   her:["The doctor helps sick people.", "My doctor is nice."],
   herKu:['Bijîşk arîkariya nexweşan dike.', 'Bijîşkê min xweş e.'], emoji:'👨‍⚕️'),

  (id:'en_child_a2_090', en:'nurse', ku:'hemşîre', ipa:'/nɜːs/', pos:'noun',
   form:null, kat:'malbat', zor:0.82,
   notKu:'Hemşîre. Kesê ku li nexweşan dinêre.',
   her:["The nurse is helpful.", "Nurses work at hospitals."],
   herKu:['Hemşîre alîkar e.', 'Hemşîre li nexweşxaneyan dixebitin.'], emoji:'👩‍⚕️'),

  (id:'en_child_a2_091', en:'dentist', ku:'diransaz', ipa:'/ˈdentɪst/', pos:'noun',
   form:null, kat:'malbat', zor:0.85,
   notKu:'Diransaz. Bijîşkê diranan.',
   her:["The dentist checks teeth.", "I visit the dentist."],
   herKu:['Diransaz li diranan dinêre.', 'Ez diçim diransazî.'], emoji:'🦷'),

  (id:'en_child_a2_092', en:'police', ku:'polîs', ipa:'/pəˈliːs/', pos:'noun',
   form:null, kat:'malbat', zor:0.83,
   notKu:'Polîs. Kesê ku ewlehiyê diparêze.',
   her:["The police help us.", "Police are brave."],
   herKu:['Polîs arîkariya me dikin.', 'Polîs mêrxas in.'], emoji:'👮'),

  (id:'en_child_a2_093', en:'firefighter', ku:'agirkuj', ipa:'/ˈfaɪəfaɪtə/', pos:'noun',
   form:null, kat:'malbat', zor:0.88,
   notKu:'Agirkuj. Kesê ku agir vedimirîne.',
   her:["A firefighter is brave.", "Firefighters save people."],
   herKu:['Agirkuj mêrxas e.', 'Agirkuj mirovan rizgar dikin.'], emoji:'👨‍🚒'),

  (id:'en_child_a2_094', en:'farmer', ku:'cotkar', ipa:'/ˈfɑːmə/', pos:'noun',
   form:null, kat:'malbat', zor:0.82,
   notKu:'Cotkar. Kesê ku çandiniyê dike.',
   her:["The farmer works hard.", "Farmers grow food."],
   herKu:['Cotkar zehmet dixebite.', 'Cotkar xwarinê çêdikin.'], emoji:'👨‍🌾'),

  (id:'en_child_a2_095', en:'baker', ku:'nanpêj', ipa:'/ˈbeɪkə/', pos:'noun',
   form:null, kat:'malbat', zor:0.84,
   notKu:'Nanpêj. Kesê ku nanê çêdike.',
   her:["The baker makes bread.", "My baker is kind."],
   herKu:['Nanpêj nan çêdike.', 'Nanpêjê min dilovan e.'], emoji:'👨‍🍳'),

  (id:'en_child_a2_096', en:'chef', ku:'aşpêj', ipa:'/ʃef/', pos:'noun',
   form:null, kat:'malbat', zor:0.82,
   notKu:'Aşpêj. Kesê ku xwarinê çêdike.',
   her:["The chef cooks well.", "Chefs make tasty food."],
   herKu:['Aşpêj baş dikelîne.', 'Aşpêj xwarinên bi tam çêdikin.'], emoji:'👨‍🍳'),

  (id:'en_child_a2_097', en:'singer', ku:'stranbêj', ipa:'/ˈsɪŋə/', pos:'noun',
   form:null, kat:'malbat', zor:0.84,
   notKu:'Stranbêj. Kesê ku stranan dibêje.',
   her:["The singer is famous.", "Singers sing songs."],
   herKu:['Stranbêj navdar e.', 'Stranbêj stranan dibêjin.'], emoji:'🎤'),

  (id:'en_child_a2_098', en:'dancer', ku:'reqaskar', ipa:'/ˈdɑːnsə/', pos:'noun',
   form:null, kat:'malbat', zor:0.85,
   notKu:'Reqaskar. Kesê ku reqas dike.',
   her:["The dancer is quick.", "Dancers move beautifully."],
   herKu:['Reqaskar lez e.', 'Reqaskar xweş dilivin.'], emoji:'💃'),

  (id:'en_child_a2_099', en:'actor', ku:'lîstikvan', ipa:'/ˈæktə/', pos:'noun',
   form:null, kat:'malbat', zor:0.83,
   notKu:'Lîstikvan. Kesê ku di fîlman de dilîze.',
   her:["The actor is funny.", "Actors work in movies."],
   herKu:['Lîstikvan henek e.', 'Lîstikvan di fîlman de dixebitin.'], emoji:'🎭'),

  (id:'en_child_a2_100', en:'artist', ku:'hunermend', ipa:'/ˈɑːtɪst/', pos:'noun',
   form:null, kat:'malbat', zor:0.84,
   notKu:'Hunermend. Kesê hunerê.',
   her:["The artist paints.", "Artists are creative."],
   herKu:['Hunermend boyaxê dike.', 'Hunermend afirandêr in.'], emoji:'🎨'),

  (id:'en_child_a2_101', en:'stomach', ku:'zik', ipa:'/ˈstʌmək/', pos:'noun',
   form:null, kat:'beden', zor:0.84,
   notKu:'Zik. Beşa navê laş.',
   her:["My stomach hurts.", "I eat with my stomach."],
   herKu:['Zikê min diêşe.', 'Ez bi zikê xwe dixwim.'], emoji:'🫃'),

  (id:'en_child_a2_102', en:'knee', ku:'çok', ipa:'/niː/', pos:'noun',
   form:null, kat:'beden', zor:0.82,
   notKu:'Çok. Gira lingê.',
   her:["My knee hurts.", "I bend my knee."],
   herKu:['Çokê min diêşe.', 'Ez çokê xwe bitewînim.'], emoji:'🦵'),

  (id:'en_child_a2_103', en:'elbow', ku:'enîşk', ipa:'/ˈelbəʊ/', pos:'noun',
   form:null, kat:'beden', zor:0.84,
   notKu:'Enîşk. Gira destê.',
   her:["My elbow hurts.", "I bend my elbow."],
   herKu:['Enîşka min diêşe.', 'Ez enîşka xwe bitewînim.'], emoji:'💪'),

  (id:'en_child_a2_104', en:'shoulder', ku:'mil', ipa:'/ˈʃəʊldə/', pos:'noun',
   form:null, kat:'beden', zor:0.83,
   notKu:'Mil. Jor serê destê.',
   her:["My shoulder is strong.", "She touches my shoulder."],
   herKu:['Milê min bihêz e.', 'Ew dest dide milê min.'], emoji:'💪'),

  (id:'en_child_a2_105', en:'ankle', ku:'gûzek', ipa:'/ˈæŋkl/', pos:'noun',
   form:null, kat:'beden', zor:0.85,
   notKu:'Gûzek. Gira jêr lingê.',
   her:["My ankle hurts.", "The ankle is small."],
   herKu:['Gûzeka min diêşe.', 'Gûzek piçûk e.'], emoji:'🦶'),

  (id:'en_child_a2_106', en:'wrist', ku:'zenda dest', ipa:'/rɪst/', pos:'noun',
   form:null, kat:'beden', zor:0.85,
   notKu:'Zenda dest. Gira navbera dest û bask.',
   her:["My wrist is thin.", "I wear a watch on my wrist."],
   herKu:['Zenda destê min zirav e.', 'Ez saetê li zenda destê xwe dikim.'], emoji:'⌚'),

  (id:'en_child_a2_107', en:'neck', ku:'stû', ipa:'/nek/', pos:'noun',
   form:null, kat:'beden', zor:0.80,
   notKu:'Stû. Navbera ser û milan.',
   her:["My neck is long.", "She turns her neck."],
   herKu:['Stûyê min dirêj e.', 'Ew stûyê xwe vedigerîne.'], emoji:'🧑'),

  (id:'en_child_a2_108', en:'chest', ku:'sîng', ipa:'/tʃest/', pos:'noun',
   form:null, kat:'beden', zor:0.82,
   notKu:'Sîng. Beşa jor a laş.',
   her:["My chest is strong.", "The chest is wide."],
   herKu:['Sîngê min bihêz e.', 'Sîng fireh e.'], emoji:'🫁'),

  (id:'en_child_a2_109', en:'back', ku:'pişt', ipa:'/bæk/', pos:'noun',
   form:null, kat:'beden', zor:0.80,
   notKu:'Pişt. Beşa paş a laş.',
   her:["My back hurts.", "The back is straight."],
   herKu:['Pişta min diêşe.', 'Pişt rast e.'], emoji:'🧍'),

  (id:'en_child_a2_110', en:'skin', ku:'çerm', ipa:'/skɪn/', pos:'noun',
   form:null, kat:'beden', zor:0.81,
   notKu:'Çerm. Perda derveyî ya laş.',
   her:["My skin is soft.", "The sun warms my skin."],
   herKu:['Çermê min nerm e.', 'Roj çermê min germ dike.'], emoji:'✋'),

  (id:'en_child_a2_111', en:'blood', ku:'xwîn', ipa:'/blʌd/', pos:'noun',
   form:null, kat:'beden', zor:0.82,
   notKu:'Xwîn. Şilava sor a nav laş.',
   her:["Blood is red.", "Blood runs in my body."],
   herKu:['Xwîn sor e.', 'Xwîn di laşê min de dimeşe.'], emoji:'🩸'),

  (id:'en_child_a2_112', en:'brain', ku:'mejî', ipa:'/breɪn/', pos:'noun',
   form:null, kat:'beden', zor:0.82,
   notKu:'Mejî. Organa serê me.',
   her:["My brain is smart.", "The brain thinks."],
   herKu:['Mejiyê min jîr e.', 'Mejî difikire.'], emoji:'🧠'),

  (id:'en_child_a2_113', en:'heart', ku:'dil', ipa:'/hɑːt/', pos:'noun',
   form:null, kat:'beden', zor:0.81,
   notKu:'Dil. Organa ku xwînê dişîne.',
   her:["My heart beats.", "The heart is red."],
   herKu:['Dilê min lê dide.', 'Dil sor e.'], emoji:'❤️'),

  (id:'en_child_a2_114', en:'bone', ku:'hestî', ipa:'/bəʊn/', pos:'noun',
   form:null, kat:'beden', zor:0.81,
   notKu:'Hestî. Beşê hişk ê laş.',
   her:["Bones are hard.", "I have strong bones."],
   herKu:['Hestî hişk in.', 'Hestiyên min bihêz in.'], emoji:'🦴'),

  (id:'en_child_a2_115', en:'muscle', ku:'masûlke', ipa:'/ˈmʌsl/', pos:'noun',
   form:null, kat:'beden', zor:0.85,
   notKu:'Masûlke. Goştê bihêz ê laş.',
   her:["My muscles are strong.", "Muscles help me run."],
   herKu:['Masûlkên min bihêz in.', 'Masûlke arîkariya bezê dikin.'], emoji:'💪'),

  (id:'en_child_a2_116', en:'sick', ku:'nexweş', ipa:'/sɪk/', pos:'adj',
   form:null, kat:'beden', zor:0.80,
   notKu:'Nexweş. Ne saẍlem.',
   her:["I am sick today.", "The baby is sick."],
   herKu:['Ez îro nexweş im.', 'Pitik nexweş e.'], emoji:'🤒'),

  (id:'en_child_a2_117', en:'healthy', ku:'saẍlem', ipa:'/ˈhelθi/', pos:'adj',
   form:null, kat:'beden', zor:0.83,
   notKu:'Saẍlem. Bê nexweşî.',
   her:["I am healthy.", "Fruits are healthy."],
   herKu:['Ez saẍlem im.', 'Fêkî saẍlem in.'], emoji:'💚'),

  (id:'en_child_a2_118', en:'medicine', ku:'derman', ipa:'/ˈmedsn/', pos:'noun',
   form:null, kat:'beden', zor:0.84,
   notKu:'Derman. Ji bo sibehbûna ji nexweşiyê.',
   her:["I take medicine.", "The medicine helps me."],
   herKu:['Ez dermanê vedixwim.', 'Derman alîkariya min dike.'], emoji:'💊'),

  (id:'en_child_a2_119', en:'hospital', ku:'nexweşxane', ipa:'/ˈhɒspɪtl/', pos:'noun',
   form:null, kat:'beden', zor:0.86,
   notKu:'Nexweşxane. Cihê ku nexweş lê derman dibin.',
   her:["The hospital is big.", "Doctors work at hospitals."],
   herKu:['Nexweşxane mezin e.', 'Bijîşk li nexweşxaneyan dixebitin.'], emoji:'🏥'),

  (id:'en_child_a2_120', en:'bandage', ku:'sarixe', ipa:'/ˈbændɪdʒ/', pos:'noun',
   form:null, kat:'beden', zor:0.86,
   notKu:'Sarixe. Pêçeka birînê.',
   her:["I need a bandage.", "The bandage is white."],
   herKu:['Ez sarixeyekê dixwazim.', 'Sarixe spî ye.'], emoji:'🩹'),

  (id:'en_child_a2_121', en:'sneeze', ku:'pêkijîn', ipa:'/sniːz/', pos:'verb',
   form:null, kat:'beden', zor:0.86,
   notKu:'Pêkijîn. Derxistina ji pozê.',
   her:["I sneeze loudly.", "She sneezes again."],
   herKu:['Ez bi dengekî bilind pêkijîm.', 'Ew dîsa pêkijiye.'], emoji:'🤧'),

  (id:'en_child_a2_122', en:'cough', ku:'kuxîn', ipa:'/kɒf/', pos:'verb',
   form:null, kat:'beden', zor:0.84,
   notKu:'Kuxîn. Derxistina bi dengî ji qirikê.',
   her:["I cough a lot.", "The boy coughs."],
   herKu:['Ez gelekî dikuxim.', 'Kur dikuxî.'], emoji:'😷'),

  (id:'en_child_a2_123', en:'cold', ku:'sermayî', ipa:'/kəʊld/', pos:'noun',
   form:null, kat:'beden', zor:0.81,
   notKu:'Sermayî. Nexweşiya pozê.',
   her:["I have a cold.", "A cold is no fun."],
   herKu:['Ez sermayî me.', 'Sermayî ne xweş e.'], emoji:'🤧'),

  (id:'en_child_a2_124', en:'fever', ku:'tayî', ipa:'/ˈfiːvə/', pos:'noun',
   form:null, kat:'beden', zor:0.84,
   notKu:'Tayî. Germbûna laş.',
   her:["I have a fever.", "The fever is high."],
   herKu:['Tayiya min heye.', 'Tayî bilind e.'], emoji:'🤒'),

  (id:'en_child_a2_125', en:'headache', ku:'serêş', ipa:'/ˈhedeɪk/', pos:'noun',
   form:null, kat:'beden', zor:0.86,
   notKu:'Serêş. Êşa serê.',
   her:["I have a headache.", "The headache is bad."],
   herKu:['Serêşa min heye.', 'Serêş xerab e.'], emoji:'🤕'),

  (id:'en_child_a2_126', en:'living room', ku:'odeya rûniştinê', ipa:'/ˈlɪvɪŋ ruːm/', pos:'noun',
   form:null, kat:'mal', zor:0.87,
   notKu:'Odeya rûniştinê. Cihê mêvanê.',
   her:["The living room is big.", "We watch TV in the living room."],
   herKu:['Odeya rûniştinê mezin e.', 'Em li odeyê TV temaşe dikin.'], emoji:'🛋️'),

  (id:'en_child_a2_127', en:'bedroom', ku:'odeya razanê', ipa:'/ˈbedruːm/', pos:'noun',
   form:null, kat:'mal', zor:0.86,
   notKu:'Odeya razanê. Cihê ku em lê radizên.',
   her:["My bedroom is blue.", "I sleep in my bedroom."],
   herKu:['Odeya razana min şîn e.', 'Ez di odeya xwe de radizêm.'], emoji:'🛏️'),

  (id:'en_child_a2_128', en:'bathroom', ku:'serşok', ipa:'/ˈbɑːθruːm/', pos:'noun',
   form:null, kat:'mal', zor:0.85,
   notKu:'Serşok. Cihê hemamê û destşokê.',
   her:["The bathroom is clean.", "I wash in the bathroom."],
   herKu:['Serşok paqij e.', 'Ez di serşokê de dişom.'], emoji:'🛁'),

  (id:'en_child_a2_129', en:'kitchen', ku:'aşxane', ipa:'/ˈkɪtʃɪn/', pos:'noun',
   form:null, kat:'mal', zor:0.85,
   notKu:'Aşxane. Cihê ku xwarin tê çêkirin.',
   her:["Mom cooks in the kitchen.", "The kitchen is warm."],
   herKu:['Dayik di aşxaneyê de dikelîne.', 'Aşxane germ e.'], emoji:'🍳'),

  (id:'en_child_a2_130', en:'garage', ku:'garaj', ipa:'/ˈɡærɑːʒ/', pos:'noun',
   form:null, kat:'mal', zor:0.84,
   notKu:'Garaj. Cihê otomobîlê.',
   her:["The car is in the garage.", "Our garage is big."],
   herKu:['Otomobîl di garajê de ye.', 'Garaja me mezin e.'], emoji:'🚗'),

  (id:'en_child_a2_131', en:'basement', ku:'jêrzemîn', ipa:'/ˈbeɪsmənt/', pos:'noun',
   form:null, kat:'mal', zor:0.88,
   notKu:'Jêrzemîn. Qata binerd.',
   her:["The basement is dark.", "We store things in the basement."],
   herKu:['Jêrzemîn tarî ye.', 'Em tiştan di jêrzemînê de hildigirin.'], emoji:'🏚️'),

  (id:'en_child_a2_132', en:'attic', ku:'banî', ipa:'/ˈætɪk/', pos:'noun',
   form:null, kat:'mal', zor:0.85,
   notKu:'Banî. Qata jorîn a xênî.',
   her:["The attic is old.", "We find toys in the attic."],
   herKu:['Banî kevn e.', 'Em li banî leyîstikan dibînin.'], emoji:'🏠'),

  (id:'en_child_a2_133', en:'garden', ku:'baxçe', ipa:'/ˈɡɑːdn/', pos:'noun',
   form:null, kat:'mal', zor:0.83,
   notKu:'Baxçe. Cihê kulîlkan û daran.',
   her:["The garden is green.", "Flowers grow in the garden."],
   herKu:['Baxçe kesk e.', 'Kulîlk di baxçe de şîn dibin.'], emoji:'🌳'),

  (id:'en_child_a2_134', en:'balcony', ku:'eywan', ipa:'/ˈbælkəni/', pos:'noun',
   form:null, kat:'mal', zor:0.85,
   notKu:'Eywan. Meydana derve ya xênî.',
   her:["The balcony is sunny.", "I sit on the balcony."],
   herKu:['Eywan roja dike.', 'Ez li ser eywanê rûdinim.'], emoji:'🏡'),

  (id:'en_child_a2_135', en:'stairs', ku:'derence', ipa:'/steəz/', pos:'noun',
   form:null, kat:'mal', zor:0.83,
   notKu:'Derence. Pêgehên jor û jêr.',
   her:["I climb the stairs.", "The stairs are long."],
   herKu:['Ez derenceyan hildikişim.', 'Derence dirêj in.'], emoji:'🪜'),

  (id:'en_child_a2_136', en:'sofa', ku:'kursî', ipa:'/ˈsəʊfə/', pos:'noun',
   form:null, kat:'mal', zor:0.82,
   notKu:'Kursî. Cihê rûniştinê yê nerm.',
   her:["The sofa is soft.", "I sit on the sofa."],
   herKu:['Kursî nerm e.', 'Ez li ser kursî rûdinim.'], emoji:'🛋️'),

  (id:'en_child_a2_137', en:'lamp', ku:'lampe', ipa:'/læmp/', pos:'noun',
   form:null, kat:'mal', zor:0.81,
   notKu:'Lampe. Amûra ronîkirinê.',
   her:["The lamp is bright.", "I turn on the lamp."],
   herKu:['Lampe geş e.', 'Ez lampê vêdixim.'], emoji:'💡'),

  (id:'en_child_a2_138', en:'mirror', ku:'eynik', ipa:'/ˈmɪrə/', pos:'noun',
   form:null, kat:'mal', zor:0.83,
   notKu:'Eynik. Cama ku xwe tê de dibînin.',
   her:["The mirror is big.", "I look in the mirror."],
   herKu:['Eynik mezin e.', 'Ez di eynikê de dinêrim.'], emoji:'🪞'),

  (id:'en_child_a2_139', en:'towel', ku:'destmal', ipa:'/ˈtaʊəl/', pos:'noun',
   form:null, kat:'mal', zor:0.84,
   notKu:'Destmal. Cawê ku destan pê ziwa dikî.',
   her:["The towel is wet.", "I use a towel."],
   herKu:['Destmal şil e.', 'Ez destmalekê bi kar tînim.'], emoji:'🧻'),

  (id:'en_child_a2_140', en:'soap', ku:'sabûn', ipa:'/səʊp/', pos:'noun',
   form:null, kat:'mal', zor:0.80,
   notKu:'Sabûn. Ji bo şûştinê.',
   her:["I use soap.", "The soap smells nice."],
   herKu:['Ez sabûnê bi kar tînim.', 'Bîna sabûnê xweş e.'], emoji:'🧼'),

  (id:'en_child_a2_141', en:'fridge', ku:'sarinc', ipa:'/frɪdʒ/', pos:'noun',
   form:null, kat:'mal', zor:0.83,
   notKu:'Sarinc. Amûra parastina xwarinê.',
   her:["The fridge is cold.", "I open the fridge."],
   herKu:['Sarinc sar e.', 'Ez sarincê vedikim.'], emoji:'❄️'),

  (id:'en_child_a2_142', en:'oven', ku:'firne', ipa:'/ˈʌvn/', pos:'noun',
   form:null, kat:'mal', zor:0.82,
   notKu:'Firne. Amûra pehtina xwarinê.',
   her:["The oven is hot.", "Mom uses the oven."],
   herKu:['Firne germ e.', 'Dayik firnê bi kar tîne.'], emoji:'🔥'),

  (id:'en_child_a2_143', en:'stove', ku:'soba', ipa:'/stəʊv/', pos:'noun',
   form:null, kat:'mal', zor:0.84,
   notKu:'Soba. Amûra germkirina xwarinê.',
   her:["The stove is on.", "I cook on the stove."],
   herKu:['Soba vêkirî ye.', 'Ez li ser sobê dikelînim.'], emoji:'🔥'),

  (id:'en_child_a2_144', en:'sink', ku:'destşok', ipa:'/sɪŋk/', pos:'noun',
   form:null, kat:'mal', zor:0.82,
   notKu:'Destşok. Cihê şûştina destan.',
   her:["I wash at the sink.", "The sink is clean."],
   herKu:['Ez li destşokê dişom.', 'Destşok paqij e.'], emoji:'🚰'),

  (id:'en_child_a2_145', en:'washing machine', ku:'makîneya şûştinê', ipa:'/ˈwɒʃɪŋ məˈʃiːn/', pos:'noun',
   form:null, kat:'mal', zor:0.90,
   notKu:'Makîneya şûştinê. Amûra şûştina kincan.',
   her:["The washing machine is loud.", "Mom uses the washing machine."],
   herKu:['Makîneya şûştinê pir dengdar e.', 'Dayik makîneyê bi kar tîne.'], emoji:'🧺'),

  (id:'en_child_a2_146', en:'vacuum', ku:'makîneya tozê', ipa:'/ˈvækjuːm/', pos:'noun',
   form:null, kat:'mal', zor:0.88,
   notKu:'Makîneya tozê. Amûra paqijkirina xalîyê.',
   her:["The vacuum is loud.", "Dad uses the vacuum."],
   herKu:['Makîneya tozê pir dengdar e.', 'Bav makîneyê bi kar tîne.'], emoji:'🧹'),

  (id:'en_child_a2_147', en:'blanket', ku:'betaniye', ipa:'/ˈblæŋkɪt/', pos:'noun',
   form:null, kat:'mal', zor:0.85,
   notKu:'Betaniye. Cawê germkirinê yê razanê.',
   her:["The blanket is warm.", "I use a blanket."],
   herKu:['Betaniye germ e.', 'Ez betaniyekê bi kar tînim.'], emoji:'🛏️'),

  (id:'en_child_a2_148', en:'pillow', ku:'balgeh', ipa:'/ˈpɪləʊ/', pos:'noun',
   form:null, kat:'mal', zor:0.83,
   notKu:'Balgeh. Cihê bin serê ji bo razanê.',
   her:["My pillow is soft.", "I hug my pillow."],
   herKu:['Balgeha min nerm e.', 'Ez balgeha xwe hembêz dikim.'], emoji:'🛌'),

  (id:'en_child_a2_149', en:'curtain', ku:'perde', ipa:'/ˈkɜːtn/', pos:'noun',
   form:null, kat:'mal', zor:0.83,
   notKu:'Perde. Cawê li ber pencereyê.',
   her:["The curtain is blue.", "I open the curtain."],
   herKu:['Perde şîn e.', 'Ez perdê vedikim.'], emoji:'🪟'),

  (id:'en_child_a2_150', en:'carpet', ku:'xalî', ipa:'/ˈkɑːpɪt/', pos:'noun',
   form:null, kat:'mal', zor:0.82,
   notKu:'Xalî. Cawê li ser erdê.',
   her:["The carpet is soft.", "I sit on the carpet."],
   herKu:['Xalî nerm e.', 'Ez li ser xalîyê rûdinim.'], emoji:'🪴'),

  (id:'en_child_a2_151', en:'t-shirt', ku:'kirase', ipa:'/ˈtiː ʃɜːt/', pos:'noun',
   form:null, kat:'cil', zor:0.83,
   notKu:'Kirase. Kincê jor ê destkurt.',
   her:["My t-shirt is red.", "I wear a t-shirt."],
   herKu:['Kirasê min sor e.', 'Ez kirasekî li xwe dikim.'], emoji:'👕'),

  (id:'en_child_a2_152', en:'jeans', ku:'pantolonê jîn', ipa:'/dʒiːnz/', pos:'noun',
   form:null, kat:'cil', zor:0.85,
   notKu:'Pantolonê jîn. Pantolonê kot ê şîn.',
   her:["My jeans are blue.", "I wear jeans."],
   herKu:['Pantolonê min ê jîn şîn e.', 'Ez pantolonê jîn li xwe dikim.'], emoji:'👖'),

  (id:'en_child_a2_153', en:'shorts', ku:'pantolê kurt', ipa:'/ʃɔːts/', pos:'noun',
   form:null, kat:'cil', zor:0.85,
   notKu:'Pantolê kurt. Pantolonê kin ê havînê.',
   her:["I wear shorts.", "My shorts are black."],
   herKu:['Ez pantolê kurt li xwe dikim.', 'Pantolê min ê kurt reş e.'], emoji:'🩳'),

  (id:'en_child_a2_154', en:'sweater', ku:'kazak', ipa:'/ˈswetə/', pos:'noun',
   form:null, kat:'cil', zor:0.85,
   notKu:'Kazak. Kincê germ ê hirî.',
   her:["The sweater is warm.", "I wear a sweater."],
   herKu:['Kazak germ e.', 'Ez kazakekê li xwe dikim.'], emoji:'🧥'),

  (id:'en_child_a2_155', en:'hoodie', ku:'kazaka serpûşî', ipa:'/ˈhʊdi/', pos:'noun',
   form:null, kat:'cil', zor:0.87,
   notKu:'Kazaka serpûşî. Kazaka bi seraqî.',
   her:["My hoodie is gray.", "I love my hoodie."],
   herKu:['Kazaka min a serpûşî gewr e.', 'Ez ji kazaka xwe ya serpûşî hez dikim.'], emoji:'🧥'),

  (id:'en_child_a2_156', en:'jacket', ku:'çakêt', ipa:'/ˈdʒækɪt/', pos:'noun',
   form:null, kat:'cil', zor:0.83,
   notKu:'Çakêt. Kincê jor ê sivik.',
   her:["My jacket is new.", "I wear a jacket."],
   herKu:['Çakêtê min nû ye.', 'Ez çakêtekî li xwe dikim.'], emoji:'🧥'),

  (id:'en_child_a2_157', en:'coat', ku:'palto', ipa:'/kəʊt/', pos:'noun',
   form:null, kat:'cil', zor:0.82,
   notKu:'Palto. Kincê zivistanê yê dirêj.',
   her:["The coat is heavy.", "I wear my coat."],
   herKu:['Palto giran e.', 'Ez paltoya xwe li xwe dikim.'], emoji:'🧥'),

  (id:'en_child_a2_158', en:'raincoat', ku:'palto baranê', ipa:'/ˈreɪnkəʊt/', pos:'noun',
   form:null, kat:'cil', zor:0.87,
   notKu:'Palto baranê. Paltoya ji bo baranê.',
   her:["I wear a raincoat.", "The raincoat is yellow."],
   herKu:['Ez palto baranê li xwe dikim.', 'Palto baranê zer e.'], emoji:'🧥'),

  (id:'en_child_a2_159', en:'scarf', ku:'şal', ipa:'/skɑːf/', pos:'noun',
   form:null, kat:'cil', zor:0.83,
   notKu:'Şal. Cawê stû yê germ.',
   her:["My scarf is warm.", "I wear a scarf."],
   herKu:['Şalê min germ e.', 'Ez şalekê li xwe dikim.'], emoji:'🧣'),

  (id:'en_child_a2_160', en:'gloves', ku:'destkêş', ipa:'/ɡlʌvz/', pos:'noun',
   form:null, kat:'cil', zor:0.83,
   notKu:'Destkêş. Ji bo destan ên germ.',
   her:["My gloves are black.", "I wear gloves."],
   herKu:['Destkêşên min reş in.', 'Ez destkêşan li xwe dikim.'], emoji:'🧤'),

  (id:'en_child_a2_161', en:'hat', ku:'şapik', ipa:'/hæt/', pos:'noun',
   form:null, kat:'cil', zor:0.80,
   notKu:'Şapik. Kincê serê.',
   her:["My hat is big.", "I wear a hat."],
   herKu:['Şapika min mezin e.', 'Ez şapikekê li xwe dikim.'], emoji:'👒'),

  (id:'en_child_a2_162', en:'cap', ku:'qepsûl', ipa:'/kæp/', pos:'noun',
   form:null, kat:'cil', zor:0.81,
   notKu:'Qepsûl. Şapika werzîşî.',
   her:["My cap is red.", "I wear a cap."],
   herKu:['Qepsûla min sor e.', 'Ez qepsûlekê li xwe dikim.'], emoji:'🧢'),

  (id:'en_child_a2_163', en:'sock', ku:'gore', ipa:'/sɒk/', pos:'noun',
   form:null, kat:'cil', zor:0.80,
   notKu:'Gore. Kincê binpêya.',
   her:["My socks are clean.", "I put on socks."],
   herKu:['Gorên min paqij in.', 'Ez goran li xwe dikim.'], emoji:'🧦'),

  (id:'en_child_a2_164', en:'shoe', ku:'sol', ipa:'/ʃuː/', pos:'noun',
   form:null, kat:'cil', zor:0.78,
   notKu:'Sol. Ji bo parastina pêyan.',
   her:["My shoe is new.", "I tie my shoe."],
   herKu:['Solê min nû ye.', 'Ez solê xwe girê didim.'], emoji:'👟'),

  (id:'en_child_a2_165', en:'boot', ku:'çekme', ipa:'/buːt/', pos:'noun',
   form:null, kat:'cil', zor:0.82,
   notKu:'Çekme. Solê dirêj ê zivistanê.',
   her:["My boots are brown.", "I wear boots."],
   herKu:['Çekmeyên min qehweyî ne.', 'Ez çekmeyan li xwe dikim.'], emoji:'🥾'),

  (id:'en_child_a2_166', en:'sneakers', ku:'sola werzîşê', ipa:'/ˈsniːkəz/', pos:'noun',
   form:null, kat:'cil', zor:0.88,
   notKu:'Sola werzîşê. Solê rehet ê sivik.',
   her:["My sneakers are white.", "I like sneakers."],
   herKu:['Solên min ên werzîşê spî ne.', 'Ez ji solên werzîşê hez dikim.'], emoji:'👟'),

  (id:'en_child_a2_167', en:'dress', ku:'fîstan', ipa:'/dres/', pos:'noun',
   form:null, kat:'cil', zor:0.83,
   notKu:'Fîstan. Kincê keçan ê dirêj.',
   her:["The dress is pretty.", "She wears a dress."],
   herKu:['Fîstan xweşik e.', 'Ew fîstanekê li xwe dike.'], emoji:'👗'),

  (id:'en_child_a2_168', en:'skirt', ku:'etek', ipa:'/skɜːt/', pos:'noun',
   form:null, kat:'cil', zor:0.82,
   notKu:'Etek. Kincê jêr ê keçan.',
   her:["My skirt is pink.", "She wears a skirt."],
   herKu:['Eteka min pembe ye.', 'Ew etekekê li xwe dike.'], emoji:'👗'),

  (id:'en_child_a2_169', en:'pajamas', ku:'cilê razanê', ipa:'/pəˈdʒɑːməz/', pos:'noun',
   form:null, kat:'cil', zor:0.87,
   notKu:'Cilê razanê. Kincê ji bo razanê.',
   her:["My pajamas are soft.", "I wear pajamas at night."],
   herKu:['Cilên razanê yên min nerm in.', 'Ez bi şev cilên razanê li xwe dikim.'], emoji:'🩱'),

  (id:'en_child_a2_170', en:'swimsuit', ku:'kincê avjeniyê', ipa:'/ˈswɪmsuːt/', pos:'noun',
   form:null, kat:'cil', zor:0.88,
   notKu:'Kincê avjeniyê. Ji bo avjeniyê.',
   her:["My swimsuit is blue.", "I wear a swimsuit."],
   herKu:['Kincê min ê avjeniyê şîn e.', 'Ez kincê avjeniyê li xwe dikim.'], emoji:'🩱'),

  (id:'en_child_a2_171', en:'belt', ku:'kember', ipa:'/belt/', pos:'noun',
   form:null, kat:'cil', zor:0.81,
   notKu:'Kember. Cawê dor navê laş.',
   her:["My belt is black.", "I wear a belt."],
   herKu:['Kembera min reş e.', 'Ez kemberekê li xwe dikim.'], emoji:'👔'),

  (id:'en_child_a2_172', en:'watch', ku:'saet', ipa:'/wɒtʃ/', pos:'noun',
   form:null, kat:'cil', zor:0.80,
   notKu:'Saet. Amûra pîvana demê.',
   her:["My watch is small.", "I wear a watch."],
   herKu:['Saeta min piçûk e.', 'Ez saetê li xwe dikim.'], emoji:'⌚'),

  (id:'en_child_a2_173', en:'glasses', ku:'berçavk', ipa:'/ˈɡlɑːsɪz/', pos:'noun',
   form:null, kat:'cil', zor:0.83,
   notKu:'Berçavk. Ji bo dîtina baştir.',
   her:["I wear glasses.", "The glasses are new."],
   herKu:['Ez berçavkê li xwe dikim.', 'Berçavk nû ne.'], emoji:'👓'),

  (id:'en_child_a2_174', en:'bag', ku:'çente', ipa:'/bæɡ/', pos:'noun',
   form:null, kat:'cil', zor:0.78,
   notKu:'Çente. Ji bo hilgirtina tiştan.',
   her:["My bag is heavy.", "I carry a bag."],
   herKu:['Çenteya min giran e.', 'Ez çenteyekê hildigirim.'], emoji:'🎒'),

  (id:'en_child_a2_175', en:'backpack', ku:'çenteya pişt', ipa:'/ˈbækpæk/', pos:'noun',
   form:null, kat:'cil', zor:0.87,
   notKu:'Çenteya pişt. Çenteya dibistanê.',
   her:["My backpack is red.", "I carry a backpack."],
   herKu:['Çenteya min a pişt sor e.', 'Ez çenteyekê pişt hildigirim.'], emoji:'🎒'),

  (id:'en_child_a2_176', en:'forest', ku:'daristan', ipa:'/ˈfɒrɪst/', pos:'noun',
   form:null, kat:'xweza', zor:0.83,
   notKu:'Daristan. Cihê darên pir.',
   her:["The forest is big.", "Animals live in the forest."],
   herKu:['Daristan mezin e.', 'Heywan di daristanê de dijîn.'], emoji:'🌲'),

  (id:'en_child_a2_177', en:'beach', ku:'behrqirax', ipa:'/biːtʃ/', pos:'noun',
   form:null, kat:'xweza', zor:0.84,
   notKu:'Behrqirax. Qiraxa behrê ya qûmî.',
   her:["The beach is sunny.", "I play at the beach."],
   herKu:['Behrqirax roja dike.', 'Ez li behrqiraxê dilîzim.'], emoji:'🏖️'),

  (id:'en_child_a2_178', en:'ocean', ku:'okyanûs', ipa:'/ˈəʊʃn/', pos:'noun',
   form:null, kat:'xweza', zor:0.86,
   notKu:'Okyanûs. Behra herî mezin.',
   her:["The ocean is blue.", "Fish live in the ocean."],
   herKu:['Okyanûs şîn e.', 'Masî di okyanûsê de dijîn.'], emoji:'🌊'),

  (id:'en_child_a2_179', en:'lake', ku:'gol', ipa:'/leɪk/', pos:'noun',
   form:null, kat:'xweza', zor:0.80,
   notKu:'Gol. Kompa avê ya piçûk.',
   her:["The lake is quiet.", "I swim in the lake."],
   herKu:['Gol bêdeng e.', 'Ez di golê de avjeniyê dikim.'], emoji:'🏞️'),

  (id:'en_child_a2_180', en:'mountain', ku:'çiya', ipa:'/ˈmaʊntən/', pos:'noun',
   form:null, kat:'xweza', zor:0.83,
   notKu:'Çiya. Zemîna bilind a xwezayê.',
   her:["The mountain is high.", "We climb the mountain."],
   herKu:['Çiya bilind e.', 'Em hildikişin çiyê.'], emoji:'⛰️'),

  (id:'en_child_a2_181', en:'hill', ku:'gir', ipa:'/hɪl/', pos:'noun',
   form:null, kat:'xweza', zor:0.80,
   notKu:'Gir. Zemîna bilind a piçûk.',
   her:["The hill is green.", "I walk up the hill."],
   herKu:['Gir kesk e.', 'Ez bi girê diçim jor.'], emoji:'🏞️'),

  (id:'en_child_a2_182', en:'cliff', ku:'zinar', ipa:'/klɪf/', pos:'noun',
   form:null, kat:'xweza', zor:0.85,
   notKu:'Zinar. Zemîna berza ya rast.',
   her:["The cliff is high.", "Birds fly over the cliff."],
   herKu:['Zinar bilind e.', 'Çûk li ser zinarê difirin.'], emoji:'🏔️'),

  (id:'en_child_a2_183', en:'cave', ku:'şkeft', ipa:'/keɪv/', pos:'noun',
   form:null, kat:'xweza', zor:0.83,
   notKu:'Şkeft. Qula xwezayî di çiyê de.',
   her:["The cave is dark.", "Bats live in caves."],
   herKu:['Şkeft tarî ye.', 'Şevşevk di şkeftan de dijîn.'], emoji:'🕳️'),

  (id:'en_child_a2_184', en:'valley', ku:'newal', ipa:'/ˈvæli/', pos:'noun',
   form:null, kat:'xweza', zor:0.84,
   notKu:'Newal. Navbera du çiyan.',
   her:["The valley is green.", "A river flows in the valley."],
   herKu:['Newal kesk e.', 'Çem di newalê de diherike.'], emoji:'🏞️'),

  (id:'en_child_a2_185', en:'field', ku:'zevî', ipa:'/fiːld/', pos:'noun',
   form:null, kat:'xweza', zor:0.81,
   notKu:'Zevî. Qada çandiniyê ya vala.',
   her:["The field is wide.", "Cows graze in the field."],
   herKu:['Zevî fireh e.', 'Çêlek di zeviyê de dicerin.'], emoji:'🌾'),

  (id:'en_child_a2_186', en:'farm', ku:'çandinî', ipa:'/fɑːm/', pos:'noun',
   form:null, kat:'xweza', zor:0.82,
   notKu:'Çandinî. Cihê heywanan û çandinê.',
   her:["The farm is big.", "Animals live on the farm."],
   herKu:['Çandinî mezin e.', 'Heywan li çandiniyê dijîn.'], emoji:'🚜'),

  (id:'en_child_a2_187', en:'jungle', ku:'daristana tropîkal', ipa:'/ˈdʒʌŋɡl/', pos:'noun',
   form:null, kat:'xweza', zor:0.89,
   notKu:'Daristana tropîkal. Daristanek germ û şil.',
   her:["The jungle is hot.", "Tigers live in the jungle."],
   herKu:['Daristana tropîkal germ e.', 'Piling di daristanê de dijîn.'], emoji:'🌴'),

  (id:'en_child_a2_188', en:'desert', ku:'çol', ipa:'/ˈdezət/', pos:'noun',
   form:null, kat:'xweza', zor:0.83,
   notKu:'Çol. Cihê zuwa yê qûmî.',
   her:["The desert is hot.", "Camels live in the desert."],
   herKu:['Çol germ e.', 'Deve di çolê de dijîn.'], emoji:'🏜️'),

  (id:'en_child_a2_189', en:'ice', ku:'cemed', ipa:'/aɪs/', pos:'noun',
   form:null, kat:'xweza', zor:0.80,
   notKu:'Cemed. Ava hişkbûyî.',
   her:["The ice is cold.", "I like ice in water."],
   herKu:['Cemed sar e.', 'Ez ji cemedê di avê de hez dikim.'], emoji:'🧊'),

  (id:'en_child_a2_190', en:'sand', ku:'qûm', ipa:'/sænd/', pos:'noun',
   form:null, kat:'xweza', zor:0.80,
   notKu:'Qûm. Qirt-qirtên piçûk ên behrê.',
   her:["The sand is hot.", "I play with sand."],
   herKu:['Qûm germ e.', 'Ez bi qûmê dilîzim.'], emoji:'🏖️'),

  (id:'en_child_a2_191', en:'stone', ku:'kevir', ipa:'/stəʊn/', pos:'noun',
   form:null, kat:'xweza', zor:0.81,
   notKu:'Kevir. Pariyê hişk ê erdê.',
   her:["The stone is heavy.", "I throw a stone."],
   herKu:['Kevir giran e.', 'Ez kevirekî diavêjim.'], emoji:'🪨'),

  (id:'en_child_a2_192', en:'rock', ku:'tahş', ipa:'/rɒk/', pos:'noun',
   form:null, kat:'xweza', zor:0.80,
   notKu:'Tahş. Kevirê mezin û hişk.',
   her:["The rock is big.", "I sit on the rock."],
   herKu:['Tahş mezin e.', 'Ez li ser tahşê rûdinim.'], emoji:'🪨'),

  (id:'en_child_a2_193', en:'leaf', ku:'pel', ipa:'/liːf/', pos:'noun',
   form:null, kat:'xweza', zor:0.80,
   notKu:'Pel. Beşê kesk ê darê.',
   her:["The leaf is green.", "Leaves fall in autumn."],
   herKu:['Pel kesk e.', 'Pel di payîzê de dikevin.'], emoji:'🍃'),

  (id:'en_child_a2_194', en:'branch', ku:'çiq', ipa:'/brɑːntʃ/', pos:'noun',
   form:null, kat:'xweza', zor:0.82,
   notKu:'Çiq. Beşê darê yê pelgirtî.',
   her:["The branch is long.", "Birds sit on branches."],
   herKu:['Çiq dirêj e.', 'Çûk li ser çiqan rûdinin.'], emoji:'🌿'),

  (id:'en_child_a2_195', en:'root', ku:'reh', ipa:'/ruːt/', pos:'noun',
   form:null, kat:'xweza', zor:0.82,
   notKu:'Reh. Beşê binerdê yê darê.',
   her:["The root is strong.", "Roots grow down."],
   herKu:['Reh bihêz e.', 'Reh ber bi jêr şîn dibin.'], emoji:'🌱'),

  (id:'en_child_a2_196', en:'seed', ku:'tov', ipa:'/siːd/', pos:'noun',
   form:null, kat:'xweza', zor:0.81,
   notKu:'Tov. Tiştê ku lê dar şîn dibe.',
   her:["A seed grows.", "I plant a seed."],
   herKu:['Tov şîn dibe.', 'Ez tovekî diçînim.'], emoji:'🌰'),

  (id:'en_child_a2_197', en:'flower', ku:'kulîlk', ipa:'/ˈflaʊə/', pos:'noun',
   form:null, kat:'xweza', zor:0.80,
   notKu:'Kulîlk. Beşê rengîn ê riwekê.',
   her:["The flower is pretty.", "Flowers grow in spring."],
   herKu:['Kulîlk xweşik e.', 'Kulîlk di biharê de şîn dibin.'], emoji:'🌸'),

  (id:'en_child_a2_198', en:'grass', ku:'giha', ipa:'/ɡrɑːs/', pos:'noun',
   form:null, kat:'xweza', zor:0.81,
   notKu:'Giha. Riwekê kesk ê kurt ê erdê.',
   her:["The grass is green.", "I sit on the grass."],
   herKu:['Giha kesk e.', 'Ez li ser gihayê rûdinim.'], emoji:'🌱'),

  (id:'en_child_a2_199', en:'mud', ku:'heri', ipa:'/mʌd/', pos:'noun',
   form:null, kat:'xweza', zor:0.82,
   notKu:'Heri. Axa şil a qirêj.',
   her:["The mud is wet.", "I step in mud."],
   herKu:['Heri şil e.', 'Ez di heriyê de digerim.'], emoji:'💩'),

  (id:'en_child_a2_200', en:'puddle', ku:'golika avê', ipa:'/ˈpʌdl/', pos:'noun',
   form:null, kat:'xweza', zor:0.88,
   notKu:'Golika avê. Ava piçûk a piştî baranê.',
   her:["The puddle is small.", "I jump in the puddle."],
   herKu:['Golika avê piçûk e.', 'Ez di golikê de bazdidim.'], emoji:'💧'),

  (id:'en_child_a2_201', en:'jump', ku:'bazdan', ipa:'/dʒʌmp/', pos:'verb',
   form:null, kat:'leker', zor:0.80,
   notKu:'Bazdan. Livîna bi ser de.',
   her:["I jump high.", "The dog jumps."],
   herKu:['Ez bilind bazdidim.', 'Kûçik bazdide.'], emoji:'🤸'),

  (id:'en_child_a2_202', en:'hop', ku:'pengekî bazdan', ipa:'/hɒp/', pos:'verb',
   form:null, kat:'leker', zor:0.85,
   notKu:'Pengekî bazdan. Bazdana piçûk.',
   her:["The rabbit hops.", "I hop on one foot."],
   herKu:['Kêvroşk pengekî bazdide.', 'Ez li ser pêyekî bazdidim.'], emoji:'🐇'),

  (id:'en_child_a2_203', en:'skip', ku:'hişkehişk', ipa:'/skɪp/', pos:'verb',
   form:null, kat:'leker', zor:0.84,
   notKu:'Hişkehişk. Bazdan û bezîn bi hev re.',
   her:["I skip to school.", "Kids skip in the park."],
   herKu:['Ez hişkehişk diçim dibistanê.', 'Zarok di park de hişkehişk dikin.'], emoji:'🏃'),

  (id:'en_child_a2_204', en:'run', ku:'bezîn', ipa:'/rʌn/', pos:'verb',
   form:null, kat:'leker', zor:0.78,
   notKu:'Bezîn. Meşa bi lez.',
   her:["I run fast.", "The boy runs."],
   herKu:['Ez zû dibezim.', 'Kur dibeze.'], emoji:'🏃'),

  (id:'en_child_a2_205', en:'walk', ku:'meşîn', ipa:'/wɔːk/', pos:'verb',
   form:null, kat:'leker', zor:0.78,
   notKu:'Meşîn. Çûyîn bi pêyan.',
   her:["I walk to school.", "We walk every day."],
   herKu:['Ez bi pêyan diçim dibistanê.', 'Em her roj dimeşin.'], emoji:'🚶'),

  (id:'en_child_a2_206', en:'climb', ku:'hilkişîn', ipa:'/klaɪm/', pos:'verb',
   form:null, kat:'leker', zor:0.83,
   notKu:'Hilkişîn. Ber bi jor çûyîn.',
   her:["I climb the tree.", "Cats climb fast."],
   herKu:['Ez hildikişim darê.', 'Pisîk zû hildikişin.'], emoji:'🧗'),

  (id:'en_child_a2_207', en:'crawl', ku:'xwişîn', ipa:'/krɔːl/', pos:'verb',
   form:null, kat:'leker', zor:0.85,
   notKu:'Xwişîn. Meşa li ser dest û çokan.',
   her:["The baby crawls.", "I crawl under the bed."],
   herKu:['Pitik dixwişe.', 'Ez di bin nivînê de dixwişim.'], emoji:'🐣'),

  (id:'en_child_a2_208', en:'fly', ku:'firîn', ipa:'/flaɪ/', pos:'verb',
   form:null, kat:'leker', zor:0.80,
   notKu:'Firîn. Di hewayê de çûyîn.',
   her:["Birds fly high.", "Planes fly fast."],
   herKu:['Çûk bilind difirin.', 'Balafir zû difirin.'], emoji:'✈️'),

  (id:'en_child_a2_209', en:'swim', ku:'avjenî kirin', ipa:'/swɪm/', pos:'verb',
   form:null, kat:'leker', zor:0.82,
   notKu:'Avjenî kirin. Hereket di avê de.',
   her:["I swim in summer.", "Fish swim in water."],
   herKu:['Ez di havînê de avjeniyê dikim.', 'Masî di avê de avjeniyê dikin.'], emoji:'🏊'),

  (id:'en_child_a2_210', en:'dive', ku:'daleqandin', ipa:'/daɪv/', pos:'verb',
   form:null, kat:'leker', zor:0.84,
   notKu:'Daleqandin. Daketina nav avê ji jor.',
   her:["I dive into water.", "She dives well."],
   herKu:['Ez daleqîm nav avê.', 'Ew baş daleqî.'], emoji:'🏊'),

  (id:'en_child_a2_211', en:'ride', ku:'siwarbûn', ipa:'/raɪd/', pos:'verb',
   form:null, kat:'leker', zor:0.82,
   notKu:'Siwarbûn. Rûniştina li ser duçerxê.',
   her:["I ride a bike.", "He rides a horse."],
   herKu:['Ez siwarî duçerxê me.', 'Ew siwarî hespê ye.'], emoji:'🚴'),

  (id:'en_child_a2_212', en:'drive', ku:'ajotin', ipa:'/draɪv/', pos:'verb',
   form:null, kat:'leker', zor:0.82,
   notKu:'Ajotin. Otomobîl bir dikî.',
   her:["Dad drives the car.", "She drives slowly."],
   herKu:['Bav otomobîlê dajo.', 'Ew hêdî dajo.'], emoji:'🚗'),

  (id:'en_child_a2_213', en:'push', ku:'pêlkirin', ipa:'/pʊʃ/', pos:'verb',
   form:null, kat:'leker', zor:0.82,
   notKu:'Pêlkirin. Ber bi pêş zorê.',
   her:["I push the door.", "Push the button."],
   herKu:['Ez pêl deriyê dikim.', 'Pêl bişkoka bike.'], emoji:'👊'),

  (id:'en_child_a2_214', en:'pull', ku:'kişandin', ipa:'/pʊl/', pos:'verb',
   form:null, kat:'leker', zor:0.82,
   notKu:'Kişandin. Ber bi xwe de zorê.',
   her:["I pull the rope.", "Pull the door."],
   herKu:['Ez werîsê dikişînim.', 'Deriyê bikişîne.'], emoji:'💪'),

  (id:'en_child_a2_215', en:'throw', ku:'avêtin', ipa:'/θrəʊ/', pos:'verb',
   form:null, kat:'leker', zor:0.82,
   notKu:'Avêtin. Tiştekê bi destê şandin.',
   her:["I throw the ball.", "He throws far."],
   herKu:['Ez bilûrê diavêjim.', 'Ew dûr diavêje.'], emoji:'🏐'),

  (id:'en_child_a2_216', en:'catch', ku:'girtin', ipa:'/kætʃ/', pos:'verb',
   form:null, kat:'leker', zor:0.81,
   notKu:'Girtin. Tiştekê bi destê bistînî.',
   her:["I catch the ball.", "She catches fast."],
   herKu:['Ez bilûrê digirim.', 'Ew zû digire.'], emoji:'🥎'),

  (id:'en_child_a2_217', en:'kick', ku:'lêxistin', ipa:'/kɪk/', pos:'verb',
   form:null, kat:'leker', zor:0.81,
   notKu:'Lêxistin. Bi lingê lê xistin.',
   her:["I kick the ball.", "He kicks hard."],
   herKu:['Ez bilûrê lê dixim.', 'Ew xurt lê dixe.'], emoji:'⚽'),

  (id:'en_child_a2_218', en:'hit', ku:'lêdan', ipa:'/hɪt/', pos:'verb',
   form:null, kat:'leker', zor:0.79,
   notKu:'Lêdan. Bi destê lê dan.',
   her:["I hit the ball.", "Don't hit me."],
   herKu:['Ez bilûrê lê didim.', 'Li min nede.'], emoji:'🎾'),

  (id:'en_child_a2_219', en:'hug', ku:'hembêzkirin', ipa:'/hʌɡ/', pos:'verb',
   form:null, kat:'leker', zor:0.84,
   notKu:'Hembêzkirin. Bi baskê zû girtin.',
   her:["I hug my mom.", "Hug your friend."],
   herKu:['Ez dayika xwe hembêz dikim.', 'Hevalê xwe hembêz bike.'], emoji:'🤗'),

  (id:'en_child_a2_220', en:'kiss', ku:'ramûsan', ipa:'/kɪs/', pos:'verb',
   form:null, kat:'leker', zor:0.82,
   notKu:'Ramûsan. Bi devê dayîn.',
   her:["I kiss my mom.", "Kiss the baby."],
   herKu:['Ez dayika xwe diramûsim.', 'Pitik biramûse.'], emoji:'😘'),

  (id:'en_child_a2_221', en:'wave', ku:'destbêjtin', ipa:'/weɪv/', pos:'verb',
   form:null, kat:'leker', zor:0.85,
   notKu:'Destbêjtin. Destê hejandin.',
   her:["I wave hello.", "She waves back."],
   herKu:['Ez silav didim bi destê.', 'Ew bersiv bi destê dide.'], emoji:'👋'),

  (id:'en_child_a2_222', en:'point', ku:'pêçek kirin', ipa:'/pɔɪnt/', pos:'verb',
   form:null, kat:'leker', zor:0.83,
   notKu:'Pêçek kirin. Bi tiliyê nîşan dayîn.',
   her:["I point at the bird.", "Don't point at people."],
   herKu:['Ez tilîyê xwe li çûkê digirim.', 'Tilîyê xwe li mirovan negire.'], emoji:'👉'),

  (id:'en_child_a2_223', en:'smile', ku:'bişirîn', ipa:'/smaɪl/', pos:'verb',
   form:null, kat:'leker', zor:0.82,
   notKu:'Bişirîn. Kêfxweşî bi devê.',
   her:["I smile at mom.", "She smiles a lot."],
   herKu:['Ez li dayikê xwe dibişirim.', 'Ew pir dibişire.'], emoji:'😊'),

  (id:'en_child_a2_224', en:'laugh', ku:'kenîn', ipa:'/lɑːf/', pos:'verb',
   form:null, kat:'leker', zor:0.82,
   notKu:'Kenîn. Bi dengî kêfxweş bûyîn.',
   her:["I laugh loudly.", "We laugh together."],
   herKu:['Ez bi dengî dikenim.', 'Em bi hev re dikenin.'], emoji:'😂'),

  (id:'en_child_a2_225', en:'cry', ku:'girîn', ipa:'/kraɪ/', pos:'verb',
   form:null, kat:'leker', zor:0.81,
   notKu:'Girîn. Derxistina hêsiran.',
   her:["The baby cries.", "Don't cry."],
   herKu:['Pitik digirî.', 'Negirî.'], emoji:'😢'),

  (id:'en_child_a2_226', en:'weather', ku:'hewa', ipa:'/ˈweðə/', pos:'noun',
   form:null, kat:'hewa', zor:0.83,
   notKu:'Hewa. Rewşa asmanê.',
   her:["The weather is nice.", "Check the weather."],
   herKu:['Hewa xweş e.', 'Li hewayê binêre.'], emoji:'🌤️'),

  (id:'en_child_a2_227', en:'storm', ku:'bahoz', ipa:'/stɔːm/', pos:'noun',
   form:null, kat:'hewa', zor:0.82,
   notKu:'Bahoz. Bayê bihêz û baranê.',
   her:["The storm is strong.", "A storm is coming."],
   herKu:['Bahoz bihêz e.', 'Bahozek tê.'], emoji:'⛈️'),

  (id:'en_child_a2_228', en:'lightning', ku:'birûsk', ipa:'/ˈlaɪtnɪŋ/', pos:'noun',
   form:null, kat:'hewa', zor:0.85,
   notKu:'Birûsk. Ronahiya bihêz a asmanê.',
   her:["Lightning is bright.", "I see lightning."],
   herKu:['Birûsk geş e.', 'Ez birûskê dibînim.'], emoji:'⚡'),

  (id:'en_child_a2_229', en:'thunder', ku:'birusk', ipa:'/ˈθʌndə/', pos:'noun',
   form:null, kat:'hewa', zor:0.84,
   notKu:'Birusk. Dengê bilind ê asmanê.',
   her:["Thunder is loud.", "I hear thunder."],
   herKu:['Birusk dengdar e.', 'Ez biruskê dibihîzim.'], emoji:'🌩️'),

  (id:'en_child_a2_230', en:'rainbow', ku:'keskesor', ipa:'/ˈreɪnbəʊ/', pos:'noun',
   form:null, kat:'hewa', zor:0.84,
   notKu:'Keskesor. Rengên asmanê piştî baranê.',
   her:["The rainbow is pretty.", "I see a rainbow."],
   herKu:['Keskesor xweşik e.', 'Ez keskesorekê dibînim.'], emoji:'🌈'),

  (id:'en_child_a2_231', en:'fog', ku:'mij', ipa:'/fɒɡ/', pos:'noun',
   form:null, kat:'hewa', zor:0.81,
   notKu:'Mij. Ewrê nêzî erdê.',
   her:["The fog is thick.", "I can't see through fog."],
   herKu:['Mij zexm e.', 'Ez di nav mijê de nabînim.'], emoji:'🌫️'),

  (id:'en_child_a2_232', en:'mist', ku:'dûman', ipa:'/mɪst/', pos:'noun',
   form:null, kat:'hewa', zor:0.83,
   notKu:'Dûman. Mijeka sivik.',
   her:["The mist is light.", "Morning mist is pretty."],
   herKu:['Dûman sivik e.', 'Dûmana sibehê xweşik e.'], emoji:'🌁'),

  (id:'en_child_a2_233', en:'frost', ku:'qerês', ipa:'/frɒst/', pos:'noun',
   form:null, kat:'hewa', zor:0.84,
   notKu:'Qerês. Cemeda sibehê li ser giha.',
   her:["The frost is white.", "Frost covers the grass."],
   herKu:['Qerês spî ye.', 'Qerês giha dipêçe.'], emoji:'❄️'),

  (id:'en_child_a2_234', en:'sunshine', ku:'tava rojê', ipa:'/ˈsʌnʃaɪn/', pos:'noun',
   form:null, kat:'hewa', zor:0.86,
   notKu:'Tava rojê. Ronahiya rojê ya germ.',
   her:["Sunshine is warm.", "I love sunshine."],
   herKu:['Tava rojê germ e.', 'Ez ji tava rojê hez dikim.'], emoji:'☀️'),

  (id:'en_child_a2_235', en:'breeze', ku:'bayê nerm', ipa:'/briːz/', pos:'noun',
   form:null, kat:'hewa', zor:0.86,
   notKu:'Bayê nerm. Bayê hêdî yê xweş.',
   her:["The breeze is cool.", "I feel the breeze."],
   herKu:['Bayê nerm sar e.', 'Ez bayê nerm hîs dikim.'], emoji:'🍃'),

  (id:'en_child_a2_236', en:'wind', ku:'ba', ipa:'/wɪnd/', pos:'noun',
   form:null, kat:'hewa', zor:0.79,
   notKu:'Ba. Herîkîna hewayê.',
   her:["The wind is strong.", "I feel the wind."],
   herKu:['Ba bihêz e.', 'Ez bayê hîs dikim.'], emoji:'💨'),

  (id:'en_child_a2_237', en:'today', ku:'îro', ipa:'/təˈdeɪ/', pos:'adv',
   form:null, kat:'hewa', zor:0.80,
   notKu:'Îro. Roja niha.',
   her:["Today is sunny.", "I play today."],
   herKu:['Îro roj e.', 'Ez îro dilîzim.'], emoji:'📅'),

  (id:'en_child_a2_238', en:'tomorrow', ku:'sibe', ipa:'/təˈmɒrəʊ/', pos:'adv',
   form:null, kat:'hewa', zor:0.83,
   notKu:'Sibe. Roja piştî îro.',
   her:["Tomorrow is Saturday.", "See you tomorrow."],
   herKu:['Sibe Şemî ye.', 'Sibe dîsa bibînim.'], emoji:'📅'),

  (id:'en_child_a2_239', en:'yesterday', ku:'duh', ipa:'/ˈjestədeɪ/', pos:'adv',
   form:null, kat:'hewa', zor:0.84,
   notKu:'Duh. Roja beriya îro.',
   her:["Yesterday was fun.", "I played yesterday."],
   herKu:['Duh xweş bû.', 'Min duh lîst.'], emoji:'📅'),

  (id:'en_child_a2_240', en:'morning', ku:'sibe', ipa:'/ˈmɔːnɪŋ/', pos:'noun',
   form:null, kat:'hewa', zor:0.81,
   notKu:'Sibe. Destpêka rojê.',
   her:["Good morning!", "I wake up in the morning."],
   herKu:['Sibeya baş!', 'Ez sibehê şiyar dibim.'], emoji:'🌅'),

  (id:'en_child_a2_241', en:'afternoon', ku:'piştî nîro', ipa:'/ˌɑːftəˈnuːn/', pos:'noun',
   form:null, kat:'hewa', zor:0.87,
   notKu:'Piştî nîro. Pişt demjimêra 12.',
   her:["Good afternoon!", "I play in the afternoon."],
   herKu:['Piştî nîroya baş!', 'Ez piştî nîroyê dilîzim.'], emoji:'🌇'),

  (id:'en_child_a2_242', en:'evening', ku:'êvar', ipa:'/ˈiːvnɪŋ/', pos:'noun',
   form:null, kat:'hewa', zor:0.82,
   notKu:'Êvar. Beriya şevê.',
   her:["Good evening!", "We eat in the evening."],
   herKu:['Êvara baş!', 'Em êvarê dixwin.'], emoji:'🌆'),

  (id:'en_child_a2_243', en:'weekend', ku:'dawiya heftê', ipa:'/ˈwiːkend/', pos:'noun',
   form:null, kat:'hewa', zor:0.86,
   notKu:'Dawiya heftê. Şemî û Yekşem.',
   her:["The weekend is fun.", "I rest on the weekend."],
   herKu:['Dawiya heftê xweş e.', 'Ez di dawiya heftê de bêhnê vedidim.'], emoji:'📅'),

  (id:'en_child_a2_244', en:'season', ku:'demsal', ipa:'/ˈsiːzn/', pos:'noun',
   form:null, kat:'hewa', zor:0.83,
   notKu:'Demsal. Dewra salê.',
   her:["Summer is my season.", "There are four seasons."],
   herKu:['Havîn demsala min e.', 'Çar demsal hene.'], emoji:'🍂'),

  (id:'en_child_a2_245', en:'month', ku:'meh', ipa:'/mʌnθ/', pos:'noun',
   form:null, kat:'hewa', zor:0.81,
   notKu:'Meh. Dewra 30 rojan.',
   her:["This month is May.", "The month has 30 days."],
   herKu:['Vê mehê Gulan e.', 'Meh 30 rojan heye.'], emoji:'📅'),

  (id:'en_child_a2_246', en:'year', ku:'sal', ipa:'/jɪə/', pos:'noun',
   form:null, kat:'hewa', zor:0.80,
   notKu:'Sal. Dewra 12 mehan.',
   her:["This year is new.", "The year has 12 months."],
   herKu:['Ev sala nû ye.', 'Sal 12 meh heye.'], emoji:'📆'),

  (id:'en_child_a2_247', en:'happy', ku:'kêfxweş', ipa:'/ˈhæpi/', pos:'adj',
   form:null, kat:'his', zor:0.79,
   notKu:'Kêfxweş. Dema dilê te şa dibe.',
   her:["I am happy.", "She feels happy."],
   herKu:['Ez kêfxweş im.', 'Ew kêfxweş e.'], emoji:'😊'),

  (id:'en_child_a2_248', en:'sad', ku:'xemgîn', ipa:'/sæd/', pos:'adj',
   form:null, kat:'his', zor:0.80,
   notKu:'Xemgîn. Dema dilê te xemgîn e.',
   her:["I am sad.", "He looks sad."],
   herKu:['Ez xemgîn im.', 'Ew xemgîn xuya dike.'], emoji:'😢'),

  (id:'en_child_a2_249', en:'angry', ku:'hêrs', ipa:'/ˈæŋɡri/', pos:'adj',
   form:null, kat:'his', zor:0.82,
   notKu:'Hêrs. Dema ku tu hêrs bûyî.',
   her:["I am angry.", "Don't be angry."],
   herKu:['Ez hêrs im.', 'Hêrs nebe.'], emoji:'😠'),

  (id:'en_child_a2_250', en:'scared', ku:'tirsbar', ipa:'/skeəd/', pos:'adj',
   form:null, kat:'his', zor:0.84,
   notKu:'Tirsbar. Dema ku tu ditirsî.',
   her:["I am scared.", "The cat is scared."],
   herKu:['Ez tirsbar im.', 'Pisîk tirsbar e.'], emoji:'😨'),

  (id:'en_child_a2_251', en:'surprised', ku:'heyirî', ipa:'/səˈpraɪzd/', pos:'adj',
   form:null, kat:'his', zor:0.87,
   notKu:'Heyirî. Dema ku tu şaş dimînî.',
   her:["I am surprised.", "She looks surprised."],
   herKu:['Ez heyirî me.', 'Ew heyirî xuya dike.'], emoji:'😲'),

  (id:'en_child_a2_252', en:'excited', ku:'heyecanî', ipa:'/ɪkˈsaɪtɪd/', pos:'adj',
   form:null, kat:'his', zor:0.87,
   notKu:'Heyecanî. Bi coş û heyecanî.',
   her:["I am excited.", "The kids are excited."],
   herKu:['Ez heyecanî me.', 'Zarok heyecanî ne.'], emoji:'🤩'),

  (id:'en_child_a2_253', en:'bored', ku:'bêzar', ipa:'/bɔːd/', pos:'adj',
   form:null, kat:'his', zor:0.83,
   notKu:'Bêzar. Dema ku kêfa te tuneye.',
   her:["I am bored.", "The boy is bored."],
   herKu:['Ez bêzar im.', 'Kur bêzar e.'], emoji:'😒'),

  (id:'en_child_a2_254', en:'tired', ku:'westiyayî', ipa:'/ˈtaɪəd/', pos:'adj',
   form:null, kat:'his', zor:0.83,
   notKu:'Westiyayî. Dema ku tu westî.',
   her:["I am tired.", "She is tired."],
   herKu:['Ez westiyayî me.', 'Ew westiyayî ye.'], emoji:'😴'),

  (id:'en_child_a2_255', en:'sleepy', ku:'xewalî', ipa:'/ˈsliːpi/', pos:'adj',
   form:null, kat:'his', zor:0.84,
   notKu:'Xewalî. Dema ku tu dixwazî bi razê.',
   her:["I am sleepy.", "The cat is sleepy."],
   herKu:['Ez xewalî me.', 'Pisîk xewalî ye.'], emoji:'😪'),

  (id:'en_child_a2_256', en:'hungry', ku:'birçî', ipa:'/ˈhʌŋɡri/', pos:'adj',
   form:null, kat:'his', zor:0.80,
   notKu:'Birçî. Dema ku tu dixwazî bixwî.',
   her:["I am hungry.", "The dog is hungry."],
   herKu:['Ez birçî me.', 'Kûçik birçî ye.'], emoji:'🍽️'),

  (id:'en_child_a2_257', en:'thirsty', ku:'tî', ipa:'/ˈθɜːsti/', pos:'adj',
   form:null, kat:'his', zor:0.83,
   notKu:'Tî. Dema ku tu dixwazî av bivexwî.',
   her:["I am thirsty.", "The man is thirsty."],
   herKu:['Ez tî me.', 'Mêr tî ye.'], emoji:'🥤'),

  (id:'en_child_a2_258', en:'lonely', ku:'bitenê', ipa:'/ˈləʊnli/', pos:'adj',
   form:null, kat:'his', zor:0.86,
   notKu:'Bitenê. Dema ku tu bi tenê yî.',
   her:["I am lonely.", "She feels lonely."],
   herKu:['Ez bitenê me.', 'Ew bitenê hîs dike.'], emoji:'😔'),

  (id:'en_child_a2_259', en:'brave', ku:'mêrxas', ipa:'/breɪv/', pos:'adj',
   form:null, kat:'his', zor:0.83,
   notKu:'Mêrxas. Bê tirs.',
   her:["The boy is brave.", "Be brave!"],
   herKu:['Kur mêrxas e.', 'Mêrxas be!'], emoji:'🦁'),

  (id:'en_child_a2_260', en:'shy', ku:'fedîker', ipa:'/ʃaɪ/', pos:'adj',
   form:null, kat:'his', zor:0.83,
   notKu:'Fedîker. Kesê ku fedî dike.',
   her:["The girl is shy.", "Don't be shy."],
   herKu:['Keçik fedîker e.', 'Fedî neke.'], emoji:'😳'),

  (id:'en_child_a2_261', en:'jealous', ku:'çavbirçî', ipa:'/ˈdʒeləs/', pos:'adj',
   form:null, kat:'his', zor:0.86,
   notKu:'Çavbirçî. Dema ku tu heset dike.',
   her:["Don't be jealous.", "He is jealous."],
   herKu:['Çavbirçî nebe.', 'Ew çavbirçî ye.'], emoji:'😒'),

  (id:'en_child_a2_262', en:'proud', ku:'serbilind', ipa:'/praʊd/', pos:'adj',
   form:null, kat:'his', zor:0.85,
   notKu:'Serbilind. Dema ku tu bi xwe şanazî dikî.',
   her:["I am proud of you.", "Mom is proud."],
   herKu:['Ez pê serbilind im ji te.', 'Dayik serbilind e.'], emoji:'😌'),

  (id:'en_child_a2_263', en:'calm', ku:'aram', ipa:'/kɑːm/', pos:'adj',
   form:null, kat:'his', zor:0.82,
   notKu:'Aram. Bêdeng û hêdî.',
   her:["The sea is calm.", "She is calm."],
   herKu:['Behr aram e.', 'Ew aram e.'], emoji:'😌'),

  (id:'en_child_a2_264', en:'worried', ku:'xemkêş', ipa:'/ˈwʌrid/', pos:'adj',
   form:null, kat:'his', zor:0.86,
   notKu:'Xemkêş. Dema ku tu xem dikişîne.',
   her:["I am worried.", "Mom looks worried."],
   herKu:['Ez xemkêş im.', 'Dayik xemkêş xuya dike.'], emoji:'😟'),

  (id:'en_child_a2_265', en:'confused', ku:'tevlihev', ipa:'/kənˈfjuːzd/', pos:'adj',
   form:null, kat:'his', zor:0.87,
   notKu:'Tevlihev. Dema ku tu fam nakî.',
   her:["I am confused.", "He feels confused."],
   herKu:['Ez tevlihev im.', 'Ew tevlihev e.'], emoji:'😕'),

  (id:'en_child_a2_266', en:'play', ku:'lîstin', ipa:'/pleɪ/', pos:'verb',
   form:null, kat:'leyîstik', zor:0.78,
   notKu:'Lîstin. Bi lîstikan mijûl bûyîn.',
   her:["I play with my friend.", "Kids play all day."],
   herKu:['Ez bi hevalê xwe re dilîzim.', 'Zarok tevahiya rojê dilîzin.'], emoji:'🎮'),

  (id:'en_child_a2_267', en:'game', ku:'lîstik', ipa:'/ɡeɪm/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.80,
   notKu:'Lîstik. Tiştê ku tu bi wê dilîzî.',
   her:["The game is fun.", "I play a game."],
   herKu:['Lîstik xweş e.', 'Ez lîstikekê dilîzim.'], emoji:'🎲'),

  (id:'en_child_a2_268', en:'toy', ku:'leyîstik', ipa:'/tɔɪ/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.80,
   notKu:'Leyîstik. Tiştê ku zarok pê dilîzin.',
   her:["My toy is new.", "I love my toys."],
   herKu:['Leyîstika min nû ye.', 'Ez ji leyîstikên xwe hez dikim.'], emoji:'🧸'),

  (id:'en_child_a2_269', en:'puzzle', ku:'kîtekît', ipa:'/ˈpʌzl/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.85,
   notKu:'Kîtekît. Lîstika parçeyên piçûk.',
   her:["The puzzle is hard.", "I do a puzzle."],
   herKu:['Kîtekît zehmet e.', 'Ez kîtekîtekê dikim.'], emoji:'🧩'),

  (id:'en_child_a2_270', en:'doll', ku:'lûtke', ipa:'/dɒl/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.81,
   notKu:'Lûtke. Leyîstika bi şiklê mirovê.',
   her:["My doll is pretty.", "I play with my doll."],
   herKu:['Lûtkeya min xweşik e.', 'Ez bi lûtkeya xwe dilîzim.'], emoji:'🪆'),

  (id:'en_child_a2_271', en:'ball', ku:'bilûr', ipa:'/bɔːl/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.79,
   notKu:'Bilûr. Tişta gilover ji bo lîstikê.',
   her:["The ball is round.", "I kick the ball."],
   herKu:['Bilûr gilover e.', 'Ez lêdixim bilûrê.'], emoji:'⚽'),

  (id:'en_child_a2_272', en:'kite', ku:'bayokê', ipa:'/kaɪt/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.82,
   notKu:'Bayokê. Leyîstika ku li hewayê difire.',
   her:["My kite flies high.", "I love my kite."],
   herKu:['Bayokeya min bilind difire.', 'Ez ji bayokeya xwe hez dikim.'], emoji:'🪁'),

  (id:'en_child_a2_273', en:'bike', ku:'duçerx', ipa:'/baɪk/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.82,
   notKu:'Duçerx. Amûra du çerxî.',
   her:["My bike is fast.", "I ride my bike."],
   herKu:['Duçerxa min zû ye.', 'Ez li duçerxê siwar dibim.'], emoji:'🚲'),

  (id:'en_child_a2_274', en:'scooter', ku:'îskûter', ipa:'/ˈskuːtə/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.85,
   notKu:'Îskûter. Leyîstika du çerxî.',
   her:["My scooter is red.", "I ride my scooter."],
   herKu:['Îskûtera min sor e.', 'Ez li îskûterê siwar dibim.'], emoji:'🛴'),

  (id:'en_child_a2_275', en:'swing', ku:'dolîdang', ipa:'/swɪŋ/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.83,
   notKu:'Dolîdang. Leyîstika ber û pêş.',
   her:["The swing is fun.", "I swing high."],
   herKu:['Dolîdang xweş e.', 'Ez bilind dolîdangê dikim.'], emoji:'🛝'),

  (id:'en_child_a2_276', en:'slide', ku:'şemitok', ipa:'/slaɪd/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.84,
   notKu:'Şemitok. Leyîstika ku pê diherikî.',
   her:["The slide is tall.", "I go down the slide."],
   herKu:['Şemitok bilind e.', 'Ez bi şemitokê jêr tên.'], emoji:'🛝'),

  (id:'en_child_a2_277', en:'sandbox', ku:'kutîka qûmê', ipa:'/ˈsændbɒks/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.88,
   notKu:'Kutîka qûmê. Cihê qûmê ji bo lîstikê.',
   her:["The sandbox is fun.", "Kids play in the sandbox."],
   herKu:['Kutîka qûmê xweş e.', 'Zarok di kutîka qûmê de dilîzin.'], emoji:'🏖️'),

  (id:'en_child_a2_278', en:'pool', ku:'hewz', ipa:'/puːl/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.81,
   notKu:'Hewz. Cihê avjeniyê.',
   her:["The pool is cold.", "I swim in the pool."],
   herKu:['Hewz sar e.', 'Ez di hewzê de avjeniyê dikim.'], emoji:'🏊'),

  (id:'en_child_a2_279', en:'picnic', ku:'pîknîk', ipa:'/ˈpɪknɪk/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.84,
   notKu:'Pîknîk. Xwarina li derve ya bi malbatê.',
   her:["We have a picnic.", "The picnic is fun."],
   herKu:['Em pîknîkek dikin.', 'Pîknîk xweş e.'], emoji:'🧺'),

  (id:'en_child_a2_280', en:'camping', ku:'kampkirin', ipa:'/ˈkæmpɪŋ/', pos:'noun',
   form:null, kat:'leyîstik', zor:0.88,
   notKu:'Kampkirin. Mayîna di xêmayê de.',
   her:["Camping is fun.", "We go camping."],
   herKu:['Kampkirin xweş e.', 'Em diçin kampê.'], emoji:'⛺'),

  (id:'en_child_a2_281', en:'hike', ku:'meş kirin', ipa:'/haɪk/', pos:'verb',
   form:null, kat:'leyîstik', zor:0.82,
   notKu:'Meş kirin. Gera dirêj di xwezayê de.',
   her:["We hike in the mountain.", "I like to hike."],
   herKu:['Em di çiyê de meş dikin.', 'Ez ji meşkirinê hez dikim.'], emoji:'🥾'),

  (id:'en_child_a2_282', en:'dance', ku:'reqas', ipa:'/dɑːns/', pos:'verb',
   form:null, kat:'leyîstik', zor:0.82,
   notKu:'Reqas. Livîn bi muzîkê.',
   her:["I dance to music.", "She dances well."],
   herKu:['Ez bi muzîkê reqas dikim.', 'Ew baş reqas dike.'], emoji:'💃'),

  (id:'en_child_a2_283', en:'sing', ku:'stran gotin', ipa:'/sɪŋ/', pos:'verb',
   form:null, kat:'leyîstik', zor:0.81,
   notKu:'Stran gotin. Gotina stranan.',
   her:["I sing a song.", "She sings loudly."],
   herKu:['Ez stranekê dibêjim.', 'Ew bi deng distirê.'], emoji:'🎤'),

  (id:'en_child_a2_284', en:'draw', ku:'resimkirin', ipa:'/drɔː/', pos:'verb',
   form:null, kat:'leyîstik', zor:0.83,
   notKu:'Resimkirin. Kişandina resman.',
   her:["I draw a cat.", "She draws well."],
   herKu:['Ez resmekî pisîkê dikişînim.', 'Ew baş resm dikişîne.'], emoji:'✏️'),

  (id:'en_child_a2_285', en:'tall', ku:'dirêj', ipa:'/tɔːl/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.78,
   notKu:'Dirêj. Bilind ji ser heta jêr.',
   her:["The boy is tall.", "The tree is tall."],
   herKu:['Kur dirêj e.', 'Dar dirêj e.'], emoji:'📏'),

  (id:'en_child_a2_286', en:'short', ku:'kin', ipa:'/ʃɔːt/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.78,
   notKu:'Kin. Ne dirêj.',
   her:["The girl is short.", "My pencil is short."],
   herKu:['Keçik kin e.', 'Qelema min kin e.'], emoji:'📏'),

  (id:'en_child_a2_287', en:'strong', ku:'bihêz', ipa:'/strɒŋ/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.80,
   notKu:'Bihêz. Xwedî hêz.',
   her:["The man is strong.", "Elephants are strong."],
   herKu:['Mêr bihêz e.', 'Fîl bihêz in.'], emoji:'💪'),

  (id:'en_child_a2_288', en:'weak', ku:'lawaz', ipa:'/wiːk/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.81,
   notKu:'Lawaz. Ne bihêz.',
   her:["I feel weak.", "The baby is weak."],
   herKu:['Ez lawaz hîs dikim.', 'Pitik lawaz e.'], emoji:'🥺'),

  (id:'en_child_a2_289', en:'fast', ku:'zû', ipa:'/fɑːst/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.79,
   notKu:'Zû. Bi lez.',
   her:["The car is fast.", "She runs fast."],
   herKu:['Otomobîl zû ye.', 'Ew zû dibeze.'], emoji:'⚡'),

  (id:'en_child_a2_290', en:'slow', ku:'hêdî', ipa:'/sləʊ/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.79,
   notKu:'Hêdî. Ne zû.',
   her:["The turtle is slow.", "The bus is slow."],
   herKu:['Kûsî hêdî ye.', 'Otobus hêdî ye.'], emoji:'🐢'),

  (id:'en_child_a2_291', en:'loud', ku:'dengdar', ipa:'/laʊd/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.81,
   notKu:'Dengdar. Bi dengekî bilind.',
   her:["The music is loud.", "Don't be loud."],
   herKu:['Muzîk dengdar e.', 'Dengdar nebe.'], emoji:'🔊'),

  (id:'en_child_a2_292', en:'quiet', ku:'bêdeng', ipa:'/ˈkwaɪət/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.83,
   notKu:'Bêdeng. Bê dengê.',
   her:["The room is quiet.", "Please be quiet."],
   herKu:['Ode bêdeng e.', 'Ji kerema xwe bêdeng be.'], emoji:'🤫'),

  (id:'en_child_a2_293', en:'dark', ku:'tarî', ipa:'/dɑːk/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.79,
   notKu:'Tarî. Bê ronahî.',
   her:["The room is dark.", "Night is dark."],
   herKu:['Ode tarî ye.', 'Şev tarî ye.'], emoji:'🌑'),

  (id:'en_child_a2_294', en:'bright', ku:'geş', ipa:'/braɪt/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.82,
   notKu:'Geş. Bi ronahî.',
   her:["The sun is bright.", "The light is bright."],
   herKu:['Roj geş e.', 'Ronahî geş e.'], emoji:'💡'),

  (id:'en_child_a2_295', en:'easy', ku:'hêsan', ipa:'/ˈiːzi/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.79,
   notKu:'Hêsan. Ne zehmet.',
   her:["The lesson is easy.", "Math is easy for me."],
   herKu:['Ders hêsan e.', 'Matematîk ji min re hêsan e.'], emoji:'✅'),

  (id:'en_child_a2_296', en:'hard', ku:'zehmet', ipa:'/hɑːd/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.80,
   notKu:'Zehmet. Ne hêsan.',
   her:["The test is hard.", "This job is hard."],
   herKu:['Tawan zehmet e.', 'Ev kar zehmet e.'], emoji:'😓'),

  (id:'en_child_a2_297', en:'soft', ku:'nerm', ipa:'/sɒft/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.80,
   notKu:'Nerm. Ne hişk.',
   her:["The pillow is soft.", "The cat is soft."],
   herKu:['Balgeh nerm e.', 'Pisîk nerm e.'], emoji:'☁️'),

  (id:'en_child_a2_298', en:'rough', ku:'qerpil', ipa:'/rʌf/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.84,
   notKu:'Qerpil. Ne nerm, ne hemvar.',
   her:["The stone is rough.", "This wood is rough."],
   herKu:['Kevir qerpil e.', 'Ev dar qerpil e.'], emoji:'🪨'),

  (id:'en_child_a2_299', en:'smooth', ku:'hemvar', ipa:'/smuːð/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.85,
   notKu:'Hemvar. Ne qerpil.',
   her:["The glass is smooth.", "Her skin is smooth."],
   herKu:['Cam hemvar e.', 'Çermê wê hemvar e.'], emoji:'✨'),

  (id:'en_child_a2_300', en:'sweet', ku:'şîrîn', ipa:'/swiːt/', pos:'adj',
   form:null, kat:'rengdêr', zor:0.80,
   notKu:'Şîrîn. Bi tama şekir.',
   her:["The cake is sweet.", "Honey is sweet."],
   herKu:['Kek şîrîn e.', 'Hingiv şîrîn e.'], emoji:'🍰')
];
