class EnListeningExercise {
  final String id;
  final String level;
  final String type; // 'transcribe', 'multiple_choice', 'true_false'
  final String audioText; // TTS için metin
  final String promptKu; // Kurmancî talimat
  final String correctAnswer;
  final List<String>? options;
  final String explanationKu;

  const EnListeningExercise({
    required this.id,
    required this.level,
    required this.type,
    required this.audioText,
    required this.promptKu,
    required this.correctAnswer,
    required this.options,
    required this.explanationKu,
  });
}

const List<EnListeningExercise> kEnListeningExercises = [
  EnListeningExercise(
    id: 'en_listen_001',
    level: 'A1',
    type: 'transcribe',
    audioText: 'Good morning.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'Good morning.',
    options: null,
    explanationKu: '"Good morning" = Sibê baş. Silava sibehê.',
  ),
  EnListeningExercise(
    id: 'en_listen_002',
    level: 'A1',
    type: 'multiple_choice',
    audioText: 'I have three cats.',
    promptKu: 'Guhdarî bike û bersivê hilbijêre:',
    correctAnswer: 'three',
    options: ['three', 'two', 'four', 'five'],
    explanationKu: '"I have three cats" = Sê pisîkên min hene.',
  ),
  EnListeningExercise(
    id: 'en_listen_003',
    level: 'A1',
    type: 'transcribe',
    audioText: 'My name is Sara.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'My name is Sara.',
    options: null,
    explanationKu: '"My name is Sara" = Navê min Sara ye.',
  ),
  EnListeningExercise(
    id: 'en_listen_004',
    level: 'A1',
    type: 'transcribe',
    audioText: 'I am a student.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'I am a student.',
    options: null,
    explanationKu: '"I am a student" = Ez xwendekar im.',
  ),
  EnListeningExercise(
    id: 'en_listen_005',
    level: 'A1',
    type: 'multiple_choice',
    audioText: 'The book is on the table.',
    promptKu: 'Guhdarî bike: Pirtûk li ku derê ye?',
    correctAnswer: 'table',
    options: ['table', 'chair', 'bed', 'floor'],
    explanationKu: '"on the table" = li ser masê. Cihê pirtûkê masê ye.',
  ),
  EnListeningExercise(
    id: 'en_listen_006',
    level: 'A1',
    type: 'true_false',
    audioText: 'I like apples.',
    promptKu: 'Guhdarî bike. Îdia: "The speaker likes apples." Rast an Şaş?',
    correctAnswer: 'true',
    options: ['true', 'false'],
    explanationKu: '"I like apples" = Ez ji sêvan hez dikim. Îdia rast e.',
  ),
  EnListeningExercise(
    id: 'en_listen_007',
    level: 'A1',
    type: 'transcribe',
    audioText: 'She is my sister.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'She is my sister.',
    options: null,
    explanationKu: '"She is my sister" = Ew xwişka min e.',
  ),
  EnListeningExercise(
    id: 'en_listen_008',
    level: 'A1',
    type: 'transcribe',
    audioText: 'I drink water.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'I drink water.',
    options: null,
    explanationKu: '"I drink water" = Ez av vedixwim.',
  ),
  EnListeningExercise(
    id: 'en_listen_009',
    level: 'A1',
    type: 'multiple_choice',
    audioText: 'It is Monday today.',
    promptKu: 'Guhdarî bike: Îro çi roj e?',
    correctAnswer: 'Monday',
    options: ['Monday', 'Tuesday', 'Friday', 'Sunday'],
    explanationKu: '"Monday" = Duşem. Îro duşem e.',
  ),
  EnListeningExercise(
    id: 'en_listen_010',
    level: 'A1',
    type: 'transcribe',
    audioText: 'The dog is black.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'The dog is black.',
    options: null,
    explanationKu: '"The dog is black" = Kûçik reş e.',
  ),
  EnListeningExercise(
    id: 'en_listen_011',
    level: 'A1',
    type: 'transcribe',
    audioText: 'I am ten years old.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'I am ten years old.',
    options: null,
    explanationKu: '"I am ten years old" = Ez deh salî me.',
  ),
  EnListeningExercise(
    id: 'en_listen_012',
    level: 'A1',
    type: 'multiple_choice',
    audioText: 'I have two brothers.',
    promptKu: 'Guhdarî bike: Çend bira heye?',
    correctAnswer: 'two',
    options: ['two', 'one', 'three', 'four'],
    explanationKu: '"two brothers" = du bira. Du bira heye.',
  ),
  EnListeningExercise(
    id: 'en_listen_013',
    level: 'A1',
    type: 'true_false',
    audioText: 'The sky is blue.',
    promptKu: 'Guhdarî bike. Îdia: "The sky is green." Rast an Şaş?',
    correctAnswer: 'false',
    options: ['true', 'false'],
    explanationKu: '"The sky is blue" = Ezman şîn e. Îdia dibêje "green" (kesk), ji ber vê şaş e.',
  ),
  EnListeningExercise(
    id: 'en_listen_014',
    level: 'A1',
    type: 'transcribe',
    audioText: 'I go to school.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'I go to school.',
    options: null,
    explanationKu: '"I go to school" = Ez diçim dibistanê.',
  ),
  EnListeningExercise(
    id: 'en_listen_015',
    level: 'A1',
    type: 'transcribe',
    audioText: 'He is my friend.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'He is my friend.',
    options: null,
    explanationKu: '"He is my friend" = Ew hevalê min e.',
  ),
  EnListeningExercise(
    id: 'en_listen_016',
    level: 'A1',
    type: 'multiple_choice',
    audioText: 'I live in London.',
    promptKu: 'Guhdarî bike: Li ku derê dijî?',
    correctAnswer: 'London',
    options: ['London', 'Paris', 'Berlin', 'Rome'],
    explanationKu: '"I live in London" = Ez li Londonê dijîm.',
  ),
  EnListeningExercise(
    id: 'en_listen_017',
    level: 'A1',
    type: 'transcribe',
    audioText: 'I have a red car.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'I have a red car.',
    options: null,
    explanationKu: '"I have a red car" = Otomobîleke min a sor heye.',
  ),
  EnListeningExercise(
    id: 'en_listen_018',
    level: 'A1',
    type: 'true_false',
    audioText: 'My father is a teacher.',
    promptKu: 'Guhdarî bike. Îdia: "The speaker\'s father is a doctor." Rast an Şaş?',
    correctAnswer: 'false',
    options: ['true', 'false'],
    explanationKu: 'Dengbêj dibêje "teacher" (mamoste), ne "doctor" (bijîşk). Ji ber vê îdia şaş e.',
  ),
  EnListeningExercise(
    id: 'en_listen_019',
    level: 'A1',
    type: 'transcribe',
    audioText: 'I eat bread and cheese.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'I eat bread and cheese.',
    options: null,
    explanationKu: '"I eat bread and cheese" = Ez nan û penîr dixwim.',
  ),
  EnListeningExercise(
    id: 'en_listen_020',
    level: 'A1',
    type: 'multiple_choice',
    audioText: 'The cat is under the bed.',
    promptKu: 'Guhdarî bike: Pisîk li ku derê ye?',
    correctAnswer: 'under the bed',
    options: ['under the bed', 'on the bed', 'near the door', 'in the box'],
    explanationKu: '"under the bed" = li bin nivînan. Pisîk li bin nivînan e.',
  ),
  EnListeningExercise(
    id: 'en_listen_021',
    level: 'A1',
    type: 'transcribe',
    audioText: 'I am happy today.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'I am happy today.',
    options: null,
    explanationKu: '"I am happy today" = Ez îro kêfxweş im.',
  ),
  EnListeningExercise(
    id: 'en_listen_022',
    level: 'A1',
    type: 'transcribe',
    audioText: 'She has long hair.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'She has long hair.',
    options: null,
    explanationKu: '"She has long hair" = Porê wê yê dirêj heye.',
  ),
  EnListeningExercise(
    id: 'en_listen_023',
    level: 'A1',
    type: 'multiple_choice',
    audioText: 'The time is seven o\'clock.',
    promptKu: 'Guhdarî bike: Kat çi ye?',
    correctAnswer: 'seven',
    options: ['seven', 'five', 'six', 'eight'],
    explanationKu: '"seven o\'clock" = saet heft. Kat heft e.',
  ),
  EnListeningExercise(
    id: 'en_listen_024',
    level: 'A1',
    type: 'transcribe',
    audioText: 'I play football.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'I play football.',
    options: null,
    explanationKu: '"I play football" = Ez futbolê dilîzim.',
  ),
  EnListeningExercise(
    id: 'en_listen_025',
    level: 'A1',
    type: 'true_false',
    audioText: 'I have a small dog.',
    promptKu: 'Guhdarî bike. Îdia: "The speaker has a small dog." Rast an Şaş?',
    correctAnswer: 'true',
    options: ['true', 'false'],
    explanationKu: '"I have a small dog" = Kûçikekî min ê piçûk heye. Îdia rast e.',
  ),
  EnListeningExercise(
    id: 'en_listen_026',
    level: 'A2',
    type: 'transcribe',
    audioText: 'Yesterday I went to the park.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'Yesterday I went to the park.',
    options: null,
    explanationKu: 'Dema borî (past simple): "went" = çû. "Duh ez çûm parkê."',
  ),
  EnListeningExercise(
    id: 'en_listen_027',
    level: 'A2',
    type: 'transcribe',
    audioText: 'My mother cooked dinner last night.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'My mother cooked dinner last night.',
    options: null,
    explanationKu: '"cooked" dema borî ye. "Dayika min şeva çûyî şîv çêkir."',
  ),
  EnListeningExercise(
    id: 'en_listen_028',
    level: 'A2',
    type: 'multiple_choice',
    audioText: 'We visited our grandparents in Istanbul.',
    promptKu: 'Guhdarî bike: Serdana kê kirin?',
    correctAnswer: 'grandparents',
    options: ['grandparents', 'parents', 'friends', 'teachers'],
    explanationKu: '"grandparents" = dapîr û bapîr. Serdana dapîr û bapîran kirin.',
  ),
  EnListeningExercise(
    id: 'en_listen_029',
    level: 'A2',
    type: 'transcribe',
    audioText: 'I traveled to Paris last summer.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'I traveled to Paris last summer.',
    options: null,
    explanationKu: '"traveled" dema borî. "Havîna çûyî ez çûm Parîsê."',
  ),
  EnListeningExercise(
    id: 'en_listen_030',
    level: 'A2',
    type: 'true_false',
    audioText: 'My brother bought a new bike yesterday.',
    promptKu: 'Guhdarî bike. Îdia: "The brother bought a car." Rast an Şaş?',
    correctAnswer: 'false',
    options: ['true', 'false'],
    explanationKu: 'Dengbêj dibêje "bike" (bîsîklêt), ne "car" (otomobîl). Îdia şaş e.',
  ),
  EnListeningExercise(
    id: 'en_listen_031',
    level: 'A2',
    type: 'transcribe',
    audioText: 'She studied English for two years.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'She studied English for two years.',
    options: null,
    explanationKu: '"studied" dema borî. "Wê du salan Îngilîzî xwend."',
  ),
  EnListeningExercise(
    id: 'en_listen_032',
    level: 'A2',
    type: 'multiple_choice',
    audioText: 'The train arrives at nine in the morning.',
    promptKu: 'Guhdarî bike: Tren kîngê tê?',
    correctAnswer: 'nine',
    options: ['nine', 'seven', 'eleven', 'ten'],
    explanationKu: '"at nine" = saet neh. Tren saet neh a sibê tê.',
  ),
  EnListeningExercise(
    id: 'en_listen_033',
    level: 'A2',
    type: 'transcribe',
    audioText: 'My family moved to a new house.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'My family moved to a new house.',
    options: null,
    explanationKu: '"moved" dema borî. "Malbata min çû malek nû."',
  ),
  EnListeningExercise(
    id: 'en_listen_034',
    level: 'A2',
    type: 'transcribe',
    audioText: 'We stayed at the hotel for three nights.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'We stayed at the hotel for three nights.',
    options: null,
    explanationKu: '"stayed" dema borî. "Em sê şevan li otêlê man."',
  ),
  EnListeningExercise(
    id: 'en_listen_035',
    level: 'A2',
    type: 'multiple_choice',
    audioText: 'My sister is a doctor in the hospital.',
    promptKu: 'Guhdarî bike: Pîşeya xwişkê çi ye?',
    correctAnswer: 'doctor',
    options: ['doctor', 'teacher', 'nurse', 'engineer'],
    explanationKu: '"doctor" = bijîşk. Xwişk bijîşk e.',
  ),
  EnListeningExercise(
    id: 'en_listen_036',
    level: 'A2',
    type: 'transcribe',
    audioText: 'I walked to school this morning.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'I walked to school this morning.',
    options: null,
    explanationKu: '"walked" dema borî. "Ez vê sibehê bi peyatî çûm dibistanê."',
  ),
  EnListeningExercise(
    id: 'en_listen_037',
    level: 'A2',
    type: 'true_false',
    audioText: 'They arrived at the airport at noon.',
    promptKu: 'Guhdarî bike. Îdia: "They arrived in the evening." Rast an Şaş?',
    correctAnswer: 'false',
    options: ['true', 'false'],
    explanationKu: '"noon" = nîvro. Îdia dibêje "evening" (êvar), ji ber vê şaş e.',
  ),
  EnListeningExercise(
    id: 'en_listen_038',
    level: 'A2',
    type: 'transcribe',
    audioText: 'He watched a movie yesterday evening.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'He watched a movie yesterday evening.',
    options: null,
    explanationKu: '"watched" dema borî. "Wî duh êvarê fîlmek temaşe kir."',
  ),
  EnListeningExercise(
    id: 'en_listen_039',
    level: 'A2',
    type: 'multiple_choice',
    audioText: 'The plane landed in Berlin.',
    promptKu: 'Guhdarî bike: Balafir li ku daket?',
    correctAnswer: 'Berlin',
    options: ['Berlin', 'Madrid', 'Vienna', 'Prague'],
    explanationKu: '"landed in Berlin" = li Berlînê daket. Balafir li Berlînê daket.',
  ),
  EnListeningExercise(
    id: 'en_listen_040',
    level: 'A2',
    type: 'transcribe',
    audioText: 'My grandfather lived in a small village.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'My grandfather lived in a small village.',
    options: null,
    explanationKu: '"lived" dema borî. "Bapîrê min li gundekî piçûk dijiya."',
  ),
  EnListeningExercise(
    id: 'en_listen_041',
    level: 'A2',
    type: 'transcribe',
    audioText: 'We had a big party last weekend.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'We had a big party last weekend.',
    options: null,
    explanationKu: '"had" dema borî ya "have". "Dawiya hefteya çûyî şahiyeke mezin hebû."',
  ),
  EnListeningExercise(
    id: 'en_listen_042',
    level: 'A2',
    type: 'multiple_choice',
    audioText: 'I bought four apples at the market.',
    promptKu: 'Guhdarî bike: Çend sêv kirîn?',
    correctAnswer: 'four',
    options: ['four', 'five', 'three', 'six'],
    explanationKu: '"four apples" = çar sêv. Çar sêv kirîn.',
  ),
  EnListeningExercise(
    id: 'en_listen_043',
    level: 'A2',
    type: 'true_false',
    audioText: 'She wrote a letter to her friend.',
    promptKu: 'Guhdarî bike. Îdia: "She wrote a letter." Rast an Şaş?',
    correctAnswer: 'true',
    options: ['true', 'false'],
    explanationKu: '"wrote a letter" = nameyek nivîsand. Îdia rast e.',
  ),
  EnListeningExercise(
    id: 'en_listen_044',
    level: 'A2',
    type: 'transcribe',
    audioText: 'I will visit my aunt next Sunday.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'I will visit my aunt next Sunday.',
    options: null,
    explanationKu: '"will visit" dema bê. "Yekşema bê ezê serdana met/xaltîkê bikim."',
  ),
  EnListeningExercise(
    id: 'en_listen_045',
    level: 'A2',
    type: 'multiple_choice',
    audioText: 'The meeting starts at three in the afternoon.',
    promptKu: 'Guhdarî bike: Civîn kîngê dest pê dike?',
    correctAnswer: 'three',
    options: ['three', 'two', 'four', 'five'],
    explanationKu: '"at three" = saet sê. Civîn saet sê dest pê dike.',
  ),
  EnListeningExercise(
    id: 'en_listen_046',
    level: 'B1',
    type: 'transcribe',
    audioText: 'I think learning a new language opens many doors.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'I think learning a new language opens many doors.',
    options: null,
    explanationKu: '"opens many doors" derbirînek metafor e: fersendên nû çêdike. "Ez difikirim hînbûna zimanekî nû gelek deriyan vedike."',
  ),
  EnListeningExercise(
    id: 'en_listen_047',
    level: 'B1',
    type: 'transcribe',
    audioText: 'She decided to study abroad after graduation.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'She decided to study abroad after graduation.',
    options: null,
    explanationKu: '"abroad" = li welatên biyanî. "Piştî qedandinê biryar da ku li welatên biyanî bixwîne."',
  ),
  EnListeningExercise(
    id: 'en_listen_048',
    level: 'B1',
    type: 'multiple_choice',
    audioText: 'He has lived in the city for over ten years.',
    promptKu: 'Guhdarî bike: Çend sal e li bajêr dijî?',
    correctAnswer: 'over ten years',
    options: ['over ten years', 'less than five years', 'about two years', 'seven months'],
    explanationKu: '"for over ten years" = zêdetirî deh salan. Deh sal zêdetir li bajêr dijiya.',
  ),
  EnListeningExercise(
    id: 'en_listen_049',
    level: 'B1',
    type: 'transcribe',
    audioText: 'In my opinion, reading books is very important.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'In my opinion, reading books is very important.',
    options: null,
    explanationKu: '"In my opinion" = li gor ramana min. "Li gor ramana min, xwendina pirtûkan gelek girîng e."',
  ),
  EnListeningExercise(
    id: 'en_listen_050',
    level: 'B1',
    type: 'true_false',
    audioText: 'Although it was raining, we went for a walk in the park.',
    promptKu: 'Guhdarî bike. Îdia: "They stayed home because of the rain." Rast an Şaş?',
    correctAnswer: 'false',
    options: ['true', 'false'],
    explanationKu: 'Dengbêj dibêje "we went for a walk" (em çûn gerê), ne li malê man. Îdia şaş e.',
  ),
  EnListeningExercise(
    id: 'en_listen_051',
    level: 'B1',
    type: 'transcribe',
    audioText: 'If I had more time, I would travel around the world.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'If I had more time, I would travel around the world.',
    options: null,
    explanationKu: 'Conditional type 2. "Eger dema min zêdetir hebûya, ezê li dora cîhanê bigeriyama."',
  ),
  EnListeningExercise(
    id: 'en_listen_052',
    level: 'B1',
    type: 'multiple_choice',
    audioText: 'The children were playing in the garden when it started to rain.',
    promptKu: 'Guhdarî bike: Gava baran dest pê kir zarok li ku bûn?',
    correctAnswer: 'in the garden',
    options: ['in the garden', 'in the house', 'at school', 'at the park'],
    explanationKu: '"in the garden" = li baxçê. Zarok li baxçê dilîstin.',
  ),
  EnListeningExercise(
    id: 'en_listen_053',
    level: 'B1',
    type: 'transcribe',
    audioText: 'He has been working as an engineer for five years.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'He has been working as an engineer for five years.',
    options: null,
    explanationKu: 'Present perfect continuous. "Pênc sal in wek endezyar dixebite."',
  ),
  EnListeningExercise(
    id: 'en_listen_054',
    level: 'B1',
    type: 'true_false',
    audioText: 'Despite the cold weather, the children enjoyed their day outside.',
    promptKu: 'Guhdarî bike. Îdia: "The children had fun outside." Rast an Şaş?',
    correctAnswer: 'true',
    options: ['true', 'false'],
    explanationKu: '"enjoyed their day" = kêfa xwe anîn. Bi tevî sermayê kêfxweş bûn. Îdia rast e.',
  ),
  EnListeningExercise(
    id: 'en_listen_055',
    level: 'B1',
    type: 'multiple_choice',
    audioText: 'She believes that honesty is the best policy in life.',
    promptKu: 'Guhdarî bike: Li gor wê ya baştirîn çi ye?',
    correctAnswer: 'honesty',
    options: ['honesty', 'wealth', 'power', 'silence'],
    explanationKu: '"honesty is the best policy" = rastgotî çareya herî baş e. Wê bawer dike rastgotî baştirîn e.',
  ),
  EnListeningExercise(
    id: 'en_listen_056',
    level: 'B2',
    type: 'transcribe',
    audioText: 'The government should invest more in renewable energy sources.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'The government should invest more in renewable energy sources.',
    options: null,
    explanationKu: '"renewable energy sources" = çavkaniyên enerjiya nûjenbar. Mijara abstract: siyaseta enerjiyê.',
  ),
  EnListeningExercise(
    id: 'en_listen_057',
    level: 'B2',
    type: 'transcribe',
    audioText: 'Globalization has transformed the way we communicate with each other.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'Globalization has transformed the way we communicate with each other.',
    options: null,
    explanationKu: '"Globalization" = cîhanîbûn. "Cîhanîbûnê awayê me yê peywendîkirinê guhartiye."',
  ),
  EnListeningExercise(
    id: 'en_listen_058',
    level: 'B2',
    type: 'multiple_choice',
    audioText: 'Critical thinking is essential for solving complex problems in modern society.',
    promptKu: 'Guhdarî bike: Ji bo çareserkirina pirsgirêkan çi pêwîst e?',
    correctAnswer: 'critical thinking',
    options: ['critical thinking', 'memorization', 'speed reading', 'physical strength'],
    explanationKu: '"critical thinking" = ramana rexneyî. Ji bo pirsgirêkên tevlihev ramana rexneyî pêwîst e.',
  ),
  EnListeningExercise(
    id: 'en_listen_059',
    level: 'B2',
    type: 'true_false',
    audioText: 'Despite technological advancements, many people still prefer traditional methods of learning.',
    promptKu: 'Guhdarî bike. Îdia: "Everyone has abandoned traditional learning." Rast an Şaş?',
    correctAnswer: 'false',
    options: ['true', 'false'],
    explanationKu: 'Dengbêj dibêje "many people still prefer traditional methods" (gelek kes hîn jî rêbazên kevneşopî tercîh dikin). Îdia şaş e.',
  ),
  EnListeningExercise(
    id: 'en_listen_060',
    level: 'B2',
    type: 'transcribe',
    audioText: 'Freedom of expression is a fundamental right in any democratic society.',
    promptKu: 'Guhdarî bike û binivîse:',
    correctAnswer: 'Freedom of expression is a fundamental right in any democratic society.',
    options: null,
    explanationKu: '"Freedom of expression" = azadiya derbirînê. Mijara abstract: mafên bingehîn ên demokrasiyê.',
  ),
];
