// LÛTKE English Speaking/Pronunciation Database
// Kurmancî L1 learners için konuşma ve telaffuz alıştırmaları
// Dağılım: A1(25) + A2(20) + B1(10) + B2(5) = 60
// Tür: pronunciation(20) + repeat(20) + respond(10) + read_aloud(10)

class EnSpeakingExercise {
  final String id;
  final String level;
  final String type; // 'pronunciation', 'repeat', 'respond', 'read_aloud'
  final String textEn;
  final String? ipa;
  final String promptKu;
  final String tipKu;
  final List<String>? acceptableVariants;

  const EnSpeakingExercise({
    required this.id,
    required this.level,
    required this.type,
    required this.textEn,
    this.ipa,
    required this.promptKu,
    required this.tipKu,
    this.acceptableVariants,
  });
}

const List<EnSpeakingExercise> kEnSpeakingExercises = [
  // ============= PRONUNCIATION (20) — zor sesler =============
  EnSpeakingExercise(
    id: 'en_speak_001',
    level: 'A1',
    type: 'pronunciation',
    textEn: 'Thank you.',
    ipa: '/θæŋk juː/',
    promptKu: 'Bibêje: "Thank you"',
    tipKu: '"th" (θ) denge Kurmancî de tune. Ziman bixe navbera diranan, hewa bidî der. Ne "tenk" ne jî "senk" — nerm bi zimên.',
    acceptableVariants: ['thank you', 'thanks'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_002',
    level: 'A1',
    type: 'pronunciation',
    textEn: 'Think.',
    ipa: '/θɪŋk/',
    promptKu: 'Bibêje: "Think"',
    tipKu: '/θ/ bêdeng e — ziman li navbera diranan, bi hewa derxe. Ne "tink" ne "sink". Diranê jor û zimanê sivik.',
    acceptableVariants: ['think'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_003',
    level: 'A1',
    type: 'pronunciation',
    textEn: 'Three.',
    ipa: '/θriː/',
    promptKu: 'Bibêje: "Three"',
    tipKu: '/θr/ pir zehmet e — pêşî /θ/ (ziman di navbera diranan) paşê /r/. Xebatek dike: "th...ree".',
    acceptableVariants: ['three'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_004',
    level: 'A1',
    type: 'pronunciation',
    textEn: 'This.',
    ipa: '/ðɪs/',
    promptKu: 'Bibêje: "This"',
    tipKu: '/ð/ dengdêr e (birayê /θ/), lê di Kurmancî de tune. Ziman li navbera diranan, lê bi dengê qirikê. Ne "dis" ne "zis".',
    acceptableVariants: ['this'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_005',
    level: 'A1',
    type: 'pronunciation',
    textEn: 'That.',
    ipa: '/ðæt/',
    promptKu: 'Bibêje: "That"',
    tipKu: '/ð/ + /æ/ — /ð/ dengdêr (ziman di navbera diranan), /æ/ ne "a" ne "e" — devê xwe vekirî, kurt.',
    acceptableVariants: ['that'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_006',
    level: 'A1',
    type: 'pronunciation',
    textEn: 'Mother.',
    ipa: '/ˈmʌðər/',
    promptKu: 'Bibêje: "Mother"',
    tipKu: '/ð/ di nav peyvê de — navbera "mo" û "er". Ne "moder" ne "moze". Zimanê nerm di navbera diranan.',
    acceptableVariants: ['mother', 'mom'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_007',
    level: 'A1',
    type: 'pronunciation',
    textEn: 'Cat.',
    ipa: '/kæt/',
    promptKu: 'Bibêje: "Cat"',
    tipKu: '/æ/ deng ne "kat" ye — navbera "a" û "e". Devê xwe firehtir veke, wek ku tu bibêjî "eaaa". Bi kurmancî "e" naşibe.',
    acceptableVariants: ['cat'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_008',
    level: 'A1',
    type: 'pronunciation',
    textEn: 'Apple.',
    ipa: '/ˈæpəl/',
    promptKu: 'Bibêje: "Apple"',
    tipKu: '/æ/ li destpêkê — fireh û kurt. "Æ" ne "e" ye ne "a" ye. Paşê /ə/ (schwa) qels: "ap-pl".',
    acceptableVariants: ['apple'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_009',
    level: 'A1',
    type: 'pronunciation',
    textEn: 'Man.',
    ipa: '/mæn/',
    promptKu: 'Bibêje: "Man"',
    tipKu: '/æ/ — devê vekirî, kurt. Ne "men" ne "man". Dengê nava "a" û "e".',
    acceptableVariants: ['man'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_010',
    level: 'A2',
    type: 'pronunciation',
    textEn: 'Ship.',
    ipa: '/ʃɪp/',
    promptKu: 'Bibêje: "Ship" (keştî)',
    tipKu: '/ɪ/ kurt e — ne "şip" bi "i"ya dirêj. Devê xwe hinekî vekirî bihêle, kurt. Cudahiya "ship" û "sheep" li vir e.',
    acceptableVariants: ['ship'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_011',
    level: 'A2',
    type: 'pronunciation',
    textEn: 'Sheep.',
    ipa: '/ʃiːp/',
    promptKu: 'Bibêje: "Sheep" (pez)',
    tipKu: '/iː/ dirêj e — wek kurmancî "î". Devê xwe teng bike, dirêj bibêje "şîîîp". Ji "ship" cudatir.',
    acceptableVariants: ['sheep'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_012',
    level: 'A2',
    type: 'pronunciation',
    textEn: 'Very.',
    ipa: '/ˈveri/',
    promptKu: 'Bibêje: "Very"',
    tipKu: '/v/ bi diranê jor û lêvê jêrîn — wek kurmancî "v", lê paqijtir. Ne "beri" ne "weri". Diran bigihîne lêv.',
    acceptableVariants: ['very'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_013',
    level: 'A2',
    type: 'pronunciation',
    textEn: 'Water.',
    ipa: '/ˈwɔːtər/',
    promptKu: 'Bibêje: "Water"',
    tipKu: '/w/ bi lêvên girover — wek tu bibêjî "uuu" paşê "a". Ne "vater" (Kurmancî v). Lêv zivirî, paqij.',
    acceptableVariants: ['water'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_014',
    level: 'A2',
    type: 'pronunciation',
    textEn: 'World.',
    ipa: '/wɜːrld/',
    promptKu: 'Bibêje: "World"',
    tipKu: '/w/ + /ɜːr/ zehmet e. Destpêkê lêv girover (w), paşê dengê dirêj ê wek "ör" bi zimên ber bi paş. Dawî /ld/ bi hev re.',
    acceptableVariants: ['world'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_015',
    level: 'A2',
    type: 'pronunciation',
    textEn: 'About.',
    ipa: '/əˈbaʊt/',
    promptKu: 'Bibêje: "About"',
    tipKu: '/ə/ (schwa) li destpêkê pir qels e — wek "ı" ya tirkî, lê kurtir. Tu tîpê nehilde, şil bike: "ə-baut".',
    acceptableVariants: ['about'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_016',
    level: 'B1',
    type: 'pronunciation',
    textEn: 'Weather.',
    ipa: '/ˈweðər/',
    promptKu: 'Bibêje: "Weather" (hewa)',
    tipKu: '/w/ + /ð/ — du dengên zehmet li pey hev. Lêv girover ji bo "we", paşê ziman di navbera diranan ji bo "ther".',
    acceptableVariants: ['weather'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_017',
    level: 'B1',
    type: 'pronunciation',
    textEn: 'Through.',
    ipa: '/θruː/',
    promptKu: 'Bibêje: "Through"',
    tipKu: '/θ/ + /r/ + /uː/ — yek ji zehmettirîn peyvên Îngilîzî. Destpêkê ziman navbera diranan, paşê /r/ya nerm, dawî "û"ya dirêj.',
    acceptableVariants: ['through'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_018',
    level: 'B1',
    type: 'pronunciation',
    textEn: 'Clothes.',
    ipa: '/kloʊðz/',
    promptKu: 'Bibêje: "Clothes" (cil)',
    tipKu: 'Dawî /ðz/ — /ð/ û /z/ bi hev re, pir zor. Gelek kes dibêjin "kloz" — ew jî tê qebûlkirin, lê /kloʊðz/ rasttir e.',
    acceptableVariants: ['clothes', 'cloths'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_019',
    level: 'B2',
    type: 'pronunciation',
    textEn: 'Rural.',
    ipa: '/ˈrʊərəl/',
    promptKu: 'Bibêje: "Rural" (gundî)',
    tipKu: 'Du /r/ û du /ə/ — pir zehmet. Kurmancî "r" bi lerzandina zimên e; Îngilîzî "r" bêlerz, zimên ber bi paş. Hêdî bibêje.',
    acceptableVariants: ['rural'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_020',
    level: 'B2',
    type: 'pronunciation',
    textEn: 'Thoroughly.',
    ipa: '/ˈθʌrəli/',
    promptKu: 'Bibêje: "Thoroughly" (bi temamî)',
    tipKu: '/θ/ + /ʌ/ + /r/ + /ə/ — çar dengên cuda. Perçe perçe xebatê bike: "tho-rough-ly". Ziman navbera diranan, paşê /r/ bêlerz.',
    acceptableVariants: ['thoroughly'],
  ),

  // ============= REPEAT (20) — rojane, hêsan =============
  EnSpeakingExercise(
    id: 'en_speak_021',
    level: 'A1',
    type: 'repeat',
    textEn: 'Hello!',
    ipa: '/həˈloʊ/',
    promptKu: 'Dûbare bike: "Hello!"',
    tipKu: '/h/ sivik wek kurmancî "h". Destpêkê qels, paşê "lo" bi dengê jêr-jor.',
    acceptableVariants: ['hello', 'hi'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_022',
    level: 'A1',
    type: 'repeat',
    textEn: 'Good morning.',
    ipa: '/ɡʊd ˈmɔːrnɪŋ/',
    promptKu: 'Dûbare bike: "Good morning."',
    tipKu: '/ʊ/ di "good" de kurt e — ne "gûd". Dawî "ing" bi dengê -ŋ (poz).',
    acceptableVariants: ['good morning'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_023',
    level: 'A1',
    type: 'repeat',
    textEn: 'How are you?',
    ipa: '/haʊ ɑːr juː/',
    promptKu: 'Dûbare bike: "How are you?"',
    tipKu: '"how" (haʊ) /h/ wek kurmancî. "are" yê kurt /ɑːr/. Pirs e — dengê dawiyê bilind bike.',
    acceptableVariants: ['how are you'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_024',
    level: 'A1',
    type: 'repeat',
    textEn: 'I am fine.',
    ipa: '/aɪ æm faɪn/',
    promptKu: 'Dûbare bike: "I am fine."',
    tipKu: '/æ/ di "am" de — devê vekirî. Dawî "fine" bi dengê /aɪ/ (ayy).',
    acceptableVariants: ['i am fine', "i'm fine"],
  ),
  EnSpeakingExercise(
    id: 'en_speak_025',
    level: 'A1',
    type: 'repeat',
    textEn: 'See you later.',
    ipa: '/siː juː ˈleɪtər/',
    promptKu: 'Dûbare bike: "See you later."',
    tipKu: '/iː/ dirêj di "see" de. "later" bi dengê /eɪ/ (ey) — ne "later" bi "a"yê teqîner.',
    acceptableVariants: ['see you later'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_026',
    level: 'A1',
    type: 'repeat',
    textEn: 'Nice to meet you.',
    ipa: '/naɪs tə miːt juː/',
    promptKu: 'Dûbare bike: "Nice to meet you."',
    tipKu: '"to" qels dibe /tə/ (ne "tû"). "meet" bi /iː/ dirêj. Axaftina rojane şil e.',
    acceptableVariants: ['nice to meet you'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_027',
    level: 'A1',
    type: 'repeat',
    textEn: 'I am hungry.',
    ipa: '/aɪ æm ˈhʌŋɡri/',
    promptKu: 'Dûbare bike: "I am hungry."',
    tipKu: '/ʌ/ di "hungry" de — wek "a"yek kurt, qirik-nêzik. "ng" bi dengê poz /ŋ/.',
    acceptableVariants: ['i am hungry', "i'm hungry"],
  ),
  EnSpeakingExercise(
    id: 'en_speak_028',
    level: 'A1',
    type: 'repeat',
    textEn: 'Please help me.',
    ipa: '/pliːz help miː/',
    promptKu: 'Dûbare bike: "Please help me."',
    tipKu: '/pl/ bi hev re, bê dengdêr. "Please" bi /iː/ dirêj. Bi kerî bibêje, hêdî.',
    acceptableVariants: ['please help me'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_029',
    level: 'A1',
    type: 'repeat',
    textEn: 'I like coffee.',
    ipa: '/aɪ laɪk ˈkɔːfi/',
    promptKu: 'Dûbare bike: "I like coffee."',
    tipKu: '"like" bi /aɪ/. "coffee" /ɔː/ dirêj — ne "kofi" bi o ya kurmancî, bêhntir.',
    acceptableVariants: ['i like coffee'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_030',
    level: 'A2',
    type: 'repeat',
    textEn: 'What time is it?',
    ipa: '/wɒt taɪm ɪz ɪt/',
    promptKu: 'Dûbare bike: "What time is it?"',
    tipKu: '/w/ bi lêvên girover. "time" bi /aɪ/. /ɪ/ kurt li dawiyê — "it" nerm. Pirs: dengê dawî bilind.',
    acceptableVariants: ['what time is it'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_031',
    level: 'A2',
    type: 'repeat',
    textEn: 'Where is the bathroom?',
    ipa: '/wer ɪz ðə ˈbæθruːm/',
    promptKu: 'Dûbare bike: "Where is the bathroom?"',
    tipKu: '"the" dibe /ðə/ (schwa) — qels. "bathroom" — /æ/ + /θ/, her du jî zehmet. Hêdî bibêje.',
    acceptableVariants: ['where is the bathroom'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_032',
    level: 'A2',
    type: 'repeat',
    textEn: 'Can you help me?',
    ipa: '/kæn juː help miː/',
    promptKu: 'Dûbare bike: "Can you help me?"',
    tipKu: '"can" bi /æ/ (devê vekirî). Pirs e — dengê "me" bilind bike. Wek daxwazê nerm bibêje.',
    acceptableVariants: ['can you help me'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_033',
    level: 'A2',
    type: 'repeat',
    textEn: 'I do not understand.',
    ipa: '/aɪ duː nɒt ˌʌndərˈstænd/',
    promptKu: 'Dûbare bike: "I do not understand."',
    tipKu: '"understand" kêşandin li ser "stand". /ʌ/ + /ə/ + /æ/ — sê dengên cuda di yek peyvê de.',
    acceptableVariants: ['i do not understand', "i don't understand"],
  ),
  EnSpeakingExercise(
    id: 'en_speak_034',
    level: 'A2',
    type: 'repeat',
    textEn: 'How much does it cost?',
    ipa: '/haʊ mʌtʃ dʌz ɪt kɒst/',
    promptKu: 'Dûbare bike: "How much does it cost?"',
    tipKu: '/ʌ/ sê caran — "much", "does", ne wek "a" an "o". "cost" bi /ɒ/ kurt, dengê "o" ya vekirî.',
    acceptableVariants: ['how much does it cost', 'how much is it'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_035',
    level: 'A2',
    type: 'repeat',
    textEn: 'I would like some tea.',
    ipa: '/aɪ wʊd laɪk səm tiː/',
    promptKu: 'Dûbare bike: "I would like some tea."',
    tipKu: '"would" bi /ʊ/ kurt — ne "wûd". "some" dibe /səm/ qels. "tea" bi /iː/ dirêj.',
    acceptableVariants: ['i would like some tea', "i'd like some tea"],
  ),
  EnSpeakingExercise(
    id: 'en_speak_036',
    level: 'A2',
    type: 'repeat',
    textEn: 'The weather is nice today.',
    ipa: '/ðə ˈweðər ɪz naɪs təˈdeɪ/',
    promptKu: 'Dûbare bike: "The weather is nice today."',
    tipKu: 'Du /ð/ — "the" û "weather". Her du /ð/ dengdêr: ziman navbera diranan, bi qirik.',
    acceptableVariants: ['the weather is nice today'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_037',
    level: 'B1',
    type: 'repeat',
    textEn: 'I have been waiting for an hour.',
    ipa: '/aɪ hæv bɪn ˈweɪtɪŋ fɔːr ən ˈaʊər/',
    promptKu: 'Dûbare bike: "I have been waiting for an hour."',
    tipKu: '"hour" /h/ bêdeng — "auər" dest pê dike. "for an" bi hev ve: "fərən".',
    acceptableVariants: ['i have been waiting for an hour', "i've been waiting for an hour"],
  ),
  EnSpeakingExercise(
    id: 'en_speak_038',
    level: 'B1',
    type: 'repeat',
    textEn: 'Could you repeat that, please?',
    ipa: '/kʊd juː rɪˈpiːt ðæt pliːz/',
    promptKu: 'Dûbare bike: "Could you repeat that, please?"',
    tipKu: '"could" /ʊ/ kurt. /ð/ di "that" de. Bi bilindbûna dengê "please" pirsê tîne.',
    acceptableVariants: ['could you repeat that please', 'could you repeat that'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_039',
    level: 'B1',
    type: 'repeat',
    textEn: 'I think it will rain tomorrow.',
    ipa: '/aɪ θɪŋk ɪt wɪl reɪn təˈmɒroʊ/',
    promptKu: 'Dûbare bike: "I think it will rain tomorrow."',
    tipKu: '"think" bi /θ/ — ziman navbera diranan. "rain" /eɪ/ (reyn). Yek hêla hevokê nerm.',
    acceptableVariants: ['i think it will rain tomorrow'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_040',
    level: 'B2',
    type: 'repeat',
    textEn: 'I would rather stay at home tonight.',
    ipa: '/aɪ wʊd ˈræðər steɪ æt hoʊm təˈnaɪt/',
    promptKu: 'Dûbare bike: "I would rather stay at home tonight."',
    tipKu: '"rather" /æ/ + /ð/ — her du zehmet. "would rather" bi hev re lez bibêje: "wədrəðər".',
    acceptableVariants: ['i would rather stay at home tonight', "i'd rather stay at home tonight"],
  ),

  // ============= RESPOND (10) — pirs → bersiv =============
  EnSpeakingExercise(
    id: 'en_speak_041',
    level: 'A1',
    type: 'respond',
    textEn: 'What is your name?',
    ipa: '/wɒt ɪz jɔːr neɪm/',
    promptKu: 'Bersiv bide: "What is your name?" — Navê xwe bibêje bi Îngilîzî.',
    tipKu: 'Bersiv: "My name is ___". /m/ nerm, paşê "name" bi /eɪ/ (neym). Navê xwe li dawiyê zelal bibêje.',
    acceptableVariants: ['my name is', "i'm", 'i am'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_042',
    level: 'A1',
    type: 'respond',
    textEn: 'How old are you?',
    ipa: '/haʊ oʊld ɑːr juː/',
    promptKu: 'Bersiv bide: "How old are you?" — Temenê xwe bibêje.',
    tipKu: 'Bersiv: "I am ___ years old." /ɪə/ di "years" de — nerm, dirêj. Hejmar zelal bibêje.',
    acceptableVariants: ['i am', "i'm", 'years old'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_043',
    level: 'A1',
    type: 'respond',
    textEn: 'Where are you from?',
    ipa: '/wer ɑːr juː frəm/',
    promptKu: 'Bersiv bide: "Where are you from?" — Tu ji ku derê yî?',
    tipKu: 'Bersiv: "I am from ___." "from" bi /ə/ qels (frəm). Welatê xwe bibêje: Kurdistan, Turkey, Germany, hwd.',
    acceptableVariants: ['i am from', "i'm from", 'from'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_044',
    level: 'A1',
    type: 'respond',
    textEn: 'What do you do?',
    ipa: '/wɒt duː juː duː/',
    promptKu: 'Bersiv bide: "What do you do?" — Tu çi kar dikî?',
    tipKu: 'Bersiv: "I am a ___." "I work as ___." Kar/pîşeya xwe bibêje: student, teacher, doctor, hwd.',
    acceptableVariants: ['i am a', "i'm a", 'i work'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_045',
    level: 'A2',
    type: 'respond',
    textEn: 'What is your favorite color?',
    ipa: '/wɒt ɪz jɔːr ˈfeɪvərɪt ˈkʌlər/',
    promptKu: 'Bersiv bide: "What is your favorite color?"',
    tipKu: 'Bersiv: "My favorite color is ___." "color" /ʌ/ — ne "kolor". Rengê xwe bibêje: red, blue, green...',
    acceptableVariants: ['my favorite color is', 'my favourite color is'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_046',
    level: 'A2',
    type: 'respond',
    textEn: 'What did you eat today?',
    ipa: '/wɒt dɪd juː iːt təˈdeɪ/',
    promptKu: 'Bersiv bide: "What did you eat today?" — Îro te çi xwar?',
    tipKu: 'Bersiv: "I ate ___." "ate" bi /eɪt/. Xwarina xwe bibêje: rice, bread, meat, hwd.',
    acceptableVariants: ['i ate', 'i had', 'today i ate'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_047',
    level: 'A2',
    type: 'respond',
    textEn: 'Do you have any siblings?',
    ipa: '/duː juː hæv ˈeni ˈsɪblɪŋz/',
    promptKu: 'Bersiv bide: "Do you have any siblings?" — Xwişk û birayên te hene?',
    tipKu: 'Bersiv: "Yes, I have ___ brother(s)/sister(s)." an "No, I am an only child." Hejmarê zelal bibêje.',
    acceptableVariants: ['yes i have', 'no i am', 'i have'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_048',
    level: 'B1',
    type: 'respond',
    textEn: 'What are your hobbies?',
    ipa: '/wɒt ɑːr jɔːr ˈhɒbiz/',
    promptKu: 'Bersiv bide: "What are your hobbies?" — Vala demên te çi ne?',
    tipKu: 'Bersiv: "I enjoy ___ing." an "My hobbies are ___." Lêkerê bi -ing bike: reading, walking, cooking.',
    acceptableVariants: ['my hobbies are', 'i enjoy', 'i like'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_049',
    level: 'B1',
    type: 'respond',
    textEn: 'Why are you learning English?',
    ipa: '/waɪ ɑːr juː ˈlɜːrnɪŋ ˈɪŋɡlɪʃ/',
    promptKu: 'Bersiv bide: "Why are you learning English?" — Çima tu Îngilîzî hîn dibî?',
    tipKu: 'Bersiv: "I am learning English because ___." Sedem bibêje: work, travel, study, hwd. "because" /ɪ/ kurt.',
    acceptableVariants: ['because', 'i am learning', 'for work', 'for travel'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_050',
    level: 'B2',
    type: 'respond',
    textEn: 'If you could travel anywhere, where would you go?',
    ipa: '/ɪf juː kʊd ˈtrævəl ˈeniwer wer wʊd juː ɡoʊ/',
    promptKu: 'Bersiv bide: Ger tu bikaribî her ciyê biçî, tê biçî ku derê?',
    tipKu: 'Bersiv: "I would go to ___ because ___." "would" /wʊd/ kurt. Cih + sedem bibêje. Conditional — nerm axiftin.',
    acceptableVariants: ['i would go to', 'i would travel to', 'because'],
  ),

  // ============= READ_ALOUD (10) — pasaj (2-3 hevok) =============
  EnSpeakingExercise(
    id: 'en_speak_051',
    level: 'A1',
    type: 'read_aloud',
    textEn: 'My name is Sara. I am from Kurdistan. I am a student.',
    ipa: null,
    promptKu: 'Bi dengê bilind bixwîne:',
    tipKu: 'Her hevok cuda, navbera hevokan bêhnvedanek biçûk. "student" /ˈstuːdənt/ — "stu" bi /uː/ dirêj.',
    acceptableVariants: ['my name is sara i am from kurdistan i am a student'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_052',
    level: 'A1',
    type: 'read_aloud',
    textEn: 'I like coffee. I drink coffee every morning. It is hot and black.',
    ipa: null,
    promptKu: 'Bi dengê bilind bixwîne:',
    tipKu: 'Paqij bibêje. "drink" /drɪŋk/ bi /ŋ/. "every" sê tîp lê dengdar: /ˈevri/. "black" /æ/ — devê vekirî.',
    acceptableVariants: ['i like coffee i drink coffee every morning it is hot and black'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_053',
    level: 'A1',
    type: 'read_aloud',
    textEn: 'This is my family. My mother is a teacher. My father is a doctor.',
    ipa: null,
    promptKu: 'Bi dengê bilind bixwîne:',
    tipKu: 'Du /ð/: "This" û "mother". Her du jî ziman navbera diranan. "doctor" /ˈdɒktər/ — /ɒ/ kurt.',
    acceptableVariants: ['this is my family my mother is a teacher my father is a doctor'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_054',
    level: 'A2',
    type: 'read_aloud',
    textEn: 'I have three brothers and two sisters. We live in a big house. My family is very happy.',
    ipa: null,
    promptKu: 'Bi dengê bilind bixwîne:',
    tipKu: '"three" /θr/ — zehmet, hêdî. "very" /v/ diran-lêv. "happy" /æ/ kurt. Navbera hevokan kurt bêhnvedan.',
    acceptableVariants: ['i have three brothers and two sisters we live in a big house my family is very happy'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_055',
    level: 'A2',
    type: 'read_aloud',
    textEn: 'Yesterday I went to the park. The weather was sunny and warm. I played football with my friends.',
    ipa: null,
    promptKu: 'Bi dengê bilind bixwîne:',
    tipKu: '"Yesterday" /ˈjestərdeɪ/ sê kîte. "weather" /ð/. "played" /pleɪd/ — /d/ dawiyê. Hevokên çîrokî, ahengek bîne.',
    acceptableVariants: ['yesterday i went to the park the weather was sunny and warm i played football with my friends'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_056',
    level: 'A2',
    type: 'read_aloud',
    textEn: 'I wake up at seven o\'clock every day. I eat breakfast with my family. Then I go to school.',
    ipa: null,
    promptKu: 'Bi dengê bilind bixwîne:',
    tipKu: '"seven o\'clock" bi hev: "seven-ə-klɒk". "breakfast" /ˈbrekfəst/ — /e/ kurt. "Then" /ð/ dengdêr.',
    acceptableVariants: ["i wake up at seven o'clock every day i eat breakfast with my family then i go to school"],
  ),
  EnSpeakingExercise(
    id: 'en_speak_057',
    level: 'B1',
    type: 'read_aloud',
    textEn: 'Learning a new language is not easy. You need patience and practice. But it opens many doors in life.',
    ipa: null,
    promptKu: 'Bi dengê bilind bixwîne:',
    tipKu: '"Learning" /lɜːr/ dirêj, zimên ber bi paş. "patience" /ˈpeɪʃəns/ — /ʃ/ (ş). "opens" /ˈoʊpənz/ — /z/ li dawî.',
    acceptableVariants: ['learning a new language is not easy you need patience and practice but it opens many doors in life'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_058',
    level: 'B1',
    type: 'read_aloud',
    textEn: 'Technology has changed our lives completely. We can talk to people around the world. However, we should not forget real conversations.',
    ipa: null,
    promptKu: 'Bi dengê bilind bixwîne:',
    tipKu: '"Technology" /tekˈnɒlədʒi/ — /dʒ/ (c). "changed" /tʃ/ (ç). "However" — bêhnvedaneke biçûk berî wê. Bi baldarî bibêje.',
    acceptableVariants: ['technology has changed our lives completely we can talk to people around the world however we should not forget real conversations'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_059',
    level: 'B2',
    type: 'read_aloud',
    textEn: 'Climate change is one of the biggest challenges of our time. We must take action now. Every small step matters for the future of our planet.',
    ipa: null,
    promptKu: 'Bi dengê bilind bixwîne:',
    tipKu: '"challenges" /ˈtʃælɪndʒɪz/ — /tʃ/ destpêk, /dʒ/ nav. "future" /ˈfjuːtʃər/ — /fj/ bi hev. "planet" /æ/. Hevokên cidî — dengê xwe qaîm bike.',
    acceptableVariants: ['climate change is one of the biggest challenges of our time we must take action now every small step matters for the future of our planet'],
  ),
  EnSpeakingExercise(
    id: 'en_speak_060',
    level: 'B2',
    type: 'read_aloud',
    textEn: 'Although the journey was long and exhausting, we finally reached the mountain peak. The view from there was absolutely breathtaking. It was worth every single step we had taken.',
    ipa: null,
    promptKu: 'Bi dengê bilind bixwîne:',
    tipKu: '"Although" /ɔːlˈðoʊ/ — /ð/ nav. "exhausting" /ɪɡˈzɔːstɪŋ/ — /ɡz/ bi hev. "breathtaking" /θ/ + /t/. Ahengek çîrokî veneqetîne, bi rihetî bibêje.',
    acceptableVariants: ['although the journey was long and exhausting we finally reached the mountain peak the view from there was absolutely breathtaking it was worth every single step we had taken'],
  ),
];
