class EnWritingExercise {
  final String id;
  final String level;
  final String type; // 'dictation', 'fill_blank', 'reorder', 'correct'
  final String promptKu;
  final String correctAnswer;
  final List<String>? words;
  final String explanationKu;

  const EnWritingExercise({
    required this.id,
    required this.level,
    required this.type,
    required this.promptKu,
    required this.correctAnswer,
    required this.words,
    required this.explanationKu,
  });
}

const List<EnWritingExercise> kEnWritingExercises = [
  // ============ A1 LEVEL (40) ============
  // --- Dictation A1 (20) ---
  EnWritingExercise(
    id: 'en_write_001',
    level: 'A1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Ez kêfxweş im." Bi Îngilîzî binivîse:',
    correctAnswer: 'I am happy.',
    words: null,
    explanationKu: '"I am" = Ez im. "Happy" = kêfxweş. Formul: I + am + rengdêr.',
  ),
  EnWritingExercise(
    id: 'en_write_002',
    level: 'A1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Navê min Alan e." Bi Îngilîzî binivîse:',
    correctAnswer: 'My name is Alan.',
    words: null,
    explanationKu: '"My name" = navê min. "Is" = e. Formul: My + name + is + nav.',
  ),
  EnWritingExercise(
    id: 'en_write_003',
    level: 'A1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Ew mamoste ye." Bi Îngilîzî binivîse:',
    correctAnswer: 'He is a teacher.',
    words: null,
    explanationKu: '"He is" = Ew (nêr) ye. Navên pîşeyan bi "a/an" re tên.',
  ),
  EnWritingExercise(
    id: 'en_write_004',
    level: 'A1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Em xwendekar in." Bi Îngilîzî binivîse:',
    correctAnswer: 'We are students.',
    words: null,
    explanationKu: '"We are" = Em in. Pirjimarî: student -> students.',
  ),
  EnWritingExercise(
    id: 'en_write_005',
    level: 'A1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Ev kitêbek e." Bi Îngilîzî binivîse:',
    correctAnswer: 'This is a book.',
    words: null,
    explanationKu: '"This is" = Ev... e. "A book" = kitêbek (yek).',
  ),
  EnWritingExercise(
    id: 'en_write_006',
    level: 'A1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Ez sêvekê dixwim." Bi Îngilîzî binivîse:',
    correctAnswer: 'I eat an apple.',
    words: null,
    explanationKu: '"I eat" = Ez dixwim. Berî dengdêran "an" tê: an apple.',
  ),
  EnWritingExercise(
    id: 'en_write_007',
    level: 'A1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Ew av vedixwe." Bi Îngilîzî binivîse:',
    correctAnswer: 'She drinks water.',
    words: null,
    explanationKu: 'She/He/It bi -s digire: drink -> drinks.',
  ),
  EnWritingExercise(
    id: 'en_write_008',
    level: 'A1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Ez diçim dibistanê." Bi Îngilîzî binivîse:',
    correctAnswer: 'I go to school.',
    words: null,
    explanationKu: '"Go to" = biçe bo. "School" = dibistan.',
  ),
  EnWritingExercise(
    id: 'en_write_009',
    level: 'A1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Kêlî çend e?" Bi Îngilîzî binivîse:',
    correctAnswer: 'What time is it?',
    words: null,
    explanationKu: 'Pirsa demê: What time is it? = Kêlî çend e?',
  ),
  EnWritingExercise(
    id: 'en_write_010',
    level: 'A1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Ez pisîkekê dibînim." Bi Îngilîzî binivîse:',
    correctAnswer: 'I see a cat.',
    words: null,
    explanationKu: '"I see" = Ez dibînim. "A cat" = pisîkek.',
  ),
  EnWritingExercise(
    id: 'en_write_011',
    level: 'A1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Ew dibistanê hez dike." Bi Îngilîzî binivîse:',
    correctAnswer: 'He likes school.',
    words: null,
    explanationKu: '"Like" bi "he/she/it" re dibe "likes".',
  ),
  EnWritingExercise(
    id: 'en_write_012',
    level: 'A1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Sibe roja Yekşemê ye." Bi Îngilîzî binivîse:',
    correctAnswer: 'Tomorrow is Sunday.',
    words: null,
    explanationKu: 'Rojên hefteyê herdem bi tîpa mezin dest pê dikin.',
  ),
  EnWritingExercise(
    id: 'en_write_013',
    level: 'A1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Ez 10 salî me." Bi Îngilîzî binivîse:',
    correctAnswer: 'I am 10 years old.',
    words: null,
    explanationKu: 'Temen: I am + jimar + years old.',
  ),
  EnWritingExercise(
    id: 'en_write_014',
    level: 'A1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Tu çawa yî?" Bi Îngilîzî binivîse:',
    correctAnswer: 'How are you?',
    words: null,
    explanationKu: 'Pirsa silavkirinê: How are you?',
  ),
  EnWritingExercise(
    id: 'en_write_015',
    level: 'A1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Ez baş im, spas." Bi Îngilîzî binivîse:',
    correctAnswer: 'I am fine, thank you.',
    words: null,
    explanationKu: '"Fine" = baş. "Thank you" = spas.',
  ),
  EnWritingExercise(
    id: 'en_write_016',
    level: 'A1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Diya min xweş e." Bi Îngilîzî binivîse:',
    correctAnswer: 'My mother is nice.',
    words: null,
    explanationKu: '"My mother" = diya min. "Nice" = xweş.',
  ),
  EnWritingExercise(
    id: 'en_write_017',
    level: 'A1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Ez rengê şîn hez dikim." Bi Îngilîzî binivîse:',
    correctAnswer: 'I like the color blue.',
    words: null,
    explanationKu: '"The color" = reng. "Blue" = şîn.',
  ),
  EnWritingExercise(
    id: 'en_write_018',
    level: 'A1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Hewa îro germ e." Bi Îngilîzî binivîse:',
    correctAnswer: 'The weather is hot today.',
    words: null,
    explanationKu: '"Weather" = hewa. "Hot" = germ. "Today" = îro.',
  ),
  EnWritingExercise(
    id: 'en_write_019',
    level: 'A1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Ez nanî dixwim." Bi Îngilîzî binivîse:',
    correctAnswer: 'I eat bread.',
    words: null,
    explanationKu: '"Bread" (nan) bi gelemperî bê artîkel tê.',
  ),
  EnWritingExercise(
    id: 'en_write_020',
    level: 'A1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Ev malbata min e." Bi Îngilîzî binivîse:',
    correctAnswer: 'This is my family.',
    words: null,
    explanationKu: '"My family" = malbata min. Pêşkêşî: This is...',
  ),

  // --- Fill Blank A1 (12) ---
  EnWritingExercise(
    id: 'en_write_021',
    level: 'A1',
    type: 'fill_blank',
    promptKu: 'Valahiyê dagire (be): "I ___ a student."',
    correctAnswer: 'am',
    words: null,
    explanationKu: 'I + am. "I am a student" = Ez xwendekar im.',
  ),
  EnWritingExercise(
    id: 'en_write_022',
    level: 'A1',
    type: 'fill_blank',
    promptKu: 'Valahiyê dagire (be): "She ___ happy."',
    correctAnswer: 'is',
    words: null,
    explanationKu: 'He/She/It + is. "She is happy" = Ew kêfxweş e.',
  ),
  EnWritingExercise(
    id: 'en_write_023',
    level: 'A1',
    type: 'fill_blank',
    promptKu: 'Valahiyê dagire (be): "We ___ friends."',
    correctAnswer: 'are',
    words: null,
    explanationKu: 'We/You/They + are. "We are friends" = Em heval in.',
  ),
  EnWritingExercise(
    id: 'en_write_024',
    level: 'A1',
    type: 'fill_blank',
    promptKu: 'Valahiyê dagire: "He ___ (go) to school."',
    correctAnswer: 'goes',
    words: null,
    explanationKu: 'Present simple, 3. kesê yekjimar: go -> goes.',
  ),
  EnWritingExercise(
    id: 'en_write_025',
    level: 'A1',
    type: 'fill_blank',
    promptKu: 'Valahiyê dagire: "I ___ (like) apples."',
    correctAnswer: 'like',
    words: null,
    explanationKu: 'I/you/we/they + like (bê -s).',
  ),
  EnWritingExercise(
    id: 'en_write_026',
    level: 'A1',
    type: 'fill_blank',
    promptKu: 'Artîkel dagire: "I see ___ elephant."',
    correctAnswer: 'an',
    words: null,
    explanationKu: 'Berî dengdêran (a,e,i,o,u) "an" tê: an elephant.',
  ),
  EnWritingExercise(
    id: 'en_write_027',
    level: 'A1',
    type: 'fill_blank',
    promptKu: 'Artîkel dagire: "He has ___ dog."',
    correctAnswer: 'a',
    words: null,
    explanationKu: 'Berî dengdarê "a" tê: a dog.',
  ),
  EnWritingExercise(
    id: 'en_write_028',
    level: 'A1',
    type: 'fill_blank',
    promptKu: 'Valahiyê dagire (have/has): "She ___ a book."',
    correctAnswer: 'has',
    words: null,
    explanationKu: 'She/He/It + has. "She has" = ew xwedî ye.',
  ),
  EnWritingExercise(
    id: 'en_write_029',
    level: 'A1',
    type: 'fill_blank',
    promptKu: 'Cînav dagire: "___ name is Alan." (navê min)',
    correctAnswer: 'My',
    words: null,
    explanationKu: '"My" = ya min. "My name" = navê min.',
  ),
  EnWritingExercise(
    id: 'en_write_030',
    level: 'A1',
    type: 'fill_blank',
    promptKu: 'Valahiyê dagire: "I ___ (not) like coffee."',
    correctAnswer: 'do not',
    words: null,
    explanationKu: 'Nefî: do + not. Xeberok: "I do not like" = Ez hez nakim.',
  ),
  EnWritingExercise(
    id: 'en_write_031',
    level: 'A1',
    type: 'fill_blank',
    promptKu: 'Pirs dagire: "___ are you?" (Tu çawa yî?)',
    correctAnswer: 'How',
    words: null,
    explanationKu: '"How" = çawa. "How are you?" = Tu çawa yî?',
  ),
  EnWritingExercise(
    id: 'en_write_032',
    level: 'A1',
    type: 'fill_blank',
    promptKu: 'Jimar dagire: "I have ___ (3) brothers."',
    correctAnswer: 'three',
    words: null,
    explanationKu: 'Jimar bi tîpan: 3 = three.',
  ),

  // --- Reorder A1 (5) ---
  EnWritingExercise(
    id: 'en_write_033',
    level: 'A1',
    type: 'reorder',
    promptKu: 'Kelîmeyan bi rêz bike: (Ez kêfxweş im.)',
    correctAnswer: 'I am happy.',
    words: ['am', 'I', 'happy'],
    explanationKu: 'Rêz: Kesîn + lêker + rengdêr. I + am + happy.',
  ),
  EnWritingExercise(
    id: 'en_write_034',
    level: 'A1',
    type: 'reorder',
    promptKu: 'Kelîmeyan bi rêz bike: (Ew xwendekar e.)',
    correctAnswer: 'She is a student.',
    words: ['student', 'is', 'She', 'a'],
    explanationKu: 'She + is + a + student. Artîkel "a" berî navê pîşeyê.',
  ),
  EnWritingExercise(
    id: 'en_write_035',
    level: 'A1',
    type: 'reorder',
    promptKu: 'Kelîmeyan bi rêz bike: (Ez diçim dibistanê.)',
    correctAnswer: 'I go to school.',
    words: ['to', 'school', 'I', 'go'],
    explanationKu: 'I + go + to + school. "Go to" = biçe bo.',
  ),
  EnWritingExercise(
    id: 'en_write_036',
    level: 'A1',
    type: 'reorder',
    promptKu: 'Kelîmeyan bi rêz bike: (Em heval in.)',
    correctAnswer: 'We are friends.',
    words: ['friends', 'are', 'We'],
    explanationKu: 'We + are + friends. Pirjimar: friend -> friends.',
  ),
  EnWritingExercise(
    id: 'en_write_037',
    level: 'A1',
    type: 'reorder',
    promptKu: 'Kelîmeyan bi rêz bike: (Ew sêvekê dixwe.)',
    correctAnswer: 'He eats an apple.',
    words: ['an', 'eats', 'apple', 'He'],
    explanationKu: 'He + eats + an + apple. Lêker bi -s, artîkel "an" berî "apple".',
  ),

  // --- Correct A1 (3) ---
  EnWritingExercise(
    id: 'en_write_038',
    level: 'A1',
    type: 'correct',
    promptKu: 'Çewtiyê rast bike: "He are teacher."',
    correctAnswer: 'He is a teacher.',
    words: null,
    explanationKu: 'Du çewtî: "are" -> "is" (He ji bo yekjimar), û "a teacher" (artîkel).',
  ),
  EnWritingExercise(
    id: 'en_write_039',
    level: 'A1',
    type: 'correct',
    promptKu: 'Çewtiyê rast bike: "I has a book."',
    correctAnswer: 'I have a book.',
    words: null,
    explanationKu: '"I" bi "have" re tê, ne "has". I + have.',
  ),
  EnWritingExercise(
    id: 'en_write_040',
    level: 'A1',
    type: 'correct',
    promptKu: 'Çewtiyê rast bike: "She go to school."',
    correctAnswer: 'She goes to school.',
    words: null,
    explanationKu: 'She/He/It bi -s/-es: go -> goes.',
  ),

  // ============ A2 LEVEL (30) ============
  // --- Dictation A2 (12) ---
  EnWritingExercise(
    id: 'en_write_041',
    level: 'A2',
    type: 'dictation',
    promptKu: 'Kurmancî: "Duh ez çûm bazarê." Bi Îngilîzî binivîse:',
    correctAnswer: 'Yesterday I went to the market.',
    words: null,
    explanationKu: 'Past simple: go -> went. "Yesterday" = duh.',
  ),
  EnWritingExercise(
    id: 'en_write_042',
    level: 'A2',
    type: 'dictation',
    promptKu: 'Kurmancî: "Wî fîlm temaşe kir." Bi Îngilîzî binivîse:',
    correctAnswer: 'He watched a movie.',
    words: null,
    explanationKu: 'Past simple regular: watch -> watched.',
  ),
  EnWritingExercise(
    id: 'en_write_043',
    level: 'A2',
    type: 'dictation',
    promptKu: 'Kurmancî: "Min nameyek nivîsiye." Bi Îngilîzî binivîse:',
    correctAnswer: 'I have written a letter.',
    words: null,
    explanationKu: 'Present perfect: have + 3. forma lêkerê (write -> written).',
  ),
  EnWritingExercise(
    id: 'en_write_044',
    level: 'A2',
    type: 'dictation',
    promptKu: 'Kurmancî: "Ez ê sibê werim." Bi Îngilîzî binivîse:',
    correctAnswer: 'I will come tomorrow.',
    words: null,
    explanationKu: 'Future: will + lêker. "Tomorrow" = sibê.',
  ),
  EnWritingExercise(
    id: 'en_write_045',
    level: 'A2',
    type: 'dictation',
    promptKu: 'Kurmancî: "Ew li parkê dileyize." Bi Îngilîzî binivîse:',
    correctAnswer: 'She is playing in the park.',
    words: null,
    explanationKu: 'Present continuous: is + lêker-ing.',
  ),
  EnWritingExercise(
    id: 'en_write_046',
    level: 'A2',
    type: 'dictation',
    promptKu: 'Kurmancî: "Em li Stenbolê dijîn." Bi Îngilîzî binivîse:',
    correctAnswer: 'We live in Istanbul.',
    words: null,
    explanationKu: '"Live in" + navê bajêr. Istanbul bi tîpa mezin.',
  ),
  EnWritingExercise(
    id: 'en_write_047',
    level: 'A2',
    type: 'dictation',
    promptKu: 'Kurmancî: "Wê xwarin çêkir." Bi Îngilîzî binivîse:',
    correctAnswer: 'She cooked food.',
    words: null,
    explanationKu: 'Past simple: cook -> cooked (regular).',
  ),
  EnWritingExercise(
    id: 'en_write_048',
    level: 'A2',
    type: 'dictation',
    promptKu: 'Kurmancî: "Ez niha dixwînim." Bi Îngilîzî binivîse:',
    correctAnswer: 'I am reading now.',
    words: null,
    explanationKu: 'Continuous: am + reading. "Now" = niha.',
  ),
  EnWritingExercise(
    id: 'en_write_049',
    level: 'A2',
    type: 'dictation',
    promptKu: 'Kurmancî: "Min ev kitêb xwendiye." Bi Îngilîzî binivîse:',
    correctAnswer: 'I have read this book.',
    words: null,
    explanationKu: 'Present perfect: have + read (3. form). Tecrûbe/encam.',
  ),
  EnWritingExercise(
    id: 'en_write_050',
    level: 'A2',
    type: 'dictation',
    promptKu: 'Kurmancî: "Wan dawî gotin." Bi Îngilîzî binivîse:',
    correctAnswer: 'They said goodbye.',
    words: null,
    explanationKu: 'Past: say -> said. "Goodbye" = dawî/xatir.',
  ),
  EnWritingExercise(
    id: 'en_write_051',
    level: 'A2',
    type: 'dictation',
    promptKu: 'Kurmancî: "Her roj ez stranan guhdar dikim." Bi Îngilîzî binivîse:',
    correctAnswer: 'I listen to songs every day.',
    words: null,
    explanationKu: '"Listen to" pêwîst e. "Every day" = her roj.',
  ),
  EnWritingExercise(
    id: 'en_write_052',
    level: 'A2',
    type: 'dictation',
    promptKu: 'Kurmancî: "Ew nikare were." Bi Îngilîzî binivîse:',
    correctAnswer: 'He cannot come.',
    words: null,
    explanationKu: '"Cannot" = nikare. Modal + lêker (bê to).',
  ),

  // --- Fill Blank A2 (10) ---
  EnWritingExercise(
    id: 'en_write_053',
    level: 'A2',
    type: 'fill_blank',
    promptKu: 'Valahiyê dagire: "I ___ (go) to school yesterday."',
    correctAnswer: 'went',
    words: null,
    explanationKu: 'Past simple: go -> went (irregular).',
  ),
  EnWritingExercise(
    id: 'en_write_054',
    level: 'A2',
    type: 'fill_blank',
    promptKu: 'Valahiyê dagire: "She ___ (eat) dinner an hour ago."',
    correctAnswer: 'ate',
    words: null,
    explanationKu: 'Past simple: eat -> ate.',
  ),
  EnWritingExercise(
    id: 'en_write_055',
    level: 'A2',
    type: 'fill_blank',
    promptKu: 'Valahiyê dagire: "They have ___ (finish) their work."',
    correctAnswer: 'finished',
    words: null,
    explanationKu: 'Present perfect: have + past participle. Finish -> finished.',
  ),
  EnWritingExercise(
    id: 'en_write_056',
    level: 'A2',
    type: 'fill_blank',
    promptKu: 'Valahiyê dagire: "He is ___ (read) a book now."',
    correctAnswer: 'reading',
    words: null,
    explanationKu: 'Present continuous: is + reading (-ing).',
  ),
  EnWritingExercise(
    id: 'en_write_057',
    level: 'A2',
    type: 'fill_blank',
    promptKu: 'Valahiyê dagire: "I ___ (see) her yesterday."',
    correctAnswer: 'saw',
    words: null,
    explanationKu: 'Past: see -> saw. "Yesterday" past simple.',
  ),
  EnWritingExercise(
    id: 'en_write_058',
    level: 'A2',
    type: 'fill_blank',
    promptKu: 'Valahiyê dagire: "We ___ (live) here for 5 years."',
    correctAnswer: 'have lived',
    words: null,
    explanationKu: 'Present perfect "for 5 years": have lived.',
  ),
  EnWritingExercise(
    id: 'en_write_059',
    level: 'A2',
    type: 'fill_blank',
    promptKu: 'Valahiyê dagire: "She ___ (not go) to the party."',
    correctAnswer: 'did not go',
    words: null,
    explanationKu: 'Past nefî: did + not + base form (go).',
  ),
  EnWritingExercise(
    id: 'en_write_060',
    level: 'A2',
    type: 'fill_blank',
    promptKu: 'Valahiyê dagire: "I ___ (be) tired last night."',
    correctAnswer: 'was',
    words: null,
    explanationKu: 'Past of "be": I/he/she/it was.',
  ),
  EnWritingExercise(
    id: 'en_write_061',
    level: 'A2',
    type: 'fill_blank',
    promptKu: 'Valahiyê dagire: "They ___ (be) students last year."',
    correctAnswer: 'were',
    words: null,
    explanationKu: 'Past of "be": we/you/they were.',
  ),
  EnWritingExercise(
    id: 'en_write_062',
    level: 'A2',
    type: 'fill_blank',
    promptKu: 'Preposîsyon dagire: "I am interested ___ music."',
    correctAnswer: 'in',
    words: null,
    explanationKu: '"Interested in" = eleqedar bi. Kollokasyon sabit.',
  ),

  // --- Reorder A2 (5) ---
  EnWritingExercise(
    id: 'en_write_063',
    level: 'A2',
    type: 'reorder',
    promptKu: 'Kelîmeyan bi rêz bike: (Duh ez çûm bazarê.)',
    correctAnswer: 'Yesterday I went to the market.',
    words: ['market', 'I', 'to', 'Yesterday', 'went', 'the'],
    explanationKu: 'Dem + kes + lêker + cih. Yesterday + I + went + to + the + market.',
  ),
  EnWritingExercise(
    id: 'en_write_064',
    level: 'A2',
    type: 'reorder',
    promptKu: 'Kelîmeyan bi rêz bike: (Min nameyek nivîsiye.)',
    correctAnswer: 'I have written a letter.',
    words: ['a', 'written', 'have', 'letter', 'I'],
    explanationKu: 'Present perfect: I + have + written + a + letter.',
  ),
  EnWritingExercise(
    id: 'en_write_065',
    level: 'A2',
    type: 'reorder',
    promptKu: 'Kelîmeyan bi rêz bike: (Ez ê sibê werim.)',
    correctAnswer: 'I will come tomorrow.',
    words: ['tomorrow', 'will', 'come', 'I'],
    explanationKu: 'Future: I + will + come + tomorrow.',
  ),
  EnWritingExercise(
    id: 'en_write_066',
    level: 'A2',
    type: 'reorder',
    promptKu: 'Kelîmeyan bi rêz bike: (Ew niha dileyize.)',
    correctAnswer: 'She is playing now.',
    words: ['playing', 'is', 'now', 'She'],
    explanationKu: 'Continuous: She + is + playing + now.',
  ),
  EnWritingExercise(
    id: 'en_write_067',
    level: 'A2',
    type: 'reorder',
    promptKu: 'Kelîmeyan bi rêz bike: (Em li Amedê dijîn.)',
    correctAnswer: 'We live in Amed.',
    words: ['in', 'live', 'Amed', 'We'],
    explanationKu: 'Live in + bajar. We + live + in + Amed.',
  ),

  // --- Correct A2 (3) ---
  EnWritingExercise(
    id: 'en_write_068',
    level: 'A2',
    type: 'correct',
    promptKu: 'Çewtiyê rast bike: "I goed to school yesterday."',
    correctAnswer: 'I went to school yesterday.',
    words: null,
    explanationKu: '"Go" irregular e: past -> went, ne "goed".',
  ),
  EnWritingExercise(
    id: 'en_write_069',
    level: 'A2',
    type: 'correct',
    promptKu: 'Çewtiyê rast bike: "She have finished her work."',
    correctAnswer: 'She has finished her work.',
    words: null,
    explanationKu: 'She/he/it + has (ne have) + past participle.',
  ),
  EnWritingExercise(
    id: 'en_write_070',
    level: 'A2',
    type: 'correct',
    promptKu: 'Çewtiyê rast bike: "They was happy."',
    correctAnswer: 'They were happy.',
    words: null,
    explanationKu: 'They + were (pirjimar), ne "was".',
  ),

  // ============ B1 LEVEL (20) ============
  // --- Dictation B1 (8) ---
  EnWritingExercise(
    id: 'en_write_071',
    level: 'B1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Eger baran bibare, ez naxwazim derkevim." Bi Îngilîzî binivîse:',
    correctAnswer: 'If it rains, I will not go out.',
    words: null,
    explanationKu: 'First conditional: If + present, will + base. Şert-encam.',
  ),
  EnWritingExercise(
    id: 'en_write_072',
    level: 'B1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Ev kitêb ji aliyê wî ve hat nivîsîn." Bi Îngilîzî binivîse:',
    correctAnswer: 'This book was written by him.',
    words: null,
    explanationKu: 'Passive past: was + past participle + by + agent.',
  ),
  EnWritingExercise(
    id: 'en_write_073',
    level: 'B1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Heger ez dewlemend bûma, dê seyahat bikira." Bi Îngilîzî binivîse:',
    correctAnswer: 'If I were rich, I would travel.',
    words: null,
    explanationKu: 'Second conditional: If + past, would + base. Xeyalî.',
  ),
  EnWritingExercise(
    id: 'en_write_074',
    level: 'B1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Ew ji min mezintir e." Bi Îngilîzî binivîse:',
    correctAnswer: 'He is older than me.',
    words: null,
    explanationKu: 'Comparative: old -> older + than.',
  ),
  EnWritingExercise(
    id: 'en_write_075',
    level: 'B1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Ew mirovê ku duh hat hevalê min e." Bi Îngilîzî binivîse:',
    correctAnswer: 'The man who came yesterday is my friend.',
    words: null,
    explanationKu: 'Relative clause: "who" ji bo mirovan.',
  ),
  EnWritingExercise(
    id: 'en_write_076',
    level: 'B1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Dibe ku ez sibê biçim." Bi Îngilîzî binivîse:',
    correctAnswer: 'I might go tomorrow.',
    words: null,
    explanationKu: 'Modal "might" = dibe ku / îhtîmal. Might + base form.',
  ),
  EnWritingExercise(
    id: 'en_write_077',
    level: 'B1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Divê ew zûtir were." Bi Îngilîzî binivîse:',
    correctAnswer: 'He should come earlier.',
    words: null,
    explanationKu: 'Modal "should" = divê (pêşniyar). Early -> earlier.',
  ),
  EnWritingExercise(
    id: 'en_write_078',
    level: 'B1',
    type: 'dictation',
    promptKu: 'Kurmancî: "Ez ji dû salan vir de li vir dijîm." Bi Îngilîzî binivîse:',
    correctAnswer: 'I have lived here for two years.',
    words: null,
    explanationKu: 'Present perfect: for + dem (berdewamî).',
  ),

  // --- Fill Blank B1 (7) ---
  EnWritingExercise(
    id: 'en_write_079',
    level: 'B1',
    type: 'fill_blank',
    promptKu: 'Valahiyê dagire: "If I ___ (be) you, I would study more."',
    correctAnswer: 'were',
    words: null,
    explanationKu: 'Second conditional: If + were (ji bo hemû kesan).',
  ),
  EnWritingExercise(
    id: 'en_write_080',
    level: 'B1',
    type: 'fill_blank',
    promptKu: 'Valahiyê dagire: "The letter ___ (write) by her."',
    correctAnswer: 'was written',
    words: null,
    explanationKu: 'Passive: was + past participle (write -> written).',
  ),
  EnWritingExercise(
    id: 'en_write_081',
    level: 'B1',
    type: 'fill_blank',
    promptKu: 'Valahiyê dagire: "If it ___ (rain), we will stay home."',
    correctAnswer: 'rains',
    words: null,
    explanationKu: 'First conditional: If + present (rains).',
  ),
  EnWritingExercise(
    id: 'en_write_082',
    level: 'B1',
    type: 'fill_blank',
    promptKu: 'Relative dagire: "The girl ___ is singing is my sister."',
    correctAnswer: 'who',
    words: null,
    explanationKu: '"Who" ji bo mirovan. Relative pronoun.',
  ),
  EnWritingExercise(
    id: 'en_write_083',
    level: 'B1',
    type: 'fill_blank',
    promptKu: 'Modal dagire: "You ___ (must/should) see a doctor." (pêşniyar)',
    correctAnswer: 'should',
    words: null,
    explanationKu: '"Should" = pêşniyar. "Must" = pêwîstiya xurt.',
  ),
  EnWritingExercise(
    id: 'en_write_084',
    level: 'B1',
    type: 'fill_blank',
    promptKu: 'Comparative dagire: "He is ___ (tall) than me."',
    correctAnswer: 'taller',
    words: null,
    explanationKu: 'Comparative: tall -> taller + than.',
  ),
  EnWritingExercise(
    id: 'en_write_085',
    level: 'B1',
    type: 'fill_blank',
    promptKu: 'Superlative dagire: "She is the ___ (good) student."',
    correctAnswer: 'best',
    words: null,
    explanationKu: 'Superlative: good -> the best (irregular).',
  ),

  // --- Reorder B1 (3) ---
  EnWritingExercise(
    id: 'en_write_086',
    level: 'B1',
    type: 'reorder',
    promptKu: 'Kelîmeyan bi rêz bike: (Eger baran bibare, ez li malê dimînim.)',
    correctAnswer: 'If it rains, I will stay home.',
    words: ['rains', 'If', 'stay', 'I', 'home', 'will', 'it'],
    explanationKu: 'First conditional: If + it + rains, I + will + stay + home.',
  ),
  EnWritingExercise(
    id: 'en_write_087',
    level: 'B1',
    type: 'reorder',
    promptKu: 'Kelîmeyan bi rêz bike: (Ev name ji aliyê wê ve hat nivîsîn.)',
    correctAnswer: 'This letter was written by her.',
    words: ['her', 'was', 'by', 'written', 'letter', 'This'],
    explanationKu: 'Passive: This + letter + was + written + by + her.',
  ),
  EnWritingExercise(
    id: 'en_write_088',
    level: 'B1',
    type: 'reorder',
    promptKu: 'Kelîmeyan bi rêz bike: (Divê tu bêhtir bixwînî.)',
    correctAnswer: 'You should study more.',
    words: ['more', 'should', 'study', 'You'],
    explanationKu: 'Modal: You + should + study + more.',
  ),

  // --- Correct B1 (2) ---
  EnWritingExercise(
    id: 'en_write_089',
    level: 'B1',
    type: 'correct',
    promptKu: 'Çewtiyê rast bike: "If I will see him, I will tell you."',
    correctAnswer: 'If I see him, I will tell you.',
    words: null,
    explanationKu: 'First conditional: piştî "if" will nayê, present tê.',
  ),
  EnWritingExercise(
    id: 'en_write_090',
    level: 'B1',
    type: 'correct',
    promptKu: 'Çewtiyê rast bike: "The book was wrote by him."',
    correctAnswer: 'The book was written by him.',
    words: null,
    explanationKu: 'Passive: past participle (written), ne past simple (wrote).',
  ),

  // ============ B2 LEVEL (10) ============
  // --- Dictation B2 (5) ---
  EnWritingExercise(
    id: 'en_write_091',
    level: 'B2',
    type: 'dictation',
    promptKu: 'Kurmancî: "Heger ew zûtir hatiba, me dê fîlm dîtibûya." Bi Îngilîzî binivîse:',
    correctAnswer: 'If he had come earlier, we would have watched the movie.',
    words: null,
    explanationKu: 'Third conditional: If + past perfect, would have + past participle.',
  ),
  EnWritingExercise(
    id: 'en_write_092',
    level: 'B2',
    type: 'dictation',
    promptKu: 'Kurmancî: "Tevî ku ew westiya bû, wî xebata xwe xilas kir." Bi Îngilîzî binivîse:',
    correctAnswer: 'Although he was tired, he finished his work.',
    words: null,
    explanationKu: '"Although" = tevî ku. Komcumle berovajî.',
  ),
  EnWritingExercise(
    id: 'en_write_093',
    level: 'B2',
    type: 'dictation',
    promptKu: 'Kurmancî: "Wî got ku ew ê sibê werin." Bi Îngilîzî binivîse:',
    correctAnswer: 'He said that they would come the next day.',
    words: null,
    explanationKu: 'Reported speech: will -> would, tomorrow -> the next day.',
  ),
  EnWritingExercise(
    id: 'en_write_094',
    level: 'B2',
    type: 'dictation',
    promptKu: 'Kurmancî: "Heke mamoste nebûya, ez ê derbas nebûma." Bi Îngilîzî binivîse:',
    correctAnswer: 'If it had not been for the teacher, I would not have passed.',
    words: null,
    explanationKu: 'Third conditional formulek taybet: "If it had not been for..."',
  ),
  EnWritingExercise(
    id: 'en_write_095',
    level: 'B2',
    type: 'dictation',
    promptKu: 'Kurmancî: "Ew ne tenê jîr e, lê her wiha dilovan jî ye." Bi Îngilîzî binivîse:',
    correctAnswer: 'She is not only smart but also kind.',
    words: null,
    explanationKu: 'Correlative: "not only... but also" = ne tenê... lê her wiha.',
  ),

  // --- Fill Blank B2 (3) ---
  EnWritingExercise(
    id: 'en_write_096',
    level: 'B2',
    type: 'fill_blank',
    promptKu: 'Valahiyê dagire: "If she ___ (study) harder, she would have passed."',
    correctAnswer: 'had studied',
    words: null,
    explanationKu: 'Third conditional: If + had + past participle.',
  ),
  EnWritingExercise(
    id: 'en_write_097',
    level: 'B2',
    type: 'fill_blank',
    promptKu: 'Valahiyê dagire: "He told me that he ___ (be) tired." (reported)',
    correctAnswer: 'was',
    words: null,
    explanationKu: 'Reported speech: is -> was (dem yek paş).',
  ),
  EnWritingExercise(
    id: 'en_write_098',
    level: 'B2',
    type: 'fill_blank',
    promptKu: 'Valahiyê dagire: "___ (despite/although) the rain, we went out."',
    correctAnswer: 'Despite',
    words: null,
    explanationKu: '"Despite" + navdêr. "Although" + komcumle.',
  ),

  // --- Reorder B2 (1) ---
  EnWritingExercise(
    id: 'en_write_099',
    level: 'B2',
    type: 'reorder',
    promptKu: 'Kelîmeyan bi rêz bike: (Heger min bizaniya, min ê ji te re bigota.)',
    correctAnswer: 'If I had known, I would have told you.',
    words: ['known', 'I', 'told', 'If', 'have', 'had', 'you', 'would', 'I'],
    explanationKu: 'Third conditional: If + had + known, + would have + told.',
  ),

  // --- Correct B2 (1) ---
  EnWritingExercise(
    id: 'en_write_100',
    level: 'B2',
    type: 'correct',
    promptKu: 'Çewtiyê rast bike: "If I would have known, I would have come."',
    correctAnswer: 'If I had known, I would have come.',
    words: null,
    explanationKu: 'Third conditional: "If" bi "had + past participle" re, ne "would have".',
  ),
];
