import 'lesson_entities.dart';
import 'b1_kelime_db.dart';

// ════════════════════════════════════════════════════════════════
// B1 — 30 DERS TANIMI (Navîn-Jêr / Orta-Alt)
//
// Müfredat: kurmanci_duzey_icerikleri.md — B1 bölümü
// Kaynak: [BH] §170–195 + [TH] §70–82 + [AZ] Ders 13–18
//
// Pedagoji sırası:
//   1. Ergatif tam sistem (4 ders) — en kritik konu
//   2. Geçmiş zaman türleri (3 ders)
//   3. Subjunctive / İstek-olasılık kipi (3 ders)
//   4. Pasif yapı (2 ders)
//   5. Bağımlı cümleler / Complex sentences (3 ders)
//   6. Konu dersleri: Sağlık, Kültür, Ekoloji, Kimlik... (15 ders)
// ════════════════════════════════════════════════════════════════

List<String> _b1Cards(List<String> katlar) => kB1TamListe
    .where((k) => katlar.contains(k.kat))
    .map((k) => k.id)
    .toList();

ExerciseModel _mc({
  required String id, required String ku, required String tr,
  required List<String> opts, required int ci,
  String? note, int xp = 10,
}) => ExerciseModel(
  id: id, type: ExerciseType.multipleChoice,
  kurmanjPrompt: ku, turkishPrompt: tr,
  options: opts, correctAnswer: opts[ci], correctIndex: ci,
  grammarNote: note, xpReward: xp,
);

ExerciseModel _ls({
  required String id, required String ku, required String tr,
  required List<String> opts, required int ci,
  String? audio, String? note, int xp = 10,
}) => ExerciseModel(
  id: id, type: ExerciseType.listenAndSelect,
  kurmanjPrompt: ku, turkishPrompt: tr,
  options: opts, correctAnswer: opts[ci], correctIndex: ci,
  audioAsset: audio, grammarNote: note, xpReward: xp,
);

ExerciseModel _fill({
  required String id, required String before, required String after,
  required String tr, required List<String> opts, required int ci,
  String? note, int xp = 12,
}) => ExerciseModel(
  id: id, type: ExerciseType.fillInBlank,
  kurmanjPrompt: '$before ___ $after', turkishPrompt: tr,
  options: opts, correctAnswer: opts[ci], correctIndex: ci,
  grammarNote: note, xpReward: xp,
  wordPieces: [before.trim(), after.trim()],
);

ExerciseModel _speak({
  required String id, required String ku, required String tr,
  int xp = 15,
}) => ExerciseModel(
  id: id, type: ExerciseType.speakingPractice,
  kurmanjPrompt: ku, turkishPrompt: tr,
  options: ['Gelek baş', 'Nêzîk', 'Carek din'],
  correctAnswer: ku, xpReward: xp,
);

// ════════════════════════════════════════════════════════════════
// 30 DERS
// ════════════════════════════════════════════════════════════════

final kB1Lessons = <LessonModel>[

  // ─────────────────────────────────────────────────────────────
  // ÜNİTE 1 — Ergatif Yapı: Geçişli Geçmiş Zaman (4 ders)
  // [BH] §170–180 + [TH] §75–78
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'b1_l01',
    kurmanjTitle: 'Çima Min û Ez Cûda Ne?',
    turkishTitle: 'Neden Min ve Ez Farklı?',
    unitNumber: 1, lessonNumber: 1, level: 3,
    path: LessonPath.general,
    targetCardIds: _b1Cards(['ergatif']).take(4).toList(),
    estimatedMinutes: 14,
    exercises: [
      _mc(id:'b1_l01_e1',
        ku:'Kurmancî\'de neden iki tür geçmiş zaman var?',
        tr:'Doğru açıklamayı seç',
        opts:['Tesadüf','Geçişli/geçişsiz fiil ayrımı — ergatif','Lehçe farkı','Yazım hatası'],
        ci:1, note:'Bölünmüş ergatiflik (split ergativity): geçişsiz fiilde özne yalın, geçişli fiilde özne eğik hale girer. [BH] §170'),
      _mc(id:'b1_l01_e2',
        ku:'"Ew hat" — "hat" geçişli mi yoksa geçişsiz mi?',
        tr:'Doğru cevabı seç',
        opts:['Geçişli — ergatif gerektirir','Geçişsiz — özne yalın halde kalır','İkisi de olabilir','Bilinmiyor'],
        ci:1, note:'"Hatin" = gelmek — geçişsiz fiil. Dolayısıyla özne yalın: "Ew hat" (o geldi). Ergatif gerekmez.'),
      _mc(id:'b1_l01_e3',
        ku:'"Ez nanê dixwim" şimdiki zamanda doğru. Geçmişte nasıl olur?',
        tr:'Ergatif dönüşümü seç',
        opts:['Ez nan xwar','Min nan xwar','Ez nan xwarî','Me nan xwar'],
        ci:1, note:'Şimdiki: "Ez … dixwim" (nominatif). Geçmiş + geçişli: "Min … xwar" (ergatif: Ez → Min). [TH] §76'),
      _fill(id:'b1_l01_e4', before:'', after:'pirtûk xwend.',
        tr:'O (eril) kitap okudu.',
        opts:['Ew','Wî','Wê','Me'], ci:1,
        note:'"Xwendin" geçişli → ergatif. Eril "ew" → eğik hali "wî"'),
      _fill(id:'b1_l01_e5', before:'', after:'stran got.',
        tr:'O (dişil) şarkı söyledi.',
        opts:['Ew','Wî','Wê','Me'], ci:2,
        note:'Dişil "ew" → eğik hali "wê". "Gotin" geçişli → ergatif'),
      _speak(id:'b1_l01_e6',
        ku:'Min got, te bîst, wê kir, me dît!',
        tr:'Ben söyledim, sen duydun, o yaptı, biz gördük!'),
    ],
  ),

  LessonModel(
    id: 'b1_l02',
    kurmanjTitle: 'Min Got — Tam Çekim',
    turkishTitle: 'Ergatif Tam Çekim Tablosu',
    unitNumber: 1, lessonNumber: 2, level: 3,
    path: LessonPath.general,
    targetCardIds: _b1Cards(['ergatif']),
    estimatedMinutes: 14,
    exercises: [
      _mc(id:'b1_l02_e1',
        ku:'"Wan got" cümlesinde "wan" neden?',
        tr:'Doğru açıklamayı seç',
        opts:['Wan = onlar (nominatif)','Wan = ew\'in eğik hali (çoğul ergatif)','Yanlış — ew olmalı','Wan yalnız çoğul için'],
        ci:1, note:'"Wan" = "ew" (çoğul)\'un eğik hali. [BH] §170: tüm çoğul ergatif "wan" kullanır'),
      _fill(id:'b1_l02_e2', before:'', after:'nanê xwar.',
        tr:'Biz ekmek yedik.',
        opts:['Em','Me','Wan','We'], ci:1,
        note:'"Me" = "em"in eğik hali. "Xwarin" geçişli → ergatif'),
      _fill(id:'b1_l02_e3', before:'', after:'vîdyo dît.',
        tr:'Siz video gördünüz.',
        opts:['Hûn','We','Wan','Me'], ci:1,
        note:'"We" = "hûn"un eğik hali'),
      _mc(id:'b1_l02_e4',
        ku:'Ergatif çekimde hangi zamirler değişmez?',
        tr:'Doğru cevabı seç',
        opts:['Hiçbiri değişmez','Hepsi değişir — Ez→Min, Tu→Te, Ew→Wî/Wê, Em→Me, Hûn→We, Ew(çoğ)→Wan','Sadece tekiller','Sadece çoğullar'],
        ci:1, note:'Tam çekim: Ez→Min / Tu→Te / Ew(eril)→Wî / Ew(diş)→Wê / Em→Me / Hûn→We / Ew(çoğ)→Wan'),
      _speak(id:'b1_l02_e5',
        ku:'Min got — te got — wî got — wê got — me got — we got — wan got.',
        tr:'Ben söyledim — sen söyledin — o (eril) söyledi — o (dişil) söyledi — biz söyledik — siz söylediniz — onlar söyledi.'),
    ],
  ),

  LessonModel(
    id: 'b1_l03',
    kurmanjTitle: 'Kîjan Fiil Ergatîf Dixwaze?',
    turkishTitle: 'Hangi Fiil Ergatif İster?',
    unitNumber: 1, lessonNumber: 3, level: 3,
    path: LessonPath.heritage,
    targetCardIds: _b1Cards(['ergatif']).skip(3).toList(),
    estimatedMinutes: 14,
    exercises: [
      _mc(id:'b1_l03_e1',
        ku:'Ergatif hangi fiillerde kullanılır?',
        tr:'Doğru kuralı seç',
        opts:['Tüm fiillerde','Yalnızca geçmişte geçişli fiillerde','Yalnızca gelecekte','Bağımsız değil'],
        ci:1, note:'Kural: SADECE geçmiş zaman + geçişli fiil = ergatif. Şimdiki/gelecek + geçişli = nominatif. Geçmiş + geçişsiz = nominatif.'),
      _mc(id:'b1_l03_e2',
        ku:'"Pîrê hat" — ergatif mi?',
        tr:'Doğru cevabı seç',
        opts:['Evet — "pîrê" eğik olmalı','Hayır — hatin geçişsiz, nominatif doğru','Yanlış cümle','İkisi de olur'],
        ci:1, note:'"Hatin" = gelmek (geçişsiz) → nominatif. "Pîrê hat" doğru. Eğik "pîrê" değil.'),
      _mc(id:'b1_l03_e3',
        ku:'"Pîrê stran got" doğru mu?',
        tr:'Dilbilgisel analizi yap',
        opts:['Evet — gotin geçişli ama "pîrê" doğal hal','Hayır — "wê stran got" olmalı / ya da "pîrêya..." ','İkisi de doğru','Hiçbiri doğru değil'],
        ci:1, note:'Geçişli fiil + isim özne: İsim de eğik hale girer. "Pîrê" → "Pîrê" (aynı — eril gibi). Aslında serbest kullanım var; "Pîrê got" yaygın kabul görür.'),
      _fill(id:'b1_l03_e4', before:'Dêya min', after:'goşt pijand.',
        tr:'Annem et pişirdi. (deyim)',
        opts:['dêya min','diya min','wê','min'], ci:2,
        note:'İsim özne ergatif: "Dêya min" → dişil → özne "wê" eğik ile ifade edilir ya da isim doğrudan bırakılır (lehçeye göre)'),
      _speak(id:'b1_l03_e5',
        ku:'Min got, pîrê hat, wê stran got, me bîst.',
        tr:'Ben söyledim, büyükanne geldi, o şarkı söyledi, biz duyduk.'),
    ],
  ),

  LessonModel(
    id: 'b1_l04',
    kurmanjTitle: 'Pîrêya Min Çîrok Got',
    turkishTitle: 'Büyükannem Hikâye Anlattı — Pratik',
    unitNumber: 1, lessonNumber: 4, level: 3,
    path: LessonPath.heritage,
    targetCardIds: _b1Cards(['ergatif', 'deyim']).take(8).toList(),
    culturalRewardId: 'c_003',
    estimatedMinutes: 15,
    exercises: [
      _ls(id:'b1_l04_e1', ku:'Wê got ku pîrê tê.',
        tr:'Bu cümle ne anlama gelir?',
        opts:['O geldi','O dedi ki büyükanne geliyor','Büyükanne söyledi','Ben söyledim'],
        ci:1, audio:'assets/audio/b1/we_got_ku.mp3',
        note:'"Wê got ku…" = o (dişil) dedi ki… Dolaylı anlatım + ergatif'),
      _fill(id:'b1_l04_e2', before:'Pîrê', after:'çîrokeke xweş got.',
        tr:'Büyükannem güzel bir hikâye anlattı.',
        opts:['min','te','wê','me'], ci:2,
        note:'"Pîrê" dişil özne → ergatif: wê. "Gotin" geçişli.'),
      _mc(id:'b1_l04_e3',
        ku:'"Me çîrok bîst" doğru mu?',
        tr:'Ergatif kontrolü',
        opts:['Evet — me = em eğik hali, bîstin geçişli → doğru','Hayır — bîstin geçişsiz','Hayır — me yerine em olmalı','İkisi de doğru'],
        ci:0, note:'"Bîstin" = duymak (geçişli) → ergatif. Me = em\'in eğik hali ✓'),
      _fill(id:'b1_l04_e4', before:'', after:'navê xwe got.',
        tr:'O adını söyledi. (Bilinmiyor eril mi dişil mi)',
        opts:['Ew','Wî','Wê','Wan'], ci:0,
        note:'Cinsiyet bilinmiyorsa "ew" de kabul görür ama teknik olarak eğik form gerekir. Bağlamdan anlaşılır.'),
      _speak(id:'b1_l04_e5',
        ku:'Pîrêya min çîrokeke xweş got. Me guhdarî kir û me hez kir!',
        tr:'Büyükannem güzel bir hikâye anlattı. Biz dinledik ve sevdik!'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // ÜNİTE 2 — Geçmiş Zaman Türleri (3 ders)
  // [BH] §182–186 + [TH] §70–73
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'b1_l05',
    kurmanjTitle: 'Digot, Dihat — Sürekli Geçmiş',
    turkishTitle: 'Hikâye Kipi: Sürekli Geçmiş',
    unitNumber: 2, lessonNumber: 1, level: 3,
    path: LessonPath.heritage,
    targetCardIds: _b1Cards(['dem_devam']),
    estimatedMinutes: 13,
    exercises: [
      _mc(id:'b1_l05_e1',
        ku:'"Pîrê timî dihat malê" ne anlama gelir?',
        tr:'Doğru çeviriyi seç',
        opts:['Büyükanne geldi','Büyükanne her zaman gelirdi','Büyükanne gelecek','Büyükanne gelmiyordu'],
        ci:1, note:'"Dihat" = sürekli geçmiş (imperfect). "Timî dihat" = her zaman gelirdi. [TH] §70: imperfect aspect'),
      _mc(id:'b1_l05_e2',
        ku:'Sürekli geçmiş nasıl yapılır?',
        tr:'Doğru kuralı seç',
        opts:['Kök + -iye','"di-" + geçmiş kök + kişi eki','"dê" + şimdiki','"hat" + mastar'],
        ci:1, note:'"di-xwend-im" = okuyordum. "di-" şimdiki öneki + geçmiş kök + kişi eki. [BH] §182'),
      _fill(id:'b1_l05_e3', before:'Bavê min her sibê', after:'.',
        tr:'Babam her sabah okurdu.',
        opts:['dixwîne','dixwend','xwend','dixwînim'], ci:1,
        note:'"Dixwend" = okuyordu/okurdu (sürekli geçmiş 3.tekil)'),
      _fill(id:'b1_l05_e4', before:'Pîrê her êvarê stran', after:'.',
        tr:'Büyükanne her akşam şarkı söylerdi.',
        opts:['dibêje','digot','got','dibêjim'], ci:1,
        note:'"Digot" = söylerdi/diyordu (sürekli geçmiş 3.tekil gotin)'),
      _speak(id:'b1_l05_e5',
        ku:'Pîrê timî dihat. Wê çîrok digot û em guhdarî dikirin.',
        tr:'Büyükanne her zaman gelirdi. Hikâye anlatırdı ve biz dinlerdik.'),
    ],
  ),

  LessonModel(
    id: 'b1_l06',
    kurmanjTitle: 'Gotiye — Şimdiki Mükemmel',
    turkishTitle: 'Şimdiki Mükemmel: -iye Eki',
    unitNumber: 2, lessonNumber: 2, level: 3,
    path: LessonPath.general,
    targetCardIds: _b1Cards(['dem_temam']),
    estimatedMinutes: 13,
    exercises: [
      _mc(id:'b1_l06_e1',
        ku:'"Pîrê hatiye" ile "pîrê hat" arasındaki fark nedir?',
        tr:'Doğru açıklamayı seç',
        opts:['Aynı anlam','Hat = geçti-bitti; hatiye = geldi ve hâlâ burada (şimdiye etkisi)','Hatiye daha eski','Hat daha kibar'],
        ci:1, note:'Şimdiki mükemmel (-iye): geçmişte oldu, şimdi hâlâ etkisi var. [TH] §72: present perfect'),
      _fill(id:'b1_l06_e2', before:'Bavê min', after:'.',
        tr:'Babam gelmiş (ve burada).',
        opts:['hat','hatiye','tê','dihê'], ci:1,
        note:'"Hatiye" = geçişsiz şimdiki mükemmel. Özne yalın halde (nominatif)'),
      _mc(id:'b1_l06_e3',
        ku:'"Min pirtûk xwendiye" doğru mu?',
        tr:'Dilbilgisel kontrol',
        opts:['Evet — min ergatif + xwend + iye = şimdiki mükemmel geçişli','Hayır — min yerine ez olmalı','Hayır — iye eki yanlış','İkisi de doğru'],
        ci:0, note:'Geçişli şimdiki mükemmel: ergatif özne + kök + -iye. [BH] §186'),
      _fill(id:'b1_l06_e4', before:'Te', after:'kir.',
        tr:'Sen yapmışsın / yaptın (etkisi var).',
        opts:['kir','kiriye','dike','kira'], ci:1,
        note:'"Te kiriye" = sen yapmışsın. Te = tu eğik (ergatif) + kir + iye'),
      _speak(id:'b1_l06_e5',
        ku:'Pîrê hatiye! Min got û tu bîstiye!',
        tr:'Büyükanne gelmiş! Ben söyledim ve sen duydun!'),
    ],
  ),

  LessonModel(
    id: 'b1_l07',
    kurmanjTitle: 'Gotibû — Geçmiş Mükemmel',
    turkishTitle: 'Geçmiş Mükemmel: -ibû Eki',
    unitNumber: 2, lessonNumber: 3, level: 3,
    path: LessonPath.general,
    targetCardIds: _b1Cards(['dem_temam', 'dem_devam']).skip(2).toList(),
    estimatedMinutes: 13,
    exercises: [
      _mc(id:'b1_l07_e1',
        ku:'"Pîrê hatibû" ne anlama gelir?',
        tr:'Doğru çeviriyi seç',
        opts:['Büyükanne geliyor','Büyükanne geldi','Büyükanne gelmişti (önceki geçmişte)','Büyükanne gelecek'],
        ci:2, note:'Geçmiş mükemmel (-ibû): başka bir geçmiş olaydan da önce gerçekleşmiş. [TH] §73: past perfect'),
      _mc(id:'b1_l07_e2',
        ku:'Geçmiş mükemmel ne zaman kullanılır?',
        tr:'Doğru bağlamı seç',
        opts:['Her zaman','İki geçmiş olaydan daha önceki için','Gelecekte','Şimdiki zamanda'],
        ci:1, note:'"Ew hatibû, lê ez nehatim" = O gelmişti ama ben gelmedim. "-ibû" önce olan geçmiş için.'),
      _fill(id:'b1_l07_e3', before:'Min pirtûk', after:', berî ku tu bêyî.',
        tr:'Sen gelmeden önce ben kitabı okumuştum.',
        opts:['xwend','xwendibû','dixwend','xwendiye'], ci:1,
        note:'"Xwendibû" = okumuştu (geçmiş mükemmel geçişli, min ergatif zaten anlaşılıyor)'),
      _speak(id:'b1_l07_e6',
        ku:'Pîrê çûbû. Dema ku em hatim, mal vala bû.',
        tr:'Büyükanne gitmişti. Biz geldiğimizde ev boştu.'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // ÜNİTE 3 — Subjunctive / İstek-Olasılık Kipi (3 ders)
  // [BH] §190 + [TH] §78–79 + [AZ] Ders 16–17
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'b1_l08',
    kurmanjTitle: 'Bixwim, Biçim — Subjunctive',
    turkishTitle: 'İstek Kipi: bi- Öneki',
    unitNumber: 3, lessonNumber: 1, level: 3,
    path: LessonPath.general,
    targetCardIds: _b1Cards(['subjunctive']).take(3).toList(),
    estimatedMinutes: 13,
    exercises: [
      _mc(id:'b1_l08_e1',
        ku:'Subjunctive (istek kipi) nasıl yapılır?',
        tr:'Doğru kuralı seç',
        opts:['di- + kök + kişi eki','bi- + kök + kişi eki','kök + -iye','dê + şimdiki'],
        ci:1, note:'"Bi-" öneki + kök + kişi eki. "Bixwim" = yiyeyim/yemem gerek. [BH] §190: subjunctive mood'),
      _fill(id:'b1_l08_e2', before:'Ez dixwazim', after:'.',
        tr:'Ben gitmek istiyorum.',
        opts:['diçim','biçim','çûm','naçim'], ci:1,
        note:'"Dixwazim + biçim" = gitmek istiyorum. Subjunctive "biçim" dixwazim\'den sonra gelir.'),
      _mc(id:'b1_l08_e3',
        ku:'"Dikarî bibêjî?" ne anlama gelir?',
        tr:'Doğru çeviriyi seç',
        opts:['Söyledin mi?','Söyleyebilir misin?','Söylüyorsun','Söylemeyeceksin'],
        ci:1, note:'"Dikarî" = yapabilirsin + "bibêjî" (subjunctive) = söyleme eylemi. İzin/olasılık'),
      _mc(id:'b1_l08_e4',
        ku:'"Divê tu bixwî" ne anlama gelir?',
        tr:'Doğru çeviriyi seç',
        opts:['Yemek istiyorsun','Yemedin','Yemen gerekiyor','Yiyeceksin'],
        ci:2, note:'"Divê" = gereklidir + subjunctive. "Divê tu bixwî" = yemen gerekiyor. [TH] §78'),
      _speak(id:'b1_l08_e5',
        ku:'Ez dixwazim bixwim. Dikarî alîkariyê bikî? Divê em biçin!',
        tr:'Yemek istiyorum. Yardım edebilir misin? Gitmemiz gerekiyor!'),
    ],
  ),

  LessonModel(
    id: 'b1_l09',
    kurmanjTitle: 'Ji Bo Ku — Amaç Cümleleri',
    turkishTitle: 'Amaç Cümleleri: Ji Bo Ku',
    unitNumber: 3, lessonNumber: 2, level: 3,
    path: LessonPath.general,
    targetCardIds: _b1Cards(['subjunctive', 'daçek']).take(5).toList(),
    estimatedMinutes: 12,
    exercises: [
      _mc(id:'b1_l09_e1',
        ku:'"Ji bo ku" + hangi kip?',
        tr:'Doğru yapıyı seç',
        opts:['Şimdiki zaman','Geçmiş zaman','Subjunctive (bi- kipi)','Gelecek zaman'],
        ci:2, note:'"Ji bo ku bibêjim" = söylemek için. Amaç cümleleri subjunctive gerektirir. [TH] §78'),
      _fill(id:'b1_l09_e2', before:'Ez diçim xwendegehê ji bo ku', after:'.',
        tr:'Kurmancî öğrenmek için okula gidiyorum.',
        opts:['hîn dibim','hîn bibim','hîn bûm','hîn dikim'], ci:1,
        note:'"Ji bo ku hîn bibim" = öğrenmek için (subjunctive: hîn + bi + im)'),
      _mc(id:'b1_l09_e3',
        ku:'"Bila pîrê bê!" ne tür bir ifade?',
        tr:'Doğru tanımı seç',
        opts:['Soru','Dilek/istek ifadesi (subjunctive)','Emir','Gelecek zaman'],
        ci:1, note:'"Bila" + subjunctive = dilek/temenn. "Bila bê" = gelsin. [BH] §190'),
      _fill(id:'b1_l09_e3b', before:'Divê em', after:'berî ku hewa xirab bibe.',
        tr:'Hava bozulmadan gitmemiz gerekiyor.',
        opts:['diçin','biçin','çûn','naçin'], ci:1),
      _speak(id:'b1_l09_e4',
        ku:'Ji bo ku Kurmancî hîn bibim, ez gelek dixwînim. Bila ziman bijî!',
        tr:'Kurmancî öğrenmek için çok okuyorum. Dil yaşasın!'),
    ],
  ),

  LessonModel(
    id: 'b1_l10',
    kurmanjTitle: 'Ger Bêyî — Şartlı Cümleler',
    turkishTitle: 'Şartlı Cümleler: Ger + Subjunctive',
    unitNumber: 3, lessonNumber: 3, level: 3,
    path: LessonPath.general,
    targetCardIds: _b1Cards(['subjunctive', 'daçek']).skip(3).toList(),
    estimatedMinutes: 12,
    exercises: [
      _mc(id:'b1_l10_e1',
        ku:'"Ger bêyî, ez jî bêm" yapısı nedir?',
        tr:'Doğru açıklamayı seç',
        opts:['Gelecek zaman','Şartlı cümle: ger + subjunctive + subjunctive','Geçmiş','Edilgen'],
        ci:1, note:'"Ger + subjunctive, ... + subjunctive" = gerçekleşebilir şart. [TH] §79'),
      _fill(id:'b1_l10_e2', before:'Ger hewa baş be, em', after:'.',
        tr:'Hava güzelse gideceğiz.',
        opts:['diçin','biçin','çûn','naçin'], ci:1,
        note:'"Ger ... be, ... biçin" — iki subjunctive. Ya da: "ger baş be, em diçin" (şimdiki)'),
      _mc(id:'b1_l10_e3',
        ku:'"Ger dizanibûm, nedigotim" yapısı — geçmiş şart:',
        tr:'Doğru açıklamayı seç',
        opts:['Gerçekleşmiş şart','Gerçekleşmemiş geçmiş şart (-ibûm / -iya)','Gelecek şart','Pasif şart'],
        ci:1, note:'"Ger ... -ibûm, ne-digotim" = bilseydim söylemezdim. Gerçekleşmemiş. [BH] §192'),
      _speak(id:'b1_l10_e4',
        ku:'Ger pîrê were, em gelek şa dibin! Ger neyê, dê kovan bibin.',
        tr:'Büyükanne gelirse çok mutlu oluruz! Gelmezse üzgün olurlar.'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // ÜNİTE 4 — Pasif Yapı (2 ders)
  // [BH] §193 + [TH] §82
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'b1_l11',
    kurmanjTitle: 'Tê Kirin — Pasif Yapı',
    turkishTitle: 'Edilgen Yapı: Tê + Mastar',
    unitNumber: 4, lessonNumber: 1, level: 3,
    path: LessonPath.general,
    targetCardIds: [],
    estimatedMinutes: 13,
    exercises: [
      _mc(id:'b1_l11_e1',
        ku:'"Tê gotin ku…" ne anlama gelir?',
        tr:'Doğru çeviriyi seç',
        opts:['O söylüyor','Denilir ki…','Ben söyledim','Söyleyecek'],
        ci:1, note:'"Tê" (hatin 3.tekil şimdiki) + mastar = pasif. "Tê gotin" = söyleniyor/deniliyor. [TH] §82'),
      _fill(id:'b1_l11_e2', before:'', after:'gotin ku Kurdistan xweş e.',
        tr:'Kürdistan\'ın güzel olduğu söylenir.',
        opts:['Ez','Ew','Tê','Hate'], ci:2,
        note:'"Tê gotin ku…" = denilir ki… Şimdiki pasif'),
      _mc(id:'b1_l11_e3',
        ku:'"Hate kirin" yapısı ne zamanı gösterir?',
        tr:'Doğru zamanı seç',
        opts:['Şimdiki','Geçmiş','Gelecek','Şart'],
        ci:1, note:'"Hate" (hatin geçmiş 3.tekil) + mastar = geçmiş pasif. "Hate kirin" = yapıldı. [BH] §193'),
      _fill(id:'b1_l11_e4', before:'Pirsgirêk', after:'çarakirin.',
        tr:'Sorun çözüldü.',
        opts:['tê','hate','bê','dê'], ci:1,
        note:'"Hate çarakirin" = çözüldü (geçmiş pasif)'),
      _speak(id:'b1_l11_e5',
        ku:'Tê gotin ku ziman jiyan e. Û ev rast hatiye gotin!',
        tr:'Dil hayattır denilir. Ve bu doğru söylenmiştir!'),
    ],
  ),

  LessonModel(
    id: 'b1_l12',
    kurmanjTitle: 'Bête Zanîn — Resmi Pasif',
    turkishTitle: 'Resmi Pasif: Gazete Dili',
    unitNumber: 4, lessonNumber: 2, level: 3,
    path: LessonPath.general,
    targetCardIds: [],
    estimatedMinutes: 12,
    exercises: [
      _mc(id:'b1_l12_e1',
        ku:'"Dê bête kirin" yapısı nedir?',
        tr:'Doğru açıklamayı seç',
        opts:['Şimdiki pasif','Geçmiş pasif','Gelecek pasif','Şart pasif'],
        ci:2, note:'"Dê" (gelecek) + "bê" (bûn subjunctive) + mastar = gelecek pasif. [TH] §82'),
      _fill(id:'b1_l12_e2', before:'Pirsgirêk', after:'çarakirin.',
        tr:'Sorun çözülecek.',
        opts:['tê','hate','dê bête','bête'], ci:2,
        note:'"Dê bête çarakirin" = çözülecek (gelecek pasif)'),
      _mc(id:'b1_l12_e3',
        ku:'Gazete dilinde en çok hangi pasif formu kullanılır?',
        tr:'Doğru seçeneği seç',
        opts:['"Tê gotin" şimdiki','"Hate kirin" geçmiş','"Bête zanîn" — her ikisi de yaygın','Pasif kullanılmaz'],
        ci:2, note:'"Wek ku bête zanîn" = bilindiği gibi. Haber dilinde çok yaygın.'),
      _speak(id:'b1_l12_e4',
        ku:'Tê gotin ku guhertin tê. Dê bête dîtin ku ev rast e.',
        tr:'Değişimin geleceği söyleniyor. Bunun doğru olduğu görülecek.'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // ÜNİTE 5 — Bağımlı Cümleler (3 ders)
  // [TH] §: complex sentences + [AZ] Ders 14–15
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'b1_l13',
    kurmanjTitle: 'Ko/Ku — Bağımlı Cümleler',
    turkishTitle: 'Ki Bağlacı: Dolaylı Anlatım',
    unitNumber: 5, lessonNumber: 1, level: 3,
    path: LessonPath.heritage,
    targetCardIds: _b1Cards(['daçek']).take(4).toList(),
    estimatedMinutes: 12,
    exercises: [
      _mc(id:'b1_l13_e1',
        ku:'"Wî got ku pîrê tê" yapısında "ku" ne işlev görür?',
        tr:'Doğru açıklamayı seç',
        opts:['Soru başlatır','Bağımlı cümle başlatır (dolaylı anlatım)','Olumsuz yapar','Zarf ekler'],
        ci:1, note:'"Ku" = ki. Dolaylı anlatım bağlacı. "Wî got ku…" = o dedi ki… [TH] §: reported speech'),
      _fill(id:'b1_l13_e2', before:'Ez dizanim', after:'pîrê tê.',
        tr:'Büyükannenin geleceğini biliyorum.',
        opts:['ku','ger','heta','ji ber'], ci:0,
        note:'"Ez dizanim ku…" = biliyorum ki…'),
      _mc(id:'b1_l13_e3',
        ku:'"Nizanim kî hat" yapısında "kî" neden?',
        tr:'Doğru açıklamayı seç',
        opts:['Soru zamiri','Bağımlı soru zamiri — kimin geldiğini bilmiyorum','Özne','Nesne zamiri'],
        ci:1, note:'Bağımlı soru zamiri: "Nizanim kî hat" = kimin geldiğini bilmiyorum. [TH] §: indirect questions'),
      _fill(id:'b1_l13_e4', before:'Pîrê got', after:'xwarin amade ye.',
        tr:'Büyükanne yemeğin hazır olduğunu söyledi.',
        opts:['ger','ku','heta','lê'], ci:1),
      _speak(id:'b1_l13_e5',
        ku:'Ez dizanim ku pîrê hez dike. Ew got ku ziman jiyan e.',
        tr:'Büyükannenin sevdiğini biliyorum. O dedi ki dil hayattır.'),
    ],
  ),

  LessonModel(
    id: 'b1_l14',
    kurmanjTitle: 'Ko/Dema Ku — Zaman Bağlaçları',
    turkishTitle: 'Zaman Bağlaçları: Dema Ku, Berî Ku',
    unitNumber: 5, lessonNumber: 2, level: 3,
    path: LessonPath.general,
    targetCardIds: _b1Cards(['daçek']).skip(2).toList(),
    estimatedMinutes: 12,
    exercises: [
      _mc(id:'b1_l14_e1',
        ku:'"Dema ku ez hatim, ew çû" cümlesinde zaman ilişkisi nedir?',
        tr:'Doğru açıklamayı seç',
        opts:['Aynı anda','Ben geldiğimde o zaten gitti','O geldiğimde ben gittim','Gelecek'],
        ci:1, note:'"Dema ku" = -dığında. "Hatim" geldi, "çû" gitmişti. [TH] §: time clauses'),
      _fill(id:'b1_l14_e2', before:'Berî ku pîrê bê,', after:'xanî paqij kir.',
        tr:'Büyükanne gelmeden önce evi temizledi.',
        opts:['dêya min','pîrê','ew','min'], ci:0,
        note:'"Berî ku" = -den önce. Özne berî ku\'dan önce veya sonra gelebilir'),
      _mc(id:'b1_l14_e3',
        ku:'"Heya ku ez dijim" ne anlama gelir?',
        tr:'Doğru çeviriyi seç',
        opts:['Yaşadığım zaman','Yaşadığım sürece','Yaşayacağım','Yaşıyorum'],
        ci:1, note:'"Heya ku" = -dığı sürece. Süre bağlacı.'),
      _speak(id:'b1_l14_e4',
        ku:'Dema ku pîrê digot, em hemî guhdarî dikirin. Berî ku ew here, me spas kir.',
        tr:'Büyükanne anlattığında hepimiz dinliyorduk. O gitmeden önce teşekkür ettik.'),
    ],
  ),

  LessonModel(
    id: 'b1_l15',
    kurmanjTitle: 'Çawa Ku — Karşılaştırma Cümleleri',
    turkishTitle: 'Karşılaştırma: Çawa Ku, Ji ... Baştir',
    unitNumber: 5, lessonNumber: 3, level: 3,
    path: LessonPath.general,
    targetCardIds: [],
    estimatedMinutes: 11,
    exercises: [
      _mc(id:'b1_l15_e1',
        ku:'"Ji Kurmancî baştir ziman nîne" yapısı nedir?',
        tr:'Doğru çeviriyi seç',
        opts:['Kurmancî kötüdür','Kurmancîden daha iyi dil yoktur','En iyi dil','Diller eşittir'],
        ci:1, note:'"Ji X baştir" = X\'den daha iyi. Üstünlük karşılaştırması. [BH] §58'),
      _fill(id:'b1_l15_e2', before:'Ev pirtûk', after:'ya berê ye.',
        tr:'Bu kitap eskisinden daha iyidir.',
        opts:['wek','baştir ji','xirab ji','heman'], ci:1),
      _mc(id:'b1_l15_e3',
        ku:'"Çawa ku pîrê digot" bağlacının işlevi:',
        tr:'Doğru açıklamayı seç',
        opts:['Soru sorar','Benzetme/kıyaslama yapar','Olumsuz','Gelecek'],
        ci:1, note:'"Çawa ku" = nasıl ki/gibi. Edebi dilde sık kullanılan benzetme bağlacı'),
      _speak(id:'b1_l15_e4',
        ku:'Çawa ku pîrê digot, ziman şîrîntirîn tiştê cîhanê ye.',
        tr:'Büyükannenin dediği gibi, dil dünyanın en tatlı şeyidir.'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // ÜNİTE 6 — Sağlık ve Tenduristî (2 ders)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'b1_l16',
    kurmanjTitle: 'Bijîşkî û Derman',
    turkishTitle: 'Doktor ve İlaç — İleri Düzey',
    unitNumber: 6, lessonNumber: 1, level: 3,
    path: LessonPath.general,
    targetCardIds: [],
    culturalRewardId: 'c_009',
    estimatedMinutes: 12,
    exercises: [
      _mc(id:'b1_l16_e1',
        ku:'"Ez xwe baş nabînim" ne anlama gelir?',
        tr:'Doğru çeviriyi seç',
        opts:['Göremiyorum','Kendimi iyi hissetmiyorum','İyi değil','Görmek istemiyorum'],
        ci:1, note:'"Xwe baş nabînim" = lit. "kendimi iyi göremiyorum" = kendimi iyi hissetmiyorum. Kürt deyimsel ifadesi'),
      _fill(id:'b1_l16_e2', before:'Min got ku', after:'heye.',
        tr:'Alerjim olduğunu söyledim.',
        opts:['germahî','nexweşî','alerjiya min','serêşî'], ci:2,
        note:'"Alerjiya min heye" = alerjim var. Min gotiye = söylemişim (ergatif mükemmel)'),
      _mc(id:'b1_l16_e3',
        ku:'"Keser kirin" ne anlama gelir?',
        tr:'Doğru çeviriyi seç',
        opts:['Bıçak almak','Ameliyat olmak','Dikiş dikmek','Kesmek'],
        ci:1, note:'"Keser" = ameliyat. "Keser kirin" = ameliyat olmak. B1 sağlık kelimesi'),
      _speak(id:'b1_l16_e4',
        ku:'Ez xwe baş nabînim. Bijîşkê min got ku divê ez bêhna xwe vdim.',
        tr:'Kendimi iyi hissetmiyorum. Doktorum dinlenmem gerektiğini söyledi.'),
    ],
  ),

  LessonModel(
    id: 'b1_l17',
    kurmanjTitle: 'Laş û Ruh',
    turkishTitle: 'Beden ve Ruh — Psikoloji',
    unitNumber: 6, lessonNumber: 2, level: 3,
    path: LessonPath.heritage,
    targetCardIds: _b1Cards(['psikoloji']).take(4).toList(),
    estimatedMinutes: 12,
    exercises: [
      _mc(id:'b1_l17_e1',
        ku:'"Dilşikestî" kelimesinin anlamı?',
        tr:'Doğru çeviriyi seç',
        opts:['Mutlu','Hasta','Kırık kalpli','Yorgun'],
        ci:2, note:'"Dil" (gönül) + "şikestî" (kırılmış) = kırık kalpli. Kürt şiirinin temel kelimesi'),
      _fill(id:'b1_l17_e2', before:'Ez', after:'me ji ber ku pîrê nehat.',
        tr:'Büyükanne gelmediği için üzgünüm.',
        opts:['şa','kovan','dilşa','xemgîn'], ci:3,
        note:'"Xemgîn" = kederli/hüzünlü. "Ji ber ku" + geçmiş = çünkü'),
      _mc(id:'b1_l17_e3',
        ku:'"Hişyariya zimanî" ne anlama gelir?',
        tr:'Doğru çeviriyi seç',
        opts:['Dil öğrenmek','Dil farkındalığı','Dil kullanmak','Dil kayıpları'],
        ci:1, note:'"Hişyarî" = farkındalık. "Hişyariya zimanî" = dil farkındalığı — Heritage kavramı'),
      _speak(id:'b1_l17_e4',
        ku:'Dema ku mirov zimanê xwe ji bîr dike, dilşikestî dibe. Lê ji nû ve fêr bûn şa dike!',
        tr:'Kişi dilini unuttuğunda kırık kalpli olur. Ama yeniden öğrenmek mutlu eder!'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // ÜNİTE 7 — Kültür, Edebiyat ve Kimlik (5 ders)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'b1_l18',
    kurmanjTitle: 'Dengbêj û Stran',
    turkishTitle: 'Dengbêj Geleneği',
    unitNumber: 7, lessonNumber: 1, level: 3,
    path: LessonPath.heritage,
    targetCardIds: _b1Cards(['edebiyat']).take(5).toList(),
    culturalRewardId: 'c_008',
    estimatedMinutes: 13,
    exercises: [
      _ls(id:'b1_l18_e1', ku:'Dengbêj',
        tr:'Ne anlama gelir?',
        opts:['Şair','Halk ozanı — sesle söyleyen','Müzisyen','Öğretmen'],
        ci:1, audio:'assets/audio/b1/dengbej.mp3',
        note:'"Deng" (ses) + "bêj" (söyleyen). Kürt sözlü geleneğinin taşıyıcısı'),
      _mc(id:'b1_l18_e2',
        ku:'Dengbêj geleneği neden önemlidir?',
        tr:'Doğru açıklamayı seç',
        opts:['Sadece eğlence','Tarihi ve kültürü sözlü aktarır','Yalnızca dini','Ekonomik değer'],
        ci:1, note:'Dengbêjler yüzyıllarca Kürt tarihini, aşkını, acısını sözlü aktardı — yazılı edebiyat yasak döneminde bile'),
      _mc(id:'b1_l18_e3',
        ku:'"Stran" kelimesinin cinsiyeti nedir?',
        tr:'Bedir Han\'dan doğru cevabı seç',
        opts:['Eril','Dişil','Cinsiyetsiz','Değişken'],
        ci:1, note:'[BH] p.56: "Stran, şarkı : stranê, stranan" — dişil ✓'),
      _fill(id:'b1_l18_e4', before:'Dengbêj straneke', after:'got.',
        tr:'Dengbêj çok güzel bir şarkı söyledi.',
        opts:['baş','xweş','gelek xweş','mezin'], ci:2,
        note:'"Straneke gelek xweş" = çok güzel bir şarkı. Belirsiz + sıfat'),
      _speak(id:'b1_l18_e5',
        ku:'Dengbêjên kurd stranên dîrokî digotin. Em ji wan fêr dibin.',
        tr:'Kürt dengbêjleri tarihî şarkılar söylerdi. Biz onlardan öğreniyoruz.'),
    ],
  ),

  LessonModel(
    id: 'b1_l19',
    kurmanjTitle: 'Ehmedê Xanî û Mem û Zîn',
    turkishTitle: 'Kürt Edebiyatı: Mem û Zîn',
    unitNumber: 7, lessonNumber: 2, level: 3,
    path: LessonPath.heritage,
    targetCardIds: _b1Cards(['edebiyat']).skip(3).toList(),
    culturalRewardId: 'c_011',
    estimatedMinutes: 13,
    exercises: [
      _mc(id:'b1_l19_e1',
        ku:'Ehmedê Xanî kim e?',
        tr:'Doğru açıklamayı seç',
        opts:['Modern şair','17. yüzyıl Kürt şairi, Mem û Zîn yazarı','Dengbêj','Dilbilimci'],
        ci:1, note:'Ehmedê Xanî (1651–1707) — "Mem û Zîn" (1695) Kürt edebiyatının başyapıtı'),
      _mc(id:'b1_l19_e2',
        ku:'"Mem û Zîn" nasıl bir yapıttır?',
        tr:'Doğru açıklamayı seç',
        opts:['Tarih kitabı','Destansı aşk şiiri — Kürt Romeo ve Juliet\'i','Gramer kitabı','Sözlük'],
        ci:1, note:'"Mem û Zîn" hem aşk hikâyesi hem de Kürt kimliği ve birliği çağrısı'),
      _ls(id:'b1_l19_e3',
        ku:'Kurd û kurdanî gelek baş in',
        tr:'Bu dize ne anlatıyor?',
        opts:['Kürtler kötüdür','Kürtler ve Kürtlük çok iyidir','Kürtçe zordur','Kürt tarihi'],
        ci:1, audio:'assets/audio/b1/xani_dize.mp3'),
      _fill(id:'b1_l19_e4', before:'Mem ji Zîn re', after:'bû.',
        tr:'Mem Zîn\'e sadık oldu.',
        opts:['dilsoz','xemgîn','bengî','wêrek'], ci:0,
        note:'"Dilsoz" = sadık. "Ji ... re" = -e karşı (yön edatı)'),
      _speak(id:'b1_l19_e5',
        ku:'Mem û Zîn berhema Ehmedê Xanî ye. Zimanê wê xweş û kûr e.',
        tr:'Mem û Zîn Ehmedê Xanî\'nin eseridir. Dili güzel ve derindir.'),
    ],
  ),

  LessonModel(
    id: 'b1_l20',
    kurmanjTitle: 'Nasname û Ziman',
    turkishTitle: 'Kimlik ve Dil',
    unitNumber: 7, lessonNumber: 3, level: 3,
    path: LessonPath.heritage,
    targetCardIds: _b1Cards(['kimlik', 'psikoloji']),
    estimatedMinutes: 13,
    exercises: [
      _mc(id:'b1_l20_e1',
        ku:'"Serbilindî" ne anlama gelir?',
        tr:'Doğru çeviriyi seç',
        opts:['Utanç','Gurur/Onur','Korku','Özgürlük'],
        ci:1, note:'"Ser" (baş) + "bilind" (yüksek) = başı yüksek → gurur'),
      _fill(id:'b1_l20_e2', before:'Nasnameya kurdî', after:'e.',
        tr:'Kürt kimliği güçlüdür.',
        opts:['baş','bihêz','mezin','kevin'], ci:1,
        note:'"Bihêz" = güçlü. [FB]: bihêz adj.'),
      _mc(id:'b1_l20_e3',
        ku:'"Têkçûn" ne anlama gelir?',
        tr:'Doğru çeviriyi seç',
        opts:['Başarı','Asimilasyon / Dilde erime','Yurt','Özgürlük'],
        ci:1, note:'"Têkçûn" = asimilasyon. "Têk" (bozulma) + "çûn" (gitme). Kurmancî özgün term'),
      _speak(id:'b1_l20_e4',
        ku:'Ez serbilindim ku kurd im û bi Kurmancî dipeyivim. Têkçûn dawî ye!',
        tr:'Kürt olduğum ve Kurmancî konuştuğum için gurur duyuyorum. Asimilasyon bitti!'),
    ],
  ),

  LessonModel(
    id: 'b1_l21',
    kurmanjTitle: 'Welat û Gurbet',
    turkishTitle: 'Vatan ve Gurbet',
    unitNumber: 7, lessonNumber: 4, level: 3,
    path: LessonPath.heritage,
    targetCardIds: _b1Cards(['dîrok', 'siyaset']).take(6).toList(),
    estimatedMinutes: 12,
    exercises: [
      _mc(id:'b1_l21_e1',
        ku:'"Welat" kelimesinin cinsiyeti?',
        tr:'Doğru cevabı seç',
        opts:['Dişil','Eril','Cinsiyetsiz','Değişken'],
        ci:1, note:'"Welat" = vatan/yurt. Eril (nêr). "Welatê min" = vatanım'),
      _ls(id:'b1_l21_e2',
        ku:'Kurdistan welê min e',
        tr:'Bu dize nereden?',
        opts:['Bedir Han','Cegerxwîn şiiri','Mem û Zîn','Dengbêj stranı'],
        ci:1, audio:'assets/audio/b1/cegerxwin.mp3',
        note:'Cegerxwîn (1903–1984) modern Kurmancî şiirinin öncüsü'),
      _fill(id:'b1_l21_e3', before:'Em li', after:'ne, lê dilê me li welatê ye.',
        tr:'Gurbetteyiz ama kalbimiz vatandadır.',
        opts:['welatê','gurbetê','bajêr','malê'], ci:1),
      _speak(id:'b1_l21_e4',
        ku:'Welat dûr e, lê ziman bi me re ye. Bi zimên em li welatê dimînin.',
        tr:'Vatan uzaktır ama dil bizimledir. Dille vatanda kalıyoruz.'),
    ],
  ),

  LessonModel(
    id: 'b1_l22',
    kurmanjTitle: 'Azadî û Maf',
    turkishTitle: 'Özgürlük ve Haklar',
    unitNumber: 7, lessonNumber: 5, level: 3,
    path: LessonPath.general,
    targetCardIds: _b1Cards(['siyaset']),
    estimatedMinutes: 12,
    exercises: [
      _mc(id:'b1_l22_e1',
        ku:'"Azadî" kelimesinin cinsiyeti?',
        tr:'Bedir Han\'dan doğru cevap',
        opts:['Eril','Dişil','Cinsiyetsiz','Her ikisi'],
        ci:1, note:'[BH] §275: "-ahî" sonek dişil yapar. "Azadî" dişil (mê). "Azadiya me" = bizim özgürlüğümüz'),
      _fill(id:'b1_l22_e2', before:'', after:'dermanê dilê mirov e.',
        tr:'Dil, insanın kalp ilacıdır.',
        opts:['Maf','Ziman','Azadî','Aştî'], ci:1,
        note:'A1\'den gelen atasözü — B1\'de derin anlam'),
      _mc(id:'b1_l22_e3',
        ku:'"Mafên mirovan" ifadesi ne demek?',
        tr:'Doğru çeviriyi seç',
        opts:['Kürt milletleri','İnsan hakları','Hukuk sistemi','Zagonlar'],
        ci:1, note:'"Maf" = hak (eril). "Mafên" = haklar (çoğul). "Mirovan" = insanların'),
      _speak(id:'b1_l22_e4',
        ku:'Mafê zimanê xwe hîn bûn mafekî bingehîn e. Azadî bi ziman dest pê dike!',
        tr:'Kendi dilini öğrenme hakkı temel bir haktır. Özgürlük dille başlar!'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // ÜNİTE 8 — Bağlaçlar ve Karmaşık Metin (3 ders)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'b1_l23',
    kurmanjTitle: 'Çimkî û Ji Ber Ku — Neden?',
    turkishTitle: 'Neden Cümleleri: Ji Ber Ku, Lewre',
    unitNumber: 8, lessonNumber: 1, level: 3,
    path: LessonPath.general,
    targetCardIds: _b1Cards(['daçek']).skip(2).toList(),
    estimatedMinutes: 11,
    exercises: [
      _mc(id:'b1_l23_e1',
        ku:'"Ji ber ku" ile "lewre" farkı nedir?',
        tr:'Doğru açıklamayı seç',
        opts:['Aynı anlam','Ji ber ku = çünkü (sebep), lewre = bunun için (sonuç)','Tersine','İkisi de "ama"'],
        ci:1, note:'"Ji ber ku" = çünkü (sebep cümlesi başında). "Lewre" = bu yüzden/bunun için (sonuç)'),
      _fill(id:'b1_l23_e2', before:'Pîrê hat,', after:'em şa bûn.',
        tr:'Büyükanne geldi, bu yüzden mutlu olduk.',
        opts:['ji ber ku','lewre','lê','û'], ci:1),
      _fill(id:'b1_l23_e3', before:'Ez naçim', after:'nexweş im.',
        tr:'Hasta olduğum için gitmiyorum.',
        opts:['û','lewre','ji ber ku','heta'], ci:2),
      _speak(id:'b1_l23_e4',
        ku:'Ji ber ku ez kurd im, zimanê xwe hîn dibim. Lewre ez serbilind im!',
        tr:'Kürt olduğum için dilimi öğreniyorum. Bu yüzden gururluyum!'),
    ],
  ),

  LessonModel(
    id: 'b1_l24',
    kurmanjTitle: 'Kîjan Ko Tê — İlgeç Cümleleri',
    turkishTitle: 'Sıfat Cümlesi: Ko Tê',
    unitNumber: 8, lessonNumber: 2, level: 3,
    path: LessonPath.general,
    targetCardIds: [],
    estimatedMinutes: 12,
    exercises: [
      _mc(id:'b1_l24_e1',
        ku:'"Pîrêya ku hat" yapısı nedir?',
        tr:'Doğru açıklamayı seç',
        opts:['Basit cümle','Sıfat cümlesi: "gelen büyükanne"','Soru','Olumsuz'],
        ci:1, note:'"Ku" + yüklem = sıfat cümlesi. "Pîrêya ku hat" = gelen büyükanne. [TH] §: relative clauses'),
      _fill(id:'b1_l24_e2', before:'Pirtûka', after:'min xwend gelek baş bû.',
        tr:'Okuduğum kitap çok güzeldi.',
        opts:['ger','ku','ji ber','lewre'], ci:1,
        note:'"Pirtûka ku min xwend" = okuduğum kitap. "Min xwend" = ben okudum (ergatif)'),
      _mc(id:'b1_l24_e3',
        ku:'"Kesê ku Kurmancî dizane" ne anlama gelir?',
        tr:'Doğru çeviriyi seç',
        opts:['Kurmancî bilmek','Kurmancî bilen kişi','Kurmancî öğrenen','Kurmancî isteyen'],
        ci:1, note:'"Kesê ku ... dizane" = bilen kişi. Sıfat cümlesi'),
      _speak(id:'b1_l24_e4',
        ku:'Kesê ku zimanê xwe nizane, nasnameya xwe jî nizane.',
        tr:'Dilini bilmeyen kişi, kimliğini de bilmez.'),
    ],
  ),

  LessonModel(
    id: 'b1_l25',
    kurmanjTitle: 'Metin Xwendin — B1',
    turkishTitle: 'Kısa Metin Okuma',
    unitNumber: 8, lessonNumber: 3, level: 3,
    path: LessonPath.heritage,
    targetCardIds: _b1Cards(['deyim']),
    estimatedMinutes: 15,
    exercises: [
      _ls(id:'b1_l25_e1',
        ku:'Dengbêj Şakiro got: "Bêyî ziman, bêyî nasname."',
        tr:'Bu söz ne anlama gelir?',
        opts:['Dil güçtür','Dilsiz kimliksiz','Kimlik önemlidir','Dil zordur'],
        ci:1, audio:'assets/audio/b1/sakiro.mp3',
        note:'Dengbêj Şakiro (1921–2005) — ünlü Kürt dengbêji'),
      _mc(id:'b1_l25_e2',
        ku:'"Serê xwe xweş bike" deyimi ne anlama gelir?',
        tr:'Doğru çeviriyi seç',
        opts:['Başını yıka','Kendine iyi bak','Başını kaldır','Saçını tara'],
        ci:1, note:'Deyim: "Serê xwe xweş bike" = kendine iyi bak/güvende ol'),
      _mc(id:'b1_l25_e3',
        ku:'"Dil û can" ifadesi neyi anlatır?',
        tr:'Doğru açıklamayı seç',
        opts:['İki farklı şey','Tüm kalpten/can ve gönülden','Güçlü savaş','Para ve güç'],
        ci:1, note:'"Dil û can" = gönül ve can — tüm varlığıyla'),
      _speak(id:'b1_l25_e4',
        ku:'Dil û can ji zimanê xwe hez dikim. Serê xwe xweş bike, heval!',
        tr:'Tüm kalbimle dilimi seviyorum. Kendine iyi bak, arkadaşım!'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // ÜNİTE 9 — Doğa, Ekoloji ve Toprak (2 ders)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'b1_l26',
    kurmanjTitle: 'Kurdistan û Xweza',
    turkishTitle: 'Kürdistan ve Doğa',
    unitNumber: 9, lessonNumber: 1, level: 3,
    path: LessonPath.heritage,
    targetCardIds: _b1Cards(['xweza']),
    estimatedMinutes: 12,
    exercises: [
      _ls(id:'b1_l26_e1', ku:'Bereket',
        tr:'Ne anlama gelir?',
        opts:['Yoksulluk','Bereket/Bolluk','Kuraklık','Savaş'],
        ci:1, audio:'assets/audio/b1/bereket.mp3',
        note:'"Bereket" dişil. "Erdê bereketdar" = bereketli toprak — Kürdistan için kullanılan ifade'),
      _mc(id:'b1_l26_e2',
        ku:'"Keskesor" nedir?',
        tr:'Doğru açıklamayı seç',
        opts:['Yeşil renk','Gökkuşağı','Kırmızı-yeşil','Sis'],
        ci:1, note:'[BH] p.277: "Keskesor, diş., gökkuşağı (kesk=yeşil + sor=kırmızı)". Bileşik kelime!'),
      _fill(id:'b1_l26_e3', before:'Çiyayên Kurdistanê', after:'û bereketdar in.',
        tr:'Kürdistan dağları yeşil ve bereketlidir.',
        opts:['reş','hêşîn','sar','germ'], ci:1,
        note:'"Hêşîn" = koyu/canlı yeşil (doğa için)'),
      _speak(id:'b1_l26_e4',
        ku:'Çiyayên Kurdistanê hêşîn in. Axê me bereketdar e. Em welatê xwe hez dikin!',
        tr:'Kürdistan dağları yemyeşil. Toprağımız bereketlidir. Vatanımızı seviyoruz!'),
    ],
  ),

  LessonModel(
    id: 'b1_l27',
    kurmanjTitle: 'Jîngeh û Çand',
    turkishTitle: 'Çevre ve Kültür',
    unitNumber: 9, lessonNumber: 2, level: 3,
    path: LessonPath.general,
    targetCardIds: _b1Cards(['xweza']).skip(3).toList(),
    estimatedMinutes: 11,
    exercises: [
      _mc(id:'b1_l27_e1',
        ku:'"Jîngeh" ne anlama gelir?',
        tr:'Doğru çeviriyi seç',
        opts:['Ülke','Çevre/Yaşam ortamı','Ev','Tarla'],
        ci:1, note:'"Jîngeh" = çevre/habitat. "Jî" (yaşamak) + "-ngeh" (yer). Kurmancî özgün terim'),
      _fill(id:'b1_l27_e2', before:'Jîngeh', after:'korumalıyız.',
        tr:'Çevreyi korumalıyız. (Kurmancî\'ye çevir)',
        opts:['biparêzin','biparêze','diparêzin','hate parastin'], ci:0,
        note:'"Jîngeh biparêzin!" = çevreyi koruyun! (subjunctive çoğul)'),
      _speak(id:'b1_l27_e3',
        ku:'Jîngeh û çand ji hev cuda nîne. Xweza parastina çandê ye.',
        tr:'Çevre ve kültür birbirinden ayrı değildir. Doğa kültürün korumasıdır.'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // ÜNİTE 10 — Aborî û Kar: Ekonomi ve İş (2 ders)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'b1_l28',
    kurmanjTitle: 'Aborî û Bazirganî',
    turkishTitle: 'Ekonomi ve Ticaret',
    unitNumber: 10, lessonNumber: 1, level: 3,
    path: LessonPath.general,
    targetCardIds: _b1Cards(['aborî']),
    estimatedMinutes: 11,
    exercises: [
      _mc(id:'b1_l28_e1',
        ku:'"Aborî" ne anlama gelir?',
        tr:'Doğru çeviriyi seç',
        opts:['Hukuk','Ekonomi','Politika','Tarih'],
        ci:1, note:'"Aborî" = ekonomi. [AS] s.65: "İKTİSAT = ABORÎ". Dişil'),
      _fill(id:'b1_l28_e2', before:'Bazirganiya Kurdistanê', after:'dibe.',
        tr:'Kürdistan ticareti büyüyor.',
        opts:['mezin','mezintir','biçûk','kevni'], ci:1,
        note:'"Mezintir dibe" = daha büyük oluyor. Karşılaştırmalı + süreç'),
      _mc(id:'b1_l28_e3',
        ku:'"Sermaye" ne anlama gelir?',
        tr:'Doğru çeviriyi seç',
        opts:['Faiz','Borç','Sermaye/Kapital','Maaş'],
        ci:2),
      _speak(id:'b1_l28_e4',
        ku:'Aboriya baş pêşketina civakê ye. Bi bazirganiyê em pêşde diçin.',
        tr:'İyi ekonomi toplumun gelişmesidir. Ticaretle ilerleriz.'),
    ],
  ),

  LessonModel(
    id: 'b1_l29',
    kurmanjTitle: 'Kar û Xebat — İş Hayatı',
    turkishTitle: 'Çalışma Hayatı',
    unitNumber: 10, lessonNumber: 2, level: 3,
    path: LessonPath.general,
    targetCardIds: [],
    estimatedMinutes: 11,
    exercises: [
      _mc(id:'b1_l29_e1',
        ku:'"Berpirsiyar" ne anlama gelir?',
        tr:'Doğru çeviriyi seç',
        opts:['Çalışkan','Sorumlu','Yetkili','Müdür'],
        ci:1, note:'"Berpirsiyar" = sorumlu. [BH] §275 türetme listesinde "berpêksiyarî, sorumluluk" geçiyor'),
      _fill(id:'b1_l29_e2', before:'Ez', after:'vê karê me.',
        tr:'Bu işin sorumlusuyum.',
        opts:['berpirsiyarê','mamostayê','hevkarê','rêveberê'], ci:0),
      _mc(id:'b1_l29_e3',
        ku:'"Hevkarî" ne anlama gelir?',
        tr:'Doğru çeviriyi seç',
        opts:['Rekabet','Dayanışma/Yardımlaşma','Bağımsızlık','Çatışma'],
        ci:1, note:'"Hev" (karşılıklı) + "karî" (iş). Kürt kültürünün temel değeri'),
      _speak(id:'b1_l29_e4',
        ku:'Bi hevkariyê em karê xwe baş dikin. Berpirsiyarî û bawerî girîng in.',
        tr:'Dayanışmayla işimizi iyi yaparız. Sorumluluk ve güven önemlidir.'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // B1 FINAL: Metin Sentezi (1 ders)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'b1_l30',
    kurmanjTitle: 'Ziman Jiyan e — B1 Dawî',
    turkishTitle: 'Dil Hayattır — B1 Sonu',
    unitNumber: 10, lessonNumber: 3, level: 3,
    path: LessonPath.heritage,
    targetCardIds: [
      ..._b1Cards(['deyim']),
      ..._b1Cards(['kimlik']).take(2),
    ],
    culturalRewardId: 'c_a2_001',
    estimatedMinutes: 15,
    exercises: [
      _mc(id:'b1_l30_e1',
        ku:'B1\'de öğrenilen en kritik dilbilgisi yapısı hangisi?',
        tr:'Doğru cevabı seç',
        opts:['Bûn fiil çekimi','Ergatif yapı — geçişli geçmişte eğik özne','Sayılar','Renkler'],
        ci:1, note:'Ergatif: "Min got" — Kurmancî\'nin en özgün dilbilgisel özelliği'),
      _mc(id:'b1_l30_e2',
        ku:'"Ziman jiyan e" ifadesi ne anlama gelir?',
        tr:'Doğru çeviriyi seç',
        opts:['Dil zordur','Dil hayattır — dil canlı tutulmak gerekir','Dil eski','Dil güzeldir'],
        ci:1, note:'Heritage öğrenicinin temel motivasyonu: dil bir sorumluluk, bir miras'),
      _fill(id:'b1_l30_e3', before:'Min Kurmancî', after:'û ez şa me!',
        tr:'Kurmancî öğrendim ve mutluyum!',
        opts:['hîn bûm','hîn dibim','hîn bûye','hîn dike'], ci:0,
        note:'"Hîn bûm" = öğrendim (geçmiş). "Şa me" = mutluyum'),
      _speak(id:'b1_l30_e4',
        ku:'Min Kurmancî hîn bûye. Wî got ku baş e. Me ziman parastin. Bila bijî!',
        tr:'Kurmancî öğrendim. O dedi ki iyidir. Biz dili koruduk. Yaşasın!'),
      _speak(id:'b1_l30_e5',
        ku:'Ziman jiyan e. Ziman nasname ye. Bi zimên em hemî bi hev re ne!',
        tr:'Dil hayattır. Dil kimliktir. Dille hepimiz birlikteyiz!'),
    ],
  ),

]; // kB1Lessons son

// ── Yardımcı ─────────────────────────────────────────────────────
LessonModel? getB1LessonById(String id) {
  try { return kB1Lessons.firstWhere((l) => l.id == id); }
  catch (_) { return null; }
}
List<LessonModel> getB1LessonsForUnit(int unit) =>
    kB1Lessons.where((l) => l.unitNumber == unit).toList();
