import 'lesson_entities.dart';
import 'b1_kelime_db.dart';

// ════════════════════════════════════════════════════════════════
// B1 — 15 DERS TANIMI (Navîn-Jêr / Orta-Alt)
//
// Pedagojik Odak (CEFR B1):
// - Ergatif sistem TAM (Min xwend, Te dît, Wî got, Wê kir)
// - Şimdiki mükemmel (hatiye, çûye, gotiye)
// - Sürekli geçmiş / hikaye kipi (dihat, digot, dixwend)
// - Mebestî / Subjunctive (bi- + rayek + paşgir)
// - Deyimler ve kültürel selamlar
// - Rengdêrên berawirdkirinê (-tir, -tirîn)
// - Edebiyatê kurdî: Ehmedê Xanî, Mem û Zîn, Nûbahara Biçûkan
// - Gotinên pêşiyan (atasözleri)
//
// Path dağılımı: 9 general · 2 heritage · 4 cultural
// ════════════════════════════════════════════════════════════════

List<String> _b1Cards(List<String> katlar) => kB1TamListeNihayet
    .where((k) => katlar.contains(k.kat))
    .map((k) => k.id)
    .toList();

ExerciseModel _mc({
  required String id, required String ku, required String tr,
  required List<String> opts, required int ci,
  String? note, int xp = 10,
}) => ExerciseModel(
  id: id, type: ExerciseType.multipleChoice,
  kurmanjPrompt: ku, turkishPrompt: tr,
  options: opts, correctAnswer: opts[ci], correctIndex: ci,
  grammarNote: note, xpReward: xp,
);

ExerciseModel _ls({
  required String id, required String ku, required String tr,
  required List<String> opts, required int ci,
  String? audio, String? note, int xp = 12,
}) => ExerciseModel(
  id: id, type: ExerciseType.listenAndSelect,
  kurmanjPrompt: ku, turkishPrompt: tr,
  options: opts, correctAnswer: opts[ci], correctIndex: ci,
  audioAsset: audio, grammarNote: note, xpReward: xp,
);

ExerciseModel _fill({
  required String id, required String before, required String after,
  required String tr, required List<String> opts, required int ci,
  String? note, int xp = 12,
}) => ExerciseModel(
  id: id, type: ExerciseType.fillInBlank,
  kurmanjPrompt: '$before ___ $after', turkishPrompt: tr,
  options: opts, correctAnswer: opts[ci], correctIndex: ci,
  grammarNote: note, xpReward: xp,
  wordPieces: [before.trim(), after.trim()],
);

ExerciseModel _speak({
  required String id, required String ku, required String tr,
  String? audio, int xp = 15,
}) => ExerciseModel(
  id: id, type: ExerciseType.speakingPractice,
  kurmanjPrompt: ku, turkishPrompt: tr,
  audioAsset: audio, xpReward: xp,
  options: ['Gelek baş', 'Nêzîk', 'Carek din'],
  correctAnswer: ku,
);

// ════════════════════════════════════════════════════════════════
// 15 DERS
// ════════════════════════════════════════════════════════════════

final kB1Lessons = <LessonModel>[

  // ─────────────────────────────────────────────────────────────
  // BİRİM 1 — Sîstema Ergatîf (3 ders)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'b1_l01',
    kurmanjTitle: 'Min Xwend: Zamirên Ergatîf',
    turkishTitle: 'Ergatif Zamir Sistemi',
    unitNumber: 1, lessonNumber: 1, level: 3,
    path: LessonPath.general,
    targetCardIds: _b1Cards(['ergatif', 'leker_ergatif']).take(8).toList(),
    estimatedMinutes: 10,
    exercises: [
      _mc(id: 'b1_l01_e1',
        ku: 'Dema borî ya gerguhêz (ergatîf) ji bo kîjan lêkeran tê bikar anîn?',
        tr: 'Doğru kullanım alanını seç',
        opts: [
          'Tenê ji bo lêkerên negerguhêz',
          'Ji bo hemû lêkeran bêyî veqetandin',
          'Tenê ji bo lêkerên gerguhêz di dema borî de',
          'Tenê ji bo lêkerên alîkar',
        ],
        ci: 2,
        note: 'Ergatif yapı yalnızca GEÇİŞLİ fiillerin geçmişinde görülür. Özne eğik halde, fiil nesne ile uyumlu. [BH] §170'),
      _fill(id: 'b1_l01_e2', before: '', after: ' pirtûk xwend.',
        tr: '1.tekil şahıs geçmiş zaman GEÇİŞLİ cümle: ___ kitabı okudu (özne hangi halde olmalı?). İPUCU: ergatif zorunlu — eğik (oblîk) hal.',
        opts: ['Min', 'Ma', 'Ez', 'Min re'],
        ci: 0,
        note: 'Ergatif geçmişte özne eğik halde: "Min" (= ez\'in eğik hali). "Min xwend" = ben okudum. "Ez" düz hal — geçişli geçmişte yanlıştır.'),
      _fill(id: 'b1_l01_e3', before: 'Te çi', after: '?',
        tr: 'Sen ne gördün?',
        opts: ['dît', 'dîtî', 'dibînî', 'bibîne'],
        ci: 0,
        note: '"Te dît" = sen gördün. Ergatif özne "Te" + basit geçmiş rayeka "dît".'),
      _mc(id: 'b1_l01_e4',
        ku: '"Wê got" — zamira "wê" di kîjan halî de ye?',
        tr: 'Doğru hal ve cinsi seç',
        opts: [
          'Halê xwerû yê nêr',
          'Halê pirjimar',
          'Halê tewangê yê mê',
          'Halê tewangê yê nêr',
        ],
        ci: 2,
        note: '"Wê" = "ew" zamirinin dişil eğik (tewang) hali. Eril eşdeğeri "wî". [BH] §171'),
      _fill(id: 'b1_l01_e5', before: '', after: ' nan pijand.',
        tr: '1.çoğul geçmiş GEÇİŞLİ: ___ ekmek pişirdi(k). İPUCU: ergatif zorunlu — "Em" yerine eğik hali gelmeli.',
        opts: ['Hûn', 'Em', 'Me', 'Em re'],
        ci: 2,
        note: '"Em" (düz hal, biz) → "Me" (eğik hal). Ergatif geçmişte "Me nan pijand". "Hûn" siz, yanlış kişi.'),
      _speak(id: 'b1_l01_e6',
        ku: 'Min pirtûk xwend. Te çi xwend? Wan helbest xwendin.',
        tr: 'Ben kitap okudum. Sen ne okudun? Onlar şiir okudular.'),
    ],
  ),

  LessonModel(
    id: 'b1_l02',
    kurmanjTitle: 'Lêker bi Berbijêrî re Hev Dike',
    turkishTitle: 'Nesne ile Uyumluluk',
    unitNumber: 1, lessonNumber: 2, level: 3,
    path: LessonPath.general,
    targetCardIds: _b1Cards(['ergatif', 'leker_ergatif']).skip(4).take(6).toList(),
    estimatedMinutes: 10,
    exercises: [
      _mc(id: 'b1_l02_e1',
        ku: 'Di hevokeke ergatîf de lêker bi kîjanê re dihev dike?',
        tr: 'Doğru kuralı seç',
        opts: [
          'Bi kirdeyê re (zayend û hejmar)',
          'Bi lêkerê alîkar re',
          'Tu hevhatin nîne',
          'Bi berbijêrî re (zayend û hejmar)',
        ],
        ci: 3,
        note: 'Ergatif yapıda fiil NESNE ile uyum sağlar (sayı ve cinste), özneyle değil. [BH] §173'),
      _fill(id: 'b1_l02_e2', before: 'Min sêv', after: '.',
        tr: 'Ben elma yedim. (tek elma)',
        opts: ['dixwim', 'bixwe', 'xwarin', 'xwar'],
        ci: 3,
        note: '"Sêv" yekjimar → lêker yekjimar "xwar". Pirjimar olsaydı "Min sêv xwarin" (berbijêrê pirjimar, lêker pirjimar).'),
      _fill(id: 'b1_l02_e3', before: 'Te pirtûkên xwe', after: '.',
        tr: 'Sen kitaplarını okudun.',
        opts: ['dixwîne', 'bixwîne', 'xwendin', 'xwend'],
        ci: 2,
        note: '"Pirtûk" pirjimar (kitaplar) → lêker "xwendin".'),
      _mc(id: 'b1_l02_e4',
        ku: '"Me stranek got." — çima lêker "got" e, ne "gotin"?',
        tr: 'Doğru açıklamayı bul',
        opts: [
          'Çimkî "gotin" nayê bikar anîn',
          'Çimkî kirde "me" yekjimar e',
          'Çimkî dem nêzîk e',
          'Çimkî berbijêr "stranek" yekjimar e',
        ],
        ci: 3,
        note: 'Nesne "stranek" tekil → fiil tekil "got". Çoğul olsaydı (stran/stranan) → "gotin".'),
      _fill(id: 'b1_l02_e5', before: 'Wan çîrokên pîrê', after: ' ji me re.',
        tr: 'Onlar büyükannenin hikayelerini bize anlattılar.',
        opts: ['gotin', 'gotî', 'bibêjin', 'got'],
        ci: 0,
        note: '"Çîrok" pirjimar → "gotin". Wan + gotin = onlar anlattılar.'),
      _speak(id: 'b1_l02_e6',
        ku: 'Min sêv xwar. Wan sêvên kesk xwarin. Te çi xwar?',
        tr: 'Ben elma yedim. Onlar yeşil elmalar yediler. Sen ne yedin?'),
    ],
  ),

  LessonModel(
    id: 'b1_l03',
    kurmanjTitle: 'Nerênî û Pirs di Ergatîfê de',
    turkishTitle: 'Ergatif Olumsuz ve Soru',
    unitNumber: 1, lessonNumber: 3, level: 3,
    path: LessonPath.general,
    targetCardIds: _b1Cards(['ergatif', 'leker_ergatif']).skip(6).take(5).toList(),
    estimatedMinutes: 10,
    exercises: [
      _mc(id: 'b1_l03_e1',
        ku: 'Di dema borî ya gerguhêz de nerênîtî çawa tê çêkirin?',
        tr: 'Doğru öneki seç',
        opts: [
          'Bi pêşgira "na-"',
          'Bi pêşgira "ni-"',
          'Bi paşgira "-in"',
          'Bi pêşgira "ne-" li beriya rayekê',
        ],
        ci: 3,
        note: '"Ne-" eki geçmiş zaman olumsuzluğu: "nedît" = görmedi, "negot" = söylemedi. [TH] §77'),
      _fill(id: 'b1_l03_e2', before: 'Min ev tişt', after: '.',
        tr: 'Ben bu şeyi görmedim.',
        opts: ['dibînim', 'dît', 'nedît', 'nabînim'],
        ci: 2,
        note: '"Ne-" + "dît" = "nedît" (ergatif geçmiş olumsuz). Ergatifte berbijêr (nesne) halê xwerû de ye: "ev tişt".'),
      _fill(id: 'b1_l03_e3', before: 'Te', after: '?',
        tr: 'Sen söylemedin mi?',
        opts: ['bibêje', 'got', 'negot', 'dibêjî'],
        ci: 2,
        note: 'Soru kalıbı ergatif olumsuz: "Te negot?" = sen söylemedin mi? Ton soru belirler.'),
      _mc(id: 'b1_l03_e4',
        ku: '"Wan tu caran ev nekir." tê çi wateyê?',
        tr: 'Doğru çeviriyi seç',
        opts: [
          'Wan ev tenê carekê kir',
          'Wan qet ev tişt nekir',
          'Wan piştî demekê ev kir',
          'Wan her tim ev kir',
        ],
        ci: 1,
        note: '"Tu caran" (asla) olumsuzluğu güçlendirir. "Nekir" = yapmadılar (ergatif geçmiş). Tüm seçenekler ergatif geçmişte uyumlu — fark sıklık/zaman ifadesinde. [AZ] Ders 14'),
      _fill(id: 'b1_l03_e5', before: '', after: ' we ev bihîstiye?',
        tr: 'Soru kalıbı: "Acaba bunu duydunuz mu?"',
        opts: ['Gelo', 'Herwiha', 'Lewra', 'Hingê'],
        ci: 0,
        note: '"Gelo" = acaba/-mi. Soru bağlacı. [BH] §200'),
      _speak(id: 'b1_l03_e6',
        ku: 'Min ev nedît. Te çi negot? Wan tu caran ev nekir.',
        tr: 'Ben bunu görmedim. Sen ne söylemedin? Onlar asla bunu yapmadılar.'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // BİRİM 2 — Dem û Kip (3 ders)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'b1_l04',
    kurmanjTitle: 'Hatiye, Çûye: Dema Temambûyî',
    turkishTitle: 'Şimdiki Mükemmel Zaman',
    unitNumber: 2, lessonNumber: 1, level: 3,
    path: LessonPath.general,
    targetCardIds: _b1Cards(['dem_temam']).take(6).toList(),
    culturalRewardId: 'proverb_2',
    estimatedMinutes: 10,
    exercises: [
      _mc(id: 'b1_l04_e1',
        ku: '"Pîrê hatiye." tê çi wateyê?',
        tr: 'Doğru anlamı bul',
        opts: [
          'Pîrê nehat',
          'Pîrê niha dê bê',
          'Pîrê hatiye û niha li vir e',
          'Pîrê dihat',
        ],
        ci: 2,
        note: '"Hatiye" = şimdiki mükemmel: gelmiş ve şu an burada (etkisi sürüyor). [TH] §72'),
      _fill(id: 'b1_l04_e2', before: 'Pîrê ji gund', after: '.',
        tr: 'Büyükanne köyden gelmiş. (şu an burada)',
        opts: ['tê', 'hatiye', 'dihat', 'hat'],
        ci: 1,
        note: 'Etkisi devam eden geçmiş → "hatiye" (perfect).'),
      _fill(id: 'b1_l04_e3', before: 'Min', after: ' ku baş e.',
        tr: 'Ben söylemişim ki iyi.',
        opts: ['dê bibêjim', 'dibêjim', 'gotiye', 'got'],
        ci: 2,
        note: 'Ergatif + perfect: "Min gotiye" = söylemiş bulunuyorum.'),
      _mc(id: 'b1_l04_e4',
        ku: 'Dema temambûyî ya niha çawa tê çêkirin?',
        tr: 'Doğru kuralı seç',
        opts: [
          'Pêşgira "di-" + rayek',
          'Rayeka borî + paşgira "-iye/-ye"',
          'Rayeka niha + paşgira kes',
          'Pêşgira "dê" + rayeka niha',
        ],
        ci: 1,
        note: 'Geçmiş kök + "-iye/-ye": hat→hatiye, çû→çûye, got→gotiye. [TH] §72'),
      _fill(id: 'b1_l04_e5', before: 'Birê min', after: ' bajêr.',
        tr: 'Kardeşim şehre gitmiş. (hâlâ orada)',
        opts: ['diçe', 'çûye', 'dê biçe', 'çû'],
        ci: 1,
        note: '"Çûye" = gitmiş (geçişsiz perfect). Çû + -ye.'),
      _speak(id: 'b1_l04_e6',
        ku: 'Pîrê hatiye. Birayê min çûye bajêr. Min ev pirtûk xwendiye.',
        tr: 'Büyükanne gelmiş. Kardeşim şehre gitmiş. Ben bu kitabı okumuşum.'),
    ],
  ),

  LessonModel(
    id: 'b1_l05',
    kurmanjTitle: 'Dihat, Digot: Dema Berdewam a Borî',
    turkishTitle: 'Sürekli Geçmiş (Hikaye Kipi)',
    unitNumber: 2, lessonNumber: 2, level: 3,
    path: LessonPath.general,
    targetCardIds: _b1Cards(['dem_devam']).take(6).toList(),
    estimatedMinutes: 10,
    exercises: [
      _mc(id: 'b1_l05_e1',
        ku: 'Dema berdewam a borî ji bo kîjan rewşê tê bikar anîn?',
        tr: 'Doğru kullanım alanını bul',
        opts: [
          'Ji bo dema bê',
          'Ji bo karên borî yên berdewam an dubare',
          'Ji bo tiştên yekcar çêbûyî',
          'Ji bo dema niha',
        ],
        ci: 1,
        note: 'Sürekli geçmiş: devam eden ya da tekrar eden geçmiş eylemler. Hikaye anlatımında kritik.'),
      _fill(id: 'b1_l05_e2', before: 'Pîrê her êvarê', after: ' malê.',
        tr: 'Büyükanne her akşam eve geliyordu.',
        opts: ['dihat', 'hatiye', 'tê', 'hat'],
        ci: 0,
        note: '"Her êvarê" tekrar → sürekli geçmiş "dihat" (di- + hat + paşgir).'),
      _fill(id: 'b1_l05_e3', before: 'Bavê min timî', after: ' çîrokên xweş.',
        tr: 'Babam her zaman güzel hikayeler anlatırdı.',
        opts: ['gotiye', 'dibêje', 'digot', 'got'],
        ci: 2,
        note: '"Timî" = her zaman → alışkanlık → "digot". [TH] §70'),
      _mc(id: 'b1_l05_e4',
        ku: 'Dema berdewam a borî çawa tê çêkirin?',
        tr: 'Doğru yapıyı bul',
        opts: [
          'Pêşgira "di-" + rayeka borî + paşgira kes',
          'Rayeka niha + paşgira kes',
          'Pêşgira "ne-" + rayek',
          'Pêşgira "dê" + rayek',
        ],
        ci: 0,
        note: 'di- + geçmiş kök + kişi eki: di + hat + (person) = dihatim, dihatî, dihat... [TH] §70'),
      _fill(id: 'b1_l05_e5', before: 'Birê min pirtûk', after: ' li kitêbxaneyê.',
        tr: 'Kardeşim kütüphanede kitap okuyordu.',
        opts: ['dixwend', 'xwend', 'dixwîne', 'xwendiye'],
        ci: 0,
        note: 'Devam eden geçmiş eylem → "dixwend".'),
      _speak(id: 'b1_l05_e6',
        ku: 'Pîrê digot: "Xanî helbestvanekî mezin bû." Bavê min her tim dihat.',
        tr: 'Büyükanne derdi: "Xanî büyük bir şairdi." Babam her zaman gelirdi.'),
    ],
  ),

  LessonModel(
    id: 'b1_l06',
    kurmanjTitle: 'Bila Bê: Mebestî (Subjunctive)',
    turkishTitle: 'Dilek-Şart Kipi',
    unitNumber: 2, lessonNumber: 3, level: 3,
    path: LessonPath.general,
    targetCardIds: _b1Cards(['subjunctive', 'subjunctîf']).take(6).toList(),
    estimatedMinutes: 11,
    exercises: [
      _mc(id: 'b1_l06_e1',
        ku: 'Kipa mebestî (subjunctive) çawa tê çêkirin?',
        tr: 'Doğru yapıyı seç',
        opts: [
          'Pêşgira "bi-" + rayek + paşgira kes',
          'Pêşgira "ne-" + rayek',
          'Pêşgira "dê" + rayek',
          'Pêşgira "di-" + rayek',
        ],
        ci: 0,
        note: '"Bi-" eki mebestî: bikim (yapayım), bixwe (yesin), bê (gelsin). [BH] §190'),
      _fill(id: 'b1_l06_e2', before: 'Bila pîrê', after: '!',
        tr: 'Büyükanne gelsin!',
        opts: ['bê', 'dihat', 'hat', 'tê'],
        ci: 0,
        note: '"Bila" + mebestî: "bê" (gelsin). "Hatin" fiilinin mebestî kökü özel: "bê".'),
      _fill(id: 'b1_l06_e3', before: 'Dibe ku ew rast', after: '.',
        tr: 'Olabilir ki o doğru olsun.',
        opts: ['be', 'ye', 'bû', 'dibe'],
        ci: 0,
        note: '"Dibe ku" + mebestî "be" = olabilir ki olsun. İhtimal kalıbı. [TH] §78'),
      _mc(id: 'b1_l06_e4',
        ku: '"Ger ez werim, tu dê çi bikî?" — di rêza pêşî de kîjan kip heye?',
        tr: 'İlk cümledeki kipi bul',
        opts: [
          'Dema borî',
          'Kipa mebestî (ji bo merc)',
          'Dema niha',
          'Dema bê tenê',
        ],
        ci: 1,
        note: '"Ger" + mebestî "werim" (gelirsem). Şart cümlesi → mebestî.'),
      _fill(id: 'b1_l06_e5', before: 'Ez dixwazim pirtûkekê', after: '.',
        tr: 'Ben bir kitap okumak istiyorum.',
        opts: ['dixwînim', 'xwend', 'dê bixwînim', 'bixwînim'],
        ci: 3,
        note: 'Modal fiil "dixwazim" sonrası mebestî: "bixwînim" (okuyayım).'),
      _speak(id: 'b1_l06_e6',
        ku: 'Bila aştî li welatê me hebe! Dibe ku ew zû bê. Ger tu werî, em ê bi hev re biçin.',
        tr: 'Vatanımızda barış olsun! Belki erken gelir. Sen gelirsen birlikte gideriz.'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // BİRİM 3 — Qada Civakî (2 ders)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'b1_l07',
    kurmanjTitle: 'Azadî, Aştî û Welat',
    turkishTitle: 'Özgürlük, Barış ve Vatan',
    unitNumber: 3, lessonNumber: 1, level: 3,
    path: LessonPath.general,
    targetCardIds: _b1Cards(['siyaset', 'kimlik']).take(8).toList(),
    culturalRewardId: 'cegerxwin_1',
    estimatedMinutes: 10,
    exercises: [
      _ls(id: 'b1_l07_e1',
        ku: 'Azadî',
        tr: 'Ne anlama geliyor?',
        opts: ['Zordarî', 'Nîqaş', 'Azadî', 'Tirs'],
        ci: 2,
        note: '"Azadî" = özgürlük. Kürt kültürünün temel kavramı.'),
      _mc(id: 'b1_l07_e2',
        ku: '"Welat" tê çi wateyê?',
        tr: 'Doğru tanımı bul',
        opts: [
          'Gundê biçûk ê li deşt an çiyayan',
          'Kuçeya teng a di nav bajaran de',
          'Ax û memleket',
          'Bajarê mezin ê pîşesazî',
        ],
        ci: 2,
        note: '"Welat" = vatan, memleket. Kürtçe\'nin en duygusal kavramlarından.'),
      _fill(id: 'b1_l07_e3', before: 'Em aştî û', after: ' dixwazin.',
        tr: 'Barışın yanında olumlu bir ulusal kavramı istiyoruz. İPUCU: "Aştî û ___" ikilisi sık geçer; bağlam vatan/ulus.',
        opts: ['azadî', 'şer', 'kêm', 'tirs'],
        ci: 0,
        note: '"Aştî û azadî" = barış ve özgürlük (sık birlikte). "Şer" (savaş) zıt, "tirs" (korku) ve "kêm" (eksik) bağlama uymaz.'),
      _mc(id: 'b1_l07_e4',
        ku: '"Mafê mirovan" tê çi wateyê?',
        tr: 'Doğru çeviriyi bul',
        opts: [
          'Pirtûka mirovan',
          'Welatê mirovan',
          'Mafê ku her mirov xwedî ye',
          'Hikmeta mirovan',
        ],
        ci: 2,
        note: '"Maf" (hak) + "ê mirovan" (insanların) = insan hakları.'),
      _fill(id: 'b1_l07_e5', before: 'Çanda kurdî gelek', after: ' ye.',
        tr: 'Kürt kültürü çok ___ . Olumlu bir nitelik söyleniyor (kültür değerlendirmesi). İPUCU: "feqîr" (fakir) zıttı.',
        opts: ['hişk', 'dewlemend', 'feqîr', 'kêm'],
        ci: 1,
        note: '"Dewlemend" = zengin (sahibi olmak: dewlet+mend). "Feqîr" (fakir), "kêm" (az), "hişk" (sert) — kültür için olumlu değil.'),
      _speak(id: 'b1_l07_e6',
        ku: 'Azadî, aştî û maf girîng in. Welatê me bi çanda xwe dewlemend e.',
        tr: 'Özgürlük, barış ve haklar önemlidir. Vatanımız kültürüyle zengindir.'),
    ],
  ),

  LessonModel(
    id: 'b1_l08',
    kurmanjTitle: 'His û Hizirîn',
    turkishTitle: 'Duygu ve Düşünce',
    unitNumber: 3, lessonNumber: 2, level: 3,
    path: LessonPath.general,
    targetCardIds: _b1Cards(['his', 'rengder']).take(8).toList(),
    estimatedMinutes: 10,
    exercises: [
      _ls(id: 'b1_l08_e1',
        ku: 'Hişmend',
        tr: 'Ne anlama geliyor?',
        opts: ['Westayî', 'Xemgîn', 'Birçî', 'Hişyar û zana'],
        ci: 3,
        note: '"Hişmend" = akıllı, bilge. Hiş (akıl) + -mend (sahip).'),
      _mc(id: 'b1_l08_e2',
        ku: '"Dilovan" çawa mirov e?',
        tr: 'Doğru açıklamayı bul',
        opts: [
          'Mirovek xurt',
          'Mirovek bi dilê germ, bi merheme',
          'Mirovek bilind',
          'Mirovek sar û hişk',
        ],
        ci: 1,
        note: '"Dilovan" = merhametli, şefkatli. "Dil" (kalp) kök bileşeni. Aile fertleri için tipik sıfat.'),
      _fill(id: 'b1_l08_e3', before: 'Pîra min pir', after: ' e.',
        tr: 'Büyükannem çok sıcak/şefkatli — pozitif duygu sıfatı. İPUCU: kelimenin kökünde "dil" (kalp) var.',
        opts: ['sar', 'dilovan', 'dirêj', 'gewr'],
        note: '"Dilovan" = "dil" + "-ovan" — kalpten geliştiren = sevecen/merhametli. "Pîra min" — pîr (mê) + ezafe -a + min. "Sar/gewr/dirêj" anlamca uygun değil.',
        ci: 1),
      _mc(id: 'b1_l08_e4',
        ku: '"Xeyidîn" tê çi wateyê?',
        tr: 'Doğru çeviriyi bul',
        opts: [
          'Kenîna bi keyf û şahiya derûnî',
          'Qehirîn û tûre bûn',
          'Gotina peyvên hêja yên ji bo pesnê',
          'Xewandina kesekî bi awayê dilxweş',
        ],
        ci: 1,
        note: '"Xeyidîn" = kızmak. "Ez xeyidîm" = kızdım.'),
      _fill(id: 'b1_l08_e5', before: 'Ez gelek', after: ' bûm, lê niha baş im.',
        tr: 'Geçmişte olumsuz duygu durumum vardı, şimdi iyi. "şa" (mutlu) zıttı bekleniyor. İPUCU: kelimenin kökü "xem" (kaygı).',
        opts: ['şa', 'xemgîn', 'dilşikestî', 'bilind'],
        ci: 1,
        note: '"Xemgîn" = üzgün ("xem" + "-gîn"). "Şa" mutlu (zıt anlam — yanlış), "bilind" yüksek, "dilşikestî" kalbi kırık (daha güçlü). Genel günlük üzüntü için xemgîn.'),
      _speak(id: 'b1_l08_e6',
        ku: 'Ez hişmend im. Tu dilovan î. Ew wêrek e. Em bi hev re xweş in.',
        tr: 'Ben akıllıyım. Sen merhametlisin. O cesurdur. Birlikte iyiyiz.'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // BİRİM 4 — Deyim û Kêlma Kirî (2 ders — Rêya Malê)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'b1_l09',
    kurmanjTitle: 'Deyimên Rojane',
    turkishTitle: 'Günlük Deyimler',
    unitNumber: 4, lessonNumber: 1, level: 3,
    path: LessonPath.heritage,
    targetCardIds: _b1Cards(['deyim']).take(6).toList(),
    culturalRewardId: 'proverb_1',
    estimatedMinutes: 10,
    exercises: [
      _mc(id: 'b1_l09_e1',
        ku: '"Serê xwe xweş bike!" kengî tê gotin?',
        tr: 'Doğru bağlamı bul',
        opts: [
          'Di civînê de',
          'Di şerê de',
          'Di dawetê de',
          'Dema xatir ji hev dixwazin',
        ],
        ci: 3,
        note: 'Vedalaşma deyimi: "Serê xwe xweş bike" = kendine iyi bak.'),
      _mc(id: 'b1_l09_e2',
        ku: '"Çavên te ronî!" kengî tê gotin?',
        tr: 'Doğru bağlamı bul',
        opts: [
          'Di bazarê de',
          'Beriya xewê',
          'Di şîn û taziyan de',
          'Dema pîrozbahiyekê (zarok, serkeftin)',
        ],
        ci: 3,
        note: 'Tebrik deyimi: "Çavên te ronî!" = gözlerin aydın (kutlama).'),
      _fill(id: 'b1_l09_e3', before: 'Piştî alîkariyekê:', after: '!',
        tr: 'Yardımdan sonra söylenen kalıp',
        opts: ['Rojbûna te pîroz be', 'Destê te bi xêr', 'Bi xêr hatî', 'Xatirê te'],
        ci: 1,
        note: '"Destê te bi xêr" = ellerin hayırlı olsun. Yardım sonrası teşekkür.'),
      _mc(id: 'b1_l09_e4',
        ku: 'Gava yek tê mala te, tu çi dibêjî?',
        tr: 'Doğru karşılama deyimini bul',
        opts: [
          'Bi xêr hatî!',
          'Bi mêrxasî',
          'Xatirê te',
          'Serê te sax be',
        ],
        ci: 0,
        note: '"Bi xêr hatî" = hoş geldin. Konuk karşılama kalıbı.'),
      _fill(id: 'b1_l09_e5', before: 'Gava mirovek mirî:', after: '!',
        tr: 'Taziye kalıbı: "Başın sağ olsun"',
        opts: ['Dil û can', 'Serê te sax be', 'Çavên te ronî', 'Bi mêrxasî'],
        ci: 1,
        note: '"Serê te sax be" = başın sağ olsun. Standart taziye deyimi. "Sax" = sağ/sağlıklı.'),
      _speak(id: 'b1_l09_e6',
        ku: 'Bi xêr hatî, heval! Destê te bi xêr be. Serê xwe xweş bike.',
        tr: 'Hoş geldin, arkadaş! Ellerin hayırlı olsun. Kendine iyi bak.'),
    ],
  ),

  LessonModel(
    id: 'b1_l10',
    kurmanjTitle: 'Deyimên Evînî û Daxwazî',
    turkishTitle: 'Sevgi ve İyi Dilek Deyimleri',
    unitNumber: 4, lessonNumber: 2, level: 3,
    path: LessonPath.heritage,
    targetCardIds: _b1Cards(['deyim']).skip(4).take(6).toList(),
    culturalRewardId: 'proverb_2',
    estimatedMinutes: 10,
    exercises: [
      _mc(id: 'b1_l10_e1',
        ku: '"Dil û can" tê çi wateyê?',
        tr: 'Doğru çeviriyi bul',
        opts: [
          'Bi tirsê',
          'Bi dilê şikestî',
          'Bi hemû hêz û hesta xwe',
          'Bê hêz',
        ],
        ci: 2,
        note: '"Dil" (gönül) + "can" = tüm kalpten, can-ı gönülden.'),
      _fill(id: 'b1_l10_e2', before: 'Ez', after: ' ji te hez dikim.',
        tr: 'Tüm kalbimle seni seviyorum.',
        opts: ['bi tirs', 'bi sar', 'bi dil û can', 'bi kêm'],
        ci: 2,
        note: 'Deyim: "bi dil û can" = can-ı gönülden. "Bi" edatı + deyim, kuvvetli sevgi ifadesi.'),
      _mc(id: 'b1_l10_e3',
        ku: '"Bi mêrxasî" tê çi wateyê?',
        tr: 'Doğru çeviriyi bul',
        opts: [
          'Bi tirsê û dudilî',
          'Bi şermê û lawazî',
          'Bi lez û bê hêz',
          'Bi wêrekî û cesaretê',
        ],
        ci: 3,
        note: '"Mêrxas" = yiğit. "Bi mêrxasî" = yiğitçe / cesaretle. Tüm seçenekler ardışık-isim ile dengelenmiştir.'),
      _fill(id: 'b1_l10_e4', before: 'Roja te bila', after: ' be!',
        tr: 'İyi dilek (dua) kalıbı: "Bila ___ be" — biri için iyi gün dileniyor. Hangi sıfat olumlu/iyi anlamı taşır?',
        opts: ['reş', 'hişk', 'sar', 'xweş'],
        ci: 3,
        note: 'Dua kalıbı: "Bila xweş be" — mebestî ile dilek. Diğer seçenekler olumsuz: sar (soğuk), hişk (sert), reş (siyah/karanlık).'),
      _mc(id: 'b1_l10_e5',
        ku: '"Jiyana te dirêj be!" kengî tê gotin?',
        tr: 'Doğru bağlamı bul',
        opts: [
          'Di şînê de',
          'Di pîrozbahiyekê de (rojbûn, zewac)',
          'Di şerê de',
          'Dema xatir dixwazin',
        ],
        ci: 1,
        note: 'Ömür duası: "Jiyana te dirêj be" — doğum günü, evlilik vb. iyi dilek.'),
      _speak(id: 'b1_l10_e6',
        ku: 'Bi dil û can pîroz dikim. Jiyana te dirêj be! Bi mêrxasî jiyan bike.',
        tr: 'Can-ı gönülden tebrik ederim. Ömrün uzun olsun! Yiğitçe yaşa.'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // BİRİM 5 — Rengdêr û Xweza (2 ders)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'b1_l11',
    kurmanjTitle: 'Rengdêrên Berawirdkirinê',
    turkishTitle: 'Sıfat Karşılaştırma (Comparative)',
    unitNumber: 5, lessonNumber: 1, level: 3,
    path: LessonPath.general,
    targetCardIds: _b1Cards(['rengder']).take(8).toList(),
    estimatedMinutes: 10,
    exercises: [
      _mc(id: 'b1_l11_e1',
        ku: 'Paşgira berawirdkirinê (daha) di Kurmancî de çi ye?',
        tr: 'Doğru eki bul',
        opts: ['-tir', '-ok', '-in', '-tirîn'],
        ci: 0,
        note: 'Comparative eki "-tir": mezintir = daha büyük. [TH] §85'),
      _fill(id: 'b1_l11_e2', before: 'Birê min ji min', after: ' e.',
        tr: 'Kardeşim benden daha büyüktür.',
        opts: ['biçûk', 'mezintir', 'mezin', 'mezintirîn'],
        ci: 1,
        note: '"Ji ... -tir" = -den daha. "Ji min mezintir" = benden daha büyük.'),
      _mc(id: 'b1_l11_e3',
        ku: 'Paşgira bilindahiyê (en) çi ye?',
        tr: 'Doğru eki bul',
        opts: ['-ek', '-tir', '-î', '-tirîn'],
        ci: 3,
        note: 'Superlative eki "-tirîn": mezintirîn = en büyük. [TH] §86'),
      _fill(id: 'b1_l11_e4', before: 'Ev pirtûk', after: ' pirtûka min e.',
        tr: 'Bu kitap en güzel kitabımdır.',
        opts: ['xweştir', 'xweştirîn', 'xweş', 'nexweş'],
        ci: 1,
        note: '"Xweştirîn" = en güzel. Superlative "-tirîn" eki.'),
      _mc(id: 'b1_l11_e5',
        ku: '"Hişmendtir" tê çi wateyê?',
        tr: 'Doğru çeviriyi bul',
        opts: [
          'Ne hişmend',
          'Hişmend',
          'Herî hişmend',
          'Zêdetir hişmend',
        ],
        ci: 3,
        note: 'Hişmend + tir = daha akıllı (comparative).'),
      _speak(id: 'b1_l11_e6',
        ku: 'Pîrê ji min hişmendtir e. Xanî helbestvanê mezintirîn bû. Ev ya xweştirîn e.',
        tr: 'Büyükanne benden daha akıllıdır. Xanî en büyük şairdi. Bu en güzelidir.'),
    ],
  ),

  LessonModel(
    id: 'b1_l12',
    kurmanjTitle: 'Demsal û Xweza',
    turkishTitle: 'Mevsimler ve Doğa',
    unitNumber: 5, lessonNumber: 2, level: 3,
    path: LessonPath.general,
    targetCardIds: _b1Cards(['xweza']).take(8).toList(),
    culturalRewardId: 'newroz_1',
    estimatedMinutes: 10,
    exercises: [
      _ls(id: 'b1_l12_e1',
        ku: 'Demsal',
        tr: 'Ne anlama geliyor?',
        opts: [
          'Mirovek xurt',
          'Parçeyek ji salê',
          'Bajarekî mezin',
          'Xwarineke xweş',
        ],
        ci: 1,
        note: '"Demsal" = mevsim (yılın dört parçasından biri).'),
      _mc(id: 'b1_l12_e2',
        ku: '"Çandin" kîjan kar e?',
        tr: 'Doğru açıklamayı bul',
        opts: [
          'Stran lê dan',
          'Firotin di bazarê de',
          'Çîrok gotin',
          'Tov di axê de danîn',
        ],
        ci: 3,
        note: '"Çandin" = ekmek (tohum). Çiftçilik fiili. [FB]'),
      _fill(id: 'b1_l12_e3', before: 'Bavê min di biharê de genim', after: '.',
        tr: 'Babam baharda buğday ekti.',
        opts: ['çand', 'got', 'xwar', 'dît'],
        ci: 0,
        note: '"Çand" = çandin fiilinin ergatif geçmişi (= ekti).'),
      _mc(id: 'b1_l12_e4',
        ku: '"Berhev kirin" tê çi wateyê?',
        tr: 'Doğru anlamı bul',
        opts: [
          'Li hev anîn, hasat kirin',
          'Çandin',
          'Firotin',
          'Xwarin',
        ],
        ci: 0,
        note: '"Berhev" (toplu) + "kirin" (yapmak) = toplamak, hasat etmek.'),
      _fill(id: 'b1_l12_e5', before: 'Erdê Kurdistanê gelek', after: ' e.',
        tr: 'Kürdistan toprağı çok berekettir.',
        opts: ['reş', 'bereketdar', 'zuha', 'sar'],
        ci: 1,
        note: '"Bereket" + "-dar" (sahip) = bereketli.'),
      _speak(id: 'b1_l12_e6',
        ku: 'Bihar demsaleke xweş e. Payîzê em berhev dikin. Sala nû bi bereket be!',
        tr: 'Bahar güzel mevsimdir. Sonbaharda hasat yaparız. Yeni yıl bereketli olsun!'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // BİRİM 6 — Edebiyat û Çand (3 ders — Rêya Çandê)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'b1_l13',
    kurmanjTitle: 'Ehmedê Xanî û Nûbahara Biçûkan',
    turkishTitle: 'Ehmedê Xanî ve Eserleri',
    unitNumber: 6, lessonNumber: 1, level: 3,
    path: LessonPath.cultural,
    targetCardIds: _b1Cards(['edebiyat']).take(6).toList(),
    culturalRewardId: 'xani_1',
    estimatedMinutes: 11,
    exercises: [
      _mc(id: 'b1_l13_e1',
        ku: 'Ehmedê Xanî (1651–1707) kî ye?',
        tr: 'Doğru tanımı seç',
        opts: [
          'Helbestvan û nivîskarekî mezin ê kurd',
          'Cotkarekî gundewar ê serdema Osmanî',
          'Stranbêjekî gel ê dengbêjiya kevneşopî',
          'Padîşahekî herêmî yê deşta Mêrdînê',
        ],
        ci: 0,
        note: 'Xanî büyük Kürt şair ve yazardır. "Mem û Zîn" (1695) ve "Nûbahara Biçûkan" (1683) yazarı.'),
      _mc(id: 'b1_l13_e2',
        ku: '"Nûbahara Biçûkan" çi ye?',
        tr: 'Doğru tanımı bul',
        opts: [
          'Rojnameyek',
          'Pirtûkeke fenî',
          'Ferhenga pêşîn a kurdî-erebî bi nezmê',
          'Romanek niha',
        ],
        ci: 2,
        note: '"Nûbahara Biçûkan" (1683) — ilk manzum Kürtçe-Arapça sözlük. Çocuklar için.'),
      _fill(id: 'b1_l13_e3', before: '"Mem û Zîn" di sala', after: ' de hatiye nivîsîn.',
        tr: '"Mem û Zîn" hangi yılda yazılmıştır?',
        opts: ['1683', '1695', '1707', '1800'],
        ci: 1,
        note: 'Xanî "Mem û Zîn"i 1695\'te bitirdi. Kürt edebiyatının klasik eseri.'),
      _mc(id: 'b1_l13_e4',
        ku: '"Kurd in û Kurdistan heye" — ev rêz ji kê hatiye?',
        tr: 'Doğru şairi bul',
        opts: [
          'Ehmedê Xanî (Mem û Zîn)',
          'Mela Cizîrî',
          'Feqiyê Teyran',
          'Cegerxwîn',
        ],
        ci: 0,
        note: 'Xanî\'nin meşhur dizesi. Kürt ulusal bilincinin temel metni.'),
      _fill(id: 'b1_l13_e5', before: 'Xanî', after: ' ê mezin bû.',
        tr: 'Xanî büyük bir Kürt ...dı.',
        opts: ['helbestvanekî kurd', 'cotkarekî kurd', 'hunermendekî kurd', 'karmendekî kurd'],
        ci: 0,
        note: '"Helbestvanekî kurd ê mezin" = büyük bir Kürt şair. Belirsiz ezafe -î + attribute + ê mezin.'),
      _speak(id: 'b1_l13_e6',
        ku: 'Ehmedê Xanî helbestvanê mezin ê kurd bû. "Mem û Zîn" şahkara wî ye.',
        tr: 'Ehmedê Xanî büyük Kürt şairiydi. "Mem û Zîn" onun şaheseridir.'),
    ],
  ),

  LessonModel(
    id: 'b1_l14',
    kurmanjTitle: 'Gotinên Pêşiyan',
    turkishTitle: 'Atasözleri',
    unitNumber: 6, lessonNumber: 2, level: 3,
    path: LessonPath.cultural,
    targetCardIds: _b1Cards(['deyim', 'nirx']).skip(6).take(6).toList(),
    culturalRewardId: 'proverb_1',
    estimatedMinutes: 10,
    exercises: [
      _mc(id: 'b1_l14_e1',
        ku: '"Ziman dermanê dilê mirov e." tê çi peyamê dide?',
        tr: 'Doğru yorumu bul',
        opts: [
          'Ziman ji bo dil girîng e, mîna dermanê',
          'Ziman tenê ji bo peyivînê ye',
          'Dil nabêje',
          'Dil nexweş e',
        ],
        ci: 0,
        note: 'Atasözü: Dil kalbin ilacıdır. Ana dilin değerine vurgu.'),
      _mc(id: 'b1_l14_e2',
        ku: '"Zimanê xwe ji bîr neke" çi peyamê dide?',
        tr: 'Doğru mesajı bul',
        opts: [
          'Ziman ne girîng e',
          'Zimanê dayikê biparêze, nasnameyê winda neke',
          'Pîşe hilbijêre',
          'Her tim biaxive',
        ],
        ci: 1,
        note: 'Atasözü: Dilini unutma. Ana dilin korunması ve kimlik.'),
      _fill(id: 'b1_l14_e3', before: '"Av di cih de', after: ' dibe."',
        tr: 'Atasözü: "Yerinde duran su ... olur."',
        opts: ['hişk', 'zelal', 'bêhn', 'şîrîn'],
        ci: 2,
        note: '"Av di cih de bêhn dibe" = durgun su kokar. Hareketsizliğe karşı atasözü.'),
      _mc(id: 'b1_l14_e4',
        ku: '"Destê te bi xêr be!" kengî tê gotin?',
        tr: 'Doğru bağlamı seç',
        opts: [
          'Piştî alîkarî yan xebatê',
          'Di bazarê de',
          'Di şerê de',
          'Di xewê de',
        ],
        ci: 0,
        note: '"Destê te bi xêr be" = ellerin hayırlı olsun. Yardım/iş sonrası söylenen dua.'),
      _fill(id: 'b1_l14_e5', before: '"Dil bi dil re,', after: ' bi can re."',
        tr: 'Atasözünü tamamla',
        opts: ['mal', 'dil', 'can', 'av'],
        ci: 2,
        note: '"Dil bi dil re, can bi can re" = gönül gönüle, can cana. Dostluk atasözü.'),
      _speak(id: 'b1_l14_e6',
        ku: 'Ziman dermanê dilê mirov e. Zimanê xwe ji bîr neke. Dil bi dil re, can bi can re.',
        tr: 'Dil kalbin ilacıdır. Dilini unutma. Gönül gönüle, can cana.'),
    ],
  ),

  LessonModel(
    id: 'b1_l15',
    kurmanjTitle: 'Mem û Zîn: Parçe û Têgihîştin',
    turkishTitle: 'Mem û Zîn: Kısa Metin ve Kavrama',
    unitNumber: 6, lessonNumber: 3, level: 3,
    path: LessonPath.cultural,
    targetCardIds: _b1Cards(['edebiyat', 'dîrok']).skip(4).take(6).toList(),
    culturalRewardId: 'xani_1',
    estimatedMinutes: 11,
    exercises: [
      _mc(id: 'b1_l15_e1',
        ku: '"Mem û Zîn" çi ye?',
        tr: 'Doğru tanımı bul',
        opts: [
          'Şahkara edebiyata kurdî ya Ehmedê Xanî',
          'Rojnameyeke nûjen a ku îro tê weşandin',
          'Pirtûkeke zanistî ya li ser bîyolojiyê',
          'Ferhengeke kurmancî-erebî ya kevneşopî',
        ],
        ci: 0,
        note: '"Mem û Zîn" (1695) — Xanî\'nin şaheseri. Kürt edebiyatının klasik eseri.'),
      _mc(id: 'b1_l15_e2',
        ku: 'Mem û Zîn kî ne?',
        tr: 'Doğru tanımı bul',
        opts: [
          'Du helbestvan',
          'Du evîndarên ku ji hev cuda mabûn',
          'Du stranbêj',
          'Du cotkar',
        ],
        ci: 1,
        note: 'Mem û Zîn — ayrılmış iki âşık. Botan miri Mîr Zeynedîn\'in kız kardeşi Zîn ile Mem arasındaki trajik aşk.'),
      _fill(id: 'b1_l15_e3', before: 'Xanî bi', after: ' ji bêdewletiya Kurdan dipeyive.',
        tr: 'Xanî Kürtlerin devletsizliğinden ... bahseder.',
        opts: ['bê hest', 'kêfê', 'keserê', 'xewê'],
        ci: 2,
        note: '"Bi keserê" = üzüntüyle, hüzünle. Xanî\'nin temel motivi.'),
      _mc(id: 'b1_l15_e4',
        ku: 'Li gor Xanî, sedema bêtifaqiya Kurdan çi ye?',
        tr: 'Xanî\'nin teşhisini seç',
        opts: [
          'Bêçandî û nezanîna mîrasa edebiyata gel',
          'Kêmbûna axê û cografyaya çiyayî ya zehmet',
          'Bêyekîtî û tunebûna dewleta kurdî',
          'Bandora zimanên biyanî yên derdorê',
        ],
        ci: 2,
        note: 'Xanî, Kürtlerin birlik yokluğunu ve devletsizliğini başlıca sorun olarak görür.'),
      _fill(id: 'b1_l15_e5', before: 'Mem û Zîn bi', after: ' dawî dibe.',
        tr: '"Mem û Zîn" nasıl sona erer?',
        opts: ['keserê', 'şahiyê', 'bextiyariyê', 'kenê'],
        ci: 0,
        note: '"Keser" (hüzün, keder) ile sonlanır: Mem ölür, Zîn de mezarı başında ölür.'),
      _speak(id: 'b1_l15_e6',
        ku: 'Xanî di "Mem û Zîn" de behsa evîn, welat û bêdewletiya Kurdan dike.',
        tr: 'Xanî "Mem û Zîn"de aşk, vatan ve Kürt devletsizliğinden bahseder.'),
    ],
  ),
];
