import 'lesson_entities.dart';
import 'b2_kelime_db.dart';

// ════════════════════════════════════════════════════════════════
// B2 — 15 DERS TANIMI (Navîn-Jor / Orta-Üst)
//
// Pedagojik Odak (CEFR B2):
// - Dem bileşik: past perfect (hatibû), perfect subjunctive (hatibe)
// - Pasîf: tê çêkirin, hate gotin, dê bête kirin
// - Lêkerên hevedudanî (bileşik fiiller): li ber ketin, ser ketin
// - Şart kompleks: Ger bûya, eger hebûya
// - Akademik ziman: ji aliyê ... ve, bi awayekî, bi vê mebestê
// - Civak, medya, felsefe kavramları
// - Edebiyat klasîk: Mem û Zîn genişletilmiş, Mela Cizîrî dîvân
//
// Path dağılımı: 10 general · 2 heritage · 3 cultural
// ════════════════════════════════════════════════════════════════

List<String> _b2Cards(List<String> kats) => kB2All
    .where((k) => kats.contains(k.kat))
    .map((k) => k.id)
    .toList();

ExerciseModel _mc({
  required String id, required String ku, required String tr,
  required List<String> opts, required int ci,
  String? note, int xp = 12,
}) => ExerciseModel(
  id: id, type: ExerciseType.multipleChoice,
  kurmanjPrompt: ku, turkishPrompt: tr,
  options: opts, correctAnswer: opts[ci], correctIndex: ci,
  grammarNote: note, xpReward: xp,
);

ExerciseModel _ls({
  required String id, required String ku, required String tr,
  required List<String> opts, required int ci,
  String? audio, String? note, int xp = 14,
}) => ExerciseModel(
  id: id, type: ExerciseType.listenAndSelect,
  kurmanjPrompt: ku, turkishPrompt: tr,
  options: opts, correctAnswer: opts[ci], correctIndex: ci,
  audioAsset: audio, grammarNote: note, xpReward: xp,
);

ExerciseModel _fill({
  required String id, required String before, required String after,
  required String tr, required List<String> opts, required int ci,
  String? note, int xp = 14,
}) => ExerciseModel(
  id: id, type: ExerciseType.fillInBlank,
  kurmanjPrompt: '$before ___ $after', turkishPrompt: tr,
  options: opts, correctAnswer: opts[ci], correctIndex: ci,
  grammarNote: note, xpReward: xp,
  wordPieces: [before.trim(), after.trim()],
);

ExerciseModel _speak({
  required String id, required String ku, required String tr,
  String? audio, int xp = 18,
}) => ExerciseModel(
  id: id, type: ExerciseType.speakingPractice,
  kurmanjPrompt: ku, turkishPrompt: tr,
  audioAsset: audio, xpReward: xp,
  options: ['Gelek baş', 'Nêzîk', 'Carek din'],
  correctAnswer: ku,
);

// ════════════════════════════════════════════════════════════════
// 15 DERS
// ════════════════════════════════════════════════════════════════

final kB2Lessons = <LessonModel>[

  // ─────────────────────────────────────────────────────────────
  // BİRİM 1 — Dem Bileşik û Pasîf (3 ders)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'b2_l01',
    kurmanjTitle: 'Dema Borî ya Dûr: Hatibû',
    turkishTitle: 'Past Perfect (Uzak Geçmiş)',
    unitNumber: 1, lessonNumber: 1, level: 4,
    path: LessonPath.general,
    targetCardIds: _b2Cards(['dem', 'ergatif_b2']).take(8).toList(),
    estimatedMinutes: 11, emoji: '⏳',
    exercises: [
      _mc(id: 'b2_l01_e1',
        ku: 'Dema borî ya dûr çawa tê çêkirin?',
        tr: 'Doğru yapıyı seç',
        opts: [
          'Rayeka niha + bûn',
          'Pêşgira "di-" + rayek',
          'Rayeka borî + bû + paşgira kes',
          'Pêşgira "dê" + rayek',
        ],
        ci: 2,
        note: 'Past perfect: geçmiş kök + "bû" + kişi eki. "Hatibû" = gelmişti. [TH] §73'),
      _fill(id: 'b2_l01_e2', before: 'Dema ez hatim, pîrê ji mêj ve', after: '.',
        tr: 'Ben geldiğimde, büyükanne çoktan gitmişti.',
        opts: ['diçû', 'çûbû', 'diçe', 'çûye'],
        ci: 1,
        note: '"Çûbû" = past perfect (gitmişti). Ana eylemden önceki geçmiş. [BH] §175'),
      _mc(id: 'b2_l01_e3',
        ku: '"Min gotibû ku ew dê bê." tê çi wateyê?',
        tr: 'Doğru çeviriyi bul',
        opts: [
          'Söylüyorum ki o gelir',
          'Söylerim ki o gelsin',
          'Söyledim ki o geliyor',
          'Söylemiştim ki o gelecek',
        ],
        ci: 3,
        note: '"Gotibû" = söylemişti. Ergatif + past perfect.'),
      _fill(id: 'b2_l01_e4', before: 'Berî ku em bigihin, baran', after: '.',
        tr: 'Biz varmadan önce yağmur yağmıştı.',
        opts: ['baribû', 'dibariya', 'dibare', 'bariye'],
        ci: 0,
        note: '"Baribû" = yağmıştı (past perfect). "Barîn" fiilinin geçmiş kökü + "bû". Distraktor "bariye" = yağmış (perfect). [TH] §73'),
      _mc(id: 'b2_l01_e5',
        ku: 'Kîjan peyv "had done" wateyê dide?',
        tr: 'Kurmancî past perfect\'i seç',
        opts: ['kiriye', 'kir', 'kiribû', 'dike'],
        ci: 2,
        note: '"Kiribû" = yapmıştı (past perfect ergatif).'),
      _speak(id: 'b2_l01_e6',
        ku: 'Dema min ew dît, ew ji zû ve hatibû. Min gotibû ku dê bimîne.',
        tr: 'Onu gördüğümde çoktan gelmişti. Kalacağını söylemiştim.'),
    ],
  ),

  LessonModel(
    id: 'b2_l02',
    kurmanjTitle: 'Hatibe: Mebestiya Temam',
    turkishTitle: 'Perfect Subjunctive',
    unitNumber: 1, lessonNumber: 2, level: 4,
    path: LessonPath.general,
    targetCardIds: _b2Cards(['dem', 'ergatif_b2']).skip(4).take(6).toList(),
    estimatedMinutes: 11, emoji: '🔮',
    exercises: [
      _mc(id: 'b2_l02_e1',
        ku: 'Mebestiya temam (perfect subjunctive) çawa tê çêkirin?',
        tr: 'Doğru yapıyı seç',
        opts: [
          'Pêşgira "dê" + rayek',
          'Pêşgira "ne-" + rayek',
          'Rayeka borî + bi- + -e',
          'Rayeka borî + paşgira -ibe / -be',
        ],
        ci: 3,
        note: '"Hatibe" = gelmiş olsun. Past participle + subjunctive "be". [TH] §79'),
      _fill(id: 'b2_l02_e2', before: 'Dibe ku ew', after: '.',
        tr: 'Olabilir ki o gelmiş olsun.',
        opts: ['hatibe', 'hatiye', 'bê', 'tê'],
        ci: 0,
        note: '"Hatibe" = gelmiş olsun. "Dibe ku" + perfect subj. Geçmiş ihtimal.'),
      _fill(id: 'b2_l02_e3', before: 'Gelo wan ev', after: '?',
        tr: 'Acaba onlar bunu yapmış olabilir mi?',
        opts: ['kiribûn', 'kiribe', 'kiriye', 'dikin'],
        ci: 1,
        note: 'Ergatifte lêker bi BERBIJÊR re dihev dike. "Ev" yekjimar → "kiribe" (perfect subjunctive yekjimar). Eger berbijêr pirjimar bûya, dibû "kiribin". [BH] §173'),
      _mc(id: 'b2_l02_e4',
        ku: 'Ferq di navbera "hatiye" û "hatibe" de çi ye?',
        tr: 'Farkı doğru açıkla',
        opts: [
          '"hatiye" raber, "hatibe" mebestî',
          '"hatiye" pirsyar, "hatibe" raber bê pirs',
          '"hatiye" borî, "hatibe" niha',
          '"hatiye" nerênî, "hatibe" erênî',
        ],
        ci: 0,
        note: '"Hatiye" = gelmiş (indicative). "Hatibe" = gelmiş olsun (subjunctive).'),
      _fill(id: 'b2_l02_e5', before: 'Bila ew heta niha', after: '.',
        tr: 'Bırak o şimdiye kadar gelmiş olsun.',
        opts: ['hatibe', 'tê', 'hat', 'bê'],
        ci: 0,
        note: '"Hatibe" = hatin fiilinin mebestiya temam (perfect subjunctive). "Heta niha" bağlamı ile kullanım doğal.'),
      _speak(id: 'b2_l02_e6',
        ku: 'Dibe ku ew hatibe. Gelo we ev bihîstibe? Bila wan ev tiştan kiribin.',
        tr: 'O gelmiş olabilir. Duymuş olabilir misiniz? Onlar bu şeyleri yapmış olsunlar.'),
    ],
  ),

  LessonModel(
    id: 'b2_l03',
    kurmanjTitle: 'Pasîf: Tê Kirin, Hate Gotin',
    turkishTitle: 'Edilgen Yapı',
    unitNumber: 1, lessonNumber: 3, level: 4,
    path: LessonPath.general,
    targetCardIds: _b2Cards(['pasif']).take(8).toList(),
    culturalRewardId: 'proverb_2',
    estimatedMinutes: 12, emoji: '🔄',
    exercises: [
      _mc(id: 'b2_l03_e1',
        ku: 'Pasîfa niha di Kurmancî de çawa tê çêkirin?',
        tr: 'Doğru yapıyı seç',
        opts: [
          'Rayeka niha + -in',
          '"Tê" (3. kes hatin) + mastar',
          'Pêşgira "di-" + rayek',
          'Pêşgira "bi-" + rayek',
        ],
        ci: 1,
        note: 'Şimdiki pasif: "tê" + mastar. "Tê gotin" = söyleniyor. [TH] §82'),
      _fill(id: 'b2_l03_e2', before: 'Di rojnameyê de', after: ' ku ev rast e.',
        tr: 'Gazetede bunun doğru olduğu yazılıyor.',
        opts: ['bibêje', 'gotiye', 'got', 'tê gotin'],
        ci: 3,
        note: '"Tê gotin" = söyleniyor / yazılıyor. Resmi-gazete dili kalıbı.'),
      _mc(id: 'b2_l03_e3',
        ku: 'Pasîfa borî çawa tê çêkirin?',
        tr: 'Doğru yapıyı bul',
        opts: [
          '"Ne-" + rayek',
          '"Hat/hate" + mastar',
          '"Di-" + rayek',
          '"Dê" + bê + mastar',
        ],
        ci: 1,
        note: 'Geçmiş pasif: "hate" + mastar. "Hate gotin" = denildi. [BH] §193'),
      _fill(id: 'b2_l03_e4', before: 'Ev pirtûk di sala 1695 de', after: '.',
        tr: 'Bu kitap 1695 yılında yazıldı.',
        opts: ['dinivîse', 'hate nivîsîn', 'dê bête nivîsîn', 'nivîsand'],
        ci: 1,
        note: '"Hate nivîsîn" = yazıldı (geçmiş pasif).'),
      _mc(id: 'b2_l03_e5',
        ku: '"Dê bête çêkirin" tê çi wateyê?',
        tr: 'Doğru çeviriyi bul',
        opts: ['Yapıldı', 'Yapılıyor', 'Yapılabilir', 'Yapılacak'],
        ci: 3,
        note: 'Gelecek pasif: "dê bête" + mastar. "Dê bête çêkirin" = yapılacak.'),
      _speak(id: 'b2_l03_e6',
        ku: 'Tê gotin ku Kurdistan xweş e. Ev pirtûk hate nivîsîn. Dê bête çêkirin.',
        tr: 'Kürdistan\'ın güzel olduğu söyleniyor. Bu kitap yazıldı. Yapılacak.'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // BİRİM 2 — Lêkerên Hevedudanî û Şart (3 ders)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'b2_l04',
    kurmanjTitle: 'Lêkerên Hevedudanî',
    turkishTitle: 'Bileşik Fiiller',
    unitNumber: 2, lessonNumber: 1, level: 4,
    path: LessonPath.general,
    targetCardIds: _b2Cards(['bileşik_leker', 'leker']).take(8).toList(),
    estimatedMinutes: 11, emoji: '🧩',
    exercises: [
      _mc(id: 'b2_l04_e1',
        ku: '"Li ber ketin" tê çi wateyê?',
        tr: 'Doğru çeviriyi bul',
        opts: [
          'Bi lez revîn ji cihekî, dûr ketin',
          'Xemgîn bûn, bandor lê kirin',
          'Bi ser ketin, serfiraz bûn ji peywirekê',
          'Xewandin, bi laliyê dilxweş kirin',
        ],
        ci: 1,
        note: '"Li ber ketin" = üzülmek, etkilenmek. "Ez li ber ketim" = üzüldüm. Bileşik fiil. [BH]'),
      _fill(id: 'b2_l04_e2', before: 'Ez ji bo îmtihanê', after: '.',
        tr: 'Sınava hazırlık eylemi (1.tekil şimdiki zaman). İPUCU: "xwendin" (okumak) ile "xebitîn" (çalışmak) ayrımı önemli — sınav genel hazırlık fiilidir.',
        opts: ['revîm', 'dixebitim', 'dikeve', 'dixwînim'],
        ci: 1,
        note: '"Xebitîn" = çalışmak (intransitive). "Dixwînim" (okuyorum) sadece okumayı; "Dixebitim" tüm ders çalışmayı kapsar. "Revîm" kaçtım, "dikeve" düşüyor — bağlama uymaz.'),
      _mc(id: 'b2_l04_e3',
        ku: '"Ser ketin" tê çi wateyê?',
        tr: 'Doğru çeviriyi bul',
        opts: [
          'Revîn ji peywirekê an dûrketina ji berpirsiyariyê',
          'Bi ser de hatin, serfiraz bûn',
          'Xewandina kesekî bi qenciyê an aramkirina dilxweş',
          'Ketin ji bilindahiyê an winda kirina hêzê',
        ],
        ci: 1,
        note: '"Ser ketin" = başarmak, galip gelmek. Geçişsiz bileşik fiil.'),
      _fill(id: 'b2_l04_e4', before: 'Ew di pêşbaziyê de', after: '.',
        tr: 'Yarışmada başarılı oldular.',
        opts: ['ji bîr kirin', 'ser ketin', 'li hev hatin', 'revîn'],
        ci: 1,
        note: '"Ser ketin" geçişsiz → ergatif YOK. Özne halê xwerû\'da: "Ew ser ketin" (onlar başardılar).'),
      _mc(id: 'b2_l04_e5',
        ku: '"Li hev kirin" tê çi wateyê?',
        tr: 'Doğru anlamı bul',
        opts: [
          'Jihevdanîn',
          'Bîrkirin',
          'Revîn',
          'Rêkxistin, sazkirin',
        ],
        ci: 3,
        note: '"Li hev kirin" = düzenlemek, tertiplemek.'),
      _speak(id: 'b2_l04_e6',
        ku: 'Ez ji bo îmtihanê dixebitim. Em ser ketin. Wan civîn li hev kir.',
        tr: 'Sınav için çalışıyorum. Başardık. Onlar toplantıyı düzenlediler.'),
    ],
  ),

  LessonModel(
    id: 'b2_l05',
    kurmanjTitle: 'Ger Bûya: Şertê Ne-Rast',
    turkishTitle: 'Gerçek Olmayan Şart',
    unitNumber: 2, lessonNumber: 2, level: 4,
    path: LessonPath.general,
    targetCardIds: _b2Cards(['şart', 'leker']).take(6).toList(),
    estimatedMinutes: 12, emoji: '🎭',
    exercises: [
      _mc(id: 'b2_l05_e1',
        ku: 'Şerta ne-rast (counterfactual) çawa tê çêkirin?',
        tr: 'Doğru yapıyı bul',
        opts: [
          '"Ger" + dema bê',
          '"Ger" + rayeka borî + "-a/-ya" + "bûya/diba"',
          '"Ger" + dema niha',
          '"Ger" + mebestî',
        ],
        ci: 1,
        note: '"Ger ez bûma, ez ê biçûma" = ben olsaydım giderdim. Gerçekleşmemiş şart. [TH] §88'),
      _fill(id: 'b2_l05_e2', before: 'Ger ez dewlemend', after: ', min ê mal bikira.',
        tr: 'Ben zengin olsaydım, ev alırdım.',
        opts: ['bûma', 'bim', 'im', 'bûm'],
        ci: 0,
        note: '"Bûma" = olsaydım. Counterfactual. [BH] §190'),
      _mc(id: 'b2_l05_e3',
        ku: '"Eger te gotibûya, min dê bizanibûya." tê çi wateyê?',
        tr: 'Doğru çeviriyi bul',
        opts: [
          'Söyleseydin bilirdim',
          'Söylersen bilecektim',
          'Söylersen bilirim',
          'Söyledin bildim',
        ],
        ci: 0,
        note: 'Geçmiş karşı-olgusal şart: "gotibûya" + "bizanibûya" = söyleseydin bilirdim.'),
      _fill(id: 'b2_l05_e4', before: 'Ger baran bibariya, em', after: '.',
        tr: 'Yağmur yağsaydı, biz kalırdık.',
        opts: ['diçûn', 'dimana', 'çûn', 'bimînin'],
        ci: 1,
        note: '"Dimana" = kalırdık (em dimana: çoğul özne + counterfactual). [TH] §88'),
      _mc(id: 'b2_l05_e5',
        ku: 'Kîjan bikaranîn rast e?',
        tr: 'Doğru şart cümlesini seç',
        opts: [
          'Ger ez xurt bim, min ê bikira',
          'Ger ez xurt bûm, min ê bikira',
          'Ger ez xurt bûma, min ê bikira',
          'Ger ez xurt im, min ê bikira',
        ],
        ci: 2,
        note: 'Counterfactual\'da şart cümlesi "bûma/bûya", sonuç "ê bikira/bikirya". [BH] §191'),
      _speak(id: 'b2_l05_e6',
        ku: 'Ger ez li şûna te bûma, min ê cuda bikira. Eger pîrê hatibûya, em ê şa bibûyana.',
        tr: 'Ben senin yerinde olsaydım farklı yapardım. Büyükanne gelseydi mutlu olurduk.'),
    ],
  ),

  LessonModel(
    id: 'b2_l06',
    kurmanjTitle: 'Daçek û Hevokên Dirêj',
    turkishTitle: 'Edat ve Uzun Cümleler',
    unitNumber: 2, lessonNumber: 3, level: 4,
    path: LessonPath.general,
    targetCardIds: _b2Cards(['daçek', 'rêziman']).take(6).toList(),
    estimatedMinutes: 10, emoji: '🔗',
    exercises: [
      _mc(id: 'b2_l06_e1',
        ku: '"Ji bo ku" kîjan hevokê pêk tîne?',
        tr: 'Doğru kullanımı seç',
        opts: [
          'Hevoka armancê',
          'Hevoka nêrînê',
          'Hevoka sedemê',
          'Hevoka demê',
        ],
        ci: 0,
        note: '"Ji bo ku" = amaç, ki. Hedef cümlesi → sonrasında mebestî: "Ez çûm ji bo ku bibînim".'),
      _fill(id: 'b2_l06_e2', before: 'Ez dixwînim', after: ' zanibim.',
        tr: 'Bilmek için okuyorum.',
        opts: ['çimkî', 'heke', 'ji bo ku', 'lewra'],
        ci: 2,
        note: '"Ji bo ku" + mebestî = -mek için. Armanc kalıbı.'),
      _mc(id: 'b2_l06_e3',
        ku: '"Lewra" û "çimkî" tê çi wateyê?',
        tr: 'Doğru anlamı seç',
        opts: [
          'Her çend ku',
          'Çunkü, zîra',
          'Ger',
          'Ji ber vê yekê',
        ],
        ci: 1,
        note: '"Lewra / çimkî" = çünkü. Sedemê diyar dikin. [AZ] Ders 16'),
      _fill(id: 'b2_l06_e4', before: 'Em naçin,', after: ' baran dibare.',
        tr: 'Gitmiyoruz çünkü yağmur yağıyor.',
        opts: ['ji bo ku', 'piştî ku', 'heke', 'ji ber ku'],
        ci: 3,
        note: '"Ji ber ku" = çünkü. Sedem bağlacı + dema niha.'),
      _mc(id: 'b2_l06_e5',
        ku: '"Her çend ku ... lê" kîjan têkiliyê nîşan dide?',
        tr: 'Doğru ilişkiyi seç',
        opts: ['Sedem', 'Dem', 'Armanc', 'Cudahî-dijberî'],
        ci: 3,
        note: '"Her çend ku ... lê" = her ne kadar ... ama. Zıtlık kalıbı.'),
      _speak(id: 'b2_l06_e6',
        ku: 'Ez dixwînim ji bo ku zanibim. Em naçin ji ber ku baran heye. Her çend ku dereng e, lê ez ê bêm.',
        tr: 'Bilmek için okuyorum. Yağmur olduğundan gitmiyoruz. Geç olsa da geleceğim.'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // BİRİM 3 — Civak û Medya (2 ders)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'b2_l07',
    kurmanjTitle: 'Civak, Medya û Rojname',
    turkishTitle: 'Toplum, Medya ve Gazete',
    unitNumber: 3, lessonNumber: 1, level: 4,
    path: LessonPath.general,
    targetCardIds: _b2Cards(['civakî', 'medya', 'civaknas']).take(8).toList(),
    estimatedMinutes: 11, emoji: '📰',
    exercises: [
      _ls(id: 'b2_l07_e1',
        ku: 'Rojname',
        tr: 'Ne anlama geliyor?',
        opts: [
          'Televîzyona dîjîtal bi weşana zindî',
          'Pirtûk rojane, kaxiza nûçeyan',
          'Radyoya bê wêne ku nûçe û muzîkê pêşkêş dike',
          'Kovara mehane ya bi bend û şîroveyan',
        ],
        ci: 1,
        note: '"Rojname" = gazete. Roj (gün) + name (yazı).'),
      _mc(id: 'b2_l07_e2',
        ku: '"Ragihandin" tê çi wateyê?',
        tr: 'Doğru anlamı bul',
        opts: [
          'Pirsîna agahî ji kesekî bi awayekî rasterast',
          'Şandina agahî û nûçeyan, weşandin',
          'Axaftina rojane ya di navbera du kesan de',
          'Xwendina nivîsên kevneşopî yên dîrokî',
        ],
        ci: 1,
        note: '"Ragihandin" = iletişim, medya yayını. "Ragihîn" = ulaşmak\'tan türemiş.'),
      _fill(id: 'b2_l07_e3', before: 'Nûçe di medyaya', after: ' de belav bûn.',
        tr: 'Haberler dijital medyada yayıldı.',
        opts: ['dîjîtal', 'civakî', 'kevn', 'zuha'],
        ci: 0,
        note: '"Medyaya dîjîtal" = dijital medya. Ezafe + sıfat.'),
      _mc(id: 'b2_l07_e4',
        ku: '"Raya giştî" tê çi wateyê?',
        tr: 'Doğru anlamı bul',
        opts: ['Partiya giştî', 'Kara giştî', 'Dema giştî', 'Fikra gel, nêrîna civatê'],
        ci: 3,
        note: '"Raya giştî" = kamuoyu. Ra (düşünce, fikir) + giştî (genel).'),
      _fill(id: 'b2_l07_e5', before: '', after: 'medyayê di civakê de girîng e.',
        tr: 'Medyanın toplumdaki rolü önemlidir.',
        opts: ['Rol', 'Role', 'Rola', 'Rolê'],
        ci: 2,
        note: '"Rola medyayê" = medyanın rolü. "Rol" mê → ezafa binavkirî "Rola" + "medyayê" (mê oblique). [BH] §160'),
      _speak(id: 'b2_l07_e6',
        ku: 'Rojname û medyaya civakî raya giştî çêdikin. Ragihandin di demeke kurt de belav dibe.',
        tr: 'Gazete ve sosyal medya kamuoyunu şekillendirir. İletişim kısa sürede yayılır.'),
    ],
  ),

  LessonModel(
    id: 'b2_l08',
    kurmanjTitle: 'Siyaset û Mafên Mirovan',
    turkishTitle: 'Siyaset ve İnsan Hakları',
    unitNumber: 3, lessonNumber: 2, level: 4,
    path: LessonPath.general,
    targetCardIds: _b2Cards(['siyaset', 'zagon']).take(8).toList(),
    culturalRewardId: 'cegerxwin_1',
    estimatedMinutes: 11, emoji: '⚖️',
    exercises: [
      _ls(id: 'b2_l08_e1',
        ku: 'Dadwerî',
        tr: 'Ne anlama geliyor?',
        opts: ['Xewle, bê deng', 'Bê maf, bê derfet', 'Tirs û dudilî', 'Adalet, mafê rast'],
        ci: 3,
        note: '"Dadwerî" = adalet. "Dad" + "-werî". Hukuk-siyaset kavramı.'),
      _mc(id: 'b2_l08_e2',
        ku: '"Partiya siyasî" çi ye?',
        tr: 'Doğru tanımı bul',
        opts: [
          'Rêxistineke siyasî ku digel armanca desthilatdariyê',
          'Şirketek',
          'Dibistanek',
          'Komeke weşanê',
        ],
        ci: 0,
        note: '"Partî" = siyasi örgüt. Desthilatdarî (iktidar) armancıyla.'),
      _fill(id: 'b2_l08_e3', before: 'Mafê', after: ' mafekî bingehîn ê demokrasiyê ye.',
        tr: 'İfade hakkı temel demokratik haktır. İPUCU: "ifade etmek/açıklamak" eylem ismi (konuşma değil).',
        opts: ['derbirînê', 'bîr û rayê', 'nivîsandinê', 'tevgerê'],
        ci: 0,
        note: '"Mafê derbirînê" = ifade hakkı. "Derbirîn" = ifade etmek (eylem ismi). Axaftin (konuşma) yakın anlamlı ama "ifade" karşılığı derbirîndir.'),
      _mc(id: 'b2_l08_e4',
        ku: '"Wekhevî" tê çi wateyê?',
        tr: 'Doğru anlamı bul',
        opts: ['Cudabûn', 'Cudahî', 'Bilindî', 'Hevtayî, heman maf'],
        ci: 3,
        note: '"Wekhevî" = eşitlik. Temel insan hakları kavramı.'),
      _fill(id: 'b2_l08_e5', before: 'Azadiya', after: ' ji bo demokrasiyê pêwîst e.',
        tr: 'Basın özgürlüğü demokrasi için gereklidir. İPUCU: "matbaa/baskı eylemi" (genel medya/yayın değil).',
        opts: ['axaftinê', 'civînê', 'çapê', 'ragihandinê'],
        ci: 2,
        note: '"Azadiya çapê" = basın özgürlüğü. "Çap" = matbaa/basın.'),
      _speak(id: 'b2_l08_e6',
        ku: 'Dadwerî, wekhevî û azadî pêwîstên demokrasiyê ne. Mafê derbirînê divê bête parastin.',
        tr: 'Adalet, eşitlik ve özgürlük demokrasinin gereklilikleridir. İfade özgürlüğü korunmalıdır.'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // BİRİM 4 — Akademik Ziman (2 ders)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'b2_l09',
    kurmanjTitle: 'Kêlma Akademîk',
    turkishTitle: 'Akademik Dil',
    unitNumber: 4, lessonNumber: 1, level: 4,
    path: LessonPath.general,
    targetCardIds: _b2Cards(['akademik', 'zanist']).take(8).toList(),
    estimatedMinutes: 11, emoji: '🎓',
    exercises: [
      _mc(id: 'b2_l09_e1',
        ku: '"Ji aliyê ... ve" kîjan avaniyê dide?',
        tr: 'Doğru yapıyı seç',
        opts: [
          'Fail (kar kî kir, di pasîfê de)',
          'Dem (dema rûdana karî, gelo niha an berê bû)',
          'Sedem (çima karek pêk hat, sedema rûdanê)',
          'Armanc (mebesta karî, ji bo çi tê kirin)',
        ],
        ci: 0,
        note: '"Ji aliyê ... ve" = ... tarafından. Pasiften failî gösterir. Akademik kalıp.'),
      _fill(id: 'b2_l09_e2', before: 'Ev lêkolîn', after: ' Prof. Bedirxan ve hate çêkirin.',
        tr: 'Bu araştırma Prof. Bedirxan tarafından yapıldı.',
        opts: ['li ser', 'bi rêya', 'li aliyê', 'ji aliyê'],
        ci: 3,
        note: '"Ji aliyê X ve" = X tarafından (paşdaçekî "ve" pêwîst e). Akademik pasif fail kalıbı.'),
      _mc(id: 'b2_l09_e3',
        ku: '"Bi awayekî zanistî" tê çi wateyê?',
        tr: 'Doğru çeviriyi seç',
        opts: [
          'Bi lezê',
          'Bi dengekî bilind',
          'Bi dilê xwe',
          'Bi rêbazên zanistî, bi zanyarî',
        ],
        ci: 3,
        note: '"Bi awayekî zanistî" = bilimsel bir şekilde. Akademik üslup.'),
      _fill(id: 'b2_l09_e4', before: 'Em statîstîkê ji bo analîzkirinê', after: '.',
        tr: 'Analiz için istatistik kullanıyoruz.',
        opts: ['dinivîsin', 'dibihîzin', 'bikar tînin', 'dijmêrin'],
        ci: 2,
        note: '"Bikar anîn" = kullanmak (bileşik fiil). "Em statîstîkê bikar tînin" = istatistik kullanıyoruz. Akademik kalıp.'),
      _mc(id: 'b2_l09_e5',
        ku: '"Ji bilî vê" tê çi wateyê?',
        tr: 'Doğru anlamı bul',
        opts: ['Zêdeyî vê yekê, her wiha', 'Lê belê', 'Beriya vê', 'Ji ber vê'],
        ci: 0,
        note: '"Ji bilî vê" = bunun dışında / ayrıca. Akademik bağlaç.'),
      _speak(id: 'b2_l09_e6',
        ku: 'Ev lêkolîn ji aliyê zanyar ve bi awayekî zanistî hate çêkirin. Em encamên wê dinirxînin.',
        tr: 'Bu araştırma bilim insanı tarafından bilimsel bir şekilde yapıldı. Sonuçlarını değerlendiriyoruz.'),
    ],
  ),

  LessonModel(
    id: 'b2_l10',
    kurmanjTitle: 'Felsefe û Ramîn',
    turkishTitle: 'Felsefe ve Düşünce',
    unitNumber: 4, lessonNumber: 2, level: 4,
    path: LessonPath.general,
    targetCardIds: _b2Cards(['felsefe', 'soyut', 'civaknas']).take(8).toList(),
    estimatedMinutes: 11, emoji: '🧠',
    exercises: [
      _ls(id: 'b2_l10_e1',
        ku: 'Ramîn',
        tr: 'Ne anlama geliyor?',
        opts: ['Xew û aramî', 'Xeyala bê esas', 'Stran û muzîk', 'Bîra kûr, fikr'],
        ci: 3,
        note: '"Ramîn" = derin düşünce. Felsefi terim. [FB]'),
      _mc(id: 'b2_l10_e2',
        ku: '"Nasname" çi ye?',
        tr: 'Doğru tanımı bul',
        opts: [
          'Pirtûkek',
          'Ew tişt ku nîşan dide kesek kî ye, girêdana wî bi kom û çandê',
          'Navek tenê',
          'Dibistan',
        ],
        ci: 1,
        note: '"Nasname" = kimlik. Bireyin kültürel-toplumsal bağlamı.'),
      _fill(id: 'b2_l10_e3', before: 'Felsefe li ser', after: ' dipeyive.',
        tr: 'Felsefe varlık ve yokluk üzerine konuşur.',
        opts: ['hebûn û nebûnê', 'jiyana rojane', 'civatê', 'dîrokê'],
        ci: 0,
        note: '"Hebûn û nebûn" = varlık ve yokluk. Felsefenin iki temel sorusu (ontoloji).'),
      _mc(id: 'b2_l10_e4',
        ku: '"Rexne" tê çi wateyê?',
        tr: 'Doğru anlamı bul',
        opts: ['Nirxandin û şirovekirin, ceribandina fikrî', 'Stranek', 'Tirsek', 'Şoreş'],
        ci: 0,
        note: '"Rexne" = eleştiri. Akademik-felsefi düşünce aracı.'),
      _fill(id: 'b2_l10_e5', before: 'Zana bi', after: ' li ser pirsgirêkê difikirin.',
        tr: 'Bilginler sorun üzerine eleştirel bir şekilde düşünüyorlar.',
        opts: ['awayekî rexnegir', 'bi kêfê', 'rehetî', 'bê armanc'],
        ci: 0,
        note: '"Bi awayekî rexnegir" = eleştirel bir şekilde. Akademik üslup.'),
      _speak(id: 'b2_l10_e6',
        ku: 'Ramîn û rexne di felsefeyê de girîng in. Nasnameya mirov li ser bingeha çand û dîrokê ava dibe.',
        tr: 'Düşünce ve eleştiri felsefede önemlidir. İnsan kimliği kültür ve tarih üzerine kurulur.'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // BİRİM 5 — Edebiyata Klasîk (3 ders — Rêya Çandê)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'b2_l11',
    kurmanjTitle: 'Mem û Zîn: Parçeya Dirêj',
    turkishTitle: 'Mem û Zîn: Uzun Parça',
    unitNumber: 5, lessonNumber: 1, level: 4,
    path: LessonPath.cultural,
    targetCardIds: _b2Cards(['edebiyat', 'çand', 'kimlik']).take(8).toList(),
    culturalRewardId: 'xani_1',
    estimatedMinutes: 12, emoji: '📜',
    exercises: [
      _mc(id: 'b2_l11_e1',
        ku: 'Di "Mem û Zîn" de Xanî ji bo çi gazin dike?',
        tr: 'Ana gazini bul',
        opts: [
          'Ji bo ku zimanê wan tune ye',
          'Ji bo bêyekîtiya Kurdan û tunebûna dewletê',
          'Ji bo hewa sar',
          'Ji bo axa kêm',
        ],
        ci: 1,
        note: 'Xanî\'nin ana gazini: Kürtlerin birlik yokluğu ve devletsizlik. 17. yy teşhisi.'),
      _fill(id: 'b2_l11_e2', before: '"Kurd in û Kurdistan', after: '" Xanî di "Mem û Zîn"ê de gotiye.',
        tr: '"Kürtler var ve Kürdistan ..." mısrasını tamamla',
        opts: ['heye', 'nîne', 'kêm e', 'dûr e'],
        ci: 0,
        note: 'Xanî\'nin meşhur dizesi: "Kurd in û Kurdistan heye".'),
      _mc(id: 'b2_l11_e3',
        ku: 'Karekterên bingehîn ên "Mem û Zîn" kî ne?',
        tr: 'Ana karakterleri bul',
        opts: [
          'Leyla, Mecnun',
          'Mem, Zîn, Bekir, Tacdîn',
          'Ferhad, Şîrîn',
          'Rustem, Suhrab',
        ],
        ci: 1,
        note: 'Mem (âşık), Zîn (sevgili), Tacdîn (dost), Bekirê Mergaver (fitnecî). Botan\'da geçer.'),
      _fill(id: 'b2_l11_e4', before: 'Bekirê Mergaver', after: ' di navbera Mem û Zîn de çêkir.',
        tr: 'Bekir, Mem ile Zîn arasında ayrılık yarattı.',
        opts: ['bextiyarî', 'evîn', 'şadî', 'dubendî'],
        ci: 3,
        note: 'Ergatifte berbijêr halê xwerû de ye: "dubendî" (ne "dubendiyê"). Bekirê Mergaver ergatif kirde → dubendî halê xwerû berbijêr. [BH] §172'),
      _mc(id: 'b2_l11_e5',
        ku: 'Dawiya çîroka "Mem û Zîn" çawa ye?',
        tr: 'Doğru sonu seç',
        opts: [
          'Ew ji welat revin',
          'Mem û Zîn dizewicin',
          'Mîr wan efû dike',
          'Mem dimire, Zîn jî li ser gorê dimire',
        ],
        ci: 3,
        note: 'Trajik son: Mem zindanda ölür, Zîn mezarı başında ölür. Birliksizlik alegori.'),
      _speak(id: 'b2_l11_e6',
        ku: 'Di "Mem û Zîn" de Xanî behsa evîn, dubendî û bêdewletiya Kurdan dike. Kurd in û Kurdistan heye.',
        tr: '"Mem û Zîn"de Xanî aşk, ayrılık ve Kürt devletsizliğinden bahseder. Kürtler var ve Kürdistan var.'),
    ],
  ),

  LessonModel(
    id: 'b2_l12',
    kurmanjTitle: 'Mela Cizîrî: Dîwan',
    turkishTitle: 'Mela Cizîrî: Klasik Divan',
    unitNumber: 5, lessonNumber: 2, level: 4,
    path: LessonPath.cultural,
    targetCardIds: _b2Cards(['edebiyat', 'huner']).skip(4).take(6).toList(),
    estimatedMinutes: 11, emoji: '🕌',
    exercises: [
      _mc(id: 'b2_l12_e1',
        ku: 'Melayê Cizîrî (1570–1640) kî bû?',
        tr: 'Doğru tanımı bul',
        opts: [
          'Padîşahekî herêmî yê serdema Osmanî',
          'Stranbêjekî gelêrî yê dengbêjiya kevneşopî',
          'Karmendekî bilind ê dîwana padîşahên Erebî',
          'Helbestvanê sofî yê klasîk ê kurd',
        ],
        ci: 3,
        note: 'Mela Cizîrî — Kurt klasik dîwan şiirinin ilk büyük mistik şairi. Cizîr (Cizre) doğumlu.'),
      _mc(id: 'b2_l12_e2',
        ku: 'Dîwana Cizîrî li ser kîjan mijaran e?',
        tr: 'Doğru temayı bul',
        opts: [
          'Dîroka Kurdistan',
          'Aborî',
          'Şer û aştî',
          'Evîn, mizgîn û tesewuf',
        ],
        ci: 3,
        note: 'Cizîrî şiirleri: ilahi aşk, tasavvuf, mistik güzellik temaları.'),
      _fill(id: 'b2_l12_e3', before: 'Mela Cizîrî li', after: ' hat dinê.',
        tr: 'Mela Cizîrî Cizre\'de dünyaya geldi.',
        opts: ['Stembolê', 'Hewlêrê', 'Cizîrê', 'Diyarbekirê'],
        ci: 2,
        note: '"Cizîr" (Cizre) — Cizîrî\'nin doğum yeri, mahlas kaynağı.'),
      _mc(id: 'b2_l12_e4',
        ku: 'Zimanê Dîwana Cizîrî çi ye?',
        tr: 'Doğru dili bul',
        opts: ['Kurmancî (bi hinek têgehên erebî-farisî)', 'Erebî', 'Tirkî', 'Farisî tenê'],
        ci: 0,
        note: 'Cizîrî Kurmancî\'de yazdı, klasik gelenek nedeniyle Arap-Fars izafetleri kullandı.'),
      _fill(id: 'b2_l12_e5', before: 'Helbestên wî bi', after: ' ne.',
        tr: 'Şiirleri ritmik ölçüyle yazılmıştır.',
        opts: ['axaftinê', 'kêşa erûz', 'pêxwas', 'bê pîvan'],
        ci: 1,
        note: '"Kêşa erûz" = aruz vezni. Klasik dîwan şiirinin nazım birimi.'),
      _speak(id: 'b2_l12_e6',
        ku: 'Mela Cizîrî helbestvanê sofî yê mezin bû. Dîwana wî bi Kurmancî hatiye nivîsîn.',
        tr: 'Mela Cizîrî büyük sûfî şairdi. Divanı Kurmancî olarak yazılmıştır.'),
    ],
  ),

  LessonModel(
    id: 'b2_l13',
    kurmanjTitle: 'Cegerxwîn: Deng û Welat',
    turkishTitle: 'Cegerxwîn: Ses ve Vatan',
    unitNumber: 5, lessonNumber: 3, level: 4,
    path: LessonPath.cultural,
    targetCardIds: _b2Cards(['edebiyat', 'kimlik', 'çand']).skip(3).take(6).toList(),
    culturalRewardId: 'cegerxwin_1',
    estimatedMinutes: 11, emoji: '🗽',
    exercises: [
      _mc(id: 'b2_l13_e1',
        ku: 'Cegerxwîn (1903–1984) kî bû?',
        tr: 'Doğru tanımı bul',
        opts: [
          'Stranbêjekî gelêrî yê dengbêjiya kevneşopî',
          'Padîşahekî herêmî yê serdema Osmanî',
          'Alimekî dînî yê navdar ê fiqha îslamî',
          'Helbestvanê neteweyî yê nûjen ê Kurd',
        ],
        ci: 3,
        note: 'Cegerxwîn (Şêxmûs Hesen) — modern Kürt ulusal şiirinin baş figürü. 1903\'te Hesar köyünde (Gercüş ilçesi, eskiden Mardin/şimdi Batman) doğdu.'),
      _mc(id: 'b2_l13_e2',
        ku: 'Navê bingehîn ê Cegerxwîn çi bû?',
        tr: 'Asıl adını bul',
        opts: ['Şêxmûs Hesen', 'Ehmed', 'Bedirxan', 'Seîd'],
        ci: 0,
        note: '"Cegerxwîn" mahlas; gerçek adı Şêxmûs Hesen. "Cegerxwîn" = ciğeri yanan.'),
      _fill(id: 'b2_l13_e3', before: 'Cegerxwîn bi helbestên xwe yên neteweyî', after: ' bûye.',
        tr: 'Cegerxwîn ulusal şiirleriyle tanınmıştır.',
        opts: ['naskirî', 'winda', 'bêdeng', 'kêm'],
        ci: 0,
        note: '"Naskirî" = tanınmış. Ergatif değil, geçişsiz "bûye".'),
      _mc(id: 'b2_l13_e4',
        ku: 'Dîwana wî çend cilt e?',
        tr: 'Doğru sayıyı bul',
        opts: ['2', '4', '8', '10'],
        ci: 2,
        note: 'Cegerxwîn Dîwan I-VIII (1945-1985). 8 cilt şiir.'),
      _fill(id: 'b2_l13_e5', before: 'Cegerxwîn di 1984 de li', after: ' çû rehmetê.',
        tr: 'Cegerxwîn 1984\'te İsveç\'te vefat etti.',
        opts: ['Amedê', 'Hewlêrê', 'Cizîrê', 'Swêdê'],
        ci: 3,
        note: 'Cegerxwîn sürgün yıllarını İsveç\'te geçirdi ve orada öldü.'),
      _speak(id: 'b2_l13_e6',
        ku: 'Cegerxwîn dengê helbestî yê welatê Kurd bû. Dîwana wî hîn jî hêza xwe diparêze.',
        tr: 'Cegerxwîn Kürt ülkesinin şiirsel sesiydi. Divanı hâlâ gücünü koruyor.'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // BİRİM 6 — Serbest Xwendin (2 ders — Rêya Malê)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'b2_l14',
    kurmanjTitle: 'Nûçeyeke Rojane',
    turkishTitle: 'Gündelik Haber Okuma',
    unitNumber: 6, lessonNumber: 1, level: 4,
    path: LessonPath.heritage,
    targetCardIds: _b2Cards(['medya', 'civakî']).skip(4).take(6).toList(),
    estimatedMinutes: 11, emoji: '📑',
    exercises: [
      _mc(id: 'b2_l14_e1',
        ku: 'Di nûçeyekê de pêşî çi tê dayîn?',
        tr: 'Haber yapısı: ilk bölüm',
        opts: [
          'Şîroveya kesane ya nivîskar li ser bûyerê',
          'Sernivîs û paragrafa pêşî (lead)',
          'Wêneyek mezin a bûyerê di rûpela pêşî de',
          'Îmza û navê nivîskar di binê nivîsê de',
        ],
        ci: 1,
        note: 'Haber yapısı: sernivîs (başlık) → lead (açılış) → gövde. Gazetecilik kalıbı.'),
      _fill(id: 'b2_l14_e2', before: 'Dema em nûçeyê', after: ', em agahiyên bingehîn digirin.',
        tr: 'Haberi okuduğumuzda temel bilgileri alıyoruz.',
        opts: ['derbaz dibin', 'difroşin', 'dinivîsin', 'dixwînin'],
        ci: 3,
        note: '"Dixwînin" = okuyoruz (3.kes pirjimar). Nûçeya çapkirî an dîjîtal → dixwînin.'),
      _mc(id: 'b2_l14_e3',
        ku: '"Li gor çavkaniya fermî" tê çi wateyê?',
        tr: 'Doğru çeviriyi bul',
        opts: [
          'Bi saya xewnê',
          'Bi rêya hevalekî',
          'Li gor hestê xwe',
          'Li gor çavkaniya resmî, desthilatdar',
        ],
        ci: 3,
        note: '"Çavkaniya fermî" = resmi kaynak. Haber üslûbunda güvenilirlik kalıbı.'),
      _fill(id: 'b2_l14_e4', before: 'Nûçe di rojnameya', after: ' de hate weşandin.',
        tr: 'Haber dijital gazetede yayımlandı.',
        opts: ['kevn', 'dîjîtal', 'sar', 'xewle'],
        ci: 1,
        note: '"Rojnameya dîjîtal" = dijital gazete.'),
      _mc(id: 'b2_l14_e5',
        ku: '"Şîrove" çi ye?',
        tr: 'Doğru anlamı bul',
        opts: [
          'Nûçe',
          'Ravekirin û nêrîna kesane li ser bûyerê',
          'Sernivîs',
          'Wêne',
        ],
        ci: 1,
        note: '"Şîrove" = yorum, editorial. Haber + yorum farkı.'),
      _speak(id: 'b2_l14_e6',
        ku: 'Em nûçeyê dixwînin, paşê şîroveyê ji çavkaniyên cihê dibînin. Rast-derewbûn girîng e.',
        tr: 'Haberi okuyoruz, sonra farklı kaynaklardan yorumları görüyoruz. Doğruluk önemli.'),
    ],
  ),

  LessonModel(
    id: 'b2_l15',
    kurmanjTitle: 'Tekstek Akademîk',
    turkishTitle: 'Kısa Akademik Metin',
    unitNumber: 6, lessonNumber: 2, level: 4,
    path: LessonPath.heritage,
    targetCardIds: _b2Cards(['akademik', 'felsefe']).skip(3).take(6).toList(),
    culturalRewardId: 'proverb_1',
    estimatedMinutes: 12, emoji: '📚',
    exercises: [
      _mc(id: 'b2_l15_e1',
        ku: 'Metnê akademîk bi piranî çi armancê dişopîne?',
        tr: 'Doğru amacı bul',
        opts: [
          'Ecêbî',
          'Rehetiya xwendevan',
          'Pêşkêşkirina zanînê bi rêbazên zanistî',
          'Bêhêziya xwendevan',
        ],
        ci: 2,
        note: 'Akademik metin: bilimsel yöntemle bilgi sunumu. Nesnellik + kanıt.'),
      _fill(id: 'b2_l15_e2', before: 'Di vê lêkolînê de em', after: ' diceribînin.',
        tr: 'Bu araştırmada hipotez test ediyoruz.',
        opts: ['stranê', 'xeyalan', 'tiştekî', 'hîpotezê'],
        ci: 3,
        note: '"Hîpotez" = hipotez. "Ceribandin" = test etmek. Akademik terim.'),
      _mc(id: 'b2_l15_e3',
        ku: '"Bi kurtî" çi wateyê dide?',
        tr: 'Doğru anlamı bul',
        opts: [
          'Bi lezgînî',
          'Bi hûrgilî',
          'Bi dengekî bilind',
          'Bê dubare, bi rengekî kin',
        ],
        ci: 3,
        note: '"Bi kurtî" = özetle, kısaca. Akademik özet kalıbı.'),
      _fill(id: 'b2_l15_e4', before: 'Encam', after: ' ku hîpotez rast e.',
        tr: 'Sonuç hipotezin doğru olduğunu gösterdi.',
        opts: ['nîşan da', 'got', 'dipejirîne', 'bihîst'],
        ci: 0,
        note: '"Nîşan da" = gösterdi. Akademik sonuç kalıbı.'),
      _mc(id: 'b2_l15_e5',
        ku: 'Di metnekî akademîk de jêder (çavkanî) çima girîng in?',
        tr: 'Doğru sebebi bul',
        opts: [
          'Ji bo ku dirêj be',
          'Ji bo dikana bikirrin',
          'Bê sedem',
          'Ji bo pejirandina zanyarî û rûmetê',
        ],
        ci: 3,
        note: 'Jêder: bilimsel güvenilirlik, akademik etik. "Çavkanî" = kaynak.'),
      _speak(id: 'b2_l15_e6',
        ku: 'Me hîpotezek ceriband û encam nîşan da ku ew rast e. Em her argûmana xwe bi çavkaniyan piştrast dikin.',
        tr: 'Bir hipotez test ettik ve sonuç onun doğru olduğunu gösterdi. Her argümanımızı kaynaklarla doğruluyoruz.'),
    ],
  ),
];
