import 'lesson_entities.dart';
import 'c1_kelime_db.dart';

// ════════════════════════════════════════════════════════════════
// C1 — 15 DERS TANIMI (Jor / İleri)
//
// Pedagojik Odak (CEFR C1):
// - Sentaksa qedîm: uzun cümle, tabi yan cümle, relativ "ku/yê/ya"
// - Akademik Kurmancî terminoloji, nivîsîna zanistî
// - Felsefî ramîn: hebûn, nasname, azadî, rexne
// - Postkolonyalî, siyasiya nasnameyê
// - Edebiyata klasîk: Cizîrî dîvân parçe analîz, Feqiyê Teyran
// - Ergatif karmaşık istisnalar, aspekt nuance
// - Hiqûq û siyaset (uluslararası hukuk terminolojisi)
//
// Path dağılımı: 9 general · 2 heritage · 4 cultural
// ════════════════════════════════════════════════════════════════

List<String> _c1Cards(List<String> kats) => kC1All
    .where((k) => kats.contains(k.kat))
    .map((k) => k.id)
    .toList();

ExerciseModel _mc({
  required String id, required String ku, required String tr,
  required List<String> opts, required int ci,
  String? note, int xp = 14,
}) => ExerciseModel(
  id: id, type: ExerciseType.multipleChoice,
  kurmanjPrompt: ku, turkishPrompt: tr,
  options: opts, correctAnswer: opts[ci], correctIndex: ci,
  grammarNote: note, xpReward: xp,
);

ExerciseModel _ls({
  required String id, required String ku, required String tr,
  required List<String> opts, required int ci,
  String? audio, String? note, int xp = 16,
}) => ExerciseModel(
  id: id, type: ExerciseType.listenAndSelect,
  kurmanjPrompt: ku, turkishPrompt: tr,
  options: opts, correctAnswer: opts[ci], correctIndex: ci,
  audioAsset: audio, grammarNote: note, xpReward: xp,
);

ExerciseModel _fill({
  required String id, required String before, required String after,
  required String tr, required List<String> opts, required int ci,
  String? note, int xp = 16,
}) => ExerciseModel(
  id: id, type: ExerciseType.fillInBlank,
  kurmanjPrompt: '$before ___ $after', turkishPrompt: tr,
  options: opts, correctAnswer: opts[ci], correctIndex: ci,
  grammarNote: note, xpReward: xp,
  wordPieces: [before.trim(), after.trim()],
);

ExerciseModel _speak({
  required String id, required String ku, required String tr,
  String? audio, int xp = 20,
}) => ExerciseModel(
  id: id, type: ExerciseType.speakingPractice,
  kurmanjPrompt: ku, turkishPrompt: tr,
  audioAsset: audio, xpReward: xp,
  options: ['Gelek baş', 'Nêzîk', 'Carek din'],
  correctAnswer: ku,
);

ExerciseModel _order({
  required String id, required String tr, required List<String> pieces,
  required String target, String? note, int xp = 18,
}) => ExerciseModel(
  id: id, type: ExerciseType.dragAndDrop,
  kurmanjPrompt: 'Peyvan bi rêz bike:', turkishPrompt: tr,
  wordPieces: pieces, targetSentence: target,
  options: pieces, correctAnswer: target,
  grammarNote: note, xpReward: xp,
);

// ════════════════════════════════════════════════════════════════
// 15 DERS
// ════════════════════════════════════════════════════════════════

final kC1Lessons = <LessonModel>[

  // ─────────────────────────────────────────────────────────────
  // BİRİM 1 — Sentaksa Qedîm û Nûjen (3 ders)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'c1_l01',
    kurmanjTitle: 'Hevokên Tabî: "Ku" û "Yê/Ya"',
    turkishTitle: 'Yan Cümle ve Relatif',
    unitNumber: 1, lessonNumber: 1, level: 5,
    path: LessonPath.general,
    targetCardIds: _c1Cards(['rêziman', 'ziman']).take(8).toList(),
    estimatedMinutes: 12, emoji: '🧵',
    exercises: [
      _mc(id: 'c1_l01_e1',
        ku: '"Ku" di Kurmancî de çend karan dike?',
        tr: 'Doğru işlevi bul',
        opts: [
          'Tenê girêdana nav-hevokan',
          'Tenê nerênîtî',
          'Girêdana hevokên tabî, relatîf, û mebest',
          'Tenê pirskirin',
        ],
        ci: 2,
        note: '"Ku" multifonksiyonel: bağlaç (that), relativ (which), amaç (so that). [BH] §210'),
      _fill(id: 'c1_l01_e2', before: 'Ew mirovê', after: ' li kêleka min rûniştî ye, birayê min e.',
        tr: 'Yanımda oturan adam kardeşimdir.',
        opts: ['ku', 'çimkî', 'ya', 'kî'],
        ci: 0,
        note: '"Mirovê ku..." = relatif yapı. Ezafe-markerli isim (mirovê) + "ku" standart Kurmancî. [BH] §211'),
      _mc(id: 'c1_l01_e3',
        ku: 'Di hevoka "Pirtûka ku min xwend, xweş bû" de "ku" çi nîşan dide?',
        tr: 'Doğru işlevi seç',
        opts: ['Dem', 'Girêdana relatîf (which/that)', 'Sedem', 'Pirs'],
        ci: 1,
        note: 'Relatif bağlaç: "pirtûk ku min xwend" = okuduğum kitap. [TH] §95'),
      _fill(id: 'c1_l01_e4', before: 'Ez wan kesan nas dikim', after: ' ji dûr ve hatine.',
        tr: 'Uzaktan gelen o insanları tanıyorum.',
        opts: ['ku', 'çimkî', 'ji', 'bi'],
        ci: 0,
        note: '"Ku" relatif: gelen insanları. Pirjimar relatif.'),
      _mc(id: 'c1_l01_e5',
        ku: '"Yê/Ya" û "ku" cudahiya wan çi ye?',
        tr: 'Doğru farkı seç',
        opts: [
          '"Yê" borî, "ya" niha',
          '"Yê" pirs, "ku" nerênîtî',
          'Tu cudahî nîne',
          '"Yê/ya" qulabên relatîf ên cins-hejmar in, "ku" neguherbar e',
        ],
        ci: 3,
        note: '"Yê" (eril), "ya" (dişil), "yên" (çoğul) — cins-sayı uyumu. "Ku" değişmez. [BH] §211'),
      _speak(id: 'c1_l01_e6',
        ku: 'Pirtûka ku min xwend xweş bû. Mirovê ku hat birayê min e. Gundên ku em lê diçin dûr in.',
        tr: 'Okuduğum kitap güzeldi. Gelen adam kardeşimdir. Gittiğimiz köyler uzaktır.'),
    ],
  ),

  LessonModel(
    id: 'c1_l02',
    kurmanjTitle: 'Hevokên Dirêj û Tevlihev',
    turkishTitle: 'Uzun ve Karmaşık Cümle',
    unitNumber: 1, lessonNumber: 2, level: 5,
    path: LessonPath.general,
    targetCardIds: _c1Cards(['rêziman', 'akademik']).take(6).toList(),
    estimatedMinutes: 12, emoji: '🧶',
    exercises: [
      _mc(id: 'c1_l02_e1',
        ku: 'Di Kurmancî de hevokeke tevlihev (complex) çi heye?',
        tr: 'Doğru tanımı bul',
        opts: [
          'Tenê hevokên kurt',
          'Yekîneyek serbixwe + yek an çend hevokên tabî',
          'Tenê hevokek serbixwe',
          'Tenê pirsên yek peyve',
        ],
        ci: 1,
        note: 'Kompleks cümle: ana cümle + yan cümle(ler). Kurmancî uzun cümlelerin kuruluşu.'),
      _order(id: 'c1_l02_e2',
        tr: '"Eğer yarın gelirsen birlikte gideriz"i diz',
        pieces: ['Ger', 'tu', 'sibê', 'werî,', 'em', 'ê', 'bi hev re', 'biçin'],
        target: 'Ger tu sibê werî, em ê bi hev re biçin',
        note: 'Şart cümlesi: "ger" + mebestî (werî) / ana cümle: "em ê biçin".'),
      _mc(id: 'c1_l02_e3',
        ku: 'Kîjan hevok dirêj û rast e?',
        tr: 'Doğru kompleks cümleyi seç',
        opts: [
          'Dema gundê çû min.',
          'Min dît çû gund.',
          'Dema ku ez çûm gundê xwe, min dît ku pîrê li ser banî rûniştiye.',
          'Ez çûm. Min dît.',
        ],
        ci: 2,
        note: 'Kompleks cümle örneği: zaman bağlacı + relatif + karmaşık fiil yapısı. [AZ] Ders 18'),
      _fill(id: 'c1_l02_e4', before: 'Piştî', after: ' em vegeriyan malê, em hinek aram bûn.',
        tr: 'Eve döndükten sonra biraz rahatladık.',
        opts: ['ya', 'ku', 'ji', 'bi'],
        ci: 1,
        note: '"Piştî ku" = -dikten sonra. Zaman bağlacı.'),
      _mc(id: 'c1_l02_e5',
        ku: 'Di hevokê de kerîşandina rêzê (order) çawa dibe?',
        tr: 'Kurmancî standart cümle dizilişi',
        opts: [
          'Tu rêza xurt nîne',
          'Lêker - Kirde - Berbijêr',
          'Kirde - Berbijêr - Lêker (SOV)',
          'Kirde - Lêker - Berbijêr',
        ],
        ci: 2,
        note: 'Kurmancî SOV: Kirde-Berbijêr-Lêker. "Ez nan dixwim" (Ben ekmek yiyorum). [BH] §157'),
      _speak(id: 'c1_l02_e6',
        ku: 'Dema ku em vegeriyan gund, pîrê got ku ew ê sibê neçe bajêr çimkî hewa ne xweş e.',
        tr: 'Köye döndüğümüzde büyükanne yarın şehre gitmeyeceğini söyledi çünkü hava iyi değil.'),
    ],
  ),

  LessonModel(
    id: 'c1_l03',
    kurmanjTitle: 'Aspektê Nuans: Aksiyona Temamî û Domdar',
    turkishTitle: 'Aspekt Nüansı: Tamamlanmış ve Süreç',
    unitNumber: 1, lessonNumber: 3, level: 5,
    path: LessonPath.general,
    targetCardIds: _c1Cards(['rêziman', 'leker']).skip(2).take(6).toList(),
    estimatedMinutes: 11, emoji: '🔍',
    exercises: [
      _mc(id: 'c1_l03_e1',
        ku: 'Cudahiya aspektê: "Min xwend" û "Min dixwend" çi ye?',
        tr: 'Farkı doğru açıkla',
        opts: [
          '"Xwend" temam-aksiyon, "dixwend" aksiyona domdar/dubare di borî de',
          '"Xwend" niha, "dixwend" bê',
          '"Xwend" tekane, "dixwend" pirjimar (cûdahiya hejmarê)',
          '"Xwend" pasîf, "dixwend" aktîf',
        ],
        ci: 0,
        note: 'Aspekt farkı: perfective (xwend) vs imperfective (dixwend). [TH] §72'),
      _mc(id: 'c1_l03_e2',
        ku: 'Kîjan hevok "okumakta idim" wateyê dide?',
        tr: 'Doğru çeviriyi bul',
        opts: [
          'Min xwendibû',
          'Min xwend',
          'Min dixwend',
          'Min xwendiye',
        ],
        ci: 2,
        note: '"Dixwend" = okumakta/okuyordu. Sürekli geçmiş (imperfective past).'),
      _fill(id: 'c1_l03_e3', before: 'Her roj piştî îşê min', after: ' nameyek.',
        tr: 'Her gün işten sonra bir mektup yazıyordum.',
        opts: ['dê binivîsim', 'nivîsand', 'dinivîsand', 'nivîsandiye'],
        ci: 2,
        note: '"Dinivîsand" = yazıyordum. Alışkanlık → imperfective.'),
      _mc(id: 'c1_l03_e4',
        ku: 'Perfect aspekt (hatiye, xwendiye) çi watê dide?',
        tr: 'Doğru tanımı bul',
        opts: [
          'Aksiyon di borî de temam bû lê encam niha heye',
          'Aksiyon tam temam',
          'Aksiyon dê çêbe',
          'Aksiyon berdewam e',
        ],
        ci: 0,
        note: 'Perfect: geçmişte tamamlanmış ama şimdi etkisi olan. "Hatiye" = gelmiş (hâlâ burada).'),
      _fill(id: 'c1_l03_e5', before: 'Min ev pirtûk', after: ', lê hîn jî nêzî min e.',
        tr: 'Bu kitabı okudum, ama hâlâ yanımda.',
        opts: ['xwend', 'xwendibû', 'dixwînim', 'xwendiye'],
        ci: 3,
        note: '"Xwendiye" = okumuşum (perfect, hâlâ relevansı var).'),
      _speak(id: 'c1_l03_e6',
        ku: 'Her sibê min kahwe vedixwar. Îro min kahweya xwe vexwariye. Berî te min kahwe vexwaribû.',
        tr: 'Her sabah kahve içerdim. Bugün kahvemi içtim. Sen gelmeden önce ben kahve içmiştim.'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // BİRİM 2 — Felsefe û Ramîn (3 ders)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'c1_l04',
    kurmanjTitle: 'Hebûn û Nasname',
    turkishTitle: 'Varlık ve Kimlik',
    unitNumber: 2, lessonNumber: 1, level: 5,
    path: LessonPath.general,
    targetCardIds: _c1Cards(['felsefe', 'kimlik']).take(8).toList(),
    estimatedMinutes: 12, emoji: '🧘',
    exercises: [
      _ls(id: 'c1_l04_e1',
        ku: 'Hebûn',
        tr: 'Ne anlama geliyor?',
        opts: ['Rêya dirêj', 'Tunebûn', 'Xwarina xweş', 'Varoluş, jiyan'],
        ci: 3,
        note: '"Hebûn" = varoluş, existence. Felsefenin temel kavramı.'),
      _mc(id: 'c1_l04_e2',
        ku: '"Xwebûn" çi ye?',
        tr: 'Doğru tanımı bul',
        opts: [
          'Tunebûna xwe',
          'Reftara bêhurmet',
          'Rewşa bûna "ez" bi xwe — xwenasîn, otantîk bûn',
          'Xewê',
        ],
        ci: 2,
        note: '"Xwebûn" = authentic self, selfhood. Varoluşsal felsefede anahtar.'),
      _fill(id: 'c1_l04_e3', before: 'Nasname tenê ya ferdî', after: ', ew civakî jî ye.',
        tr: 'Kimlik sadece bireysel değildir, aynı zamanda toplumsaldır.',
        opts: ['giştî ye', 'kêm e', 'heye', 'nîne'],
        ci: 3,
        note: '"Tenê ... nîne, ... jî ye" kalıbı: sadece değil, aynı zamanda. Nasname bireysel + toplumsal boyut.'),
      _mc(id: 'c1_l04_e4',
        ku: '"Ontolojî" di felsefeyê de çi ye?',
        tr: 'Doğru tanımı bul',
        opts: [
          'Huner',
          'Zanîna dîrokî',
          'Lêkolîna li ser xwezaya hebûnê, pirsa "hebûn çi ye"',
          'Zanîna zimanê',
        ],
        ci: 2,
        note: 'Ontoloji: varlık felsefesi. "Hebûn çi ye?" temel sorusu.'),
      _fill(id: 'c1_l04_e5', before: 'Mirov bi', after: ' xwe têdigihe.',
        tr: 'İnsan düşünceleri aracılığıyla kendini anlar.',
        opts: ['ramînên', 'hiş', 'jiyana dinyayî', 'pere'],
        ci: 0,
        note: '"Ramîn" = derin düşünce. Pirjimar ezafe: "ramînên xwe".'),
      _speak(id: 'c1_l04_e6',
        ku: 'Hebûn û nasname du têgehên bingehîn ên felsefeyê ne. Mirov bi ramîn û bîr xwe dinase.',
        tr: 'Varlık ve kimlik felsefenin iki temel kavramıdır. İnsan düşünce ve hafıza ile kendini tanır.'),
    ],
  ),

  LessonModel(
    id: 'c1_l05',
    kurmanjTitle: 'Azadî û Xweserîya Exlaqî',
    turkishTitle: 'Özgürlük ve Ahlaki Özerklik',
    unitNumber: 2, lessonNumber: 2, level: 5,
    path: LessonPath.general,
    targetCardIds: _c1Cards(['felsefe', 'siyaset', 'nirx']).take(8).toList(),
    estimatedMinutes: 12, emoji: '🕊️',
    exercises: [
      _mc(id: 'c1_l05_e1',
        ku: '"Azadiya pozîtîf" û "azadiya negatîf" — kî diyar kiriye?',
        tr: 'Doğru filozofu bul',
        opts: ['Isaiah Berlin', 'Nietzsche', 'Kant', 'Hegel'],
        ci: 0,
        note: 'Isaiah Berlin (1958): iki özgürlük kavramı. Akademik felsefe kanonu.'),
      _fill(id: 'c1_l05_e2', before: 'Azadiya negatîf tê wateya "azadî', after: ' tiştekî".',
        tr: 'Negatif özgürlük "-den özgür olmak" anlamındadır.',
        opts: ['ji', 'li', 'bo', 'bi'],
        ci: 0,
        note: '"Azadî ji" = -den özgürlük. Negatif, engellerden kurtuluş.'),
      _mc(id: 'c1_l05_e3',
        ku: '"Exlaq" çi ye?',
        tr: 'Doğru anlamı bul',
        opts: [
          'Pere',
          'Şêwaz',
          'Sîstema nirxan, qaîdeyên rast û şaş',
          'Dirêjahiya salê',
        ],
        ci: 2,
        note: '"Exlaq" = ahlak. Değerler sistemi, doğru-yanlış kurallar.'),
      _fill(id: 'c1_l05_e4', before: 'Li gor Kant, mirov', after: ' ye, ne tenê navgîn.',
        tr: 'Kant\'a göre insan kendi başına bir amaçtır, sadece araç değil.',
        opts: ['tişt', 'navgîn', 'bê nirx', 'armanc bi serê xwe'],
        ci: 3,
        note: 'Kant\'ın kategorik imperatifi: "İnsan amaçtır, araç değil."'),
      _mc(id: 'c1_l05_e5',
        ku: '"Vîndarî" tê çi wateyê?',
        tr: 'Doğru anlamı bul',
        opts: [
          'Tirsa mirinê',
          'Şiyana biryardayînê bi serbestî — iradi bûn',
          'Bêxwedî',
          'Xewa giran',
        ],
        ci: 1,
        note: '"Vîndarî" = iradilik, özerk karar verme kabiliyeti. Moral felsefede merkezi.'),
      _speak(id: 'c1_l05_e6',
        ku: 'Azadiya pozîtîf û negatîf du ramînên cuda ne. Exlaqa Kantî li ser vîndariya mirov disekine.',
        tr: 'Pozitif ve negatif özgürlük iki farklı düşüncedir. Kantçı ahlak insan iradesine dayanır.'),
    ],
  ),

  LessonModel(
    id: 'c1_l06',
    kurmanjTitle: 'Rexne û Zanîna Rexnegir',
    turkishTitle: 'Eleştiri ve Eleştirel Düşünce',
    unitNumber: 2, lessonNumber: 3, level: 5,
    path: LessonPath.general,
    targetCardIds: _c1Cards(['felsefe', 'akademik']).skip(4).take(6).toList(),
    estimatedMinutes: 11, emoji: '🧠',
    exercises: [
      _ls(id: 'c1_l06_e1',
        ku: 'Rexnegir',
        tr: 'Ne anlama geliyor?',
        opts: [
          'Pejirandina bê pirs a fikrên dîtî',
          'Nirxandin bi awayekî analîtîk',
          'Pejirandina hemû agahiyan bê lêpirsîn',
          'Dijminayî bê analîz û bê delîl',
        ],
        ci: 1,
        note: '"Rexnegir" = eleştirel (analitik değerlendiren).'),
      _mc(id: 'c1_l06_e2',
        ku: 'Dibistana rexneyê (Frankfurt School) ji bo çi naskirî ye?',
        tr: 'Frankfurt Okulu temel katkı',
        opts: [
          'Lêkolînên bîyolojîk ên li ser geşedana mirovan',
          'Teoriya rexneyî ya civakê (Horkheimer, Adorno)',
          'Hunera nûjen a sedsala 20 û rexneya estetîk',
          'Matematîka pêşkeftî û algorîtmayên hesabkirinê',
        ],
        ci: 1,
        note: 'Frankfurt Okulu: Kritik teori — Horkheimer, Adorno, Marcuse, Habermas.'),
      _fill(id: 'c1_l06_e3', before: 'Ramîna', after: ' ji bo pêşketina zanistê pêwîst e.',
        tr: 'Bilim için zorunlu düşünce türü (analiz + sorgulama temelli). İPUCU: kelimenin kökünde "rexne" (eleştiri) var.',
        opts: ['mistîk', 'zêhnî', 'serbihûrî', 'rexnegir'],
        ci: 3,
        note: '"Rexnegir" = eleştirel ("rexne" eleştiri + "-gir" sahip). "Mistîk" mistik (ters), "serbihûrî" deneyimsel, "zêhnî" zihinsel — bilim için merkezde değil.'),
      _mc(id: 'c1_l06_e4',
        ku: '"Dogmatîzm" tê çi wateyê?',
        tr: 'Doğru anlamı bul',
        opts: [
          'Bawerî bi xwe',
          'Pejirandina ramînan bê nirxandin û rexne',
          'Nirxandina kûr',
          'Şikirî',
        ],
        ci: 1,
        note: 'Dogmatizm: eleştirisiz kabul. Eleştirel düşüncenin karşıtı.'),
      _fill(id: 'c1_l06_e5', before: 'Rexne divê bi', after: ' û bi hişmendî be.',
        tr: 'Eleştiri akademik açıdan neye dayanmalı? "bi ___" yapısı + bilinçle birlikte. İPUCU: bilim metodolojisinin temeli; "hêrs" (öfke) ve "hest" (duygu) reddedilir.',
        opts: ['delîlan', 'dem', 'hest', 'hêrs'],
        ci: 0,
        note: '"Bi delîlan" = kanıtlarla. "Delîl" oblique çoğul → "delîlan". Eleştiri öfke/duygu (hêrs/hest) ile değil, bilimsel kanıtla yapılır.'),
      _speak(id: 'c1_l06_e6',
        ku: 'Ramîna rexnegir bi analîz, pirskirin û nirxandina delîlan ava dibe. Dogmatîzm bi vê ramîn nayê.',
        tr: 'Eleştirel düşünce analiz, sorgulama ve kanıt değerlendirmesiyle oluşur. Dogmatizm bu düşünceyle bağdaşmaz.'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // BİRİM 3 — Edebiyata Klasîk (3 ders)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'c1_l07',
    kurmanjTitle: 'Mela Cizîrî: Dîwan — Parçe û Şirove',
    turkishTitle: 'Cizîrî: Divan Parça Analizi',
    unitNumber: 3, lessonNumber: 1, level: 5,
    path: LessonPath.cultural,
    targetCardIds: _c1Cards(['edebiyat', 'huner']).take(8).toList(),
    culturalRewardId: 'xani_1',
    estimatedMinutes: 13, emoji: '🕌',
    exercises: [
      _mc(id: 'c1_l07_e1',
        ku: 'Di dîwana Cizîrî de "yar" û "dilber" li ser kîjan astê tê bikar anîn?',
        tr: 'Hangi düzeyde kullanılır',
        opts: [
          'Evîna îlahî û tesewufî (mistîk)',
          'Evîna rojane (madî)',
          'Hew evîna madî',
          'Evîna navbera du kesên civakî',
        ],
        ci: 0,
        note: 'Sûfî edebiyatta "yar/dilber" Allah\'a özlem = ilahi aşk. Dünyevi aşk alegori.'),
      _mc(id: 'c1_l07_e2',
        ku: 'Dîwana Cizîrî ji kîjan cureyên helbestî pêk tê?',
        tr: 'Nazım türlerini seç',
        opts: [
          'Destan',
          'Roman',
          'Rojname',
          'Qesîde, xezel û rubaî',
        ],
        ci: 3,
        note: 'Divan şiir türleri: gazel, kaside, rubaî. "Cure" = tür/biçim. [Dîwana Mela Cizîrî]'),
      _fill(id: 'c1_l07_e3', before: 'Cizîrî bi helbestên xwe yên', after: ' wateya exlaqî û felsefî dide.',
        tr: 'Cizîrî mistik şiirleriyle ahlaki ve felsefi anlam verir.',
        opts: ['tesewufî', 'teknîkî', 'rojane', 'aborî'],
        ci: 0,
        note: '"Tesewufî" = sufî, mistik. Pirjimar ezafe zinciri: "helbestên xwe yên tesewufî".'),
      _mc(id: 'c1_l07_e4',
        ku: '"Ey reqîbê zaman" — "reqîb" tê çi wateyê?',
        tr: 'Mistik edebiyatta "reqîb"',
        opts: [
          'Dijminê evînê, ewê ku dê evîn winda bike',
          'Stêrkek geş ku şevê rê nîşanî evîndaran dide',
          'Hevalê dil ê herî nêzîk ê evîndarê reben',
          'Birayê yar ê ku evîndaran ji hev diparêze',
        ],
        ci: 0,
        note: '"Reqîb" = rakip; klasik divanda aşığın rakibi / zahirî baskıcı. [FB]'),
      _fill(id: 'c1_l07_e5', before: 'Dîwana Cizîrî di çerxa', after: ' de hate nivîsîn.',
        tr: 'Cizîrî Divanı 16-17. yüzyılda yazıldı.',
        opts: ['16-17.', '17-18.', '18-19.', '15-16.'],
        ci: 0,
        note: 'Mela Cizîrî 1570-1640 arası yaşadı. 16. yy sonu - 17. yy başı.'),
      _speak(id: 'c1_l07_e6',
        ku: 'Dîwana Cizîrî şahkareke klasîk a Kurmancî ye. Yar, dilber û reqîb sembolên tesewufî ne.',
        tr: 'Cizîrî Divanı Kurmancî\'nin klasik bir şaheseridir. Yar, dilber ve rakip mistik sembollerdir.'),
    ],
  ),

  LessonModel(
    id: 'c1_l08',
    kurmanjTitle: 'Feqiyê Teyran: Şeyxê Senan',
    turkishTitle: 'Feqiyê Teyran ve Şeyh San\'an',
    unitNumber: 3, lessonNumber: 2, level: 5,
    path: LessonPath.cultural,
    targetCardIds: _c1Cards(['edebiyat']).skip(4).take(6).toList(),
    estimatedMinutes: 12, emoji: '📖',
    exercises: [
      _mc(id: 'c1_l08_e1',
        ku: 'Feqiyê Teyran (1590–1660) kî ye?',
        tr: 'Doğru tanımı bul',
        opts: [
          'Helbestvanekî mezin ê Kurmancî yê sedsala 17',
          'Stranbêjekî gelêrî yê dema Osmaniyan ê sedsala 18',
          'Padîşahek herêmî yê Kurdistanê yê sedsala 16',
          'Alimekî dînî yê Erebî yê dema Selçûqiyan',
        ],
        ci: 0,
        note: 'Feqiyê Teyran — Kürt klasik şairi. Kuşlarla konuşma sembolizmi ünlü.'),
      _mc(id: 'c1_l08_e2',
        ku: '"Şeyxê Senan" kîjan mijarê vedibêje?',
        tr: 'Doğru temayı bul',
        opts: [
          'Evîna mutleq ya Şeyxekî sofî ji keçeke xiristîan',
          'Têkoşîna cotkarên feqîr li hember axayan',
          'Hilberîna bazirganî di navbera bajaran de',
          'Şerê du qebîleyan li ser çiyayên Botanê',
        ],
        ci: 0,
        note: 'Şeyh Sanan: sûfî şeyhinin Hıristiyan kıza tutkusu → derin tasavvufi mesaj.'),
      _fill(id: 'c1_l08_e3', before: 'Feqiyê Teyran bi ravekirina bi zimanê', after: ' navdar e.',
        tr: 'Feqiyê Teyran kuşların diliyle anlatımıyla ünlüdür.',
        opts: ['mirovan', 'rojan', 'dinê', 'teyran'],
        ci: 3,
        note: '"Teyr" = kuş. "Feqî" = talebe-alim; "yê teyran" = kuşların.'),
      _mc(id: 'c1_l08_e4',
        ku: 'Destana "Şeyxê Senan" kîjan têgeha tesewufî vedibêje?',
        tr: 'Doğru sûfî temayı bul',
        opts: [
          'Rewşa xwebûnê',
          'Marîfeta aborî',
          'Şerê asmanî',
          'Fena (windakirina xwe) di evîna îlahî de',
        ],
        ci: 3,
        note: 'Fena: ilahi aşkta benliğin yitirilmesi. Cüneyd-i Bağdadi geleneği. Şeyh Sanan bu yolu temsil eder.'),
      _fill(id: 'c1_l08_e5', before: 'Di destanê de Şeyx', after: ' xwe winda dike, hingê xwe dinase.',
        tr: 'Destanda Şeyh nefsini yitirince kendini tanır.',
        opts: ['pereyê', 'nefsa', 'zimanê', 'sala'],
        ci: 1,
        note: '"Nefs" Arapça kökenli, dişil. Şimdiki zaman geçişli fiilde nesne nominatif ezafe alır: "nefsa xwe winda dike" — oblik DEĞİL.'),
      _speak(id: 'c1_l08_e6',
        ku: 'Destana "Şeyxê Senan" a Feqiyê Teyran mînakeke dewlemend a edebiyata tesewufî ya Kurdî ye.',
        tr: '"Şeyh San\'an" destanı Feqiyê Teyran\'ın Kürt tasavvuf edebiyatının zengin bir örneğidir.'),
    ],
  ),

  LessonModel(
    id: 'c1_l09',
    kurmanjTitle: 'Xanî: Mem û Zîn — Şirovea Kûr',
    turkishTitle: 'Xanî: Mem û Zîn — Derin Analiz',
    unitNumber: 3, lessonNumber: 3, level: 5,
    path: LessonPath.cultural,
    targetCardIds: _c1Cards(['edebiyat', 'kimlik', 'siyaset']).take(8).toList(),
    culturalRewardId: 'xani_1',
    estimatedMinutes: 13, emoji: '📜',
    exercises: [
      _mc(id: 'c1_l09_e1',
        ku: '"Mem û Zîn" tenê çîrokeke evînê ye, an bi wê re çi heye?',
        tr: 'Doğru tezi seç',
        opts: [
          'Çîrokeke evînê ya sade bê veguhastina civakî',
          'Vegotinek mîtolojîk derbarê dahatûya gel',
          'Berhema dîrokî ya tenê derbarê serdema osmaniyan',
          'Allegoriya siyasî û netewî derbarê bêdewletiya Kurdan',
        ],
        ci: 3,
        note: 'Mem û Zîn çift katmanlı: yüzeyde aşk, derinde Kürt ulusal varoluş sorunu. [Xanî 1695]'),
      _mc(id: 'c1_l09_e2',
        ku: 'Xanî di "Mem û Zîn"ê de çima bi Kurmancî nivîsiye?',
        tr: 'Dil seçim gerekçesi',
        opts: [
          'Ji ber ku ferman ji desthilatdarê serdemê hatibû',
          'Ji ber ku zimanê erebî û farisî qedexe bûbûn',
          'Ji ber ku xwendevanên Kurmancî tenê di gund de bûn',
          'Ji bo nîşan bike ku Kurmancî jî zimanê edebiyata asta bilind e',
        ],
        ci: 3,
        note: 'Xanî önsözde: Kurmancî\'nin yüksek edebi dil olarak yeterliliğini kanıtlama amacı.'),
      _fill(id: 'c1_l09_e3', before: 'Xanî di "Mem û Zîn" de tekez dike ku Kurd hene û ', after: 'a wan bi nav heye.',
        tr: 'Xanî, Mem û Zîn\'de Kürtlerin var olduğunu ve adlandırılan bir … olduğunu vurgular.',
        opts: ['welat', 'Kurmancî', 'Kurdistan', 'Botan'],
        ci: 2,
        note: 'Bu doğrudan dize değil, Xanî\'nin önsözündeki tezin pedagojik özetidir. Kürt kimliği + adlandırılmış toprak → siyasi-edebî iddianın temeli.'),
      _mc(id: 'c1_l09_e4',
        ku: 'Mîrê Botan di "Mem û Zîn" de çi rolê dikişîne?',
        tr: 'Doğru rolü bul',
        opts: [
          'Cotkar',
          'Xwedanê desthilatê yê ku bi fitneya Bekir xapîyaye',
          'Fitneker',
          'Stranbêj',
        ],
        ci: 1,
        note: 'Mîr Zeynedîn: Botan emiri, Bekir\'in fitnesine kapıldı. Siyasi gücün ahlaki testi.'),
      _fill(id: 'c1_l09_e5', before: 'Xanî bi hişmendî nîşan dide ku', after: ' sedema girîng a bindestiya Kurdan e.',
        tr: 'Xanî birliksizliğin Kürt tutsaklığının önemli sebebi olduğunu gösterir.',
        opts: ['hewaya sar', 'kêmasî', 'bêyekîtî', 'bindestî'],
        ci: 2,
        note: '"Bêyekîtî" = birliksizlik. Xanî\'nin ana siyasi teşhisi.'),
      _speak(id: 'c1_l09_e6',
        ku: '"Mem û Zîn" hem çîroka evîn û hem îddîaya netewî ye. Xanî bêyekîtiya Kurdan rexne dike.',
        tr: 'Mem û Zîn hem aşk hikayesi hem ulusal iddiadır. Xanî Kürt birliksizliğini eleştirir.'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // BİRİM 4 — Siyaset û Hiqûq (2 ders)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'c1_l10',
    kurmanjTitle: 'Hiqûqa Navneteweyî',
    turkishTitle: 'Uluslararası Hukuk',
    unitNumber: 4, lessonNumber: 1, level: 5,
    path: LessonPath.general,
    targetCardIds: _c1Cards(['zagon', 'siyaset']).take(8).toList(),
    estimatedMinutes: 12, emoji: '⚖️',
    exercises: [
      _ls(id: 'c1_l10_e1',
        ku: 'Peyman',
        tr: 'Ne anlama geliyor?',
        opts: [
          'Lihevkirina resmî ya fermî',
          'Pevçûna leşkerî ya tund',
          'Pirtûka qanûna bingehîn',
          'Bazara aboriya navneteweyî',
        ],
        ci: 0,
        note: '"Peyman" = antlaşma, sözleşme. Uluslararası hukuk terimi.'),
      _mc(id: 'c1_l10_e2',
        ku: '"Serwerî" (sovereignty) tê çi wateyê?',
        tr: 'Doğru anlamı bul',
        opts: [
          'Pere',
          'Kar',
          'Bêwelat',
          'Desthilatdariya bilindtirîn ya dewletê li ser axa xwe',
        ],
        ci: 3,
        note: '"Serwerî" = egemenlik. Uluslararası hukukun çekirdek kavramı.'),
      _fill(id: 'c1_l10_e3', before: 'Mafê mirovan di', after: ' de hatiye parastin.',
        tr: 'İnsan hakları uluslararası anlaşmalarda korunmuştur.',
        opts: ['peymanên navneteweyî', 'dibistanê', 'firotgeha', 'bajarê'],
        ci: 0,
        note: '"Peymanên navneteweyî" = uluslararası anlaşmalar.'),
      _mc(id: 'c1_l10_e4',
        ku: 'Dewleta yekgirtî û federasyon cudahiya wan çi ye?',
        tr: 'Federasyon ile yekgirtî devlet farkı',
        opts: [
          'Federasyon bi parvekirina desthilatê di navbera navendê û parçeyan de',
          'Yekgirtî yek welat e, federasyon di nav xwe de gelek welatên cuda ne',
          'Her du pergal wek hev in û tu ferqeke wan a bingehîn nîne',
          'Federasyon bê axa û dewletek nîne, bi tenê hevkariyek e',
        ],
        ci: 0,
        note: 'Federasyon: merkez ile birimler arasında yetki paylaşımı. "Yekgirtî" (unitary) karşıtı.'),
      _fill(id: 'c1_l10_e5', before: 'Divê qanûn ji', after: ' kêmtir nebe.',
        tr: 'Yasa anlaşmalardan aşağı olmamalıdır.',
        opts: ['bêdengiyê', 'hewayê', 'salê', 'peymanan'],
        ci: 3,
        note: '"Ji peymanan" = antlaşmalardan. "Peyman" oblique çoğul → "peymanan". Hukuk hiyerarşisi.'),
      _speak(id: 'c1_l10_e6',
        ku: 'Hiqûqa navneteweyî serwerî, peyman û mafê mirovan tev-birêkûpêk dike. Bi wê şêweyê aştî tê parastin.',
        tr: 'Uluslararası hukuk egemenlik, anlaşmalar ve insan haklarını düzenler. Böylece barış korunur.'),
    ],
  ),

  LessonModel(
    id: 'c1_l11',
    kurmanjTitle: 'Demokrasî û Pergaleyên Siyasî',
    turkishTitle: 'Demokrasi ve Siyasi Sistemler',
    unitNumber: 4, lessonNumber: 2, level: 5,
    path: LessonPath.general,
    targetCardIds: _c1Cards(['siyaset', 'zagon']).skip(4).take(6).toList(),
    culturalRewardId: 'cegerxwin_1',
    estimatedMinutes: 12, emoji: '🗳️',
    exercises: [
      _mc(id: 'c1_l11_e1',
        ku: '"Demokrasiya rasterast" û "demokrasiya nûnerî" ferqa wan çi ye?',
        tr: 'Doğru farkı bul',
        opts: [
          'Rasterast tenê di civakên gundewar ên biçûk de tê pêkanîn',
          'Nûnerî pergaleke bêkêr e ku bi rastî nayê meşandin',
          'Rasterast: gel bi xwe biryar dide; nûnerî: bi hilbijartinê nûnerên gel biryar didin',
          'Tu ferq di navbera her du pergalan de tune ye',
        ],
        ci: 2,
        note: 'Doğrudan vs temsili demokrasi. Athena doğrudan, modern temsili.'),
      _fill(id: 'c1_l11_e2', before: 'Di demokrasiyê de', after: ' bingehîn e.',
        tr: 'Demokraside güç ayrımı temeldir.',
        opts: ['aşitî', 'veqetandina desthilatê', 'dezgehê', 'azadî'],
        ci: 1,
        note: '"Veqetandina desthilatê" = kuvvetler ayrılığı. Montesquieu prensibi.'),
      _mc(id: 'c1_l11_e3',
        ku: '"Hukumeta parlamenter" çi ye?',
        tr: 'Doğru tanımı bul',
        opts: [
          'Sîstema ku hukûmet ji piraniya meclisê tê',
          'Şahînşahî',
          'Neteweyî',
          'Yan ên beleş',
        ],
        ci: 0,
        note: 'Parlamenter sistem: hükümet yasama meclisinden çıkar (UK, Almanya, Türkiye).'),
      _fill(id: 'c1_l11_e4', before: 'Hilbijartin divê', after: ' û serbest be.',
        tr: 'Seçim şeffaf ve özgür olmalıdır.',
        opts: ['dirêj', 'bikêr', 'kêm', 'zelal'],
        ci: 3,
        note: '"Zelal" = şeffaf. Demokrasi standardı.'),
      _mc(id: 'c1_l11_e5',
        ku: '"Civaka sivîl" çi ye?',
        tr: 'Doğru tanımı bul',
        opts: [
          'Komên serbixwe yên gel: sendîka, rêxistinên ne-hukumetî, partî',
          'Hêza leşkerî ya fermî ya dewletê û saziyên wê yên ewlehiyê',
          'Hukumet û saziyên fermî yên rêveberiya navendî ya dewletê',
          'Şirketên bazirganî yên ku qezencê ji bazara serbest werdigirin',
        ],
        ci: 0,
        note: 'Sivil toplum: devlet dışı örgütlü halk alanı. Demokrasinin altyapısı.'),
      _speak(id: 'c1_l11_e6',
        ku: 'Demokrasî bi veqetandina desthilatê, civaka sivîl û hilbijartinên zelal pêşde diçe.',
        tr: 'Demokrasi kuvvetler ayrılığı, sivil toplum ve şeffaf seçimlerle ilerler.'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // BİRİM 5 — Postkolonyalî û Nasname (2 ders)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'c1_l12',
    kurmanjTitle: 'Teoriya Postkolonyal',
    turkishTitle: 'Postkolonyal Teori',
    unitNumber: 5, lessonNumber: 1, level: 5,
    path: LessonPath.general,
    targetCardIds: _c1Cards(['felsefe', 'kimlik', 'dîrok']).take(8).toList(),
    estimatedMinutes: 13, emoji: '🌍',
    exercises: [
      _mc(id: 'c1_l12_e1',
        ku: '"Postkolonyalîzm" kîjan mijarê vedikole?',
        tr: 'Doğru alanı bul',
        opts: [
          'Encamên kolonyalîzmê yên çandî, siyasî û zimanî',
          'Tenê dîroka şerên kevneşopî yên di navbera dewletan de',
          'Aboriya gundewar û pergalên hilberîna kevneşopî',
          'Huner û estetîka tevgerên hunerî yên sedsala 21an',
        ],
        ci: 0,
        note: 'Postkolonyal çalışma: sömürgeleştirmenin izleri. Said, Fanon, Spivak, Bhabha.'),
      _mc(id: 'c1_l12_e2',
        ku: '"Orientalism" a Edward Said çi tîne ser ziman?',
        tr: 'Said\'in temel tezi',
        opts: [
          'Rojhilatê taybet',
          'Pesnê Rojhilatê',
          'Aboriya Rojhilatê',
          'Rexne li temsîla Rojhilatê di dîskûra rojavayî de',
        ],
        ci: 3,
        note: 'Said 1978: Batı\'nın Doğu\'yu temsil biçimi = güç aracı. Klasik postkolonyal metin.'),
      _fill(id: 'c1_l12_e3', before: 'Ziman', after: ' jî ye, ne tenê amûrê peywendiyê.',
        tr: 'Dil aynı zamanda güç aracıdır, yalnızca iletişim aracı değil.',
        opts: ['şermê', 'şêweyek', 'havîneke', 'amûrê desthilatê'],
        ci: 3,
        note: '"Amûrê desthilatê" = iktidar aracı. Foucault-Said gelenek.'),
      _mc(id: 'c1_l12_e4',
        ku: '"Subaltern" (Spivak) çi ye?',
        tr: 'Doğru tanımı bul',
        opts: [
          'Komên xwedî desthilat ku bi raya giştî re vekirî diaxivin',
          'Çîna bilind a fermî ya ku ji hêla dewletê ve tê piştgirîkirin',
          'Rewşenbîrên fermî yên ku siyaseta dewletê dipejirînin û dimeşînin',
          'Grûpên bê-deng, yên ku ji hêla desthilatê ve nayên bihîstin',
        ],
        ci: 3,
        note: 'Spivak 1988: "Subaltern konuşabilir mi?" Marjinalleştirilmiş sesler.'),
      _fill(id: 'c1_l12_e5', before: 'Ziman û çand di', after: ' de bi hev re tên birîn.',
        tr: 'Dil ve kültür sömürgeleşmede birlikte kesilir.',
        opts: ['dibistanê', 'pazarê', 'kolonyalîzmê', 'civînekê'],
        ci: 2,
        note: 'Dilsel sömürgecilik postkolonyal teorinin merkezi (Fanon). "Bi hev re" = birlikte.'),
      _speak(id: 'c1_l12_e6',
        ku: 'Postkolonyalîzm bi rexne li ser ziman, çand û desthilatê disekine. Saîd û Spivak pîşekarên girîng in.',
        tr: 'Postkolonyalizm dil, kültür ve iktidar üzerine eleştirel olarak durur. Said ve Spivak önemli kuramcılardır.'),
    ],
  ),

  LessonModel(
    id: 'c1_l13',
    kurmanjTitle: 'Nasnameya Netewî û Ziman',
    turkishTitle: 'Ulusal Kimlik ve Dil',
    unitNumber: 5, lessonNumber: 2, level: 5,
    path: LessonPath.general,
    targetCardIds: _c1Cards(['kimlik', 'ziman', 'çand']).take(8).toList(),
    culturalRewardId: 'cegerxwin_1',
    estimatedMinutes: 12, emoji: '🪢',
    exercises: [
      _mc(id: 'c1_l13_e1',
        ku: 'Li gor Benedict Anderson, netew çi ye?',
        tr: 'Anderson\'un tanımı',
        opts: [
          'Sînorek erdnîgarî ku bi peymana navneteweyî tê diyarkirin',
          '"Civakek xeyalî" — hevpariyeke hevpar ku bi wesayîta ziman û çapê ava dibe',
          'Artêşek bi rêkûpêk ku ji bo parastina dewletê tê avakirin',
          'Komeke şarezayan ku siyaseta dewletê dimeşînin',
        ],
        ci: 1,
        note: 'Anderson 1983: "Imagined Communities" — millet = hayali topluluk.'),
      _fill(id: 'c1_l13_e2', before: 'Zimanê dayikê di avakirina', after: ' de girîng e.',
        tr: 'Ana dil ulusal kimlik inşasında önemlidir.',
        opts: ['bazarî', 'aşê', 'aboriyê', 'nasnameya netewî'],
        ci: 3,
        note: '"Nasnameya netewî" = ulusal kimlik. Herder geleneği.'),
      _mc(id: 'c1_l13_e3',
        ku: 'Çima zimanê nivîsandinê (standard) di avakirina neteweyê de girîng e?',
        tr: 'Doğru sebebi bul',
        opts: [
          'Ji bo yekgirtina dialektên ferq û ragihandina mezin',
          'Ji bo nîqaşa',
          'Ji bo şahînşahîyê',
          'Ji bo rehetiyê',
        ],
        ci: 0,
        note: 'Standart dil: lehçelerin üstünde birlik yazarı ve ulusötesi iletişim imkanı.'),
      _fill(id: 'c1_l13_e4', before: 'Standardkirina Kurmancî bi elîfba', after: ' hat dest pê kirin.',
        tr: 'Kurmancî standardizasyonu Hawar alfabesiyle başladı.',
        opts: ['Latînî (Hawar)', 'Arabî', 'Kirîlî', 'Farsî'],
        ci: 0,
        note: 'Celadet Bedirxan 1932: Hawar dergisi + Latin alfabesi = modern Kurmancî.'),
      _mc(id: 'c1_l13_e5',
        ku: 'Ethno-linguistic nationalism çi ye?',
        tr: 'Doğru tanımı bul',
        opts: [
          'Têgeh: netewe ji ziman û koka zayînê tê avakirin',
          'Têgeh: netewe bê girêdana zimanî tê avakirin',
          'Têgeh: netewe ji bo axekê ne pêwîst tê hesibandin',
          'Têgeh: netewe ji çand û dîrokê tê veqetandin',
        ],
        ci: 0,
        note: 'Etno-dilsel milliyetçilik: Herder-Fichte çizgisi, dil+etnik köken birliği.'),
      _speak(id: 'c1_l13_e6',
        ku: 'Ziman û nasnameya netewî girêdayî hev in. Kurmanciya standard di sedsala 20an de ava bû.',
        tr: 'Dil ve ulusal kimlik birbirine bağlıdır. Standart Kurmancî 20. yüzyılda inşa edildi.'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // BİRİM 6 — Nivîsîn (2 ders — Rêya Malê writing task)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'c1_l14',
    kurmanjTitle: 'Paragrafa Pêşbaziyê: Arguman û Delîl',
    turkishTitle: 'Tartışmacı Paragraf',
    unitNumber: 6, lessonNumber: 1, level: 5,
    path: LessonPath.heritage,
    targetCardIds: _c1Cards(['akademik', 'ziman']).take(6).toList(),
    estimatedMinutes: 13, emoji: '✍️',
    exercises: [
      _mc(id: 'c1_l14_e1',
        ku: 'Paragrafa pêşbaziyê (argumentative) ji çi pêk tê?',
        tr: 'Doğru yapıyı bul',
        opts: [
          'Pêşgotin - nirxandina kesane - encam',
          'Tenê ravekirina rastiyên zanistî bê analîz',
          'Vegotina kronolojîk a bûyerên dîrokî',
          'Tez - delîl-destek - rexnea dijê tezê - encam',
        ],
        ci: 3,
        note: 'Argumantasyon: claim + support + counter + rebuttal + conclusion.'),
      _order(id: 'c1_l14_e2',
        tr: '"Benim tezim: Dil insan hakkıdır" cümlesini diz',
        pieces: ['Teza', 'min', 'ev', 'e:', 'ziman', 'mafê', 'mirovan', 'e'],
        target: 'Teza min ev e: ziman mafê mirovan e',
        note: 'Akademik tez girişi: "Teza min ev e:" = "Tezim şudur:" Ezafe-marker "-a" isme yapışır.'),
      _mc(id: 'c1_l14_e3',
        ku: 'Peyveke girêdanê ji bo nîşandana delîlê çi ye?',
        tr: 'Doğru bağlayıcıyı seç',
        opts: ['lê', 'tenê', 'wek mînak / wekû', 'çimkî'],
        ci: 2,
        note: '"Wek mînak / wekû" = örneğin. Delil girişi.'),
      _fill(id: 'c1_l14_e4', before: 'Bi encameke kurt:', after: ' ramîna rexnegir di perwerdeyê de pêwîst e.',
        tr: 'Kısa sonuç olarak: kuşkusuz eleştirel düşünce eğitimde gereklidir.',
        opts: ['belkî ku', 'dibe ku', 'belkî', 'bê guman'],
        ci: 3,
        note: '"Bê guman" = kuşkusuz, şüphesiz. Akademik kesinlik kalıbı. "Divê" + "pêwîst e" birlikte kullanılmaz (redundant).'),
      _mc(id: 'c1_l14_e5',
        ku: 'Kîjan peyvrêz wateya "argûmanê dijber qebûl kirin, lê belê" dide?',
        tr: '"Karşı argümanı kabul etmek, ama" anlamını veren ifadeyi seç',
        opts: [
          'Ji bo... da ku',
          'Wek ku... ew jî',
          'Çimkî... lewra',
          'Her çend ku... lê belê',
        ],
        ci: 3,
        note: '"Her çend ku ... lê belê" = her ne kadar ... olsa da. Karşı argüman kabul kalıbı.'),
      _speak(id: 'c1_l14_e6',
        ku: 'Teza min ev e: zimanê dayikê mafê bingehîn e. Her çend ku dijberî hebe jî, delîlên zanistî vê yekê piştrast dikin.',
        tr: 'Tezim: ana dil temel bir haktır. Her ne kadar muhalefet olsa da bilimsel kanıtlar bunu doğruluyor.'),
    ],
  ),

  LessonModel(
    id: 'c1_l15',
    kurmanjTitle: 'Nivîsîna Şiroveyî û Nirxandinê',
    turkishTitle: 'Yorumlama ve Değerlendirme Yazısı',
    unitNumber: 6, lessonNumber: 2, level: 5,
    path: LessonPath.heritage,
    targetCardIds: _c1Cards(['akademik', 'felsefe']).skip(4).take(6).toList(),
    culturalRewardId: 'proverb_2',
    estimatedMinutes: 12, emoji: '📝',
    exercises: [
      _mc(id: 'c1_l15_e1',
        ku: 'Di nirxandineke akademîk de cih çi tê dayîn?',
        tr: 'Doğru bileşenleri bul',
        opts: [
          'Hem aliyên erênî û hem yên nebaş, analîz',
          'Tenê pesnê berhemê û aliyên wê yên hêja',
          'Tenê rexneya tund a kêmasiyên berhemê',
          'Bê nirxandin, tenê kurte û naverokê tê dayîn',
        ],
        ci: 0,
        note: 'Akademik değerlendirme: dengeli — güçlü-zayıf yönlerin analizi.'),
      _fill(id: 'c1_l15_e2', before: 'Berhem bi', after: ' tê dayîn lê aliyên wê yên kêm hene.',
        tr: 'Eser olumlu değerlendirilir ama eksik yönleri vardır.',
        opts: ['xewê', 'tirsê', 'şermê', 'nirxê bilind'],
        ci: 3,
        note: '"Nirxê bilind" = yüksek değer. Dengeli değerlendirme üslûbu.'),
      _mc(id: 'c1_l15_e3',
        ku: 'Peyveke girêdanê ji bo nîşandana ramanê dijber çi ye?',
        tr: 'Doğru bağlayıcıyı seç',
        opts: ['jixwe', 'herwiha', 'lê belê / berevajî vê', 'bi vî rengî'],
        ci: 2,
        note: '"Lê belê / berevajî vê" = ama, buna karşın. Zıtlık bağlaçları. "Raman" (< BH) Kurmancî asıl, "fikir" Arapça alıntı.'),
      _fill(id: 'c1_l15_e4', before: 'Di vê lêkolînê de ez', after: ' bi awayekî vekirî diyar dikim.',
        tr: 'Bu araştırmada metodumu açıkça belirtiyorum.',
        opts: ['rêbaza xwe', 'salê xwe', 'pereyê xwe', 'dengê xwe'],
        ci: 0,
        note: '"Rêbaz" = metot. Akademik şeffaflık.'),
      _mc(id: 'c1_l15_e5',
        ku: 'Paragrafa dawîn a nivîseke akademîk çi dike?',
        tr: 'Sonuç paragrafı işlevi',
        opts: [
          'Dubare dike çi hat gotin + derî li ramînên pêşerojê vedike',
          'Daxwazên kesane û hêviyên nivîskar ji bo pêşerojê pêşkêş dike',
          'Têgehên teknîkî yên ku di nivîsê de derbas bûne, rêz dike',
          'Lîsteya hemû lêkerên ku di nivîsê de hatine bikaranîn pêşkêş dike',
        ],
        ci: 0,
        note: 'Sonuç: tezi tekrar + ileriki araştırmaya açık kapı.'),
      _speak(id: 'c1_l15_e6',
        ku: 'Di nirxandineke akademîk de mirov divê bi hişmendî aliyên erênî û nebaş raber bike. Tezek zelal û rêbazeke şeffaf girîng in.',
        tr: 'Akademik bir değerlendirmede olumlu ve olumsuz yönler bilinçli sunulmalı. Net bir tez ve şeffaf metot önemlidir.'),
    ],
  ),
];
