import 'lesson_entities.dart';
import 'c2_kelime_db.dart';

// ════════════════════════════════════════════════════════════════
// C2 — 15 DERS TANIMI (Jor-Jor / Uzman)
//
// Pedagojik Odak (CEFR C2):
// - Cegerxwîn yoğunlaştırılmış (5 ders): modernîte, welatparêzî, şoreş
// - Etnolenguîstîk: Kurmancî vs Behdînî vs Serhedî farkları
// - Neolojizm ve standardizasyon tartışmaları
// - Klasik dönem: Feqiyê Teyran, Haci Qadirê Koyî
// - Psikolojî, medya kritik teorisi, karşılaştırmalı edebiyat
// - Uzman akademik yazım: paradigma, dîskûr analîzi
//
// Path dağılımı: 10 general · 2 heritage · 3 cultural
// ════════════════════════════════════════════════════════════════

List<String> _c2Cards(List<String> kats) => kC2All
    .where((k) => kats.contains(k.kat))
    .map((k) => k.id)
    .toList();

ExerciseModel _mc({
  required String id, required String ku, required String tr,
  required List<String> opts, required int ci,
  String? note, int xp = 16,
}) => ExerciseModel(
  id: id, type: ExerciseType.multipleChoice,
  kurmanjPrompt: ku, turkishPrompt: tr,
  options: opts, correctAnswer: opts[ci], correctIndex: ci,
  grammarNote: note, xpReward: xp,
);

ExerciseModel _ls({
  required String id, required String ku, required String tr,
  required List<String> opts, required int ci,
  String? audio, String? note, int xp = 18,
}) => ExerciseModel(
  id: id, type: ExerciseType.listenAndSelect,
  kurmanjPrompt: ku, turkishPrompt: tr,
  options: opts, correctAnswer: opts[ci], correctIndex: ci,
  audioAsset: audio, grammarNote: note, xpReward: xp,
);

ExerciseModel _fill({
  required String id, required String before, required String after,
  required String tr, required List<String> opts, required int ci,
  String? note, int xp = 18,
}) => ExerciseModel(
  id: id, type: ExerciseType.fillInBlank,
  kurmanjPrompt: '$before ___ $after', turkishPrompt: tr,
  options: opts, correctAnswer: opts[ci], correctIndex: ci,
  grammarNote: note, xpReward: xp,
  wordPieces: [before.trim(), after.trim()],
);

ExerciseModel _speak({
  required String id, required String ku, required String tr,
  String? audio, int xp = 22,
}) => ExerciseModel(
  id: id, type: ExerciseType.speakingPractice,
  kurmanjPrompt: ku, turkishPrompt: tr,
  audioAsset: audio, xpReward: xp,
  options: ['Gelek baş', 'Nêzîk', 'Carek din'],
  correctAnswer: ku,
);

// ════════════════════════════════════════════════════════════════
// 15 DERS
// ════════════════════════════════════════════════════════════════

final kC2Lessons = <LessonModel>[

  // ─────────────────────────────────────────────────────────────
  // BİRİM 1 — Cegerxwîn û Modernîte (5 ders)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'c2_l01',
    kurmanjTitle: 'Cegerxwîn: Jiyan û Berhem',
    turkishTitle: 'Cegerxwîn: Hayat ve Eserler',
    unitNumber: 1, lessonNumber: 1, level: 6,
    path: LessonPath.cultural,
    targetCardIds: _c2Cards(['edebiyat', 'kimlik', 'çand']).take(8).toList(),
    culturalRewardId: 'cegerxwin_2',
    estimatedMinutes: 13, emoji: '🌟',
    exercises: [
      _mc(id: 'c2_l01_e1',
        ku: 'Cegerxwîn (1903–1984) li kîjan deverê hat dinyayê?',
        tr: 'Doğum yerini bul',
        opts: [
          'Cizîr (li herêma Şirnex / Bakurê Kurdistan)',
          'Hewlêr (li herêma Başûrê Kurdistan)',
          'Hesarê (li herêma Gercûşê / Mêrdîn)',
          'Şam (paytexta Sûriyê)',
        ],
        ci: 2,
        note: 'Cegerxwîn 1903\'te Hesar köyünde (Gercüş ilçesi; o dönem Mardin\'e bağlıydı, 1990\'dan sonra Batman iline geçti) doğdu. Gerçek adı Şêxmûs Hesen. NOT: "Gerger" (Adıyaman) farklı bir ilçedir — karıştırılmamalıdır.'),
      _mc(id: 'c2_l01_e2',
        ku: 'Dîwanên Cegerxwîn çend cilt in û sal kîjan in?',
        tr: 'Divan cilt bilgisi',
        opts: ['8 cilt, 1945-85', '4 cilt, 1950-70', '6 cilt, 1960-80', '2 cilt, 1970-85'],
        ci: 0,
        note: 'Dîwan I-VIII: 1945-1985 aralığında yayımlandı.'),
      _fill(id: 'c2_l01_e3', before: '"Kî me ez?" pirseke bingehîn a helbestên', after: ' ye.',
        tr: '"Ben kimim?" Cegerxwîn\'in temel sorusudur.',
        opts: ['Cegerxwîn', 'Xanî', 'Cizîrî', 'Feqiyê'],
        ci: 0,
        note: '"Kî me ez?" = Ben kimim? Cegerxwîn\'in ünlü parçası.'),
      _mc(id: 'c2_l01_e4',
        ku: 'Cegerxwîn di berhemên xwe de çi mijaran pêşde tîne?',
        tr: 'Ana temaları bul',
        opts: [
          'Nasnameya netewî, welatparêzî, şoreş, azadî',
          'Bi tenê evîna kesane û lîrîzma romantîk',
          'Aboriya gundî û jiyana cotkarên feqîr',
          'Hunera madî û estetîka biçûkparêziyê',
        ],
        ci: 0,
        note: 'Cegerxwîn\'in temaları: ulusal kimlik, vatanseverlik, devrim, özgürlük.'),
      _fill(id: 'c2_l01_e5', before: 'Di sala 1979an de Cegerxwîn ji Sûriyê çû', after: '.',
        tr: 'Cegerxwîn 1979\'da Suriye\'den İsveç\'e gitti.',
        opts: ['Fransayê', 'Îngilterê', 'Swêdê', 'Almanyayê'],
        ci: 2,
        note: '1979: Suriye → İsveç sürgünü. Son dönemini orada yaşadı.'),
      _speak(id: 'c2_l01_e6',
        ku: 'Cegerxwîn helbestvanê bêhempa yê serdema modern e. "Kî me ez?" pirseke dîrokî ye.',
        tr: 'Cegerxwîn modern dönemin eşsiz şairidir. "Ben kimim?" tarihsel bir sorudur.'),
    ],
  ),

  LessonModel(
    id: 'c2_l02',
    kurmanjTitle: 'Cegerxwîn: "Kî me ez?" — Parçe û Tefsîr',
    turkishTitle: 'Cegerxwîn: "Ben Kimim?" Analizi',
    unitNumber: 1, lessonNumber: 2, level: 6,
    path: LessonPath.cultural,
    targetCardIds: _c2Cards(['edebiyat', 'kimlik']).skip(4).take(6).toList(),
    culturalRewardId: 'cegerxwin_2',
    estimatedMinutes: 13, emoji: '❓',
    exercises: [
      _mc(id: 'c2_l02_e1',
        ku: 'Di helbesta "Kî me ez?" de Cegerxwîn kîjan pêvajoya ramîn dişopîne?',
        tr: 'Düşünce yapısı',
        opts: [
          'Tenê pesnê welat û çiyayên Kurdistanê bi awayekî romantîk',
          'Dubarekirina mijara evînê bê pêvajoya ramanê',
          'Vegotina dîroka şerên kevneşopî yên Kurdan li dijî dewletan',
          'Pirs → lêgerîn → dîtina nasnameya xwe ya netewî',
        ],
        ci: 3,
        note: '"Kî me ez?" yapısı: soru → arama → millet-kimlik keşfi.'),
      _fill(id: 'c2_l02_e2', before: 'Kî me ez? Ez', after: ' im!',
        tr: '"Ben kimim? Ben ...im" kalıbı',
        opts: ['tenê tenê', 'bêhizir', 'bê nasname', 'Kurd û Kurdistanî'],
        ci: 3,
        note: 'Cegerxwîn\'in meşhur yanıtı: Kürt ve Kürdistanlı olmak.'),
      _mc(id: 'c2_l02_e3',
        ku: '"Kî me ez?" di çi serdemê de hatiye nivîsîn?',
        tr: 'Dönemi bul',
        opts: [
          'Beriya Yekem Şerê Cîhanê',
          'Sedsala 18an',
          'Di sedsala 17an',
          'Piştî Yekem Şerê Cîhanê û parvekirina Kurdistanê',
        ],
        ci: 3,
        note: 'Cegerxwîn\'in ulusal kimlik şiirleri — Kürdistan\'ın 4 devlet arasında bölünmesinden sonraki dönem.'),
      _fill(id: 'c2_l02_e4', before: 'Cegerxwîn bi zimanê', after: ' dinivîse.',
        tr: 'Cegerxwîn halkın sade diliyle yazar.',
        opts: ['fermî', 'dirêj û zehmet', 'erebî', 'sade û zelal'],
        ci: 3,
        note: 'Cegerxwîn\'in dilsel tercihi: sade, halk dili — klasik divandan uzaklaşır.'),
      _mc(id: 'c2_l02_e5',
        ku: 'Helbesta "Kî me ez?" bi rêya kîjan figurê hunerî hêzdar dibe?',
        tr: 'Edebi figür seç',
        opts: [
          'Bê figureke edebî, bi awayekî vegotinê yê sade',
          'Bi tenê metafor (wek "dilê min agir e")',
          'Bi tenê teşbîh (wek "wekî hevalê wê...")',
          'Pirsa retorîkî + dubarekirina destpêkê (anaphora)',
        ],
        ci: 3,
        note: 'Anafora = dubarekirina destpêkê: dizelerin başındaki aynı söz tekrarı (ör. "Ez ... / Ez ..."). Retorik soru ile birleşince duygusal ivme.'),
      _speak(id: 'c2_l02_e6',
        ku: 'Di "Kî me ez?" de Cegerxwîn bi pirsên retorîkî û zimanê gel, lêgerîna nasnameyê vedibêje.',
        tr: '"Ben kimim?"de Cegerxwîn retorik sorular ve halk diliyle kimlik arayışını dile getirir.'),
    ],
  ),

  LessonModel(
    id: 'c2_l03',
    kurmanjTitle: 'Cegerxwîn: "Keskesor" û Welatparêzî',
    turkishTitle: 'Cegerxwîn: Gökkuşağı ve Vatanseverlik',
    unitNumber: 1, lessonNumber: 3, level: 6,
    path: LessonPath.cultural,
    targetCardIds: _c2Cards(['edebiyat', 'siyaset']).take(8).toList(),
    culturalRewardId: 'cegerxwin_3',
    estimatedMinutes: 13, emoji: '🌈',
    exercises: [
      _mc(id: 'c2_l03_e1',
        ku: 'Di helbesta Cegerxwîn de "welat" (vatan) çawa tê temsîlkirin?',
        tr: 'Vatan sembolü',
        opts: [
          'Wek dibistanek mezin a ku dersan dide gel',
          'Wek daye, wek cihê zayînê û nasnameya kolektîv',
          'Wek kargehek pîşesazî ya ku xebatê dide xelkê',
          'Wek şirketek bazirganî ya ku qezencê tîne',
        ],
        ci: 1,
        note: 'Cegerxwîn\'de vatan: anne, doğum yeri, kolektif kimlik. Romantik-ulusal sembol.'),
      _fill(id: 'c2_l03_e2', before: 'Welat ji bo Cegerxwîn dîmena', after: ' ye.',
        tr: 'Cegerxwîn için vatan özgürlük manzarasıdır.',
        opts: ['azadiyê', 'zanînê', 'aşê', 'aboriyê'],
        ci: 0,
        note: '"Dîmena azadiyê" = özgürlük manzarası. Vatan-özgürlük özdeşliği.'),
      _mc(id: 'c2_l03_e3',
        ku: 'Têgeha "serbilindî" (onur) çi ye di helbestên Cegerxwîn de?',
        tr: 'Onur kavramı',
        opts: [
          'Rûmeta neteweyî, nehilxistina xwe',
          'Şermbûna ji nasname û ziman bi awayê veşartî',
          'Xewa giran a bê xeyalên welatparêziyê',
          'Pereyê zêde û dewlemendiya kesane',
        ],
        ci: 0,
        note: '"Serbilindî" = onur, gurur. Baş dik durma, ulusal onur.'),
      _fill(id: 'c2_l03_e4', before: 'Welatparêzî ne tenê hîs, ew', after: ' jî ye.',
        tr: 'Vatanseverlik yalnızca duygu değil, aynı zamanda sorumluluktur.',
        opts: ['şermek', 'saetek', 'nameyek', 'berpirsyariyek'],
        ci: 3,
        note: '"Berpirsyarî" = sorumluluk. Cegerxwîn\'in ahlaki vatanseverliği.'),
      _mc(id: 'c2_l03_e5',
        ku: 'Cegerxwîn ji bo şoreşê kîjan peyvan dikêşîne?',
        tr: 'Devrim söylem özellikleri',
        opts: [
          'Peyvên xurt û rave: şoreş, berxwedan, bilindî',
          'Peyvên evînê tenê',
          'Peyvên dilwest',
          'Peyvên sar',
        ],
        ci: 0,
        note: '"Şoreş, berxwedan, bilindî" = devrim, direniş, yücelik. Dönemsel siyasi söylem.'),
      _speak(id: 'c2_l03_e6',
        ku: 'Welat, serbilindî û şoreş sê sembolên hişmendê di helbestên Cegerxwîn de ne. Ew Kurdîtiya nûjen pênase dikin.',
        tr: 'Vatan, onur ve devrim Cegerxwîn şiirlerinde üç bilinçli semboldür. Modern Kürtlüğü tanımlarlar.'),
    ],
  ),

  LessonModel(
    id: 'c2_l04',
    kurmanjTitle: 'Cegerxwîn: Ziman û Gelerîtî',
    turkishTitle: 'Cegerxwîn: Dil ve Halkçılık',
    unitNumber: 1, lessonNumber: 4, level: 6,
    path: LessonPath.cultural,
    targetCardIds: _c2Cards(['edebiyat', 'ziman']).take(8).toList(),
    estimatedMinutes: 12, emoji: '🗣️',
    exercises: [
      _mc(id: 'c2_l04_e1',
        ku: 'Cegerxwîn di zimanê helbestan de çi şoreş kir?',
        tr: 'Dilsel yeniliği',
        opts: [
          'Tenê Kurdî birêkûpêk',
          'Derketin ji zimanê dîwanê, vegera bo zimanê gel',
          'Zêdekirina erebî',
          'Kêşa kevn',
        ],
        ci: 1,
        note: 'Cegerxwîn: klasik dîwan dilinden halk Kurmancî\'sine dönüş.'),
      _fill(id: 'c2_l04_e2', before: 'Helbestên Cegerxwîn ji bo', after: ' hatine nivîsîn.',
        tr: 'Cegerxwîn şiirleri kim için yazılmıştır? Halkçı tercih (popülist) — elit/yabancı zıddı.',
        opts: ['elîtan', 'gel', 'xerîban', 'zana tenê'],
        ci: 1,
        note: '"Gel" = halk. Cegerxwîn elitlere değil, sıradan kişilere yazardı. "Elîtan" (eliteler), "zana tenê" (sadece bilginler), "xerîban" (yabancılar) — Cegerxwîn\'in tercihi değil.'),
      _mc(id: 'c2_l04_e3',
        ku: 'Kêşa helbestên Cegerxwîn ji bo çi kurttir e?',
        tr: 'Vezin tercihi',
        opts: [
          'Bê sedem',
          'Ji bo ku ji teref gelê normal bên têgihîştin û xwendin',
          'Zor bû ji bo wî',
          'Ji bo nîşandana zanîna xwe',
        ],
        ci: 1,
        note: 'Kısa vezin + halk dili = erişilebilirlik. Modernist tercih.'),
      _fill(id: 'c2_l04_e4', before: 'Gelerîtî (populism) di helbestê de tê wateya', after: ' gel.',
        tr: 'Şiirde halkçılık halkın etrafında olmak anlamına gelir.',
        opts: ['sarbûna bi', 'vegera ser zimanê', 'dûrketina ji', 'şermî li'],
        ci: 1,
        note: '"Vegera ser zimanê gel" = halk diline dönüş.'),
      _mc(id: 'c2_l04_e5',
        ku: 'Çima zimanê Cegerxwîn ji yê Xanî sadetir e?',
        tr: 'Dilsel fark nedeni',
        opts: [
          'Bi kêfa xwe û tercîha kesane ya estetîk',
          'Wî bi armanca siyasî ya gihandina gelê ku-nexwendî',
          'Ji ber ku wî zimanê edebî yê klasîk nedizanî',
          'Tu sebebek diyar û girêdayî ya tercîhê tune ye',
        ],
        ci: 1,
        note: 'Cegerxwîn\'in siyasi hedefi: okuma-yazma bilmeyen Kürt kitlesine ulaşmak.'),
      _speak(id: 'c2_l04_e6',
        ku: 'Cegerxwîn zimanê gel bi kar tîne. Ev hilbijartin ne tesadufî ye, lê stratejiyeke siyasî-hunerî ye.',
        tr: 'Cegerxwîn halk dilini kullanır. Bu tercih tesadüf değil, politik-sanatsal bir stratejidir.'),
    ],
  ),

  LessonModel(
    id: 'c2_l05',
    kurmanjTitle: 'Cegerxwîn: Mîrasê Edebî',
    turkishTitle: 'Cegerxwîn: Edebi Miras',
    unitNumber: 1, lessonNumber: 5, level: 6,
    path: LessonPath.cultural,
    targetCardIds: _c2Cards(['edebiyat', 'kimlik', 'siyaset']).skip(4).take(6).toList(),
    culturalRewardId: 'cegerxwin_3',
    estimatedMinutes: 12, emoji: '🏛️',
    exercises: [
      _mc(id: 'c2_l05_e1',
        ku: 'Piştî Cegerxwîn, kîjan helbestvanên kurd mîrasa wî dişopînin?',
        tr: 'Sonraki nesil',
        opts: [
          'Tenê helbestvanên sedsala 21an, ne yên berê',
          'Bandora wî zû qedîya û li ser nifşên paşî nemaye',
          'Tenê helbestvanên erebîaxêv ên dîasporayê',
          'Şêrko Bêkes, Rojen Barnas, gelekên din',
        ],
        ci: 3,
        note: 'Şêrko Bêkes (Soranî), Rojen Barnas, Arjen Arî — modern Kürt şiirinde Cegerxwîn ekolünün devamı.'),
      _fill(id: 'c2_l05_e2', before: 'Bandora Cegerxwîn li ser', after: ' ya kurdî mezin e.',
        tr: 'Cegerxwîn\'in modern Kürt şiiri üzerindeki etkisi büyüktür.',
        opts: ['sporê', 'aboriyê', 'pişikiyê', 'edebiyata nûjen'],
        ci: 3,
        note: '"Edebiyata nûjen" = modern edebiyat. Canonical etki.'),
      _mc(id: 'c2_l05_e3',
        ku: 'Bi nêzî çima Cegerxwîn hê jî tê xwendin?',
        tr: 'Güncelliği',
        opts: [
          'Wek nostaljiyek edebî bê girêdana mijara îroyîn',
          'Pirsên nasnameyê hîn jî zindî ne',
          'Ji ber ku zimanê wî giran û dijwar e',
          'Tenê ji bo îmtîhanên dibistan û akademîk',
        ],
        ci: 1,
        note: 'Kimlik soruları hâlâ güncel — bu nedenle Cegerxwîn yaşamaya devam eder.'),
      _fill(id: 'c2_l05_e4', before: 'Di nav hunerên', after: ' de helbestên wî tên gotin.',
        tr: 'Modern müzik içinde şiirleri söylenir.',
        opts: ['sarê', 'muzîka nûjen', 'dûrî', 'kevnar'],
        ci: 1,
        note: 'Şiirler: Modern Kürt müziğinde (Sivan Perwer, Ciwan Haco) icra edilir.'),
      _mc(id: 'c2_l05_e5',
        ku: 'Mîrasa Cegerxwîn çima wêdetir ji "helbestên neteweyî" ye?',
        tr: 'Neden daha fazla',
        opts: [
          'Tenê ji bo armanca siyasî bê dîmenên edebî',
          'Wî zimanekî nûjen, şêwazek civakî û ramîneke rexnegir daye',
          'Berhemên wî kin in û tenê tê de mijara welat heye',
          'Mîrasa wî ne wêdetir helbestên neteweyî ye',
        ],
        ci: 1,
        note: 'Cegerxwîn: sadece ulusal temalar değil — modern dil, toplumsal üslûp, eleştirel düşünce.'),
      _speak(id: 'c2_l05_e6',
        ku: 'Mîrasa Cegerxwîn di nav edebiyata nûjen a kurdî de bingehek e. Helbestên wî bandorê dikin li ser nifşên nû.',
        tr: 'Cegerxwîn\'in mirası modern Kürt edebiyatında bir temeldir. Şiirleri yeni nesilleri etkiler.'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // BİRİM 2 — Etnolenguîstîk û Zarave (3 ders)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'c2_l06',
    kurmanjTitle: 'Zaravayên Kurdî: Kurmancî, Behdînî, Serhedî',
    turkishTitle: 'Kürt Lehçeleri: Kurmancî, Behdînî, Serhedî',
    unitNumber: 2, lessonNumber: 1, level: 6,
    path: LessonPath.general,
    targetCardIds: _c2Cards(['ziman', 'akademik']).take(8).toList(),
    estimatedMinutes: 13, emoji: '🌐',
    exercises: [
      _mc(id: 'c2_l06_e1',
        ku: 'Kîjan zarave ji zimanê Kurdî ye lê Kurmancî NE ye?',
        tr: 'Kurmancî olmayan lehçe',
        opts: ['Hewramî', 'Zazakî-Dimilî', 'Her sê jî', 'Soranî'],
        ci: 2,
        note: 'Kürtçe ailesi: Kurmancî + Soranî + Zazakî + Hewramî + Kelhurî (grup içi sınıflama tartışmalı).'),
      _fill(id: 'c2_l06_e2', before: 'Kurmancî li bakur tê axaftin,', after: ' li başûr.',
        tr: 'Kurmancî kuzeyde, Soranî güneyde konuşulur.',
        opts: ['Soranî', 'Zazakî', 'Erebî', 'Behdînî'],
        ci: 0,
        note: 'Kurmancî (bakur) = Kuzey; Soranî (başûr) = Güney (Süleymaniye, Hewlêr).'),
      _mc(id: 'c2_l06_e3',
        ku: 'Behdînî li ku tê axaftin?',
        tr: 'Behdînî lehçe bölgesi',
        opts: [
          'Duhok û Hewlêr (Başûrê Kurdistanê)',
          'Tehran û Mehabad (Rojhilatê Kurdistanê)',
          'Rewan û herêma Kurdên Qafqasyayê',
          'Stembol û koçberên Kurd ên Diyasporayê',
        ],
        ci: 0,
        note: 'Behdînî: Kurmancî\'nin bir alt-zarave, Duhok ve Hewlêr bölgelerinde (Irak Kürdistanı).'),
      _fill(id: 'c2_l06_e4', before: 'Kurmancî di alfabeya', after: ' de nivîsandin dibe.',
        tr: 'Kurmancî Latin alfabesiyle yazılır.',
        opts: ['Arabî', 'Latînî (Hawar)', 'Farsî', 'Kirîlî'],
        ci: 1,
        note: 'Celadet Bedirxan 1932: Hawar alfabesi → Latin temelli Kurmancî.'),
      _mc(id: 'c2_l06_e5',
        ku: 'Ergatifî di kîjan zaraveyan de hîn jî xurt e?',
        tr: 'Ergatif yapı',
        opts: [
          'Her çar li hev wek in',
          'Tenê Soranî',
          'Kurmancî, Zazakî û Hewramî',
          'Tenê Farsî',
        ],
        ci: 2,
        note: 'Ergatif yapı geçmiş zamanda: Kurmancî, Zazakî (Dimilî) ve Hewramî/Gûranî\'de korunur. Standart Soranî ergatifi büyük ölçüde YİTİRMİŞTİR — pronominal ek sistemine geçmiştir (MacKenzie 1961; Haig 2008).'),
      _speak(id: 'c2_l06_e6',
        ku: 'Kurmancî, Soranî, Zazakî û Hewramî zimanên/zaraveyên kurdî ne. Her yek taybetmendiyên dengnasî û rêzimanî yên cuda hene.',
        tr: 'Kurmancî, Soranî, Zazakî ve Hewramî Kürt dili/lehçeleridir. Her biri farklı fonetik ve gramer özelliklerine sahiptir.'),
    ],
  ),

  LessonModel(
    id: 'c2_l07',
    kurmanjTitle: 'Standardkirina Kurmancî',
    turkishTitle: 'Kurmancî\'nin Standardizasyonu',
    unitNumber: 2, lessonNumber: 2, level: 6,
    path: LessonPath.general,
    targetCardIds: _c2Cards(['ziman', 'akademik']).skip(4).take(6).toList(),
    culturalRewardId: 'xani_1',
    estimatedMinutes: 13, emoji: '🔤',
    exercises: [
      _mc(id: 'c2_l07_e1',
        ku: 'Kî û kengî alfabeya Hawar afirandi ye?',
        tr: 'Alfabe tarihi',
        opts: [
          'Celadet Bedirxan, 1932',
          'Cegerxwîn, 1960',
          'Xanî, 1695',
          'Kamûran Bedirxan tenê',
        ],
        ci: 0,
        note: 'Hawar: Celadet Bedirxan, Şam\'da 1932 kurdu. Kardeşi Kamûran ile birlikte.'),
      _fill(id: 'c2_l07_e2', before: 'Standardkirina Kurmancî divê', after: ' zaraveyan rê neqerçîne.',
        tr: 'Kurmancî standardizasyonu lehçe çeşitliliğini engellememeli.',
        opts: ['hejmara', 'dengê', 'cihêrengiya', 'kurtahiya'],
        ci: 2,
        note: '"Cihêrengî" = çeşitlilik. Kurmancî standardizasyonu tartışması.'),
      _mc(id: 'c2_l07_e3',
        ku: '"Kurmanciya nivîsî" û "ya axavtî" ferqa wan çi ye?',
        tr: 'Yazılı - sözlü fark',
        opts: [
          'Nivîsî: yekgirtir, fermî, li ser bingeha Bedirxan; axavtî: cihêreng li gor herêman',
          'Nivîsî: bi pirjimar lê axavtî bi yekjimar tê bikaranîn',
          'Nivîsî: tenê di sedsala 21an de derketiye, axavtî kevin e',
          'Nivîsî: bi alfabeya Erebî, axavtî: bi alfabeya Latînî',
        ],
        ci: 0,
        note: 'Yazılı standart — Bedirxan normu. Sözlü — bölgesel varyasyonlar.'),
      _fill(id: 'c2_l07_e4', before: 'Di standardkirinê de', after: ' pêwîst e.',
        tr: 'Standardizasyonda esneklik gereklidir.',
        opts: ['dirêjî', 'hişkî', 'nermahî', 'navendî'],
        ci: 2,
        note: '"Nermahî" = esneklik. Tek tip zorlaması değil — ortak norm + lehçe kabul.'),
      _mc(id: 'c2_l07_e5',
        ku: 'Kîjan sazî îro li ser standardkirina Kurmancî dixebite?',
        tr: 'Standardizasyon kurumları',
        opts: [
          'Tenê nivîskar û rojnamevanên kesane bi serê xwe',
          'Tu sazî pê re mijûl nabe, kar bi taybetî nayê meşandin',
          'Enstîtuya Kurdî ya Parîs, Kurd-Akad, û çend zanîngehên cuda',
          'Hukûmetên fermî yên dewletên herêmê bi tenê',
        ],
        ci: 2,
        note: 'Enstîtuya Kurdî (Paris 1983), Kurd-Akad, zanîngeh — dil standardizasyonu kurumları.'),
      _speak(id: 'c2_l07_e6',
        ku: 'Standardkirina Kurmancî li ser bingeha alfabeya Hawar ava bû. Divê nermahî û cihêrengî bên parastin.',
        tr: 'Kurmancî standardı Hawar alfabesi temelinde kuruldu. Esneklik ve çeşitlilik korunmalıdır.'),
    ],
  ),

  LessonModel(
    id: 'c2_l08',
    kurmanjTitle: 'Neolojîzm û Pêşketina Ziman',
    turkishTitle: 'Neolojizm ve Dil Gelişimi',
    unitNumber: 2, lessonNumber: 3, level: 6,
    path: LessonPath.general,
    targetCardIds: _c2Cards(['ziman', 'zanist']).take(8).toList(),
    estimatedMinutes: 12, emoji: '🆕',
    exercises: [
      _mc(id: 'c2_l08_e1',
        ku: '"Neolojîzm" çi ye?',
        tr: 'Doğru tanımı bul',
        opts: [
          'Peyvên pir kevn ên ku ji rojanê derketine û nayên bikaranîn',
          'Biçûkkirina hejmara peyvên ferhengê bi rêya rakirina hin têgehan',
          'Şîrovekirina maneya peyvan li gor çandê û dîrokê',
          'Peyvên nû yên ku tên çêkirin ji bo têgehên hemdem',
        ],
        ci: 3,
        note: 'Neolojizm: yeni terim üretimi — modern kavramlar için.'),
      _fill(id: 'c2_l08_e2', before: '"Komputer" peyveke', after: ' ye di Kurmancî de; hinek dibêjin "rayaner".',
        tr: '"Komputer" Kurmancî\'de yabancı bir terimdir; bazıları "rayaner" der.',
        opts: ['kevn', 'neteweyî', 'çandî', 'biyanî'],
        ci: 3,
        note: '"Biyanî" = yabancı. Alıntı - neolojizm tartışması.'),
      _mc(id: 'c2_l08_e3',
        ku: 'Awayên neolojîzmê çi ne?',
        tr: 'Neolojizm yöntemleri',
        opts: [
          'Tenê hilberandina çîrok',
          'Werger, hevedudanî (nav + nav), lêkera + pêvek, zindîkirina peyvên kevn',
          'Bê awa',
          'Tenê werger',
        ],
        ci: 1,
        note: 'Neolojizm yolları: çeviri, bileşik, türeme, eski kelimelerin canlandırılması.'),
      _fill(id: 'c2_l08_e4', before: 'Peyva "zanîngeh" (zanîn + geh)', after: ' e.',
        tr: '"Zanîngeh" kelimesi bir bileşiktir.',
        opts: ['biyanî', 'hevedudanî', 'kêm', 'basît'],
        ci: 1,
        note: '"Zanîngeh" = bilgi + yer = üniversite. Bileşik neolojizm.'),
      _mc(id: 'c2_l08_e5',
        ku: 'Pirsgirêkeke sereke ya neolojîzmê çi ye?',
        tr: 'Ana sorun',
        opts: [
          'Bêpirsgirêkî',
          'Qebûlkirina peyvan ji hêla gel û standardbûna wan',
          'Ne têkildarî zimanê civakê',
          'Pir hêsan e',
        ],
        ci: 1,
        note: 'Sorun: neolojizmin halk tarafından benimsenmesi. Zorlama neolojizmler reddedilir.'),
      _speak(id: 'c2_l08_e6',
        ku: 'Neolojîzm pêwîst e ji bo hemdemkirina zimanê Kurdî. Lê divê peyvên nû bi awayekî xwezayî di nav gel de belav bibin.',
        tr: 'Neolojizm Kürtçe\'nin çağdaşlaştırılması için gereklidir. Ama yeni sözcükler halk içinde doğal olarak yayılmalıdır.'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // BİRİM 3 — Klasîkê Devrê (3 ders)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'c2_l09',
    kurmanjTitle: 'Feqiyê Teyran: Destana Şeyxê Senan',
    turkishTitle: 'Feqiyê Teyran: Şeyh San\'an Destanı',
    unitNumber: 3, lessonNumber: 1, level: 6,
    path: LessonPath.cultural,
    targetCardIds: _c2Cards(['edebiyat']).take(8).toList(),
    culturalRewardId: 'feqî_1',
    estimatedMinutes: 13, emoji: '🦅',
    exercises: [
      _mc(id: 'c2_l09_e1',
        ku: 'Di destana Şeyxê Senan de kîjan rûdan bingehî ye?',
        tr: 'Temel olay',
        opts: [
          'Evîna Şeyxê sofî yê musulman ji keçekê xiristîan',
          'Têkoşîna padîşahekî ji bo parastina textê xwe',
          'Seyahetên bazirganî yên rê û çiyayên Rojhilatê',
          'Şerê di navbera du qebîleyên Kurd ên hevûdu de',
        ],
        ci: 0,
        note: 'Şeyh San\'an destanı: inançlararası aşk → tasavvufî dönüşüm.'),
      _mc(id: 'c2_l09_e2',
        ku: 'Destana Şeyxê Senan kîjan peyama tesewufî dide?',
        tr: 'Tasavvuf mesajı',
        opts: [
          'Di evîna îlahî de xwe winda kirin (fena)',
          'Berhevkirina malê dinyayê',
          'Şerê dînan',
          'Red kirina evînê',
        ],
        ci: 0,
        note: '"Fena" = ilahi aşkta benliğin yitirilmesi. Şeyh San\'an bu tasavvuf yolunu örnekler. Arapça kökenli "fena" klasik Kurmancî\'de korunmuştur.'),
      _fill(id: 'c2_l09_e3', before: 'Şeyx ji bo evîna keçikê xiristîan dev ji', after: ' berdide.',
        tr: 'Şeyh, Hıristiyan kızın aşkı için inançsal formalitelerden vazgeçer.',
        opts: ['malê xwe', 'rîtuelê dînî', 'karê xwe', 'serçav'],
        ci: 1,
        note: '"Rîtuelê dînî" = dinî formalite. Sûfî içsellik dış formaliteye üstün.'),
      _mc(id: 'c2_l09_e4',
        ku: 'Destan bi çi dawî dibe?',
        tr: 'Destan sonu',
        opts: [
          'Bi şerekî tund di navbera xelkê du dînan de',
          'Bi vegera Şeyx bo riya xwe û îslambûna keçikê bi kerameta evînê',
          'Bi mirina lehengan û têkçûna evîna wan a mutleq',
          'Bi hilxistina Şeyx ji aliyê alimên zahirî yên dînî',
        ],
        ci: 1,
        note: 'Klasik son: tasavvufi dönüşüm — kız iman eder, Şeyh yolunu bulur.'),
      _fill(id: 'c2_l09_e5', before: 'Feqiyê Teyran bi zimanê', after: ' diyalogan dike.',
        tr: 'Feqiyê Teyran kuşların diliyle diyaloglar kurar.',
        opts: ['teyran', 'çivîkan', 'ba û av', 'mirovan'],
        ci: 0,
        note: 'Feqiyê Teyran\'ın şairane sembolü: "kuşların dili" = sûfî-mistik iletişim.'),
      _speak(id: 'c2_l09_e6',
        ku: 'Destana Şeyxê Senan a Feqiyê Teyran mînaka têgihîştî ya edebiyata tesewufî ye. Evîn, fena û berxwedan di navenda vê çîrokê de ne.',
        tr: 'Feqiyê Teyran\'ın Şeyh San\'an destanı tasavvuf edebiyatının bilgece bir örneğidir. Aşk, fena ve direniş bu hikayenin merkezindedir.'),
    ],
  ),

  LessonModel(
    id: 'c2_l10',
    kurmanjTitle: 'Hacî Qadirê Koyî',
    turkishTitle: 'Haci Qadirê Koyî',
    unitNumber: 3, lessonNumber: 2, level: 6,
    path: LessonPath.cultural,
    targetCardIds: _c2Cards(['edebiyat', 'kimlik']).take(6).toList(),
    estimatedMinutes: 12, emoji: '📕',
    exercises: [
      _mc(id: 'c2_l10_e1',
        ku: 'Hacî Qadirê Koyî (1817–1897) kî ye?',
        tr: 'Doğru tanımı bul',
        opts: [
          'Mîrê Botanê yê sedsala 19, parêzgerê edaleta civakê',
          'Helbestvanê neteweperwer ê kurd, pêşrewa neteweperweriya kurdî',
          'Şêxê tarîqeta Neqşbendî yê herêma Mêrdînê',
          'Mamosteyê dînî yê Diyarbekirê û hostayê fiqhê',
        ],
        ci: 1,
        note: 'Koyî: 19. yy Kürt ulusal uyanışının öncü şairi. Soranî yazdı ama etkisi Kurmancî\'ye de ulaştı.'),
      _fill(id: 'c2_l10_e2', before: 'Koyî bi', after: ' dinivîsand.',
        tr: 'Koyî Soranî yazdı.',
        opts: ['Erebî', 'Soranî', 'Kurmancî', 'Farsî'],
        ci: 1,
        note: 'Koyî Güney Kürt merkezinde (Koya) doğdu, Soranî\'nin klasik şairi.'),
      _mc(id: 'c2_l10_e3',
        ku: 'Peyama bingehî ya Koyî çi bû?',
        tr: 'Ana mesajı',
        opts: [
          'Pesnê pergala şahînşahî û rêvebiriya kevneşopî',
          'Yekîtiya neteweyî û bêdewletiya Kurdan',
          'Bi tenê mijara evîna kesane û lîrîzma romantîk',
          'Pêşkeftina zanistên fenî û teknolojiya nûjen',
        ],
        ci: 1,
        note: '"Bêdewletî" = devletsizlik (bê + dewlet + î). Koyî: ulusal birlik çağrısı, Xanî\'nin 17. yy teşhisinin 19. yy devamı.'),
      _mc(id: 'c2_l10_e4',
        ku: 'Koyî bi kîjan peyvê Kurdan bang dike bîdariyê?',
        tr: 'Koyî\'nin uyanış çağrı sözcüğü',
        opts: ['Biçe!', 'Bisekine!', 'Rabe!', 'Razê!'],
        ci: 2,
        note: 'Koyî\'nin uyanış çağrısı: "Rabe!" = Kalk! Kürtlere ulusal uyanış daveti.'),
      _mc(id: 'c2_l10_e5',
        ku: 'Koyî çawa bandor kiriye li ser helbestvanên paşî?',
        tr: 'Etkisi',
        opts: [
          'Tenê wek modelek bazirganî ya nivîskariya populer',
          'Bandora wî bêsedem û rasthatî bû, ne plansaz',
          'Ew modela helbesta siyasî-neteweyî yan jî "bîdarî" ye',
          'Tu bandorek wî li ser helbestvanên dûma tunebû',
        ],
        ci: 2,
        note: 'Koyî "bîdarî" (uyanış) şiirinin prototipi — Cegerxwîn\'in de öncüsü.'),
      _speak(id: 'c2_l10_e6',
        ku: 'Hacî Qadirê Koyî bi Soranî pêşengiya hişyariya neteweyî kir. Mîrasa wî têkildarî Cegerxwîn e.',
        tr: 'Haci Qadirê Koyî Soranî\'yle ulusal uyanışın (bîdarî) öncüsü oldu. Mirası Cegerxwîn ile bağlantılıdır.'),
    ],
  ),

  LessonModel(
    id: 'c2_l11',
    kurmanjTitle: 'Edebiyata Gel: Dengbêjî',
    turkishTitle: 'Halk Edebiyatı: Dengbêjlik',
    unitNumber: 3, lessonNumber: 3, level: 6,
    path: LessonPath.cultural,
    targetCardIds: _c2Cards(['çand', 'edebiyat']).skip(4).take(6).toList(),
    culturalRewardId: 'cegerxwin_3',
    estimatedMinutes: 12, emoji: '🎶',
    exercises: [
      _ls(id: 'c2_l11_e1',
        ku: 'Dengbêj',
        tr: 'Ne anlama geliyor?',
        opts: [
          'Stranbêjek nûjen ê ku bi muzîka elektronîk distirîne',
          'Nûçegihanê radyoyê yê ku rojane agahiyan diragihîne',
          'Stranbêjê gel ê kevneşopî, ku bê enstrûman kilam dibêje',
          'Helbestvanê nûjen ê ku berhemên xwe çap dike',
        ],
        ci: 2,
        note: 'Dengbêj: geleneksel Kürt halk şarkıcısı — enstrümansız, sözle anlatıcı.'),
      _mc(id: 'c2_l11_e2',
        ku: 'Rola dengbêj di civatê de çi bû?',
        tr: 'Toplumsal işlev',
        opts: [
          'Payebilindî',
          'Kar û barî',
          'Tenê şenlik',
          'Parastina dîrok, çîrok û zimanê gel bi rêya devkî',
        ],
        ci: 3,
        note: 'Dengbêjlik: oral tarih + edebiyat + dil koruması. Yazısız dönemde kritik.'),
      _fill(id: 'c2_l11_e3', before: 'Kilamên dengbêjan di destpêkê de bê', after: ' bûn.',
        tr: 'Dengbêj şarkıları başlangıçta enstrümansızdı.',
        opts: ['mûsîqa', 'deng', 'sebebekê', 'enstrûman'],
        ci: 3,
        note: 'Geleneksel dengbêjlik: a cappella — ses olanakları ön planda.'),
      _mc(id: 'c2_l11_e4',
        ku: 'Dengbêjên navdar ên sedsala 20an kî ne?',
        tr: 'Ünlü dengbêjler',
        opts: [
          'Cegerxwîn, Bedirxan, Hawar, Mem û Zîn',
          'Ehmedê Xanî, Melayê Cizîrî, Feqiyê Teyran',
          'Ehmed Mîrazî, Mîr Celadet, Kamûran Bedirxan',
          'Şakiro, Karapetê Xaço, Ayşe Şan, Reşîdê Baso',
        ],
        ci: 3,
        note: 'Şakiro (1936-1996), Karapetê Xaço, Ayşe Şan, Reşîdê Baso — 20. yy dengbêj kanonu.'),
      _fill(id: 'c2_l11_e5', before: 'Dengbêjî îro li', after: ' jî tê hînkirin.',
        tr: 'Dengbêjlik bugün üniversitelerde de öğretiliyor.',
        opts: ['zanîngehan', 'dibistanê', 'bazarê', 'malê'],
        ci: 0,
        note: 'Modern Kürt çalışmaları: dengbêjlik akademik kategoriye dahil oldu.'),
      _speak(id: 'c2_l11_e6',
        ku: 'Dengbêj zêrîngên dîrok û zimanê gel in. Bêyî wan, gelek çîrok û kilamên Kurdî winda bûbûn.',
        tr: 'Dengbêjler halk tarihinin ve dilinin hazinesidir. Onlar olmasaydı pek çok Kürt hikayesi ve şarkısı kaybolurdu.'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // BİRİM 4 — Ramana Rexnegir (2 ders)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'c2_l12',
    kurmanjTitle: 'Dîskûr û Desthilat',
    turkishTitle: 'Söylem ve İktidar',
    unitNumber: 4, lessonNumber: 1, level: 6,
    path: LessonPath.general,
    targetCardIds: _c2Cards(['felsefe', 'medya']).take(8).toList(),
    estimatedMinutes: 13, emoji: '🔎',
    exercises: [
      _mc(id: 'c2_l12_e1',
        ku: 'Michel Foucault li ser kîjan têkiliyê kûr dixebite?',
        tr: 'Foucault ana teması',
        opts: [
          'Zanîn-desthilat (knowledge-power)',
          'Têkiliya muzîkê û jiyana civakî (etnomûzîkolojî)',
          'Felsefeya evînê di edebiyata romantîk de',
          'Aboriya cotkariyê û pergalên hilberînê',
        ],
        ci: 0,
        note: 'Foucault: "knowledge is power" — bilgi/iktidar ayrılmaz.'),
      _fill(id: 'c2_l12_e2', before: 'Dîskûr tenê peyv nîne, ew', after: ' jî dibe.',
        tr: 'Söylem yalnızca söz değildir, aynı zamanda iktidar biçimidir.',
        opts: ['dîrok', 'stran', 'xewn', 'desthilat'],
        ci: 3,
        note: '"Dîskûra desthilatê" = iktidar söylemi. Foucault kavramı.'),
      _mc(id: 'c2_l12_e3',
        ku: '"Analîza dîskûrê" çi ye?',
        tr: 'Söylem analizi',
        opts: [
          'Tenê xwendina metnê',
          'Lêkolîna dîrokî',
          'Analîza aborî',
          'Vekolîna têkiliya peyv û desthilatê di metnan de',
        ],
        ci: 3,
        note: 'Discourse analysis: metinlerin iktidar ilişkileriyle incelenmesi. Fairclough, Van Dijk.'),
      _fill(id: 'c2_l12_e4', before: 'Dîskûr', after: ' diafirîne.',
        tr: 'Söylem özneyi yaratır.',
        opts: ['kirdeyê', 'bi bûyerê', 'bi nasnameyê', 'tenê peyvê'],
        ci: 0,
        note: 'Foucault: "discourse produces the subject". "Kirde" = özne. "Dîskûr kirdeyê diafirîne" — nesne doğrudan oblique, edat yok.'),
      _mc(id: 'c2_l12_e5',
        ku: 'Kîjan ramîn Foucault û Said hevparkirin?',
        tr: 'Foucault-Said ortak tema',
        opts: [
          'Evîna romatîk',
          'Aboriya kapîtalîst',
          'Têkilîya zanîn-desthilat û temsîlê',
          'Matematîk',
        ],
        ci: 2,
        note: 'Foucault: knowledge/power. Said: bu çerçeveyi "Orient" temsili için uyguladı.'),
      _speak(id: 'c2_l12_e6',
        ku: 'Dîskûr û desthilat girêdayî ne. Analîza dîskûrê nîşan dide peyv çawa nasnameyê û rastiyan diafirîne.',
        tr: 'Söylem ve iktidar birbirine bağlıdır. Söylem analizi, sözün kimliği ve gerçekleri nasıl yarattığını gösterir.'),
    ],
  ),

  LessonModel(
    id: 'c2_l13',
    kurmanjTitle: 'Medya û Pêkhatina Rastiyê',
    turkishTitle: 'Medya ve Gerçek İnşası',
    unitNumber: 4, lessonNumber: 2, level: 6,
    path: LessonPath.general,
    targetCardIds: _c2Cards(['medya', 'felsefe', 'psikoloji']).take(8).toList(),
    estimatedMinutes: 12, emoji: '📺',
    exercises: [
      _mc(id: 'c2_l13_e1',
        ku: 'Li gor Baudrillard, di serdema nûjen de çi bûye?',
        tr: 'Baudrillard tezi',
        opts: [
          'Rastî di sedsala 17 bû',
          'Rastî xurttir e',
          'Rastî bi simulasyonê ve têkel bûye (hîperrastî)',
          'Rastî tu carê nîne',
        ],
        ci: 2,
        note: 'Baudrillard: "hyperreality" — simülasyon gerçeği yutar. Postmodern medya teorisi.'),
      _fill(id: 'c2_l13_e2', before: 'Medyaya modern', after: ' çêdike, ne ku tenê nîşan dide.',
        tr: 'Modern medya yalnız göstermiyor, gerçekliği inşa ediyor.',
        opts: ['deng', 'dîrok', 'wêne', 'rastiyê'],
        ci: 3,
        note: '"Avakirina rastiyê" = gerçek inşası. Sosyal konstrüktivizm.'),
      _mc(id: 'c2_l13_e3',
        ku: '"Fake news" di pergala hîperrastiyê de çi dike?',
        tr: 'Sahte haberlerin rolü',
        opts: [
          'Rastiya bûyeran bi delîlên berbiçav xurt dike',
          'Pêvajoya aştiyê di navbera dewletan de bi pêş dixe',
          'Cudahiya navbera rast û derew qels dike',
          'Bandorek nedixuye li ser têgihîştina civakê dike',
        ],
        ci: 2,
        note: 'Fake news: gerçek/yalan ayrımını erozyona uğratır. Postmodern medya krizi.'),
      _fill(id: 'c2_l13_e4', before: 'Raya giştî di bin', after: ' medyaya civakî de ye.',
        tr: 'Kamuoyu sosyal medyanın etkisi altındadır.',
        opts: ['bandora', 'dûrî', 'xewê', 'bêwate'],
        ci: 0,
        note: '"Di bin bandora" = ... etkisi altında. Medya sosyolojisi.'),
      _mc(id: 'c2_l13_e5',
        ku: 'Ramîna rexnegir a medyayê çi dike?',
        tr: 'Eleştirel medya düşüncesi',
        opts: [
          'Qebûla pasîf',
          'Pirskirin: Kî weşand? Ji bo çi? Kîjan perspektîv hat veşartin?',
          'Bêhişî',
          'Dûrketina ji medya',
        ],
        ci: 1,
        note: 'Eleştirel medya okuryazarlığı: kaynak, amaç, gizli perspektif sorgulaması.'),
      _speak(id: 'c2_l13_e6',
        ku: 'Medyaya modern rastiyê diafirîne. Ramîna rexnegir ji bo têgihîştina vê pêvajoyê pêwîst e.',
        tr: 'Modern medya gerçeği inşa eder. Bu süreci anlamak için eleştirel düşünce gereklidir.'),
    ],
  ),

  // ─────────────────────────────────────────────────────────────
  // BİRİM 5 — Berhev Nivîsîn (2 ders — Rêya Malê)
  // ─────────────────────────────────────────────────────────────

  LessonModel(
    id: 'c2_l14',
    kurmanjTitle: 'Vekolîna Edebî Berhevkar',
    turkishTitle: 'Karşılaştırmalı Edebiyat Analizi',
    unitNumber: 5, lessonNumber: 1, level: 6,
    path: LessonPath.heritage,
    targetCardIds: _c2Cards(['edebiyat', 'akademik']).take(6).toList(),
    estimatedMinutes: 13, emoji: '📊',
    exercises: [
      _mc(id: 'c2_l14_e1',
        ku: 'Di edebiyata berhevkar de çi tê kirin?',
        tr: 'Karşılaştırmalı yaklaşım',
        opts: [
          'Pirsên dînî yên teolojîk ji bo şîrovekirina vehiyê',
          'Bi tenê jiyanname ya nivîskêr tê lêkolînkirin',
          'Yek berhem tê xwendin bê referansa berhemên din',
          'Du yan zêdetir berhem ji cihên cuda tên hevberdan, hevparî û cudahî tên dîtin',
        ],
        ci: 3,
        note: 'Comparative literature: birden çok eseri / kültürü yan yana koyup benzer-fark analiz.'),
      _fill(id: 'c2_l14_e2', before: 'Mem û Zîn û Leyla û Mecnûn', after: ' hene.',
        tr: 'Mem û Zîn ve Leyla ile Mecnûn\'un ortak temaları var.',
        opts: ['tirsa', 'cudahî', 'hevparî', 'şerê'],
        ci: 2,
        note: 'Mem û Zîn ↔ Leyla ile Mecnûn: ayrılık aşkı teması ortak.'),
      _mc(id: 'c2_l14_e3',
        ku: 'Fonksîyona analîza berhevkar çi ye?',
        tr: 'Analiz işlevi',
        opts: [
          'Bazarîkirin',
          'Dîtina motîfên mîtîk-edebî yên gerdûnî û herêmî',
          'Biyografî',
          'Şîrove bê rê',
        ],
        ci: 1,
        note: 'Karşılaştırmalı analiz: evrensel vs bölgesel edebi motiflerin tespiti.'),
      _fill(id: 'c2_l14_e4', before: 'Di edebiyata Rojhilata Navîn de têgeha "evîn" bi', after: ' tê temsîlkirin.',
        tr: 'Ortadoğu edebiyatında aşk kavramı tasavvuf ile temsil edilir.',
        opts: ['tesewufê', 'aboriyê', 'şerê', 'dibistanê'],
        ci: 0,
        note: 'Ortak motif: tasavvufi aşk — Fars, Arap, Kürt, Türk edebiyatlarında ortak mistik dil.'),
      _mc(id: 'c2_l14_e5',
        ku: 'Rêbaza berhevkar ji bo çi pêwîst e?',
        tr: 'Neden gerekli',
        opts: [
          'Ne pêwîst e',
          'Tenê ji bo hindikahiyê',
          'Ji bo nîşandana edebiyata kurdî di çarçoveya cîhanî de û pejirandina hêza wê',
          'Nirx nîne',
        ],
        ci: 2,
        note: 'Kürt edebiyatını dünya kanonunda konumlandırmak — akademik meşruiyet.'),
      _speak(id: 'c2_l14_e6',
        ku: 'Vekolîna berhevkar xêzên girîng ên edebiyata kurdî di navbera gelemperî û kurdî de kifş dike. Ev awa ji bo akademîkbûna kurdînasiyê pêwîst e.',
        tr: 'Karşılaştırmalı araştırma Kürt edebiyatının önemli çizgilerini genel ve Kürt bağlamında keşfeder. Bu yaklaşım Kürdoloji\'nin akademikleşmesi için gereklidir.'),
    ],
  ),

  LessonModel(
    id: 'c2_l15',
    kurmanjTitle: 'Nivîsandina Tezê Doktora',
    turkishTitle: 'Doktora Tezi Yazımı',
    unitNumber: 5, lessonNumber: 2, level: 6,
    path: LessonPath.heritage,
    targetCardIds: _c2Cards(['akademik']).take(6).toList(),
    culturalRewardId: 'proverb_1',
    estimatedMinutes: 14, emoji: '🎓',
    exercises: [
      _mc(id: 'c2_l15_e1',
        ku: 'Parçeyên sereke yên tezê doktora çi ne?',
        tr: 'Doktora tezi bölümleri',
        opts: [
          'Pêşgotin - bîyografî - şîroveya kesane',
          'Tenê destpêk û pêşgotin, bê encam an analîz',
          'Tenê encam û berhevkirina dawîn, bê pêşgotin',
          'Destpêk - rêbaz - vekolîna berê - encam - çavkanî',
        ],
        ci: 3,
        note: 'Doktora tezi: Giriş, Metodoloji, Literatür Taraması, Bulgular, Sonuç, Kaynakça.'),
      _fill(id: 'c2_l15_e2', before: 'Pirsa bingehî ya', after: ' divê zelal û teng be.',
        tr: 'Araştırmanın temel sorusu açık ve dar/odaklı olmalıdır.',
        opts: ['bazarî', 'aboriyê', 'hewayê', 'lêkolînê'],
        ci: 3,
        note: '"Pirsa lêkolînê" = araştırma sorusu (research question). "Zelal û teng" = net ve odaklı.'),
      _mc(id: 'c2_l15_e3',
        ku: '"Rêbaz" (methodology) çi vedibêje?',
        tr: 'Metodoloji içeriği',
        opts: [
          'Pejirandina aboriya gundewar a kevneşopî di lêkolînê de',
          'Vegotina dîroka bûyeran tenê bi awayekî kronolojîk',
          'Vegotina çîrokên gelêrî yên devkî yên neteweyî',
          'Rêgezên ku lêkolîner bi kar tîne: analîz, berhevkarî, hevpeyvîn, statîstîk',
        ],
        ci: 3,
        note: 'Metodoloji: kullanılan araştırma yöntemleri (analiz, karşılaştırma, mülakat, istatistik) + gerekçelendirme.'),
      _fill(id: 'c2_l15_e4', before: 'Ji bo etîka akademîk divê mirov ji', after: ' dûr bisekine.',
        tr: 'Akademik etik için intihalden uzak durmak gerekir.',
        opts: ['çavkaniyê', 'bîyografiyê', 'dizîna-nivîsê (plagiarism)', 'bazarî'],
        ci: 2,
        note: '"Dizîna-nivîsê" = intihal (metin hırsızlığı). Akademik etiğin en temel yasağıdır — plagiarism.'),
      _mc(id: 'c2_l15_e5',
        ku: 'Di tezê de "tevkarî" (contribution) çi ye?',
        tr: 'Katkı alanı',
        opts: [
          'Bêgiringî',
          'Beşdariyeke nû ya ku zanîna heyî zêde dike',
          'Dubarekirin',
          'Ravekirin',
        ],
        ci: 1,
        note: '"Tevkarî" = contribution (orijinal katkı). Doktora tezinin olmazsa olmazı. "Zanîna heyî" = mevcut bilgi.'),
      _speak(id: 'c2_l15_e6',
        ku: 'Nivîsandina teza doktorayê karekî hişmend e. Pirs zelal, rêbaz şeffaf û tevkarî orîjînal divê bin. Ev pêvajo sebrê dixwaze.',
        tr: 'Doktora tezi yazımı bilinçli bir iştir. Soru net, metot şeffaf, katkı özgün olmalıdır. Bu süreç sabır ister.'),
    ],
  ),
];
