// LÛTKE — Kurmancî Konuşma Alıştırmaları Veritabanı
// 60 egzersiz: pronunciation (20), repeat (20), respond (10), read_aloud (10)
// Seviye dağılımı: A1 (25), A2 (20), B1 (10), B2 (5)

class KuSpeakingExercise {
  final String id;
  final String level; // A1, A2, B1, B2, C1
  final String type; // 'pronunciation', 'repeat', 'respond', 'read_aloud'
  final String textKu; // Söylenecek Kurmancî
  final String ipa; // IPA telaffuz
  final String promptTr; // Türkçe talimat (KU-TR modda)
  final String tipKu; // Kurmancî ipucu (telaffuz zorluğu)
  final String tipTr; // Türkçe ipucu
  final List<String>? acceptableVariants;

  const KuSpeakingExercise({
    required this.id,
    required this.level,
    required this.type,
    required this.textKu,
    required this.ipa,
    required this.promptTr,
    required this.tipKu,
    required this.tipTr,
    this.acceptableVariants,
  });
}

const List<KuSpeakingExercise> kKuSpeakingExercises = [
  // ========== PRONUNCIATION (20) — A1-A2 ==========

  // Ç sesi (tʃ) — Türkçe ç'den biraz daha sert
  KuSpeakingExercise(
    id: 'ku_speak_001',
    level: 'A1',
    type: 'pronunciation',
    textKu: 'Çay',
    ipa: '/tʃaj/',
    promptTr: 'Söyle: "Çay"',
    tipKu: 'Ç: dengê "ch" ya Îngilîzî ye, wek "cheap". Zimanê xwe li pişt diranan bigre.',
    tipTr: 'Ç sesi İngilizce "ch" (cheap) gibi. Türkçe "ç"den biraz daha sert ve hafif aspiratlı.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_002',
    level: 'A1',
    type: 'pronunciation',
    textKu: 'Çar',
    ipa: '/tʃaːɾ/',
    promptTr: 'Söyle: "Çar" (dört)',
    tipKu: 'Ç-A-R: "a" dirêj bilêv bike. Ç ne wek tirkî, hinekî zêde dengdar.',
    tipTr: 'Ç-A-R: "a" biraz uzun. Ç sesi Türkçe "ç"den biraz daha güçlü.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_003',
    level: 'A1',
    type: 'pronunciation',
    textKu: 'Çav',
    ipa: '/tʃaːv/',
    promptTr: 'Söyle: "Çav" (göz)',
    tipKu: 'Ç dengê hişk, "v" wek "v" ya tirkî. "Çav" = çav.',
    tipTr: 'Ç sert, "v" Türkçe "v" gibi. "Çav" = göz demektir.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_004',
    level: 'A1',
    type: 'pronunciation',
    textKu: 'Çiya',
    ipa: '/tʃiːja/',
    promptTr: 'Söyle: "Çiya" (dağ)',
    tipKu: 'Ç + î (dirêj) + ya. Î wek "ee" ya Îngilîzî.',
    tipTr: 'Ç + uzun î + ya. Î sesi İngilizce "ee" (see) gibi uzun.',
  ),

  // Ş sesi (ʃ)
  KuSpeakingExercise(
    id: 'ku_speak_005',
    level: 'A1',
    type: 'pronunciation',
    textKu: 'Şev',
    ipa: '/ʃɛv/',
    promptTr: 'Söyle: "Şev" (gece)',
    tipKu: 'Ş wek "sh" ya Îngilîzî, wek "she". E: kurt.',
    tipTr: 'Ş sesi Türkçe "ş" ile aynı. "Şev" = gece. E kısa.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_006',
    level: 'A1',
    type: 'pronunciation',
    textKu: 'Şîr',
    ipa: '/ʃiːɾ/',
    promptTr: 'Söyle: "Şîr" (süt)',
    tipKu: 'Ş + î (dirêj) + r. Î dirêj wek "ee".',
    tipTr: 'Ş + uzun î + r. Î uzun "ii" sesi (şiiir gibi uzatarak).',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_007',
    level: 'A1',
    type: 'pronunciation',
    textKu: 'Şahî',
    ipa: '/ʃaːhiː/',
    promptTr: 'Söyle: "Şahî" (düğün/şenlik)',
    tipKu: 'Ş-A-H-Î: du kîte. "H" bilêv bike, nehêle bêdeng.',
    tipTr: 'Ş-A-H-Î: iki heceli. "H" sesini yutma, net söyle. Î uzun.',
  ),

  // X sesi (x) — velar fricative, Almanca "Bach"taki ch
  KuSpeakingExercise(
    id: 'ku_speak_008',
    level: 'A1',
    type: 'pronunciation',
    textKu: 'Xalê',
    ipa: '/xaːlɛː/',
    promptTr: 'Söyle: "Xalê" (dayı)',
    tipKu: 'X: dengê kelandinê ye, wek "ch" ya almanî di "Bach" de. Ne wek "h" ya tirkî.',
    tipTr: 'X sesi Almanca "Bach"taki ch gibi, gırtlaktan sürtünmeli. Türkçe "h"den farklı, daha derin.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_009',
    level: 'A1',
    type: 'pronunciation',
    textKu: 'Xwîn',
    ipa: '/xwiːn/',
    promptTr: 'Söyle: "Xwîn" (kan)',
    tipKu: 'X + w + î + n. "Xw" bi hev re, wek "xw" ya xwendinê. Î dirêj.',
    tipTr: 'X + w + uzun î + n. "Xw" birlikte söylenir. "Huuiiin" değil, "xwiiin" — X gırtlaktan.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_010',
    level: 'A2',
    type: 'pronunciation',
    textKu: 'Xweş',
    ipa: '/xwɛʃ/',
    promptTr: 'Söyle: "Xweş" (güzel/hoş)',
    tipKu: 'Xw + e + ş. Xw bi hev, wek destpêka "xweş-hatinî".',
    tipTr: 'Xw + e + ş. "Xw" birlikte, gırtlaktan başla. "Hoş" değil, "xweş".',
  ),

  // Q sesi (q) — uvular, gırtlak arkasından
  KuSpeakingExercise(
    id: 'ku_speak_011',
    level: 'A1',
    type: 'pronunciation',
    textKu: 'Qehwe',
    ipa: '/qɛhwɛ/',
    promptTr: 'Söyle: "Qehwe" (kahve)',
    tipKu: 'Q: ne wek "k", li pişta zimên ji paşî tê. Wek Erebî "qaf".',
    tipTr: 'Q sesi "k"dan farklı, dil arkası gırtlağa değer. Arapça "qaf" gibi. "Kahve" değil, "qehwe".',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_012',
    level: 'A1',
    type: 'pronunciation',
    textKu: 'Qederê',
    ipa: '/qɛdɛɾɛː/',
    promptTr: 'Söyle: "Qederê" (kadar)',
    tipKu: 'Q-E-D-E-R-Ê: sê kîte. Q ji pişta zimên, Ê ya dawî dirêj.',
    tipTr: 'Q-E-D-E-R-Ê: üç heceli. Q gırtlaktan, son Ê uzun "ee".',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_013',
    level: 'A2',
    type: 'pronunciation',
    textKu: 'Qij',
    ipa: '/qɪʒ/',
    promptTr: 'Söyle: "Qij" (karga)',
    tipKu: 'Q + i (kurt) + j. "J" wek "j" ya fransî di "bonjour" de.',
    tipTr: 'Q gırtlaktan + kısa i + j (Fransızca bonjour\'daki j gibi). Türkçe "j" ile aynı.',
  ),

  // Ê sesi (ɛː) — uzun açık e
  KuSpeakingExercise(
    id: 'ku_speak_014',
    level: 'A1',
    type: 'pronunciation',
    textKu: 'Êvar',
    ipa: '/ɛːvaːɾ/',
    promptTr: 'Söyle: "Êvar" (akşam)',
    tipKu: 'Ê: "e" ya dirêj û vekirî, wek "ea" ya Îngilîzî di "bear".',
    tipTr: 'Ê uzun ve açık "e" sesi. "Evar" değil, "eeevar" — Ê uzun.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_015',
    level: 'A1',
    type: 'pronunciation',
    textKu: 'Çêlek',
    ipa: '/tʃɛːlɛk/',
    promptTr: 'Söyle: "Çêlek" (inek)',
    tipKu: 'Ç + Ê (dirêj) + l + e (kurt) + k. Ê û e cuda ne!',
    tipTr: 'Ç + UZUN Ê + lek. İlk Ê uzun, ikinci e kısa. "Çelek" değil, "çeeelek".',
  ),

  // Î sesi (iː) — uzun i
  KuSpeakingExercise(
    id: 'ku_speak_016',
    level: 'A1',
    type: 'pronunciation',
    textKu: 'Îro',
    ipa: '/iːɾo/',
    promptTr: 'Söyle: "Îro" (bugün)',
    tipKu: 'Î: "i" ya dirêj, wek "ee" ya Îngilîzî. O: "o" ya kurt.',
    tipTr: 'Î uzun "i" sesi (iiro). İ-R-O değil, İİ-R-O. O kısa.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_017',
    level: 'A1',
    type: 'pronunciation',
    textKu: 'Pîrê',
    ipa: '/piːɾɛː/',
    promptTr: 'Söyle: "Pîrê" (nine/yaşlı kadın)',
    tipKu: 'P + Î (dirêj) + r + Ê (dirêj). Her du dirêj!',
    tipTr: 'P + uzun Î + r + uzun Ê. İki uzun ünlü: "piiireee".',
  ),

  // Û sesi (uː) — uzun u
  KuSpeakingExercise(
    id: 'ku_speak_018',
    level: 'A1',
    type: 'pronunciation',
    textKu: 'Dû',
    ipa: '/duː/',
    promptTr: 'Söyle: "Dû" (duman/arka)',
    tipKu: 'D + Û (dirêj). Û wek "oo" ya Îngilîzî di "moon".',
    tipTr: 'D + uzun Û. Û Türkçe "u"dan daha uzun, "duu" diye uzat.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_019',
    level: 'A1',
    type: 'pronunciation',
    textKu: 'Bûn',
    ipa: '/buːn/',
    promptTr: 'Söyle: "Bûn" (olmak)',
    tipKu: 'B + Û (dirêj) + n. Lêkera "bûn" = "olmak".',
    tipTr: 'B + uzun Û + n. "Bun" değil, "buuun". "Olmak" fiili.',
  ),

  // Ayn (glottal) — ses kesintisi
  KuSpeakingExercise(
    id: 'ku_speak_020',
    level: 'A2',
    type: 'pronunciation',
    textKu: 'Eʼdil',
    ipa: '/ɛʕdɪl/',
    promptTr: 'Söyle: "Eʼdil" (adil)',
    tipKu: 'Apostrof (ʼ): dengê rawestînê, wek ayn ya Erebî. Di navbera "E" û "d" de bêhn bide.',
    tipTr: 'Apostrof (ʼ) gırtlakta kısa bir duraklama/gıcırtı. "E" ve "d" arasında sesi kes. Arapça "ayn" gibi.',
    acceptableVariants: ['Edil', "E'dil"],
  ),

  // ========== REPEAT (20) — A1-A2 Günlük cümleler ==========

  KuSpeakingExercise(
    id: 'ku_speak_021',
    level: 'A1',
    type: 'repeat',
    textKu: 'Silav',
    ipa: '/silaːv/',
    promptTr: 'Tekrar et: "Silav" (Merhaba)',
    tipKu: 'Du kîte: Si-lav. Stresê li ser kîta yekem.',
    tipTr: 'İki heceli: Si-LAV. Vurgu ikinci hecede. Temel selamlama.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_022',
    level: 'A1',
    type: 'repeat',
    textKu: 'Sipas',
    ipa: '/sɪpaːs/',
    promptTr: 'Tekrar et: "Sipas" (Teşekkürler)',
    tipKu: 'Si-PAS. "A" ya dirêj di kîta duyem de.',
    tipTr: 'Si-PAS. Vurgu son hecede, "a" biraz uzun. "Teşekkür".',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_023',
    level: 'A1',
    type: 'repeat',
    textKu: 'Navê te çi ye?',
    ipa: '/naːvɛː tɛ tʃi jɛ/',
    promptTr: 'Tekrar et: "Navê te çi ye?" (Adın ne?)',
    tipKu: 'Na-VÊ TE ÇI YE. "Ê" dirêj, pirsek e — dengê te bilind bike li dawiyê.',
    tipTr: 'Na-VÊ TE Çİ YE. Ê uzun. Soru olduğu için sonunda ton yükselir.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_024',
    level: 'A1',
    type: 'repeat',
    textKu: 'Navê min Azad e.',
    ipa: '/naːvɛː mɪn aːzaːd ɛ/',
    promptTr: 'Tekrar et: "Navê min Azad e." (Adım Azad.)',
    tipKu: '"Navê min" = adım/navê min. "Azad" nav e. "E" li dawiyê kurt.',
    tipTr: '"Navê min" = adım. "Azad" isim. Sondaki "e" kısa, copula.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_025',
    level: 'A1',
    type: 'repeat',
    textKu: 'Ez li malê me.',
    ipa: '/ɛz li maːlɛː mɛ/',
    promptTr: 'Tekrar et: "Ez li malê me." (Evdeyim.)',
    tipKu: '"Ez" = ez, "li malê" = li mal (durum), "me" = me/im. Malê: mal + ê.',
    tipTr: '"Ez" = ben, "li malê" = evde (bulunma hali), "me" = -(y)im. "Eve me" değil, "malê me".',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_026',
    level: 'A1',
    type: 'repeat',
    textKu: 'Tu ji kû yî?',
    ipa: '/tu ʒi kuː jiː/',
    promptTr: 'Tekrar et: "Tu ji kû yî?" (Sen nerelisin?)',
    tipKu: '"Kû" = kîjan cih, Û dirêj. "Yî" = î ya duyemîn kes.',
    tipTr: '"Kû" = nere, Û uzun. "Yî" = -sin (2. tekil şahıs). Soru tonu yüksel.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_027',
    level: 'A1',
    type: 'repeat',
    textKu: 'Ez ji Amedê me.',
    ipa: '/ɛz ʒi aːmɛdɛː mɛ/',
    promptTr: 'Tekrar et: "Ez ji Amedê me." (Ben Diyarbakırlıyım.)',
    tipKu: 'Amed + ê (rewşa mezber). "Me" = im/ez.',
    tipTr: 'Amed + ê (çıkma hali eki). "Me" = -(y)im. "Diyarbakırdan-yım".',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_028',
    level: 'A1',
    type: 'repeat',
    textKu: 'Rojbaş',
    ipa: '/ɾoʒbaːʃ/',
    promptTr: 'Tekrar et: "Rojbaş" (Günaydın/İyi günler)',
    tipKu: 'Roj + baş. Du peyv bi hev ve, yek peyv dibe. Stres li "baş".',
    tipTr: 'Roj (gün) + baş (iyi) = iyi günler. Vurgu "baş"ta.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_029',
    level: 'A1',
    type: 'repeat',
    textKu: 'Şev baş',
    ipa: '/ʃɛv baːʃ/',
    promptTr: 'Tekrar et: "Şev baş" (İyi geceler)',
    tipKu: 'Ş + ev. Şev = gece. Baş = iyi. "Baş" ya dirêj.',
    tipTr: 'Şev (gece) + baş (iyi). "Baş" kelimesinde "a" biraz uzun.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_030',
    level: 'A1',
    type: 'repeat',
    textKu: 'Bi xêr hatî',
    ipa: '/bi xɛːɾ haːtiː/',
    promptTr: 'Tekrar et: "Bi xêr hatî" (Hoş geldin)',
    tipKu: 'X ji pişta zimên. "Xêr" = xêr, "hatî" = tu hatî.',
    tipTr: 'X gırtlaktan. "Xêr" = hayır/iyi, "hatî" = geldin. "Hoş geldin".',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_031',
    level: 'A1',
    type: 'repeat',
    textKu: 'Ez baş im.',
    ipa: '/ɛz baːʃ ɪm/',
    promptTr: 'Tekrar et: "Ez baş im." (İyiyim.)',
    tipKu: '"Baş" = baş/iyi. "Im" = im/ya yekem kes.',
    tipTr: '"Baş" = iyi. "Im" = -(y)im. "Ez baş im" = iyiyim.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_032',
    level: 'A2',
    type: 'repeat',
    textKu: 'Ez kurmancî hîn dibim.',
    ipa: '/ɛz kuɾmaːndʒiː hiːn dibɪm/',
    promptTr: 'Tekrar et: "Ez kurmancî hîn dibim." (Kurmancî öğreniyorum.)',
    tipKu: '"Hîn dibim" = fêr dibim/öğreniyorum. Î dirêj di "hîn".',
    tipTr: '"Hîn dibim" = öğreniyorum. Î uzun. Kurmancî = Kürtçe (Kuzey).',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_033',
    level: 'A2',
    type: 'repeat',
    textKu: 'Min ji te hez kir.',
    ipa: '/mɪn ʒi tɛ hɛz kɪɾ/',
    promptTr: 'Tekrar et: "Min ji te hez kir." (Seni sevdim.)',
    tipKu: '"Min" = min/ben (rewşa tebatî). "Hez kir" = hez kirin ya berê.',
    tipTr: '"Min" = ben (ergatif). "Hez kir" = sevdi. Kurmancî geçmiş zaman yapısı.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_034',
    level: 'A2',
    type: 'repeat',
    textKu: 'Ez îro naçim dibistanê.',
    ipa: '/ɛz iːɾo naːtʃɪm dibistaːnɛː/',
    promptTr: 'Tekrar et: "Ez îro naçim dibistanê." (Bugün okula gitmiyorum.)',
    tipKu: '"Naçim" = ne + çûn, neyînî. "Dibistanê" = dibistan + ê.',
    tipTr: '"Naçim" = gitmiyorum (olumsuz). "Dibistanê" okula (yönelme).',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_035',
    level: 'A2',
    type: 'repeat',
    textKu: 'Tu çi dixwî?',
    ipa: '/tu tʃi dixwiː/',
    promptTr: 'Tekrar et: "Tu çi dixwî?" (Ne yiyorsun?)',
    tipKu: '"Dixwî" = tu dixwî, ji "xwarin". Xw bi hev re.',
    tipTr: '"Dixwî" = yiyorsun ("xwarin"dan). Xw birlikte, gırtlaktan.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_036',
    level: 'A2',
    type: 'repeat',
    textKu: 'Kitêb li ser masê ye.',
    ipa: '/kitɛːb li sɛɾ maːsɛː jɛ/',
    promptTr: 'Tekrar et: "Kitêb li ser masê ye." (Kitap masanın üstünde.)',
    tipKu: '"Li ser" = li ser/üstünde. "Masê" = mase + ê.',
    tipTr: '"Li ser" = üstünde. "Masê" = masa (bulunma hali). Kitêb: Ê uzun.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_037',
    level: 'A2',
    type: 'repeat',
    textKu: 'Ez avê vedixwim.',
    ipa: '/ɛz aːvɛː vɛdixwɪm/',
    promptTr: 'Tekrar et: "Ez avê vedixwim." (Su içiyorum.)',
    tipKu: '"Avê" = av + ê (tewanga mê). "Vedixwim" = vexwarin.',
    tipTr: '"Avê" = su (-yi hali, dişil). "Vedixwim" = içiyorum.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_038',
    level: 'A2',
    type: 'repeat',
    textKu: 'Em sibehê diçin bazarê.',
    ipa: '/ɛm sibɛhɛː ditʃɪn baːzaːɾɛː/',
    promptTr: 'Tekrar et: "Em sibehê diçin bazarê." (Sabah pazara gidiyoruz.)',
    tipKu: '"Em diçin" = em diçin. "Sibehê" = sibe + ê (dem).',
    tipTr: '"Em diçin" = gidiyoruz. "Sibehê" = sabah (zaman). "Bazarê" = pazara.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_039',
    level: 'A1',
    type: 'repeat',
    textKu: 'Belê',
    ipa: '/bɛlɛː/',
    promptTr: 'Tekrar et: "Belê" (Evet)',
    tipKu: 'Be-LÊ. Ê ya dawî dirêj. Maneya "erê" jî heye.',
    tipTr: 'Be-LÊ. Son Ê uzun. "Evet" anlamında. "Erê" de denir.',
    acceptableVariants: ['Erê'],
  ),
  KuSpeakingExercise(
    id: 'ku_speak_040',
    level: 'A1',
    type: 'repeat',
    textKu: 'Na',
    ipa: '/naː/',
    promptTr: 'Tekrar et: "Na" (Hayır)',
    tipKu: '"Na" = ne. A dirêj, yek kîte.',
    tipTr: '"Na" = hayır. A uzun, tek hece.',
    acceptableVariants: ['Nexêr'],
  ),

  // ========== RESPOND (10) — Soru-cevap ==========

  KuSpeakingExercise(
    id: 'ku_speak_041',
    level: 'A1',
    type: 'respond',
    textKu: 'Silav',
    ipa: '/silaːv/',
    promptTr: 'Sana "Silav" dediler. Ne dersin?',
    tipKu: 'Bersiv: "Silav" — her du alî wekhev dibêjin.',
    tipTr: 'Cevap: "Silav". Karşılıklı aynı kelime kullanılır.',
    acceptableVariants: ['Silav li te', 'Silav jî li te'],
  ),
  KuSpeakingExercise(
    id: 'ku_speak_042',
    level: 'A1',
    type: 'respond',
    textKu: 'Ez baş im, spas',
    ipa: '/ɛz baːʃ ɪm spaːs/',
    promptTr: 'Sana "Tu çawa yî?" (Nasılsın?) diyorlar. Cevap ver.',
    tipKu: 'Bersiva standard: "Ez baş im, spas". Jê bipirse: "Tu çawa yî?"',
    tipTr: 'Standart cevap: "Ez baş im, spas" (İyiyim, teşekkürler). Aynısını soru olarak sor.',
    acceptableVariants: ['Baş im', 'Ez baş im'],
  ),
  KuSpeakingExercise(
    id: 'ku_speak_043',
    level: 'A1',
    type: 'respond',
    textKu: 'Navê min …',
    ipa: '/naːvɛː mɪn/',
    promptTr: 'Sana "Navê te çi ye?" (Adın ne?) diyorlar. Adınla cevap ver.',
    tipKu: '"Navê min [nav] e." Mînak: "Navê min Rojîn e."',
    tipTr: '"Navê min [isim] e." Örnek: "Navê min Rojîn e." Sondaki "e" unutma.',
    acceptableVariants: ['Ez …', 'Navê min … ye'],
  ),
  KuSpeakingExercise(
    id: 'ku_speak_044',
    level: 'A1',
    type: 'respond',
    textKu: 'Ez ji Stenbolê me.',
    ipa: '/ɛz ʒi stɛnboːlɛː mɛ/',
    promptTr: 'Sana "Tu ji kû yî?" (Nerelisin?) diyorlar. İstanbul\'dan olduğunu söyle.',
    tipKu: 'Stenbol + ê (rewşa ji kû). "Me" ji bo yekem kes.',
    tipTr: 'Stenbol + ê (-den hali). "Me" = -(y)im. Şehrin sonuna "ê" ekle.',
    acceptableVariants: ['Stenbolê me', 'Ji Stenbolê'],
  ),
  KuSpeakingExercise(
    id: 'ku_speak_045',
    level: 'A1',
    type: 'respond',
    textKu: 'Spas xweş',
    ipa: '/spaːs xwɛʃ/',
    promptTr: 'Biri sana yardım etti. Teşekkür et.',
    tipKu: '"Spas xweş" = "tankerî gelekî". Xweş: xw bi hev.',
    tipTr: '"Spas xweş" = çok teşekkürler. "Xweş" gırtlaktan "xw".',
    acceptableVariants: ['Sipas', 'Spas', 'Gelek sipas'],
  ),
  KuSpeakingExercise(
    id: 'ku_speak_046',
    level: 'A2',
    type: 'respond',
    textKu: 'Ser çavan',
    ipa: '/sɛɾ tʃaːvaːn/',
    promptTr: 'Biri sana "Spas" (Teşekkürler) dedi. Karşılık ver.',
    tipKu: '"Ser çavan" = "rica ederim". Wek "serê te"ta dili.',
    tipTr: '"Ser çavan" = rica ederim (lafzen: gözlerimin üstüne). Nazik karşılık.',
    acceptableVariants: ['Tu bi xêr', 'Hêja ye'],
  ),
  KuSpeakingExercise(
    id: 'ku_speak_047',
    level: 'A2',
    type: 'respond',
    textKu: 'Belê, ez kurmancî dizanim.',
    ipa: '/bɛlɛː ɛz kuɾmaːndʒiː dizaːnɪm/',
    promptTr: 'Sana "Tu kurmancî dizanî?" (Kurmancî biliyor musun?) diyorlar. Olumlu cevap ver.',
    tipKu: '"Belê" (erê) + "ez dizanim". "Dizanim" = zanîn ya niha.',
    tipTr: '"Belê" (evet) + "ez dizanim" (biliyorum). "Dizanim" şimdiki zaman.',
    acceptableVariants: ['Erê, dizanim', 'Belê, hinekî'],
  ),
  KuSpeakingExercise(
    id: 'ku_speak_048',
    level: 'A2',
    type: 'respond',
    textKu: 'Saet pênc e.',
    ipa: '/saːɛt pɛːndʒ ɛ/',
    promptTr: 'Biri sana "Saet çend e?" (Saat kaç?) diyor. "Beş" diye cevap ver.',
    tipKu: '"Saet pênc e." Ê dirêj di "pênc".',
    tipTr: '"Saet pênc e" = saat beş. "Pênc" = beş, Ê uzun.',
    acceptableVariants: ['Pênc e', 'Saet pêncan'],
  ),
  KuSpeakingExercise(
    id: 'ku_speak_049',
    level: 'B1',
    type: 'respond',
    textKu: 'Ez li zanîngehê dixwînim.',
    ipa: '/ɛz li zaːniːngɛhɛː dixwiːnɪm/',
    promptTr: 'Sana "Tu çi dikî?" (Ne yapıyorsun / ne iş?) diyorlar. Üniversitede okuduğunu söyle.',
    tipKu: '"Zanîngeh" = zanîngeh/üniversite. "Dixwînim" = ji "xwendin".',
    tipTr: '"Zanîngeh" = üniversite. "Dixwînim" = okuyorum (xwendin = okumak).',
    acceptableVariants: ['Ez xwendekar im', 'Li zanîngehê'],
  ),
  KuSpeakingExercise(
    id: 'ku_speak_050',
    level: 'B1',
    type: 'respond',
    textKu: 'Bi xatirê te',
    ipa: '/bi xaːtiɾɛː tɛ/',
    promptTr: 'Vedalaşıyorsun. Nasıl "Hoşça kal" dersin?',
    tipKu: '"Bi xatirê te" = "xatirê te li min be". X ji pişta zimên.',
    tipTr: '"Bi xatirê te" = hoşça kal. X gırtlaktan. Karşılık: "Oxir be".',
    acceptableVariants: ['Xatirê te', 'Bimîne di xêrê de'],
  ),

  // ========== READ_ALOUD (10) — A2-B1 kısa pasajlar ==========

  KuSpeakingExercise(
    id: 'ku_speak_051',
    level: 'A2',
    type: 'read_aloud',
    textKu: 'Ez Rojîn im. Ez li Amedê dijîm. Ez kurmancî hîn dibim.',
    ipa: '/ɛz ɾoʒiːn ɪm ɛz li aːmɛdɛː diʒiːm ɛz kuɾmaːndʒiː hiːn dibɪm/',
    promptTr: 'Sesli oku: Kendini tanıtan kısa bir metin.',
    tipKu: 'Sê hevok kurt. Di navbera wan de bêhn bide. Î di "Rojîn", "dijîm", "hîn" de dirêj.',
    tipTr: 'Üç kısa cümle. Aralarda nefes al. "Rojîn", "dijîm", "hîn" sözcüklerinde Î uzun.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_052',
    level: 'A2',
    type: 'read_aloud',
    textKu: 'Îro hewa xweş e. Ez û hevalê xwe diçin parkê.',
    ipa: '/iːɾo hɛwaː xwɛʃ ɛ ɛz uː hɛvaːlɛː xwɛ ditʃɪn paːɾkɛː/',
    promptTr: 'Sesli oku: Hava ve arkadaşla plan.',
    tipKu: '"Xweş" û "xwe" — her du jî bi "xw" dest pê dikin. Stres li kîteyên bi Ê.',
    tipTr: '"Xweş" ve "xwe" ikisi de "xw" ile başlar. Ê uzun hecelerde vurgu.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_053',
    level: 'A2',
    type: 'read_aloud',
    textKu: 'Diya min xwarin çêdike. Bavê min rojnameyê dixwîne.',
    ipa: '/dijaː mɪn xwaːɾɪn tʃɛːdikɛ baːvɛː mɪn ɾoʒnaːmɛjɛː dixwiːnɛ/',
    promptTr: 'Sesli oku: Aile aktivitesi.',
    tipKu: '"Çêdike" = çê + dike. "Dixwîne" = dixwîne. Xw + î (dirêj).',
    tipTr: '"Çêdike" = yapıyor. "Dixwîne" = okuyor. "Xw" birlikte, Î uzun.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_054',
    level: 'A2',
    type: 'read_aloud',
    textKu: 'Her sibeh ez qehwe vedixwim û nanê xwe dixwim.',
    ipa: '/hɛɾ sibɛh ɛz qɛhwɛ vɛdixwɪm uː naːnɛː xwɛ dixwɪm/',
    promptTr: 'Sesli oku: Sabah rutini.',
    tipKu: 'Q di "qehwe" — ji pişta zimên. "Vedixwim" û "dixwim" = du lêker cuda.',
    tipTr: '"Qehwe"de Q gırtlaktan. "Vedixwim" (içiyorum) ve "dixwim" (yiyorum) iki farklı fiil.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_055',
    level: 'B1',
    type: 'read_aloud',
    textKu: 'Zarokên me her roj diçin dibistanê. Ew kurmancî hîn dibin û bi kêfa xwe dileyzin.',
    ipa: '/zaːɾokɛːn mɛ hɛɾ ɾoʒ ditʃɪn dibistaːnɛː ɛw kuɾmaːndʒiː hiːn dibɪn uː bi kɛːfaː xwɛ dilɛjzɪn/',
    promptTr: 'Sesli oku: Çocuklar ve okul.',
    tipKu: '"Zarokên" = piranî. "Dileyzin" = leyistin. Bi rîtmê bixwîne.',
    tipTr: '"Zarokên" = çocuklar (çoğul). "Dileyzin" = oynuyorlar. Ritmik oku.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_056',
    level: 'B1',
    type: 'read_aloud',
    textKu: 'Havîn hat. Roj germ e. Em ê biçin deryayê û avjenî bikin.',
    ipa: '/haːviːn haːt ɾoʒ gɛɾm ɛ ɛm ɛː bitʃɪn dɛɾjaːjɛː uː aːvʒɛniː bikɪn/',
    promptTr: 'Sesli oku: Yaz planı.',
    tipKu: '"Em ê biçin" = dema bê. "Avjenî" = sobeserê kirin. Î dirêj.',
    tipTr: '"Em ê biçin" = gideceğiz (gelecek zaman). "Avjenî" = yüzme. Î uzun.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_057',
    level: 'B1',
    type: 'read_aloud',
    textKu: 'Çîroka me li gundekî biçûk dest pê dike. Li wir jineke pîr û keçeke ciwan dijîn.',
    ipa: '/tʃiːɾokaː mɛ li gundɛkiː bitʃuːk dɛst pɛː dikɛ li wiɾ ʒinɛkɛ piːɾ uː kɛtʃɛkɛ dʒiwaːn diʒiːn/',
    promptTr: 'Sesli oku: Hikaye girişi.',
    tipKu: '"Biçûk" = Û dirêj. "Pîr û ciwan" — berevajîyek. Dengê çîrokbêjiyê.',
    tipTr: '"Biçûk" = küçük, Û uzun. "Pîr û ciwan" = yaşlı ve genç. Masal tonuyla oku.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_058',
    level: 'B1',
    type: 'read_aloud',
    textKu: 'Xwendevan divê her roj bixwîne, guhdarî bike û bipeyive da ku zimanî baş hîn bibe.',
    ipa: '/xwɛndɛvaːn divɛː hɛɾ ɾoʒ bixwiːnɛ guhdaːɾiː bikɛ uː bipɛjivɛ daː ku zɪmaːniː baːʃ hiːn bibɛ/',
    promptTr: 'Sesli oku: Öğrenci tavsiyesi.',
    tipKu: 'Hevoka dirêj. "Xwendevan" û "xwîne" bi "xw". Bêhnên rast bide.',
    tipTr: 'Uzun cümle. "Xwendevan" ve "xwîne"de "xw" birlikte. Virgüllerde nefes al.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_059',
    level: 'B2',
    type: 'read_aloud',
    textKu: 'Gava ku ez piçûk bûm, dapîra min her êvarê çîrokên kevn ji min re digotin, û ez bi dengê wê radiketim.',
    ipa: '/gaːvaː ku ɛz pitʃuːk buːm daːpiːɾaː mɪn hɛɾ ɛːvaːɾɛː tʃiːɾokɛːn kɛvn ʒi mɪn ɾɛ digotɪn uː ɛz bi dɛngɛː wɛː ɾaːdikɛtɪm/',
    promptTr: 'Sesli oku: Çocukluk anısı (B2).',
    tipKu: 'Dema borî. "Digotin" piranî. Xîtaba stranbêjiyê — dengê te nerm be.',
    tipTr: 'Geçmiş zaman. "Digotin" = söylerlerdi. Yumuşak, anlatı tonu ile oku.',
  ),
  KuSpeakingExercise(
    id: 'ku_speak_060',
    level: 'B2',
    type: 'read_aloud',
    textKu: 'Zimanê kurmancî yek ji wan zimanên kevnar e ku heta îro jî tê axaftin, û parastina wê ji bo nasnameya gelê kurd pir girîng e.',
    ipa: '/zɪmaːnɛː kuɾmaːndʒiː jɛk ʒi waːn zɪmaːnɛːn kɛvnaːɾ ɛ ku hɛtaː iːɾo ʒiː tɛː aːxaːftɪn uː paːɾaːstɪnaː wɛː ʒi bo naːsnaːmɛjaː gɛliː kuɾd piɾ giɾiːng ɛ/',
    promptTr: 'Sesli oku: Dil ve kimlik üzerine (B2).',
    tipKu: 'Hevoka akademîk. "Axaftin", "parastin", "nasname" — stresên rast deyne.',
    tipTr: 'Akademik cümle. "Axaftin" (konuşma), "parastin" (koruma), "nasname" (kimlik). Vurguları net ver.',
  ),
];
