class KuWritingExercise {
  final String id;
  final String level; // A1, A2, B1, B2, C1
  final String type; // 'dictation', 'fill_blank', 'reorder', 'correct', 'translate_tr'
  final String promptTr; // Türkçe ipucu/soru (KU-TR modda göster)
  final String correctAnswer; // Doğru Kurmancî cümle
  final List<String>? words; // reorder için
  final String explanationTr; // Türkçe kural açıklama
  final String explanationKu; // Kurmancî kural açıklama

  const KuWritingExercise({
    required this.id,
    required this.level,
    required this.type,
    required this.promptTr,
    required this.correctAnswer,
    this.words,
    required this.explanationTr,
    required this.explanationKu,
  });
}

const List<KuWritingExercise> kKuWritingExercises = [
  // ============================================================
  // DICTATION (30 toplam) — Türkçe → Kurmancî çeviri
  // ============================================================
  KuWritingExercise(
    id: 'ku_write_001',
    level: 'A1',
    type: 'dictation',
    promptTr: 'Türkçe: "Ben iyiyim." Kurmancî yaz:',
    correctAnswer: 'Ez baş im.',
    words: null,
    explanationTr: 'Ez (ben) + baş (iyi) + im (-im eki). Kurmancî zamir + sıfat + be eki.',
    explanationKu: 'Ez + rengdêr + im. Forma herî bingehîn a hevokê.',
  ),
  KuWritingExercise(
    id: 'ku_write_002',
    level: 'A1',
    type: 'dictation',
    promptTr: 'Türkçe: "Sen öğrencisin." Kurmancî yaz:',
    correctAnswer: 'Tu xwendekar î.',
    words: null,
    explanationTr: 'Tu (sen) + xwendekar (öğrenci) + î (-sin eki). 2. tekil şahıs.',
    explanationKu: 'Tu + navdêr + î. Cînavk a duyemîn yekjimar.',
  ),
  KuWritingExercise(
    id: 'ku_write_003',
    level: 'A1',
    type: 'dictation',
    promptTr: 'Türkçe: "O bir öğretmendir." Kurmancî yaz:',
    correctAnswer: 'Ew mamoste ye.',
    words: null,
    explanationTr: 'Ew (o) + mamoste (öğretmen) + ye (-dir eki, sesli harften sonra).',
    explanationKu: 'Ew + navdêr + ye. Piştî dengdêrê "ye" tê bikaranîn.',
  ),
  KuWritingExercise(
    id: 'ku_write_004',
    level: 'A1',
    type: 'dictation',
    promptTr: 'Türkçe: "Biz Kürdüz." Kurmancî yaz:',
    correctAnswer: 'Em Kurd in.',
    words: null,
    explanationTr: 'Em (biz) + Kurd + in (-iz eki). Çoğul şahıs eki "in".',
    explanationKu: 'Em + navdêr + in. Paşgira pirjimar -in e.',
  ),
  KuWritingExercise(
    id: 'ku_write_005',
    level: 'A1',
    type: 'dictation',
    promptTr: 'Türkçe: "Benim adım Azad\'dır." Kurmancî yaz:',
    correctAnswer: 'Navê min Azad e.',
    words: null,
    explanationTr: 'Nav (ad) + ê (ezafe eril) + min (benim) + Azad + e. Ezafe yapısı.',
    explanationKu: 'Nav (nêr) + ezafe -ê + cînavk + navê taybetî + e.',
  ),
  KuWritingExercise(
    id: 'ku_write_006',
    level: 'A1',
    type: 'dictation',
    promptTr: 'Türkçe: "Bu bir kitaptır." Kurmancî yaz:',
    correctAnswer: 'Ev pirtûk e.',
    words: null,
    explanationTr: 'Ev (bu) + pirtûk (kitap) + e (-dir eki, sessizden sonra).',
    explanationKu: 'Ev + navdêr + e. "Ev" ji bo nêzîk tê bikaranîn.',
  ),
  KuWritingExercise(
    id: 'ku_write_007',
    level: 'A1',
    type: 'dictation',
    promptTr: 'Türkçe: "O bir evdir." (uzaktaki) Kurmancî yaz:',
    correctAnswer: 'Ew mal e.',
    words: null,
    explanationTr: 'Ew (uzaktaki o/bu) + mal (ev) + e. Uzak işaret zamiri.',
    explanationKu: 'Ew ji bo dûr tê bikaranîn. Mal peyveke mê ye.',
  ),
  KuWritingExercise(
    id: 'ku_write_008',
    level: 'A1',
    type: 'dictation',
    promptTr: 'Türkçe: "Ben su içiyorum." Kurmancî yaz:',
    correctAnswer: 'Ez avê vedixwim.',
    words: null,
    explanationTr: 'Ez + av (+ê, nesne eki) + vedixwim (vexwarin-içmek, dema niha). Geçişli fiil nesnesi büküm alır.',
    explanationKu: 'Ez + av-ê (biresan) + vedixwim. Lêkera "vexwarin" bireser digire.',
  ),
  KuWritingExercise(
    id: 'ku_write_009',
    level: 'A1',
    type: 'dictation',
    promptTr: 'Türkçe: "Sen ekmek yiyorsun." Kurmancî yaz:',
    correctAnswer: 'Tu nan dixwî.',
    words: null,
    explanationTr: 'Tu + nan (ekmek) + dixwî (xwarin-yemek, dema niha 2. şahıs).',
    explanationKu: 'Tu + bireser + lêkera niha. Paşgira -î ji bo cînavka "tu".',
  ),
  KuWritingExercise(
    id: 'ku_write_010',
    level: 'A1',
    type: 'dictation',
    promptTr: 'Türkçe: "O eve gidiyor." Kurmancî yaz:',
    correctAnswer: 'Ew diçe malê.',
    words: null,
    explanationTr: 'Ew + diçe (çûn-gitmek) + mal (ev) + ê (yönelme eki, dişil -ê). Mal dişildir.',
    explanationKu: 'Ew + lêker + mal-ê. Mal mê ye, lewre -ê digire.',
  ),
  KuWritingExercise(
    id: 'ku_write_011',
    level: 'A1',
    type: 'dictation',
    promptTr: 'Türkçe: "Hava güzeldir." Kurmancî yaz:',
    correctAnswer: 'Hewa xweş e.',
    words: null,
    explanationTr: 'Hewa (hava) + xweş (güzel/hoş) + e. Sıfat yüklemli cümle.',
    explanationKu: 'Hewa + rengdêr + e. Hevoka navdêrî.',
  ),
  KuWritingExercise(
    id: 'ku_write_012',
    level: 'A1',
    type: 'dictation',
    promptTr: 'Türkçe: "Bugün pazartesidir." Kurmancî yaz:',
    correctAnswer: 'Îro duşem e.',
    words: null,
    explanationTr: 'Îro (bugün) + duşem (pazartesi) + e. Hafta günleri Farsça kökenli.',
    explanationKu: 'Îro + navê rojê + e. Rojên hefteyê li gor Farisî ne.',
  ),
  KuWritingExercise(
    id: 'ku_write_013',
    level: 'A1',
    type: 'dictation',
    promptTr: 'Türkçe: "Benim bir kardeşim var." Kurmancî yaz:',
    correctAnswer: 'Birayekî min heye.',
    words: null,
    explanationTr: 'Bira (kardeş/erkek) + -yekî (belgisiz eril) + min + heye (var). "Heye" tekil için.',
    explanationKu: 'Bira (nêr) + -yekî + min + heye. Ji bo pirjimar "hene" tê bikaranîn.',
  ),
  KuWritingExercise(
    id: 'ku_write_014',
    level: 'A1',
    type: 'dictation',
    promptTr: 'Türkçe: "Annem hastadır." Kurmancî yaz:',
    correctAnswer: 'Diya min nexweş e.',
    words: null,
    explanationTr: 'Dê (anne, mê) → diya + min + nexweş + e. "Dê" dişildir, ezafe -a alır.',
    explanationKu: 'Dê (mê) + ezafe -a + min + rengdêr + e. Di ezafê de "dê" dibe "diya".',
  ),
  KuWritingExercise(
    id: 'ku_write_015',
    level: 'A2',
    type: 'dictation',
    promptTr: 'Türkçe: "Dün ekmek yedim." Kurmancî yaz:',
    correctAnswer: 'Min duh nan xwar.',
    words: null,
    explanationTr: 'ERGATİF: Geçmişte geçişli fiilde özne büküm alır: Ez → Min. "Min nan xwar" = "Ben ekmek yedim".',
    explanationKu: 'Ergatîv: Di dema borî ya lêkera derhingêv de, kirde guherê: Ez → Min. Fiil nesneye göre çekilir.',
  ),
  KuWritingExercise(
    id: 'ku_write_016',
    level: 'A2',
    type: 'dictation',
    promptTr: 'Türkçe: "O kitabı okudu." Kurmancî yaz:',
    correctAnswer: 'Wî pirtûk xwend.',
    words: null,
    explanationTr: 'ERGATİF: Ew → Wî (eril) veya Wê (dişil). "Wî pirtûk xwend" = O (erkek) kitabı okudu.',
    explanationKu: 'Di ergatîvê de: Ew nêr → Wî, Ew mê → Wê. Lêker li gor biresarê tê kişandin.',
  ),
  KuWritingExercise(
    id: 'ku_write_017',
    level: 'A2',
    type: 'dictation',
    promptTr: 'Türkçe: "Biz okula gittik." Kurmancî yaz:',
    correctAnswer: 'Em çûn dibistanê.',
    words: null,
    explanationTr: 'GEÇİŞSİZ fiilde ergatif YOK: Em + çûn (gittik) + dibistan-ê. "Çûn" intransitive.',
    explanationKu: 'Lêkera neçalak (çûn) ergatîvê nagire. Dibistan (mê) + -ê = dibistanê.',
  ),
  KuWritingExercise(
    id: 'ku_write_018',
    level: 'A2',
    type: 'dictation',
    promptTr: 'Türkçe: "Babam çay içti." Kurmancî yaz:',
    correctAnswer: 'Bavê min çay vexwar.',
    words: null,
    explanationTr: 'ERGATİF: Bav (baba, nêr) + ê (ezafe) + min. Geçmiş zamanda özne ergatifte.',
    explanationKu: 'Bav (nêr) + ezafe -ê + min + çay + vexwar. Di borî de ergatîv.',
  ),
  KuWritingExercise(
    id: 'ku_write_019',
    level: 'A2',
    type: 'dictation',
    promptTr: 'Türkçe: "Yarın İstanbul\'a gideceğim." Kurmancî yaz:',
    correctAnswer: 'Ez ê sibê biçim Stenbolê.',
    words: null,
    explanationTr: 'Gelecek zaman: Ez + AYRI "ê" (gelecek işareti) + subjunktif fiil (biçim). Bedirxan-Lescot standardına göre "ê" zamirden ayrı yazılır.',
    explanationKu: 'Dema bê: cînavk + (cihê) ê + lêkera subjunktif. Li gor standarda Bedirxan-Lescot, "ê" cuda tê nivîsîn. Stenbol (mê) + -ê.',
  ),
  KuWritingExercise(
    id: 'ku_write_020',
    level: 'A2',
    type: 'dictation',
    promptTr: 'Türkçe: "Ben Kürtçe öğreniyorum." Kurmancî yaz:',
    correctAnswer: 'Ez Kurmancî hîn dibim.',
    words: null,
    explanationTr: 'Ez + Kurmancî + hîn dibim (öğreniyorum). "Hîn bûn" = öğrenmek, ayrılabilir fiil.',
    explanationKu: 'Lêkera hevdanî: "hîn bûn". Ez hîn dibim = ez fêr dibim.',
  ),
  KuWritingExercise(
    id: 'ku_write_021',
    level: 'A2',
    type: 'dictation',
    promptTr: 'Türkçe: "Onun evi büyüktür." Kurmancî yaz:',
    correctAnswer: 'Mala wî mezin e.',
    words: null,
    explanationTr: 'Mal (ev, mê) + -a (ezafe dişil) + wî (onun, eril) + mezin + e.',
    explanationKu: 'Mal mê ye → mala. Wî ji bo nêr, wê ji bo mê. Ezafe + cînavka xwedîtiyê.',
  ),
  KuWritingExercise(
    id: 'ku_write_022',
    level: 'A2',
    type: 'dictation',
    promptTr: 'Türkçe: "Beni gördün mü?" Kurmancî yaz:',
    correctAnswer: 'Te ez dîtim?',
    words: null,
    explanationTr: 'ERGATİF soru: Te (sen-ergatif) + ez (ben-nesne) + dîtim (dîtin-görmek, 1.şahıs nesneye göre).',
    explanationKu: 'Di borî de: tu → te. Lêker li gor biresarê (ez) tê kişandin: dîtim.',
  ),
  KuWritingExercise(
    id: 'ku_write_023',
    level: 'A2',
    type: 'dictation',
    promptTr: 'Türkçe: "Okulun öğretmenleri iyidir." Kurmancî yaz:',
    correctAnswer: 'Mamosteyên dibistanê baş in.',
    words: null,
    explanationTr: 'Mamoste + -yên (çoğul ezafe) + dibistan-ê + baş + in. Çoğul ezafe -yên/-ên.',
    explanationKu: 'Ezafeya pirjimar: -yên piştî dengdêr, -ên piştî bêdeng. Dibistan (mê) → dibistanê.',
  ),
  KuWritingExercise(
    id: 'ku_write_024',
    level: 'B1',
    type: 'dictation',
    promptTr: 'Türkçe: "Eğer yağmur yağsa, evde kalırım." Kurmancî yaz:',
    correctAnswer: 'Eger baran bibare, ez li malê dimînim.',
    words: null,
    explanationTr: 'Şart cümlesi: Eger + subjunktif (bibare) + sonuç (dimînim). "Li malê" = evde.',
    explanationKu: 'Hevoka şertî: Eger + subjunktîv + encam. "Li" cihê nîşan dide.',
  ),
  KuWritingExercise(
    id: 'ku_write_025',
    level: 'B1',
    type: 'dictation',
    promptTr: 'Türkçe: "Kitabı ona verdim." Kurmancî yaz:',
    correctAnswer: 'Min pirtûk da wî.',
    words: null,
    explanationTr: 'ERGATİF + yönelme: Min + pirtûk + da (verdi) + wî (ona, eril). Fiil nesne "pirtûk"a göre.',
    explanationKu: 'Min (ergatîv) + biresar + lêker + cînavka tewandî. "da" ji "dan" lêkerê.',
  ),
  KuWritingExercise(
    id: 'ku_write_026',
    level: 'B1',
    type: 'dictation',
    promptTr: 'Türkçe: "Çocuklar bahçede oynuyorlar." Kurmancî yaz:',
    correctAnswer: 'Zarok li baxçe dilîzin.',
    words: null,
    explanationTr: 'Zarok (çocuklar, çoğul aynı form) + li baxçe + dilîzin (lîstin-oynamak, çoğul).',
    explanationKu: 'Zarok heman form e ji bo yekjimar/pirjimar. Fiil piştî pirjimar -in digire.',
  ),
  KuWritingExercise(
    id: 'ku_write_027',
    level: 'B1',
    type: 'dictation',
    promptTr: 'Türkçe: "Bu mektubu yazmam gerekiyor." Kurmancî yaz:',
    correctAnswer: 'Divê ez vê nameyê binivîsim.',
    words: null,
    explanationTr: 'Divê (gerekiyor) + özne + subjunktif fiil. "Vê nameyê" = bu mektubu (dişil büküm).',
    explanationKu: 'Divê + kirde + subjunktîv. Name (mê) → vê nameyê (bireser, mê).',
  ),
  KuWritingExercise(
    id: 'ku_write_028',
    level: 'B2',
    type: 'dictation',
    promptTr: 'Türkçe: "Kitap okunmuş." (passive perfect) Kurmancî yaz:',
    correctAnswer: 'Pirtûk hatiye xwendin.',
    words: null,
    explanationTr: 'Passive: hatin + mastar. "Hatiye xwendin" = okunmuş (perfect passive).',
    explanationKu: 'Lêkera pasîv: "hatin" + rader. Dema bihurî ya çîrokî ji bo pasîvê.',
  ),
  KuWritingExercise(
    id: 'ku_write_029',
    level: 'B2',
    type: 'dictation',
    promptTr: 'Türkçe: "Gelebileceğimi sanmıyorum." Kurmancî yaz:',
    correctAnswer: 'Ez nafikirim ku ez bikaribim bêm.',
    words: null,
    explanationTr: 'Olumsuz ana + "ku" bağlacı + çift subjunktif. Dikarim-bikaribim (gelebilir).',
    explanationKu: 'Lêkera sereke neyînî + "ku" + du subjunktîv. "Bikaribim" + "bêm".',
  ),
  KuWritingExercise(
    id: 'ku_write_030',
    level: 'B2',
    type: 'dictation',
    promptTr: 'Türkçe: "Keşke onu dün görebilseydim." Kurmancî yaz:',
    correctAnswer: 'Xwezî min duh ew bidîtaya.',
    words: null,
    explanationTr: 'Dilek-şart geçmiş: Xwezî + ergatif özne + geçmiş subjunktif (-taya). Karşı-olgusal.',
    explanationKu: 'Xwezî + kirdeya ergatîv + subjunktîvê borî. Forma hîpotetîk a borî.',
  ),

  // ============================================================
  // FILL_BLANK (20 toplam) — Cümlede boşluk, kelime yaz
  // ============================================================
  KuWritingExercise(
    id: 'ku_write_031',
    level: 'A1',
    type: 'fill_blank',
    promptTr: 'Boşluğu doldur: "Ez ___ im." (İyiyim)',
    correctAnswer: 'baş',
    words: null,
    explanationTr: 'Ez baş im = Ben iyiyim. "Baş" = iyi.',
    explanationKu: 'Rengdêra "baş" wateya "iyi" ya tirkî dide.',
  ),
  KuWritingExercise(
    id: 'ku_write_032',
    level: 'A1',
    type: 'fill_blank',
    promptTr: 'EZAFE: "Mal___ min" (Benim evim) — doğru eki yaz',
    correctAnswer: 'a',
    words: null,
    explanationTr: 'Mal DİŞİL bir kelimedir, bu yüzden ezafe eki -a olur: "Mala min".',
    explanationKu: 'Mal (mê) → ezafe -a. "Mala min" = evim.',
  ),
  KuWritingExercise(
    id: 'ku_write_033',
    level: 'A1',
    type: 'fill_blank',
    promptTr: 'EZAFE: "Bav___ min" (Benim babam) — doğru eki yaz',
    correctAnswer: 'ê',
    words: null,
    explanationTr: 'Bav ERİL bir kelimedir, ezafe eki -ê olur: "Bavê min".',
    explanationKu: 'Bav (nêr) → ezafe -ê. Forma "Bavê min" diyare xwedîtiyê.',
  ),
  KuWritingExercise(
    id: 'ku_write_034',
    level: 'A1',
    type: 'fill_blank',
    promptTr: 'Boşluğu doldur: "Ew ___ dibistanê." (O okula gidiyor)',
    correctAnswer: 'diçe',
    words: null,
    explanationTr: 'Çûn (gitmek) fiilinin 3. tekil şimdiki zamanı: diçe.',
    explanationKu: 'Lêkera "çûn" → 3. kes yekjimar niha: diçe.',
  ),
  KuWritingExercise(
    id: 'ku_write_035',
    level: 'A1',
    type: 'fill_blank',
    promptTr: 'Boşluğu doldur: "Em Kurd ___." (Biz Kürdüz)',
    correctAnswer: 'in',
    words: null,
    explanationTr: 'Çoğul 1. ve 3. şahıs be eki: -in. "Em ... in", "Ew ... in".',
    explanationKu: 'Paşgira "be"yê ya pirjimar: -in.',
  ),
  KuWritingExercise(
    id: 'ku_write_036',
    level: 'A1',
    type: 'fill_blank',
    promptTr: 'EZAFE: "Keç___ mezin" (büyük kız) — eki yaz',
    correctAnswer: 'a',
    words: null,
    explanationTr: 'Keç (kız) dişildir. Ezafe: -a. "Keça mezin" = büyük kız.',
    explanationKu: 'Keç (mê) + ezafe -a + rengdêr.',
  ),
  KuWritingExercise(
    id: 'ku_write_037',
    level: 'A1',
    type: 'fill_blank',
    promptTr: 'EZAFE: "Kur___ biçûk" (küçük oğlan) — eki yaz',
    correctAnswer: 'ê',
    words: null,
    explanationTr: 'Kur (oğlan) erildir. Ezafe: -ê. "Kurê biçûk" = küçük oğlan.',
    explanationKu: 'Kur (nêr) + ezafe -ê + rengdêr.',
  ),
  KuWritingExercise(
    id: 'ku_write_038',
    level: 'A2',
    type: 'fill_blank',
    promptTr: 'ERGATİF: "___ nan xwar." (Ben ekmek yedim)',
    correctAnswer: 'Min',
    words: null,
    explanationTr: 'Geçmişte geçişli fiilde Ez → Min. "Min nan xwar" = Ben ekmek yedim.',
    explanationKu: 'Di borî ya derhingêv de: Ez → Min. Ergatîv.',
  ),
  KuWritingExercise(
    id: 'ku_write_039',
    level: 'A2',
    type: 'fill_blank',
    promptTr: 'ERGATİF: "___ av vexwar." (Sen su içtin)',
    correctAnswer: 'Te',
    words: null,
    explanationTr: 'Geçmişte: Tu → Te. "Te av vexwar" = Sen su içtin.',
    explanationKu: 'Di borî de: Tu → Te. Kişandina ergatîv.',
  ),
  KuWritingExercise(
    id: 'ku_write_040',
    level: 'A2',
    type: 'fill_blank',
    promptTr: 'ERGATİF: "___ pirtûk xwend." (O (erkek) kitabı okudu)',
    correctAnswer: 'Wî',
    words: null,
    explanationTr: 'Geçmişte: Ew (nêr) → Wî, Ew (mê) → Wê. "Wî pirtûk xwend".',
    explanationKu: 'Ew nêr → Wî; Ew mê → Wê. Di kişandina ergatîv.',
  ),
  KuWritingExercise(
    id: 'ku_write_041',
    level: 'A2',
    type: 'fill_blank',
    promptTr: 'EZAFE pirjimar: "Pirtûk___ min" (kitaplarım) — ek',
    correctAnswer: 'ên',
    words: null,
    explanationTr: 'Çoğul ezafe: -ên (bêdeng sonrası) veya -yên (dengdêr sonrası). "Pirtûkên min".',
    explanationKu: 'Ezafeya pirjimar: -ên / -yên. Pirtûk + -ên = pirtûkên.',
  ),
  KuWritingExercise(
    id: 'ku_write_042',
    level: 'A2',
    type: 'fill_blank',
    promptTr: 'Boşluğu doldur: "Ew çûn ___." (Onlar eve gittiler)',
    correctAnswer: 'malê',
    words: null,
    explanationTr: 'Mal (mê) + -ê (yönelme). Çûn → çûn (geçmiş, geçişsiz, ergatif yok).',
    explanationKu: 'Mal + -ê (rewşa tewandî ya mê). Lêkera neçalak → ergatîv nîne.',
  ),
  KuWritingExercise(
    id: 'ku_write_043',
    level: 'A2',
    type: 'fill_blank',
    promptTr: 'GELECEK: "Ez ___ sibê biçim." (Ben yarın gideceğim) — eksik kelimeyi yaz',
    correctAnswer: 'ê',
    words: null,
    explanationTr: 'Gelecek zaman işareti "ê" — Bedirxan-Lescot standardında zamirden AYRI yazılır: "Ez ê", "Tu yê" / "Tê", "Ew ê", "Em ê", "Hûn ê".',
    explanationKu: 'Dema bê: cînavk + (cihê) ê + lêkera subjunktîv. Li gor Bedirxan-Lescot, "ê" peyveke serbixwe ye, ne paşgir e.',
  ),
  KuWritingExercise(
    id: 'ku_write_044',
    level: 'B1',
    type: 'fill_blank',
    promptTr: 'EZAFE: "Dergeh___ bajar" (şehrin kapısı) — ek',
    correctAnswer: 'ê',
    words: null,
    explanationTr: 'Dergeh (kapı) erildir. Ezafe: -ê. "Dergehê bajar" = şehrin kapısı.',
    explanationKu: 'Dergeh (nêr) + ezafe -ê + bajar (nêr, bêtewang).',
  ),
  KuWritingExercise(
    id: 'ku_write_045',
    level: 'B1',
    type: 'fill_blank',
    promptTr: 'ERGATİF PAST: "Min ew ___." (Ben onu gördüm) — dîtin fiili',
    correctAnswer: 'dît',
    words: null,
    explanationTr: 'Dîtin (görmek) → kökü "dît". "Min ew dît" = Ben onu gördüm (nesne "ew" 3.tekil).',
    explanationKu: 'Dîtin → rika "dît". Lêker li gor bireserê "ew" tê kişandin.',
  ),
  KuWritingExercise(
    id: 'ku_write_046',
    level: 'B1',
    type: 'fill_blank',
    promptTr: 'Boşluğu doldur: "Divê em ___ bêjin." (Söylemeliyiz) — gotin subj.',
    correctAnswer: 'bibêjin',
    words: null,
    explanationTr: 'Divê + subjunktif. Gotin (söylemek) → bibêjin (subj. 1.çoğul).',
    explanationKu: 'Divê + subjunktîv. Gotin → bibêjin.',
  ),
  KuWritingExercise(
    id: 'ku_write_047',
    level: 'B1',
    type: 'fill_blank',
    promptTr: 'EZAFE cinsiyet: "Deng___ zarokan" (çocukların sesi) — ek',
    correctAnswer: 'ê',
    words: null,
    explanationTr: 'Deng (ses) erildir. Ezafe -ê + çoğul ad "zarokan" (ergatif/oblik çoğul).',
    explanationKu: 'Deng (nêr) + ezafe -ê + pirjimara tewandî (-an).',
  ),
  KuWritingExercise(
    id: 'ku_write_048',
    level: 'B2',
    type: 'fill_blank',
    promptTr: 'PASSIVE: "Der ___ vekirin." (Kapı açıldı) — "hatin" çekimi',
    correctAnswer: 'hat',
    words: null,
    explanationTr: 'Passive geçmiş: "hat" (3.tekil) + mastar. "Der hat vekirin" = Kapı açıldı.',
    explanationKu: 'Pasîv: "hat" + rader. Der (mê, lê vir bêtewang) + hat + vekirin.',
  ),
  KuWritingExercise(
    id: 'ku_write_049',
    level: 'B2',
    type: 'fill_blank',
    promptTr: 'SUBJUNKTİV: "Bila ew ___." (Gitsin) — çûn subj.',
    correctAnswer: 'biçe',
    words: null,
    explanationTr: 'Bila (dilek) + subjunktif 3. tekil. Çûn → biçe. "Bila ew biçe" = Gitsin.',
    explanationKu: 'Bila + subjunktîv. Çûn → biçe (3. kes yekjimar).',
  ),
  KuWritingExercise(
    id: 'ku_write_050',
    level: 'B2',
    type: 'fill_blank',
    promptTr: 'EZAFE zincir: "Navê ___ min" (dostumun adı) — hevalê/hevala',
    correctAnswer: 'hevalê',
    words: null,
    explanationTr: 'Heval (dost) eril → ezafe zinciri: Nav-ê heval-ê min. "Hevalê" (nêr).',
    explanationKu: 'Zincîra ezafê: Nav-ê + heval-ê (nêr) + min. Ji bo mê: hevala min.',
  ),

  // ============================================================
  // REORDER (15 toplam) — Karışık kelimeler → doğru cümle
  // ============================================================
  KuWritingExercise(
    id: 'ku_write_051',
    level: 'A1',
    type: 'reorder',
    promptTr: 'Kelimeleri sırala (anlam: "Ben öğrenciyim"):',
    correctAnswer: 'Ez xwendekar im.',
    words: ['xwendekar', 'Ez', 'im'],
    explanationTr: 'Kurmancî\'de özne-nesne-fiil/yüklem sırası. Ez (özne) + xwendekar (yüklem) + im.',
    explanationKu: 'Rêza Kurmancî: kirde + pêvek + be. SOV/SCV.',
  ),
  KuWritingExercise(
    id: 'ku_write_052',
    level: 'A1',
    type: 'reorder',
    promptTr: 'Kelimeleri sırala (anlam: "Bu benim evimdir"):',
    correctAnswer: 'Ev mala min e.',
    words: ['mala', 'Ev', 'e', 'min'],
    explanationTr: 'Ev (bu) + mala (ev+ezafe) + min (benim) + e (-dir). Ezafe yapısı.',
    explanationKu: 'Ev + mal-a + min + e. Avahiya ezafê bi cînavka xwedîtiyê.',
  ),
  KuWritingExercise(
    id: 'ku_write_053',
    level: 'A1',
    type: 'reorder',
    promptTr: 'Kelimeleri sırala (anlam: "Annem evdedir"):',
    correctAnswer: 'Diya min li malê ye.',
    words: ['li', 'Diya', 'ye', 'min', 'malê'],
    explanationTr: 'Diya min (annem) + li malê (evde) + ye. "Li" yer edatı.',
    explanationKu: 'Diya min + li + malê + ye. "Li" daçeka cih e.',
  ),
  KuWritingExercise(
    id: 'ku_write_054',
    level: 'A1',
    type: 'reorder',
    promptTr: 'Kelimeleri sırala (anlam: "Çocuk kitap okuyor"):',
    correctAnswer: 'Zarok pirtûkê dixwîne.',
    words: ['pirtûkê', 'dixwîne', 'Zarok'],
    explanationTr: 'Zarok (çocuk) + pirtûk-ê (kitabı, bireser) + dixwîne (xwendin-niha).',
    explanationKu: 'Kirde + bireser (tewandî) + lêker. Zarok (nêr, li vir bêtewang).',
  ),
  KuWritingExercise(
    id: 'ku_write_055',
    level: 'A2',
    type: 'reorder',
    promptTr: 'Kelimeleri sırala (anlam: "Ben dün ekmek yedim"):',
    correctAnswer: 'Min duh nan xwar.',
    words: ['nan', 'duh', 'Min', 'xwar'],
    explanationTr: 'ERGATİF: Min + duh (zaman) + nan (nesne) + xwar (fiil). Zaman kirdeden sonra.',
    explanationKu: 'Ergatîv: Min + dem + bireser + lêker. Rêza kurmancî.',
  ),
  KuWritingExercise(
    id: 'ku_write_056',
    level: 'A2',
    type: 'reorder',
    promptTr: 'Kelimeleri sırala (anlam: "Babam çay içti"):',
    correctAnswer: 'Bavê min çay vexwar.',
    words: ['çay', 'Bavê', 'vexwar', 'min'],
    explanationTr: 'Bavê min (ergatif öbek) + çay + vexwar (vexwarin-içmek, geçmiş).',
    explanationKu: 'Bavê min (ergatîv) + bireser + lêker. Bav (nêr) + ezafe -ê.',
  ),
  KuWritingExercise(
    id: 'ku_write_057',
    level: 'A2',
    type: 'reorder',
    promptTr: 'Kelimeleri sırala (anlam: "Biz okula gidiyoruz"):',
    correctAnswer: 'Em diçin dibistanê.',
    words: ['dibistanê', 'diçin', 'Em'],
    explanationTr: 'Em (biz) + diçin (çûn-niha, çoğul) + dibistan-ê (okula, mê).',
    explanationKu: 'Em + diçin + dibistanê. Lêkera niha + -in ji bo pirjimar.',
  ),
  KuWritingExercise(
    id: 'ku_write_058',
    level: 'A2',
    type: 'reorder',
    promptTr: 'Kelimeleri sırala (anlam: "O yarın gelecek"):',
    correctAnswer: 'Ew ê sibê were.',
    words: ['were', 'sibê', 'Ew ê'],
    explanationTr: 'Ew + AYRI ê (gelecek) + sibê (yarın) + were (hatin-subj. 3.tekil). Bedirxan-Lescot: "Ew" ve "ê" iki ayrı kelime.',
    explanationKu: 'Ew + (cihê) ê + dem + subjunktîv. Hatin → were. Standarda Bedirxan: "Ew ê" du peyv in.',
  ),
  KuWritingExercise(
    id: 'ku_write_059',
    level: 'B1',
    type: 'reorder',
    promptTr: 'Kelimeleri sırala (anlam: "Ben onu gördüm"):',
    correctAnswer: 'Min ew dît.',
    words: ['ew', 'Min', 'dît'],
    explanationTr: 'ERGATİF: Min (ben-ergatif) + ew (onu, nesne aynı form) + dît. Nesne 3.tekil.',
    explanationKu: 'Min + ew (bireser) + dît. Di ergatîvê de "ew" bêguhertin dimîne.',
  ),
  KuWritingExercise(
    id: 'ku_write_060',
    level: 'B1',
    type: 'reorder',
    promptTr: 'Kelimeleri sırala (anlam: "Yarın kitabı okumam lazım"):',
    correctAnswer: 'Divê ez sibê pirtûkê bixwînim.',
    words: ['sibê', 'bixwînim', 'Divê', 'ez', 'pirtûkê'],
    explanationTr: 'Divê + ez + sibê + pirtûk-ê + bixwînim (subj.). Gereklilik yapısı.',
    explanationKu: 'Divê + kirde + dem + bireser + subjunktîv.',
  ),
  KuWritingExercise(
    id: 'ku_write_061',
    level: 'B1',
    type: 'reorder',
    promptTr: 'Kelimeleri sırala (anlam: "Çocuklar parkta oynadılar"):',
    correctAnswer: 'Zarokan li parkê lîst.',
    words: ['li', 'lîst', 'Zarokan', 'parkê'],
    explanationTr: 'ERGATİF çoğul: Zarok → Zarokan (oblik çoğul). Li parkê + lîst.',
    explanationKu: 'Di borî de: zarok → zarokan (-an pirjimara tewandî).',
  ),
  KuWritingExercise(
    id: 'ku_write_062',
    level: 'B1',
    type: 'reorder',
    promptTr: 'Kelimeleri sırala (anlam: "Ben Kürtçe öğreniyorum"):',
    correctAnswer: 'Ez Kurmancî hîn dibim.',
    words: ['Kurmancî', 'dibim', 'hîn', 'Ez'],
    explanationTr: 'Hîn bûn (öğrenmek) ayrılabilir: hîn ... dibim. Ez + Kurmancî + hîn dibim.',
    explanationKu: 'Lêkera hevdanî "hîn bûn" → ez hîn dibim.',
  ),
  KuWritingExercise(
    id: 'ku_write_063',
    level: 'B2',
    type: 'reorder',
    promptTr: 'Kelimeleri sırala (anlam: "Kapı açıldı" - passive):',
    correctAnswer: 'Der hat vekirin.',
    words: ['vekirin', 'Der', 'hat'],
    explanationTr: 'PASSIVE: Der + hat (hatin-3.tekil) + vekirin (mastar).',
    explanationKu: 'Pasîv: kirde + hat + rader. "Hatin" + rader = pasîv.',
  ),
  KuWritingExercise(
    id: 'ku_write_064',
    level: 'B2',
    type: 'reorder',
    promptTr: 'Kelimeleri sırala (anlam: "Keşke onu görseydim"):',
    correctAnswer: 'Xwezî min ew bidîtaya.',
    words: ['bidîtaya', 'ew', 'Xwezî', 'min'],
    explanationTr: 'Xwezî + min (ergatif) + ew + bidîtaya (hîpotetîk geçmiş subj.).',
    explanationKu: 'Xwezî + kirdeya ergatîv + bireser + subjunktîvê borî.',
  ),
  KuWritingExercise(
    id: 'ku_write_065',
    level: 'B2',
    type: 'reorder',
    promptTr: 'Kelimeleri sırala (anlam: "Gelirse, konuşurum"):',
    correctAnswer: 'Eger were, ez peyivim.',
    words: ['peyivim', 'were', 'Eger', 'ez'],
    explanationTr: 'Şart: Eger + subjunktif (were) + sonuç (ez peyivim). Virgülle ayrılır.',
    explanationKu: 'Hevoka şertî: Eger + subjunktîv + encam.',
  ),

  // ============================================================
  // CORRECT (10 toplam) — Hatalı cümle → düzelt
  // ============================================================
  KuWritingExercise(
    id: 'ku_write_066',
    level: 'A2',
    type: 'correct',
    promptTr: 'HATA: "Ez nan xwar." (Ben ekmek yedim) — doğrusunu yaz:',
    correctAnswer: 'Min nan xwar.',
    words: null,
    explanationTr: 'ERGATİF HATASI: Geçmiş geçişli fiilde "Ez" olmaz, "Min" olur.',
    explanationKu: 'Ergatîv: di borî ya derhingêv de "Ez" → "Min".',
  ),
  KuWritingExercise(
    id: 'ku_write_067',
    level: 'A1',
    type: 'correct',
    promptTr: 'HATA: "Malê min mezin e." (Evim büyük) — düzelt:',
    correctAnswer: 'Mala min mezin e.',
    words: null,
    explanationTr: 'EZAFE CİNSİYET: Mal DİŞİLDİR, -a alır, -ê değil. "Mala min" doğru.',
    explanationKu: 'Mal (mê) → ezafe -a ye, ne -ê. Şaştî di zayendê de.',
  ),
  KuWritingExercise(
    id: 'ku_write_068',
    level: 'A1',
    type: 'correct',
    promptTr: 'HATA: "Bava min hat." (Babam geldi) — düzelt:',
    correctAnswer: 'Bavê min hat.',
    words: null,
    explanationTr: 'EZAFE CİNSİYET: Bav ERİLDİR, -ê alır, -a değil. "Bavê min" doğru.',
    explanationKu: 'Bav (nêr) → ezafe -ê. Şaşî: "bava" → rast: "bavê".',
  ),
  KuWritingExercise(
    id: 'ku_write_069',
    level: 'A2',
    type: 'correct',
    promptTr: 'HATA: "Tu pirtûk xwend." (Sen kitabı okudun) — düzelt:',
    correctAnswer: 'Te pirtûk xwend.',
    words: null,
    explanationTr: 'ERGATİF: Geçmişte Tu → Te. "Te pirtûk xwend" = sen kitabı okudun.',
    explanationKu: 'Di borî de: Tu → Te.',
  ),
  KuWritingExercise(
    id: 'ku_write_070',
    level: 'A2',
    type: 'correct',
    promptTr: 'HATA: "Ew pirtûka xwend." (O kitabı okudu) — düzelt:',
    correctAnswer: 'Wî pirtûk xwend.',
    words: null,
    explanationTr: 'ERGATİF: Ew → Wî (nêr) / Wê (mê). Ayrıca "pirtûka" değil "pirtûk" (nesne yalın).',
    explanationKu: 'Ew nêr → Wî. Di ergatîvê de bireserê sade ye.',
  ),
  KuWritingExercise(
    id: 'ku_write_071',
    level: 'A2',
    type: 'correct',
    promptTr: 'HATA: "Em çûn dibistan." (Biz okula gittik) — düzelt:',
    correctAnswer: 'Em çûn dibistanê.',
    words: null,
    explanationTr: 'YÖNELME eki eksik: Dibistan (mê) + -ê → dibistanê (okula).',
    explanationKu: 'Rewşa tewandî: dibistan → dibistanê (mê).',
  ),
  KuWritingExercise(
    id: 'ku_write_072',
    level: 'B1',
    type: 'correct',
    promptTr: 'HATA: "Min duh ez dîtim." (gramatik hata) — düzelt (Ben dün seni gördüm):',
    correctAnswer: 'Min duh tu dîtî.',
    words: null,
    explanationTr: 'ERGATİF nesne uyumu: Nesne "tu" (seni, aynı form), fiil "tu"ya göre çekilir: dîtî.',
    explanationKu: 'Ergatîv: lêker li gor bireserê "tu" → dîtî.',
  ),
  KuWritingExercise(
    id: 'ku_write_073',
    level: 'B1',
    type: 'correct',
    promptTr: 'HATA: "Mala bavê min a mezin." (Babamın büyük evi) — düzelt:',
    correctAnswer: 'Mala mezin a bavê min.',
    words: null,
    explanationTr: 'EZAFE zinciri: ad + sıfat ezafe, sonra iyelik ezafe. "Mala mezin a bavê min".',
    explanationKu: 'Zincîra ezafê: navdêr + rengdêr (ezafe) + ezafeya duyem + xwedî.',
  ),
  KuWritingExercise(
    id: 'ku_write_074',
    level: 'B2',
    type: 'correct',
    promptTr: 'HATA: "Divê ez biçe." (Gitmeliyim) — düzelt:',
    correctAnswer: 'Divê ez biçim.',
    words: null,
    explanationTr: 'SUBJUNKTİF uyumu: Ez → biçim (1.tekil subj). "Biçe" 3.tekil için.',
    explanationKu: 'Subjunktîv li gor kesê: ez biçim, tu biçî, ew biçe.',
  ),
  KuWritingExercise(
    id: 'ku_write_075',
    level: 'B2',
    type: 'correct',
    promptTr: 'HATA: "Pirtûk hatibû xwend." (Kitap okunmuştu) — düzelt:',
    correctAnswer: 'Pirtûk hatibû xwendin.',
    words: null,
    explanationTr: 'PASSIVE mastar: "hatin" + MASTAR formu. "Xwend" yerine "xwendin".',
    explanationKu: 'Pasîv: hatin + rader (ne rika demî). "Xwendin" ne "xwend".',
  ),

  // ============================================================
  // TRANSLATE_TR (5 toplam) — Kurmancî → Türkçe
  // ============================================================
  KuWritingExercise(
    id: 'ku_write_076',
    level: 'A1',
    type: 'translate_tr',
    promptTr: 'Türkçeye çevir: "Ez xwendekar im."',
    correctAnswer: 'Ben öğrenciyim.',
    words: null,
    explanationTr: 'Ez = ben, xwendekar = öğrenci, im = -im (yüklem eki).',
    explanationKu: 'Wergera tirkî: Ez → ben, xwendekar → öğrenci, im → -im.',
  ),
  KuWritingExercise(
    id: 'ku_write_077',
    level: 'A2',
    type: 'translate_tr',
    promptTr: 'Türkçeye çevir: "Min duh sêv xwar."',
    correctAnswer: 'Ben dün elma yedim.',
    words: null,
    explanationTr: 'ERGATİF: Min = ben (geçmişte), duh = dün, sêv = elma, xwar = yedim.',
    explanationKu: 'Ergatîv: Min → "ben" (di borî de), sêv → elma, xwar → yedim.',
  ),
  KuWritingExercise(
    id: 'ku_write_078',
    level: 'A2',
    type: 'translate_tr',
    promptTr: 'Türkçeye çevir: "Mala bavê min li Amedê ye."',
    correctAnswer: 'Babamın evi Diyarbakır\'dadır.',
    words: null,
    explanationTr: 'Mala (ev+ezafe) bavê min (babamın) + li Amedê (Diyarbakır\'da) + ye.',
    explanationKu: 'Mal (mê) + ezafe + xwedî + cih. Amed = Diyarbekir.',
  ),
  KuWritingExercise(
    id: 'ku_write_079',
    level: 'B1',
    type: 'translate_tr',
    promptTr: 'Türkçeye çevir: "Divê em sibê zû rabin."',
    correctAnswer: 'Yarın erken kalkmalıyız.',
    words: null,
    explanationTr: 'Divê = gerek, em = biz, sibê = yarın, zû = erken, rabin = kalkalım (subj.).',
    explanationKu: 'Divê + em + sibê + zû + rabin. Rabûn → rabin (subjunktîv).',
  ),
  KuWritingExercise(
    id: 'ku_write_080',
    level: 'B2',
    type: 'translate_tr',
    promptTr: 'Türkçeye çevir: "Xwezî te ew kitêb ji min re bianiya."',
    correctAnswer: 'Keşke o kitabı bana getirseydin.',
    words: null,
    explanationTr: 'Xwezî = keşke, te = sen (erg. past), ji min re = bana, bianiya = getirseydin (hîpotetîk).',
    explanationKu: 'Forma hîpotetîk a borî: bianiya. Xwezî + ergatîv + biresera + bianiya.',
  ),
];
