"""Oxford 3000 — A1 dilim stub.

Bu dosya, ilk batch için seçili 250 yaygın A1 İngilizce kelimeyi
içerir. Üretim aşamasında Claude API ile Kurmancî çeviri + heritage
cümleleri otomatik üretilecek.

Format: (en, ipa, pos, kat, emoji)
"""

# Oxford 3000 — A1 (Beginner) — en yaygın 250 kelime
# Kategori (kat) Kurmancî DB ile uyumlu olmalı (xwarin, malbat, reng vs)
A1_SEED = [
    # ── Selamlama / Sosyal ────────────────────────────────
    ('hello', '/həˈloʊ/', 'interjection', 'silav', '👋'),
    ('hi', '/haɪ/', 'interjection', 'silav', '👋'),
    ('goodbye', '/ɡʊdˈbaɪ/', 'interjection', 'silav', '👋'),
    ('please', '/pliːz/', 'adv', 'silav', '🙏'),
    ('thanks', '/θæŋks/', 'interjection', 'silav', '🙏'),
    ('sorry', '/ˈsɔːri/', 'adj', 'silav', '😔'),
    ('yes', '/jes/', 'adv', 'silav', '✅'),
    ('no', '/noʊ/', 'adv', 'silav', '❌'),
    ('ok', '/oʊˈkeɪ/', 'adj', 'silav', '👌'),

    # ── Sayılar ───────────────────────────────────────────
    ('zero', '/ˈzɪroʊ/', 'num', 'jimar', '0️⃣'),
    ('one', '/wʌn/', 'num', 'jimar', '1️⃣'),
    ('two', '/tuː/', 'num', 'jimar', '2️⃣'),
    ('three', '/θriː/', 'num', 'jimar', '3️⃣'),
    ('four', '/fɔːr/', 'num', 'jimar', '4️⃣'),
    ('five', '/faɪv/', 'num', 'jimar', '5️⃣'),
    ('six', '/sɪks/', 'num', 'jimar', '6️⃣'),
    ('seven', '/ˈsevən/', 'num', 'jimar', '7️⃣'),
    ('eight', '/eɪt/', 'num', 'jimar', '8️⃣'),
    ('nine', '/naɪn/', 'num', 'jimar', '9️⃣'),
    ('ten', '/ten/', 'num', 'jimar', '🔟'),
    ('hundred', '/ˈhʌndrəd/', 'num', 'jimar', '💯'),

    # ── Renkler ───────────────────────────────────────────
    ('red', '/red/', 'adj', 'reng', '🔴'),
    ('blue', '/bluː/', 'adj', 'reng', '🔵'),
    ('green', '/ɡriːn/', 'adj', 'reng', '🟢'),
    ('yellow', '/ˈjeloʊ/', 'adj', 'reng', '🟡'),
    ('black', '/blæk/', 'adj', 'reng', '⚫'),
    ('white', '/waɪt/', 'adj', 'reng', '⚪'),
    ('orange', '/ˈɔːrɪndʒ/', 'adj', 'reng', '🟠'),
    ('pink', '/pɪŋk/', 'adj', 'reng', '🩷'),
    ('purple', '/ˈpɜːrpəl/', 'adj', 'reng', '🟣'),
    ('brown', '/braʊn/', 'adj', 'reng', '🟤'),

    # ── Aile ──────────────────────────────────────────────
    ('father', '/ˈfɑːðər/', 'noun', 'malbat', '👨'),
    ('mother', '/ˈmʌðər/', 'noun', 'malbat', '👩'),
    ('son', '/sʌn/', 'noun', 'malbat', '👦'),
    ('daughter', '/ˈdɔːtər/', 'noun', 'malbat', '👧'),
    ('brother', '/ˈbrʌðər/', 'noun', 'malbat', '👨'),
    ('sister', '/ˈsɪstər/', 'noun', 'malbat', '👩'),
    ('grandfather', '/ˈɡrænfɑːðər/', 'noun', 'malbat', '👴'),
    ('grandmother', '/ˈɡrænmʌðər/', 'noun', 'malbat', '👵'),
    ('uncle', '/ˈʌŋkəl/', 'noun', 'malbat', '👨'),
    ('aunt', '/ænt/', 'noun', 'malbat', '👩'),
    ('child', '/tʃaɪld/', 'noun', 'malbat', '🧒'),
    ('baby', '/ˈbeɪbi/', 'noun', 'malbat', '👶'),
    ('family', '/ˈfæməli/', 'noun', 'malbat', '👨‍👩‍👧‍👦'),
    ('man', '/mæn/', 'noun', 'mirov', '👨'),
    ('woman', '/ˈwʊmən/', 'noun', 'mirov', '👩'),
    ('boy', '/bɔɪ/', 'noun', 'mirov', '👦'),
    ('girl', '/ɡɜːrl/', 'noun', 'mirov', '👧'),
    ('friend', '/frend/', 'noun', 'civakî', '👫'),

    # ── Vücut ─────────────────────────────────────────────
    ('head', '/hed/', 'noun', 'beden', '🗣️'),
    ('eye', '/aɪ/', 'noun', 'beden', '👁️'),
    ('ear', '/ɪər/', 'noun', 'beden', '👂'),
    ('nose', '/noʊz/', 'noun', 'beden', '👃'),
    ('mouth', '/maʊθ/', 'noun', 'beden', '👄'),
    ('hand', '/hænd/', 'noun', 'beden', '✋'),
    ('foot', '/fʊt/', 'noun', 'beden', '🦶'),
    ('leg', '/leɡ/', 'noun', 'beden', '🦵'),
    ('arm', '/ɑːrm/', 'noun', 'beden', '💪'),
    ('hair', '/heər/', 'noun', 'beden', '💇'),

    # ── Yiyecek-İçecek ────────────────────────────────────
    ('water', '/ˈwɔːtər/', 'noun', 'xwarin', '💧'),
    ('milk', '/mɪlk/', 'noun', 'xwarin', '🥛'),
    ('bread', '/bred/', 'noun', 'xwarin', '🍞'),
    ('rice', '/raɪs/', 'noun', 'xwarin', '🍚'),
    ('meat', '/miːt/', 'noun', 'xwarin', '🥩'),
    ('egg', '/eɡ/', 'noun', 'xwarin', '🥚'),
    ('cheese', '/tʃiːz/', 'noun', 'xwarin', '🧀'),
    ('apple', '/ˈæpəl/', 'noun', 'xwarin', '🍎'),
    ('banana', '/bəˈnænə/', 'noun', 'xwarin', '🍌'),
    ('orange', '/ˈɔːrɪndʒ/', 'noun', 'xwarin', '🍊'),
    ('tea', '/tiː/', 'noun', 'xwarin', '🍵'),
    ('coffee', '/ˈkɔːfi/', 'noun', 'xwarin', '☕'),
    ('sugar', '/ˈʃʊɡər/', 'noun', 'xwarin', '🍬'),
    ('salt', '/sɔːlt/', 'noun', 'xwarin', '🧂'),
    ('food', '/fuːd/', 'noun', 'xwarin', '🍽️'),

    # ── Hayvan ────────────────────────────────────────────
    ('cat', '/kæt/', 'noun', 'heywan', '🐱'),
    ('dog', '/dɔːɡ/', 'noun', 'heywan', '🐶'),
    ('horse', '/hɔːrs/', 'noun', 'heywan', '🐴'),
    ('cow', '/kaʊ/', 'noun', 'heywan', '🐄'),
    ('sheep', '/ʃiːp/', 'noun', 'heywan', '🐑'),
    ('chicken', '/ˈtʃɪkɪn/', 'noun', 'heywan', '🐔'),
    ('bird', '/bɜːrd/', 'noun', 'heywan', '🐦'),
    ('fish', '/fɪʃ/', 'noun', 'heywan', '🐟'),

    # ── Zaman ─────────────────────────────────────────────
    ('day', '/deɪ/', 'noun', 'dem', '📅'),
    ('night', '/naɪt/', 'noun', 'dem', '🌙'),
    ('morning', '/ˈmɔːrnɪŋ/', 'noun', 'dem', '🌅'),
    ('evening', '/ˈiːvnɪŋ/', 'noun', 'dem', '🌆'),
    ('today', '/təˈdeɪ/', 'adv', 'dem', '📆'),
    ('tomorrow', '/təˈmɑːroʊ/', 'adv', 'dem', '🗓️'),
    ('yesterday', '/ˈjestərdeɪ/', 'adv', 'dem', '📜'),
    ('week', '/wiːk/', 'noun', 'dem', '🗓️'),
    ('month', '/mʌnθ/', 'noun', 'dem', '🗓️'),
    ('year', '/jɪər/', 'noun', 'dem', '📅'),
    ('time', '/taɪm/', 'noun', 'dem', '⏰'),
    ('hour', '/ˈaʊər/', 'noun', 'dem', '⏱️'),
    ('minute', '/ˈmɪnɪt/', 'noun', 'dem', '⏱️'),

    # ── Hafta günleri ─────────────────────────────────────
    ('monday', '/ˈmʌndeɪ/', 'noun', 'roj', '📅'),
    ('tuesday', '/ˈtuːzdeɪ/', 'noun', 'roj', '📅'),
    ('wednesday', '/ˈwenzdeɪ/', 'noun', 'roj', '📅'),
    ('thursday', '/ˈθɜːrzdeɪ/', 'noun', 'roj', '📅'),
    ('friday', '/ˈfraɪdeɪ/', 'noun', 'roj', '📅'),
    ('saturday', '/ˈsætərdeɪ/', 'noun', 'roj', '📅'),
    ('sunday', '/ˈsʌndeɪ/', 'noun', 'roj', '📅'),

    # ── Yer-Mekan ─────────────────────────────────────────
    ('home', '/hoʊm/', 'noun', 'mal', '🏠'),
    ('house', '/haʊs/', 'noun', 'mal', '🏠'),
    ('school', '/skuːl/', 'noun', 'cih', '🏫'),
    ('work', '/wɜːrk/', 'noun', 'kar', '💼'),
    ('city', '/ˈsɪti/', 'noun', 'cih', '🏙️'),
    ('country', '/ˈkʌntri/', 'noun', 'cih', '🗺️'),
    ('street', '/striːt/', 'noun', 'cih', '🛣️'),
    ('shop', '/ʃɑːp/', 'noun', 'cih', '🏪'),
    ('hospital', '/ˈhɑːspɪtəl/', 'noun', 'cih', '🏥'),
    ('park', '/pɑːrk/', 'noun', 'cih', '🌳'),
    ('room', '/ruːm/', 'noun', 'mal', '🚪'),
    ('door', '/dɔːr/', 'noun', 'mal', '🚪'),
    ('window', '/ˈwɪndoʊ/', 'noun', 'mal', '🪟'),

    # ── Doğa ──────────────────────────────────────────────
    ('sun', '/sʌn/', 'noun', 'xweza', '☀️'),
    ('moon', '/muːn/', 'noun', 'xweza', '🌙'),
    ('star', '/stɑːr/', 'noun', 'xweza', '⭐'),
    ('sky', '/skaɪ/', 'noun', 'xweza', '🌌'),
    ('earth', '/ɜːrθ/', 'noun', 'xweza', '🌍'),
    ('tree', '/triː/', 'noun', 'xweza', '🌳'),
    ('flower', '/ˈflaʊər/', 'noun', 'xweza', '🌸'),
    ('mountain', '/ˈmaʊntən/', 'noun', 'xweza', '⛰️'),
    ('river', '/ˈrɪvər/', 'noun', 'xweza', '🏞️'),
    ('sea', '/siː/', 'noun', 'xweza', '🌊'),
    ('rain', '/reɪn/', 'noun', 'xweza', '🌧️'),
    ('snow', '/snoʊ/', 'noun', 'xweza', '❄️'),
    ('wind', '/wɪnd/', 'noun', 'xweza', '💨'),
    ('fire', '/ˈfaɪər/', 'noun', 'xweza', '🔥'),

    # ── Temel fiiller ─────────────────────────────────────
    ('be', '/biː/', 'verb', 'leker', None),
    ('have', '/hæv/', 'verb', 'leker', None),
    ('do', '/duː/', 'verb', 'leker', None),
    ('go', '/ɡoʊ/', 'verb', 'leker', '🚶'),
    ('come', '/kʌm/', 'verb', 'leker', None),
    ('see', '/siː/', 'verb', 'leker', '👀'),
    ('say', '/seɪ/', 'verb', 'leker', '💬'),
    ('know', '/noʊ/', 'verb', 'leker', '🧠'),
    ('think', '/θɪŋk/', 'verb', 'leker', '💭'),
    ('want', '/wɑːnt/', 'verb', 'leker', None),
    ('like', '/laɪk/', 'verb', 'leker', '❤️'),
    ('love', '/lʌv/', 'verb', 'his', '❤️'),
    ('eat', '/iːt/', 'verb', 'leker', '🍽️'),
    ('drink', '/drɪŋk/', 'verb', 'leker', '🥤'),
    ('sleep', '/sliːp/', 'verb', 'leker', '😴'),
    ('walk', '/wɔːk/', 'verb', 'leker', '🚶'),
    ('run', '/rʌn/', 'verb', 'leker', '🏃'),
    ('read', '/riːd/', 'verb', 'leker', '📖'),
    ('write', '/raɪt/', 'verb', 'leker', '✍️'),
    ('listen', '/ˈlɪsən/', 'verb', 'leker', '👂'),
    ('speak', '/spiːk/', 'verb', 'leker', '🗣️'),
    ('open', '/ˈoʊpən/', 'verb', 'leker', None),
    ('close', '/kloʊz/', 'verb', 'leker', None),
    ('start', '/stɑːrt/', 'verb', 'leker', '▶️'),
    ('stop', '/stɑːp/', 'verb', 'leker', '⛔'),
    ('give', '/ɡɪv/', 'verb', 'leker', None),
    ('take', '/teɪk/', 'verb', 'leker', None),
    ('make', '/meɪk/', 'verb', 'leker', None),
    ('work', '/wɜːrk/', 'verb', 'leker', '💼'),
    ('play', '/pleɪ/', 'verb', 'leker', '🎮'),
    ('learn', '/lɜːrn/', 'verb', 'leker', '📚'),
    ('teach', '/tiːtʃ/', 'verb', 'leker', '👨‍🏫'),
    ('help', '/help/', 'verb', 'leker', '🤝'),
    ('live', '/lɪv/', 'verb', 'leker', None),
    ('die', '/daɪ/', 'verb', 'leker', None),
    ('buy', '/baɪ/', 'verb', 'leker', '🛒'),
    ('sell', '/sel/', 'verb', 'leker', '💵'),
    ('use', '/juːz/', 'verb', 'leker', None),
    ('find', '/faɪnd/', 'verb', 'leker', None),

    # ── Sıfat (yaygın) ────────────────────────────────────
    ('big', '/bɪɡ/', 'adj', 'rengdêr', '🔵'),
    ('small', '/smɔːl/', 'adj', 'rengdêr', '🔹'),
    ('good', '/ɡʊd/', 'adj', 'rengdêr', '👍'),
    ('bad', '/bæd/', 'adj', 'rengdêr', '👎'),
    ('new', '/nuː/', 'adj', 'rengdêr', '✨'),
    ('old', '/oʊld/', 'adj', 'rengdêr', '🕰️'),
    ('young', '/jʌŋ/', 'adj', 'rengdêr', '👶'),
    ('happy', '/ˈhæpi/', 'adj', 'his', '😊'),
    ('sad', '/sæd/', 'adj', 'his', '😢'),
    ('hot', '/hɑːt/', 'adj', 'rengdêr', '🔥'),
    ('cold', '/koʊld/', 'adj', 'rengdêr', '❄️'),
    ('long', '/lɔːŋ/', 'adj', 'rengdêr', None),
    ('short', '/ʃɔːrt/', 'adj', 'rengdêr', None),
    ('high', '/haɪ/', 'adj', 'rengdêr', '⬆️'),
    ('low', '/loʊ/', 'adj', 'rengdêr', '⬇️'),
    ('right', '/raɪt/', 'adj', 'rengdêr', '✅'),
    ('wrong', '/rɔːŋ/', 'adj', 'rengdêr', '❌'),
    ('easy', '/ˈiːzi/', 'adj', 'rengdêr', None),
    ('hard', '/hɑːrd/', 'adj', 'rengdêr', None),
    ('beautiful', '/ˈbjuːtɪfəl/', 'adj', 'rengdêr', '🌸'),

    # ── Zamir ─────────────────────────────────────────────
    ('i', '/aɪ/', 'pronoun', 'cinavk', None),
    ('you', '/juː/', 'pronoun', 'cinavk', None),
    ('he', '/hiː/', 'pronoun', 'cinavk', None),
    ('she', '/ʃiː/', 'pronoun', 'cinavk', None),
    ('we', '/wiː/', 'pronoun', 'cinavk', None),
    ('they', '/ðeɪ/', 'pronoun', 'cinavk', None),
    ('it', '/ɪt/', 'pronoun', 'cinavk', None),
    ('this', '/ðɪs/', 'pronoun', 'cinavk', None),
    ('that', '/ðæt/', 'pronoun', 'cinavk', None),

    # ── Edat / Bağlaç ─────────────────────────────────────
    ('in', '/ɪn/', 'prep', 'daçek', None),
    ('on', '/ɑːn/', 'prep', 'daçek', None),
    ('at', '/æt/', 'prep', 'daçek', None),
    ('to', '/tuː/', 'prep', 'daçek', None),
    ('from', '/frʌm/', 'prep', 'daçek', None),
    ('with', '/wɪð/', 'prep', 'daçek', None),
    ('and', '/ænd/', 'conj', 'daçek', None),
    ('but', '/bʌt/', 'conj', 'daçek', None),
    ('or', '/ɔːr/', 'conj', 'daçek', None),
    ('because', '/bɪˈkɔːz/', 'conj', 'daçek', None),
    ('if', '/ɪf/', 'conj', 'daçek', None),

    # ── Soru sözleri ──────────────────────────────────────
    ('what', '/wʌt/', 'pronoun', 'pirsî', '❓'),
    ('who', '/huː/', 'pronoun', 'pirsî', '❓'),
    ('where', '/weər/', 'adv', 'pirsî', '❓'),
    ('when', '/wen/', 'adv', 'pirsî', '❓'),
    ('why', '/waɪ/', 'adv', 'pirsî', '❓'),
    ('how', '/haʊ/', 'adv', 'pirsî', '❓'),

    # ── Diğer önemli ──────────────────────────────────────
    ('book', '/bʊk/', 'noun', 'tişt', '📖'),
    ('pen', '/pen/', 'noun', 'tişt', '✏️'),
    ('paper', '/ˈpeɪpər/', 'noun', 'tişt', '📄'),
    ('phone', '/foʊn/', 'noun', 'tişt', '📱'),
    ('car', '/kɑːr/', 'noun', 'rêwîtî', '🚗'),
    ('bus', '/bʌs/', 'noun', 'rêwîtî', '🚌'),
    ('train', '/treɪn/', 'noun', 'rêwîtî', '🚆'),
    ('plane', '/pleɪn/', 'noun', 'rêwîtî', '✈️'),
    ('table', '/ˈteɪbəl/', 'noun', 'mal', '🪑'),
    ('chair', '/tʃeər/', 'noun', 'mal', '🪑'),
    ('bed', '/bed/', 'noun', 'mal', '🛏️'),
    ('clothes', '/kloʊz/', 'noun', 'cil', '👕'),
    ('shoe', '/ʃuː/', 'noun', 'cil', '👞'),
    ('money', '/ˈmʌni/', 'noun', 'kar', '💰'),
    ('language', '/ˈlæŋɡwɪdʒ/', 'noun', 'ziman', '🗣️'),
    ('word', '/wɜːrd/', 'noun', 'ziman', '💬'),
]

if __name__ == '__main__':
    print(f'A1 seed: {len(A1_SEED)} words')
    cats = {}
    for w in A1_SEED:
        cats[w[3]] = cats.get(w[3], 0) + 1
    for k, v in sorted(cats.items(), key=lambda x: -x[1]):
        print(f'  {k}: {v}')
